MODULE AIRSEA_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE AIRSEA_fc (KIJS, KIJL, HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG, ACD, ALPHA,  &
  & ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CM_GC,  &
  & DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPS1, EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC,  &
  & RN1_RN, RNU, RNUM, SQRTGOSURFT, WSPMIN, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, ZALP, ICHNK, NCHNK,  &
  & IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE TAUT_Z0 (KIJS, KIJL, IUSFG, HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC, USTAR, Z0, Z0B, CHRNCK)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, IUSFG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: USTAR
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: Z0, Z0B, CHRNCK
      END SUBROUTINE TAUT_Z0
    END INTERFACE
    INTERFACE
      SUBROUTINE Z0WAVE (KIJS, KIJL, US, TAUW, UTOP, Z0, Z0B, CHRNCK)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: US, TAUW, UTOP
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: Z0, Z0B, CHRNCK
      END SUBROUTINE Z0WAVE
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_WND
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IUSFG
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE AIRSEA_iso_c (KIJS, KIJL, HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG, ACD,  &
      & ALPHA, ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U,  &
      & CM_GC, DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPS1, EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, NWAV_GC, OM3GMKM_GC,  &
      & OMXKM3_GC, RN1_RN, RNU, RNUM, SQRTGOSURFT, WSPMIN, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, ZALP,  &
      & ICHNK, NCHNK, IJ) BIND(c, name="airsea_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: HALP
        TYPE(c_ptr), VALUE :: U10
        TYPE(c_ptr), VALUE :: U10DIR
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: US
        TYPE(c_ptr), VALUE :: Z0
        TYPE(c_ptr), VALUE :: Z0B
        TYPE(c_ptr), VALUE :: CHRNCK
        INTEGER(KIND=c_int), VALUE :: ICODE_WND
        INTEGER(KIND=c_int), VALUE :: IUSFG
        REAL, VALUE :: ACD
        REAL, VALUE :: ALPHA
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: ANG_GC_A
        REAL, VALUE :: ANG_GC_B
        REAL, VALUE :: ANG_GC_C
        REAL, VALUE :: BCD
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BMAXOKAP
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        REAL, VALUE :: CDMAX
        REAL, VALUE :: CHNKMIN_U
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: EPS1
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: G
        REAL, VALUE :: GM1
        LOGICAL, VALUE :: LLCAPCHNK
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        REAL, VALUE :: RN1_RN
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: WSPMIN
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: XNLEV
        REAL, VALUE :: ZALP
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE AIRSEA_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: U10(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: U10DIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: US(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: Z0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: CHRNCK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
!$acc host_data use_device( HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, C2OSQRTVG_GC, CM_GC, DELKCC_GC_NS,  &
!$acc & DELKCC_OMXKM3_GC, OM3GMKM_GC, OMXKM3_GC, XKMSQRTVGOC2_GC, XKM_GC, XK_GC )
    CALL AIRSEA_iso_c(KIJS, KIJL, c_loc(HALP), c_loc(U10), c_loc(U10DIR), c_loc(TAUW), c_loc(TAUWDIR), c_loc(RNFAC), c_loc(US),  &
    & c_loc(Z0), c_loc(Z0B), c_loc(CHRNCK), ICODE_WND, IUSFG, ACD, ALPHA, ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD,  &
    & BETAMAXOXKAPPA2, BMAXOKAP, c_loc(C2OSQRTVG_GC), CDMAX, CHNKMIN_U, c_loc(CM_GC), c_loc(DELKCC_GC_NS),  &
    & c_loc(DELKCC_OMXKM3_GC), EPS1, EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, NWAV_GC, c_loc(OM3GMKM_GC),  &
    & c_loc(OMXKM3_GC), RN1_RN, RNU, RNUM, SQRTGOSURFT, WSPMIN, XKAPPA, c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC),  &
    & XLOGKRATIOM1_GC, XNLEV, ZALP, ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE AIRSEA_fc
END MODULE AIRSEA_FC_MOD
