INTERFACE
  SUBROUTINE AKI_ICE_FC (G, XK, DEPTH, RHOW, CITH)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    IMPLICIT NONE
    
    REAL(KIND=JWRB), INTENT(IN) :: G, XK, DEPTH, RHOW, CITH
    
    !     ICE PROPERTIES (assumed fixed for now)
    
    !     RELATIVE ERROR LIMIT OF NEWTONS METHOD.
    !     MAXIMUM WAVE NUMBER
    
!$acc routine seq
  END SUBROUTINE AKI_ICE_FC
END INTERFACE