INTERFACE
  SUBROUTINE CIMSSTRN_FC (KIJS, KIJL, FL1, WAVNUM, DEPTH, CITHICK, STRN, DELTH, DFIM, FLMIN, G, NANG, NFRE, ROWATER, ICHNK,  &
  & NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    USE YOWFRED, ONLY: FR
    USE YOWPCONS, ONLY: ZPI
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      FUNCTION AKI_ICE_FC (G, XK, DEPTH, RHOW, CITH)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: AKI_ICE
        REAL(KIND=JWRB), INTENT(IN) :: G, XK, DEPTH, RHOW, CITH
      END FUNCTION AKI_ICE_FC
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CITHICK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: STRN(:, :)
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE CIMSSTRN_FC
END INTERFACE