INTERFACE
  SUBROUTINE CIWABR_FC (KIJS, KIJL, CICOVER, FL1, WAVNUM, CGROUP, CIWAB, CDICWA, DFIM, EPSMIN, IDELT, LICERUN, LMASKICE, NANG,  &
  & NFRE, ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    USE YOWFRED, ONLY: FR, DELTH
    USE YOWPCONS, ONLY: ZPI4GM2, G, ZPI
    
    
    ! ----------------------------------------------------------------------
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: CIWAB(:, :, :)
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDICWA
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDELT
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LMASKICE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE CIWABR_FC
END INTERFACE