INTERFACE
  SUBROUTINE FRCUTINDEX_FC (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH, CITHRSH_TAIL, EPSMIN, FLOGSPRDM1, FR, FRIC, G,  &
  & NFRE, RHOWG_DFIM, TAILFACTOR, TAILFACTOR_PM, ZPIFR, ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    USE YOWFRED, ONLY: DELTH, DFIM, FRATIO
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FMWS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: RHOWGDFTH(:, :)
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE FRCUTINDEX_FC
END INTERFACE