MODULE HALPHAP_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE HALPHAP_fc (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP, ALPHAPMAX, DELTH, DFIM, DFIMOFR, EPSMIN, FR, FR5, FRTAIL, NANG,  &
  & NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE HALPHAP_iso_c (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP, ALPHAPMAX, DELTH, DFIM, DFIMOFR, EPSMIN, FR, FR5,  &
      & FRTAIL, NANG, NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ) BIND(c, name="halphap_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: HALP
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMOFR
        REAL, VALUE :: EPSMIN
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRTAIL
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: WETAIL
        REAL, VALUE :: ZPI4GM2
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE HALPHAP_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
!$acc host_data use_device( WAVNUM, COSWDIF, FL1, HALP, DFIM, DFIMOFR, FR, FR5 )
    CALL HALPHAP_iso_c(KIJS, KIJL, c_loc(WAVNUM), c_loc(COSWDIF), c_loc(FL1), c_loc(HALP), ALPHAPMAX, DELTH, c_loc(DFIM),  &
    & c_loc(DFIMOFR), EPSMIN, c_loc(FR), c_loc(FR5), FRTAIL, NANG, NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE HALPHAP_fc
END MODULE HALPHAP_FC_MOD
