MODULE IMPLSCH_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE IMPLSCH_fc (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, INDEP, DEPTH, IOBND, IODP, AIRD,  &
  & WDWAVE, CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN,  &
  & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, TAUXD,  &
  & TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, AF11, AFCRV, ALPHA, ALPHAMAX,  &
  & ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, C2OSQRTVG_GC,  &
  & CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC, COFRM4, COSTH, CUMULW, DAL1, DAL2,  &
  & DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U,  &
  & EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN, FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL,  &
  & G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, IPHYS, IPSAT,  &
  & ISNONLIN, JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR,  &
  & LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC,  &
  & LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC,  &
  & OMEGA_GC, OMXKM3_GC, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR,  &
  & SINTH, SQRTGOSURFT, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7,  &
  & SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN,  &
  & WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI,  &
  & ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK_start, ICHNK_end, ICHNK_step, NCHNK, NPROMA_WAM, RAORW, EMEAN, FMEAN, HALP, EMEANWS, FMEANWS,  &
  & F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE, SINFLX_RNFAC,  &
  & SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST, SNONLIN_ENH,  &
  & SNONLIN_XNU, SNONLIN_SIG_TH)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRO, JWRB
    
    
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE CIWABR (KIJS, KIJL, CICOVER, FL1, WAVNUM, CGROUP, CIWAB)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CGROUP
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: CIWAB
      END SUBROUTINE CIWABR
    END INTERFACE
    INTERFACE
      SUBROUTINE FEMEANWS (KIJS, KIJL, FL1, XLLWS, FM, EM)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
        REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
      END SUBROUTINE FEMEANWS
    END INTERFACE
    INTERFACE
      SUBROUTINE FKMEAN (KIJS, KIJL, FL1, WAVNUM, EM, FM1, F1, AK, XK)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: EM, FM1, F1, AK, XK
      END SUBROUTINE FKMEAN
    END INTERFACE
    INTERFACE
      SUBROUTINE SBOTTOM (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
      END SUBROUTINE SBOTTOM
    END INTERFACE
    INTERFACE
      SUBROUTINE IMPHFTAIL (KIJS, KIJL, MIJ, FLM, WAVNUM, XK2CG, FL1)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      END SUBROUTINE IMPHFTAIL
    END INTERFACE
    INTERFACE
      SUBROUTINE SDEPTHLIM (KIJS, KIJL, EMAXDPT, FL1)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMAXDPT
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      END SUBROUTINE SDEPTHLIM
    END INTERFACE
    INTERFACE
      SUBROUTINE SDISSIP (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: INDEP
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMEAN, F1MEAN, XKMEAN
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, RAORW
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      END SUBROUTINE SDISSIP
    END INTERFACE
    INTERFACE
      SUBROUTINE SDIWBK (KIJS, KIJL, FL1, FLD, SL, DEPTH, EMAXDPT, EMEAN, F1MEAN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, EMAXDPT, EMEAN, F1MEAN
      END SUBROUTINE SDIWBK
    END INTERFACE
    INTERFACE
      SUBROUTINE SETICE (KIJS, KIJL, FL1, CICOVER, COSWDIF)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      END SUBROUTINE SETICE
    END INTERFACE
    INTERFACE
      SUBROUTINE SINFLX (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER,  &
      & COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ,  &
      & RHOWGDFTH, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: ICALL
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        LOGICAL, INTENT(IN) :: LUPDTUS
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: XK2CG
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: WSWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: AIRD
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSTAR
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: SINWDIF2
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FMEAN
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: HALP
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FMEANWS
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UFRIC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUW
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUWDIR
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0M
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0B
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: CHRNCK
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: PHIWA
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SL
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SPOS
        INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINFLX
    END INTERFACE
    INTERFACE
      SUBROUTINE SNONLIN (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, AKMEAN
      END SUBROUTINE SNONLIN
    END INTERFACE
    INTERFACE
      SUBROUTINE STOKESTRN (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES, STRNMS,  &
      & NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN)
        USE parkind_wave, ONLY: jwim, jwrb, jwro
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, STOKFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, WDWAVE, CICOVER, CITHICK
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: USTOKES, VSTOKES, STRNMS
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN
      END SUBROUTINE STOKESTRN
    END INTERFACE
    INTERFACE
      SUBROUTINE WNFLUXES (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD,  &
      & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD,  &
      & PHIEPS, PHIAW, LNUPD)
        USE parkind_wave, ONLY: jwim, jwrb, jwro
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: SSURF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: PHIWA
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EM, F1, WSWAVE, WDWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, AIRD
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: PHIOCD, PHIEPS, PHIAW
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOTAUY, NEMOWSWAVE, NEMOPHIF
        LOGICAL, INTENT(IN) :: LNUPD
      END SUBROUTINE WNFLUXES
    END INTERFACE
    ! ----------------------------------------------------------------------
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    
    
    
    !     *FLD* DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE
    !     *SL*  TOTAL SOURCE FUNCTION ARRAY.
    !     *SPOS* : POSITIVE SINPUT ONLY
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDICWA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDELT
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
    LOGICAL, VALUE, INTENT(IN) :: LBIWBK
    LOGICAL, VALUE, INTENT(IN) :: LCIWABR
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    LOGICAL, VALUE, INTENT(IN) :: LLUNSTR
    LOGICAL, VALUE, INTENT(IN) :: LMASKICE
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    LOGICAL, VALUE, INTENT(IN) :: LWFLUX
    LOGICAL, VALUE, INTENT(IN) :: LWFLUXOUT
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
    LOGICAL, VALUE, INTENT(IN) :: LWVFLX_SNL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_RED
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATERM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSEMEAN_MIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_start
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_end
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_step
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTEGER, VALUE, INTENT(IN) :: NPROMA_WAM
    INTERFACE
      SUBROUTINE IMPLSCH_iso_c (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, INDEP, DEPTH, IOBND, IODP,  &
      & AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES,  &
      & NEMOSTRN, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES,  &
      & STRNMS, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, AF11,  &
      & AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2,  &
      & BFCRV, BMAXOKAP, C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC, COFRM4,  &
      & COSTH, CUMULW, DAL1, DAL2, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM,  &
      & DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN, FLOGSPRDM1,  &
      & FR, FR5, FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1,  &
      & INDICESSAT, INLCOEF, IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN,  &
      & LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND,  &
      & LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL, NFRE, NFRE_ODD,  &
      & NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU,  &
      & RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR, SINTH, SQRTGOSURFT, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF,  &
      & SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN,  &
      & TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC,  &
      & XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK_start, ICHNK_end,  &
      & ICHNK_step, NCHNK, NPROMA_WAM, RAORW, EMEAN, FMEAN, HALP, EMEANWS, FMEANWS, F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF,  &
      & SINWDIF2, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE, SINFLX_RNFAC, SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS,  &
      & STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH) &
      &  BIND(c, name="implsch_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CGROUP
        TYPE(c_ptr), VALUE :: CIWA
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: STOKFAC
        TYPE(c_ptr), VALUE :: EMAXDPT
        TYPE(c_ptr), VALUE :: INDEP
        TYPE(c_ptr), VALUE :: DEPTH
        TYPE(c_ptr), VALUE :: IOBND
        TYPE(c_ptr), VALUE :: IODP
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: Z0B
        TYPE(c_ptr), VALUE :: CHRNCK
        TYPE(c_ptr), VALUE :: CITHICK
        TYPE(c_ptr), VALUE :: NEMOUSTOKES
        TYPE(c_ptr), VALUE :: NEMOVSTOKES
        TYPE(c_ptr), VALUE :: NEMOSTRN
        TYPE(c_ptr), VALUE :: NPHIEPS
        TYPE(c_ptr), VALUE :: NTAUOC
        TYPE(c_ptr), VALUE :: NSWH
        TYPE(c_ptr), VALUE :: NMWP
        TYPE(c_ptr), VALUE :: NEMOTAUX
        TYPE(c_ptr), VALUE :: NEMOTAUY
        TYPE(c_ptr), VALUE :: NEMOWSWAVE
        TYPE(c_ptr), VALUE :: NEMOPHIF
        TYPE(c_ptr), VALUE :: WSEMEAN
        TYPE(c_ptr), VALUE :: WSFMEAN
        TYPE(c_ptr), VALUE :: USTOKES
        TYPE(c_ptr), VALUE :: VSTOKES
        TYPE(c_ptr), VALUE :: STRNMS
        TYPE(c_ptr), VALUE :: TAUXD
        TYPE(c_ptr), VALUE :: TAUYD
        TYPE(c_ptr), VALUE :: TAUOCXD
        TYPE(c_ptr), VALUE :: TAUOCYD
        TYPE(c_ptr), VALUE :: TAUOC
        TYPE(c_ptr), VALUE :: PHIOCD
        TYPE(c_ptr), VALUE :: PHIEPS
        TYPE(c_ptr), VALUE :: PHIAW
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACD
        REAL, VALUE :: ACDLIN
        TYPE(c_ptr), VALUE :: AF11
        REAL, VALUE :: AFCRV
        REAL, VALUE :: ALPHA
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: ANG_GC_A
        REAL, VALUE :: ANG_GC_B
        REAL, VALUE :: ANG_GC_C
        REAL, VALUE :: BATHYMAX
        REAL, VALUE :: BCD
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BFCRV
        REAL, VALUE :: BMAXOKAP
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        REAL, VALUE :: CDICWA
        REAL, VALUE :: CDIS
        REAL, VALUE :: CDISVIS
        REAL, VALUE :: CDMAX
        REAL, VALUE :: CHNKMIN_U
        REAL, VALUE :: CIBLOCK
        REAL, VALUE :: CITHRSH
        REAL, VALUE :: CITHRSH_TAIL
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: COFRM4
        TYPE(c_ptr), VALUE :: COSTH
        TYPE(c_ptr), VALUE :: CUMULW
        REAL, VALUE :: DAL1
        REAL, VALUE :: DAL2
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: DELTA_SDIS
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMFR
        TYPE(c_ptr), VALUE :: DFIMFR2
        TYPE(c_ptr), VALUE :: DFIMOFR
        TYPE(c_ptr), VALUE :: DFIM_SIM
        REAL, VALUE :: DKMAX
        REAL, VALUE :: DTHRN_A
        REAL, VALUE :: DTHRN_U
        REAL, VALUE :: EGRCRV
        REAL, VALUE :: EPS1
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSU10
        REAL, VALUE :: EPSUS
        TYPE(c_ptr), VALUE :: FKLAM
        TYPE(c_ptr), VALUE :: FKLAM1
        TYPE(c_ptr), VALUE :: FKLAP
        TYPE(c_ptr), VALUE :: FKLAP1
        TYPE(c_ptr), VALUE :: FLMAX
        REAL, VALUE :: FLMIN
        REAL, VALUE :: FLOGSPRDM1
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRATIO
        REAL, VALUE :: FRIC
        REAL, VALUE :: FRTAIL
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: IAB
        INTEGER(KIND=c_int), VALUE :: ICODE
        INTEGER(KIND=c_int), VALUE :: ICODE_CPL
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        INTEGER(KIND=c_int), VALUE :: IDELT
        TYPE(c_ptr), VALUE :: IKM
        TYPE(c_ptr), VALUE :: IKM1
        TYPE(c_ptr), VALUE :: IKP
        TYPE(c_ptr), VALUE :: IKP1
        TYPE(c_ptr), VALUE :: INDICESSAT
        TYPE(c_ptr), VALUE :: INLCOEF
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: IPSAT
        INTEGER(KIND=c_int), VALUE :: ISNONLIN
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        TYPE(c_ptr), VALUE :: K11W
        TYPE(c_ptr), VALUE :: K1W
        TYPE(c_ptr), VALUE :: K21W
        TYPE(c_ptr), VALUE :: K2W
        INTEGER(KIND=c_int), VALUE :: KFRH
        LOGICAL, VALUE :: LBIWBK
        LOGICAL, VALUE :: LCIWABR
        LOGICAL, VALUE :: LICERUN
        LOGICAL, VALUE :: LLCAPCHNK
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        LOGICAL, VALUE :: LLUNSTR
        LOGICAL, VALUE :: LMASKICE
        LOGICAL, VALUE :: LWAMRSETCI
        LOGICAL, VALUE :: LWCOU
        LOGICAL, VALUE :: LWFLUX
        LOGICAL, VALUE :: LWFLUXOUT
        LOGICAL, VALUE :: LWNEMOCOU
        LOGICAL, VALUE :: LWNEMOCOUSEND
        LOGICAL, VALUE :: LWNEMOCOUSTK
        LOGICAL, VALUE :: LWNEMOCOUSTRN
        LOGICAL, VALUE :: LWNEMOTAUOC
        LOGICAL, VALUE :: LWVFLX_SNL
        INTEGER(KIND=c_int), VALUE :: MFRSTLW
        REAL, VALUE :: MICHE
        INTEGER(KIND=c_int), VALUE :: MLSTHG
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NDEPTH
        INTEGER(KIND=c_int), VALUE :: NDIKCUMUL
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NFRE_ODD
        INTEGER(KIND=c_int), VALUE :: NFRE_RED
        INTEGER(KIND=c_int), VALUE :: NSDSNTH
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        REAL, VALUE :: PHIEPSMAX
        REAL, VALUE :: PHIEPSMIN
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        REAL, VALUE :: RN1_RN
        TYPE(c_ptr), VALUE :: RNLCOEF
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        REAL, VALUE :: ROWATER
        REAL, VALUE :: ROWATERM1
        TYPE(c_ptr), VALUE :: SATWEIGHTS
        REAL, VALUE :: SDSBR
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: SSDSC2
        REAL, VALUE :: SSDSC3
        REAL, VALUE :: SSDSC4
        REAL, VALUE :: SSDSC5
        REAL, VALUE :: SSDSC6
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAILFACTOR
        REAL, VALUE :: TAILFACTOR_PM
        REAL, VALUE :: TAUOCMAX
        REAL, VALUE :: TAUOCMIN
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WP1TAIL
        REAL, VALUE :: WP2TAIL
        REAL, VALUE :: WSEMEAN_MIN
        REAL, VALUE :: WSPMIN
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        REAL, VALUE :: XKDMIN
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: XNLEV
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK_start
        INTEGER(KIND=c_int), VALUE :: ICHNK_end
        INTEGER(KIND=c_int), VALUE :: ICHNK_step
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: NPROMA_WAM
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: EMEAN
        TYPE(c_ptr), VALUE :: FMEAN
        TYPE(c_ptr), VALUE :: HALP
        TYPE(c_ptr), VALUE :: EMEANWS
        TYPE(c_ptr), VALUE :: FMEANWS
        TYPE(c_ptr), VALUE :: F1MEAN
        TYPE(c_ptr), VALUE :: AKMEAN
        TYPE(c_ptr), VALUE :: XKMEAN
        TYPE(c_ptr), VALUE :: PHIWA
        TYPE(c_ptr), VALUE :: FLM
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: CIREDUC
        TYPE(c_ptr), VALUE :: SSOURCE
        TYPE(c_ptr), VALUE :: SINFLX_RNFAC
        TYPE(c_ptr), VALUE :: SINFLX_TMP_EM
        TYPE(c_ptr), VALUE :: STRESSO_XSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_YSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_TAUHF
        TYPE(c_ptr), VALUE :: STRESSO_PHIHF
        TYPE(c_ptr), VALUE :: STRESSO_USDIRP
        TYPE(c_ptr), VALUE :: STRESSO_UST
        TYPE(c_ptr), VALUE :: SNONLIN_ENH
        TYPE(c_ptr), VALUE :: SNONLIN_XNU
        TYPE(c_ptr), VALUE :: SNONLIN_SIG_TH
      END SUBROUTINE IMPLSCH_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CIWA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: EMAXDPT(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDEP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IOBND(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IODP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CITHICK(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOUSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOVSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOSTRN(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSEMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSFMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRNMS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AF11(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COFRM4(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CUMULW(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR2(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLMAX(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INLCOEF(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K11W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K1W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K21W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K2W(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNLCOEF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RAORW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEANWS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEANWS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: F1MEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AKMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XKMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIWA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: COSWDIF(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINWDIF2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RHOWGDFTH(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SPOS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIREDUC(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SSOURCE(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_RNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_TMP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_ENH(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_XNU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_SIG_TH(:, :)
!$acc host_data use_device( FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, INDEP, DEPTH, IOBND, IODP, AIRD, WDWAVE,  &
!$acc & CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, NPHIEPS,  &
!$acc & NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, TAUXD, TAUYD,  &
!$acc & TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, AF11, C2OSQRTVG_GC, CM_GC, COFRM4, COSTH, CUMULW,  &
!$acc & DELKCC_GC_NS, DELKCC_OMXKM3_GC, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FR, FR5,  &
!$acc & IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, K11W, K1W, K21W, K2W, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RNLCOEF,  &
!$acc & SATWEIGHTS, SINTH, SWELLFT, TH, WTAUHF, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, ZPIFR, RAORW, EMEAN, FMEAN, HALP, EMEANWS,  &
!$acc & FMEANWS, F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE,  &
!$acc & SINFLX_RNFAC, SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP,  &
!$acc & STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH )
    CALL IMPLSCH_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(CGROUP), c_loc(CIWA), c_loc(CINV), c_loc(XK2CG),  &
    & c_loc(STOKFAC), c_loc(EMAXDPT), c_loc(INDEP), c_loc(DEPTH), c_loc(IOBND), c_loc(IODP), c_loc(AIRD), c_loc(WDWAVE),  &
    & c_loc(CICOVER), c_loc(WSWAVE), c_loc(WSTAR), c_loc(UFRIC), c_loc(TAUW), c_loc(TAUWDIR), c_loc(Z0M), c_loc(Z0B),  &
    & c_loc(CHRNCK), c_loc(CITHICK), c_loc(NEMOUSTOKES), c_loc(NEMOVSTOKES), c_loc(NEMOSTRN), c_loc(NPHIEPS), c_loc(NTAUOC),  &
    & c_loc(NSWH), c_loc(NMWP), c_loc(NEMOTAUX), c_loc(NEMOTAUY), c_loc(NEMOWSWAVE), c_loc(NEMOPHIF), c_loc(WSEMEAN),  &
    & c_loc(WSFMEAN), c_loc(USTOKES), c_loc(VSTOKES), c_loc(STRNMS), c_loc(TAUXD), c_loc(TAUYD), c_loc(TAUOCXD), c_loc(TAUOCYD),  &
    & c_loc(TAUOC), c_loc(PHIOCD), c_loc(PHIEPS), c_loc(PHIAW), c_loc(MIJ), c_loc(XLLWS), ABMAX, ABMIN, ACD, ACDLIN,  &
    & c_loc(AF11), AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN,  &
    & BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, c_loc(C2OSQRTVG_GC), CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH,  &
    & CITHRSH_TAIL, c_loc(CM_GC), c_loc(COFRM4), c_loc(COSTH), c_loc(CUMULW), DAL1, DAL2, c_loc(DELKCC_GC_NS),  &
    & c_loc(DELKCC_OMXKM3_GC), DELTA_SDIS, DELTH, c_loc(DFIM), c_loc(DFIMFR), c_loc(DFIMFR2), c_loc(DFIMOFR), c_loc(DFIM_SIM),  &
    & DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, c_loc(FKLAM), c_loc(FKLAM1), c_loc(FKLAP), c_loc(FKLAP1),  &
    & c_loc(FLMAX), FLMIN, FLOGSPRDM1, c_loc(FR), c_loc(FR5), FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL,  &
    & IDAMPING, IDELT, c_loc(IKM), c_loc(IKM1), c_loc(IKP), c_loc(IKP1), c_loc(INDICESSAT), c_loc(INLCOEF), IPHYS, IPSAT,  &
    & ISNONLIN, JTOT_TAUHF, c_loc(K11W), c_loc(K1W), c_loc(K21W), c_loc(K2W), KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK,  &
    & LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK,  &
    & LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL, NFRE, NFRE_ODD, NFRE_RED,  &
    & NSDSNTH, NWAV_GC, c_loc(OM3GMKM_GC), c_loc(OMEGA_GC), c_loc(OMXKM3_GC), PHIEPSMAX, PHIEPSMIN, c_loc(RHOWG_DFIM), RN1_RN,  &
    & c_loc(RNLCOEF), RNU, RNUM, ROWATER, ROWATERM1, c_loc(SATWEIGHTS), SDSBR, c_loc(SINTH), SQRTGOSURFT, SSDSC2, SSDSC3,  &
    & SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, c_loc(SWELLFT),  &
    & TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, c_loc(TH), WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN,  &
    & c_loc(WTAUHF), X0TAUHF, XKAPPA, XKDMIN, c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, XNLEV,  &
    & Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, c_loc(ZPIFR), ICHNK_start, ICHNK_end, ICHNK_step, NCHNK, NPROMA_WAM,  &
    & c_loc(RAORW), c_loc(EMEAN), c_loc(FMEAN), c_loc(HALP), c_loc(EMEANWS), c_loc(FMEANWS), c_loc(F1MEAN), c_loc(AKMEAN),  &
    & c_loc(XKMEAN), c_loc(PHIWA), c_loc(FLM), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(RHOWGDFTH), c_loc(FLD), c_loc(SL),  &
    & c_loc(SPOS), c_loc(CIREDUC), c_loc(SSOURCE), c_loc(SINFLX_RNFAC), c_loc(SINFLX_TMP_EM), c_loc(STRESSO_XSTRESS),  &
    & c_loc(STRESSO_YSTRESS), c_loc(STRESSO_TAUHF), c_loc(STRESSO_PHIHF), c_loc(STRESSO_USDIRP), c_loc(STRESSO_UST),  &
    & c_loc(SNONLIN_ENH), c_loc(SNONLIN_XNU), c_loc(SNONLIN_SIG_TH))
!$acc end host_data
  END SUBROUTINE IMPLSCH_fc
END MODULE IMPLSCH_FC_MOD
