! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
ATTRIBUTES(GLOBAL) SUBROUTINE IMPLSCH_FC (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, INDEP, DEPTH,  &
& IOBND, IODP, AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES,  &
& NEMOSTRN, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS,  &
& TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, AF11, AFCRV, ALPHA,  &
& ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP,  &
& C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC, COFRM4, COSTH, CUMULW, DAL1,  &
& DAL2, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U,  &
& EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN, FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL, G,  &
& GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, IPHYS, IPSAT, ISNONLIN,  &
& JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE,  &
& LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW,  &
& MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC,  &
& PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR, SINTH, SQRTGOSURFT,  &
& SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT,  &
& TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF,  &
& X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2,  &
& ZPIFR, ICHNK_start, ICHNK_end, ICHNK_step, NCHNK, NPROMA_WAM, RAORW, EMEAN, FMEAN, HALP, EMEANWS, FMEANWS, F1MEAN, AKMEAN,  &
& XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE, SINFLX_RNFAC, SINFLX_TMP_EM,  &
& STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU,  &
& SNONLIN_SIG_TH)
  
  ! ----------------------------------------------------------------------
  
  !**** *IMPLSCH* - IMPLICIT SCHEME FOR TIME INTEGRATION OF SOURCE
  !****             FUNCTIONS.
  
  
  !*    PURPOSE.
  !     --------
  
  !       THE IMPLICIT SCHEME ENABLES THE USE OF A TIMESTEP WHICH IS
  !       LARGE COMPARED WITH THE CHARACTERISTIC DYNAMIC TIME SCALE.
  !       THE SCHEME IS REQUIRED FOR THE HIGH FREQUENCIES WHICH
  !       RAPIDLY ADJUST TO A QUASI-EQUILIBRIUM.
  
  !**   INTERFACE.
  !     ----------
  
  !       *CALL* *IMPLSCH (KIJS, KIJL, FL1,
  !    &                   WVPRPT,
  !    &                   WVENVI, FF_NOW,
  !    &                   INTFLDS, WAM2NEMO,
  !    &                   MIJ,  XLLWS)
  !      *KIJS*    - LOCAL INDEX OF FIRST GRIDPOINT
  !      *KIJL*    - LOCAL INDEX OF LAST GRIDPOINT
  !      *FL1*     - FREQUENCY SPECTRUM(INPUT AND OUTPUT).
  !      *WVPRPT*  - WAVE PROPERTIES FIELDS
  !      *WVENVI*  - WAVE ENVIRONMENT
  !      *FF_NOW*    FORCING FIELDS
  !      *INTFLDS*   INTEGRATED/DERIVED PARAMETERS
  !      *WAM2NEMO*  WAVE FIELDS PASSED TO NEMO
  !      *MIJ*       LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
  !      *XLLWS*     TOTAL WINDSEA MASK FROM INPUT SOURCE TERM
  
  
  !     METHOD.
  !     -------
  
  !       THE SPECTRUM AT TIME (TN+1) IS COMPUTED AS
  !       FN+1=FN+DELT*(SN+SN+1)/2., WHERE SN IS THE TOTAL SOURCE
  !       FUNCTION AT TIME TN, SN+1=SN+(DS/DF)*DF - ONLY THE DIAGONAL
  !       TERMS OF THE FUNCTIONAL MATRIX DS/DF ARE YOWPUTED, THE
  !       NONDIAGONAL TERMS ARE NEGLIGIBLE.
  !       THE ROUTINE IS CALLED AFTER PROPAGATION FOR TIME PERIOD
  !       BETWEEN TWO PROPAGATION CALLS - ARRAY FL1 CONTAINS THE
  !       SPECTRUM AND FL IS USED AS AN INTERMEDIATE STORAGE FOR THE
  !       DIAGONAL TERM OF THE FUNCTIONAL MATRIX.
  
  
  !     REFERENCE.
  !     ----------
  
  !       S. HASSELMANN AND K. HASSELMANN, "A GLOBAL WAVE MODEL",
  !       30/6/85 (UNPUBLISHED NOTE)
  
  ! ----------------------------------------------------------------------
  
  USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRO, JWRB
  USE YOWDRVTYPE, ONLY: WAVE2OCEAN, ENVIRONMENT, FREQUENCY, FORCING_FIELDS, INTGT_PARAM_FIELDS
  
  
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE CIWABR_FC (KIJS, KIJL, CICOVER, FL1, WAVNUM, CGROUP, CIWAB)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CGROUP
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: CIWAB
    END SUBROUTINE CIWABR_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE FEMEANWS_FC (KIJS, KIJL, FL1, XLLWS, FM, EM)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
      REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
    END SUBROUTINE FEMEANWS_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE FKMEAN_FC (KIJS, KIJL, FL1, WAVNUM, EM, FM1, F1, AK, XK)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: EM, FM1, F1, AK, XK
    END SUBROUTINE FKMEAN_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SBOTTOM_FC (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH)
      USE parkind_wave, ONLY: jwim, jwrb
      USE yowparam, ONLY: nang, nfre
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
    END SUBROUTINE SBOTTOM_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE IMPHFTAIL_FC (KIJS, KIJL, MIJ, FLM, WAVNUM, XK2CG, FL1)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
    END SUBROUTINE IMPHFTAIL_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SDEPTHLIM_FC (KIJS, KIJL, EMAXDPT, FL1)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMAXDPT
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
    END SUBROUTINE SDEPTHLIM_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SDISSIP_FC (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: INDEP
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMEAN, F1MEAN, XKMEAN
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, RAORW
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
    END SUBROUTINE SDISSIP_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SDIWBK_FC (KIJS, KIJL, FL1, FLD, SL, DEPTH, EMAXDPT, EMEAN, F1MEAN)
      USE parkind_wave, ONLY: jwim, jwrb
      USE yowparam, ONLY: nang, nfre
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, EMAXDPT, EMEAN, F1MEAN
    END SUBROUTINE SDIWBK_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SETICE_FC (KIJS, KIJL, FL1, CICOVER, COSWDIF)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
    END SUBROUTINE SETICE_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SINFLX_FC (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER,  &
    & COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ,  &
    & RHOWGDFTH, XLLWS)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: ICALL
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      LOGICAL, INTENT(IN) :: LUPDTUS
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: XK2CG
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: WSWAVE
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: AIRD
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSTAR
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: SINWDIF2
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FMEAN
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: HALP
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FMEANWS
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UFRIC
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUW
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUWDIR
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0M
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0B
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: CHRNCK
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: PHIWA
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SL
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SPOS
      INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
    END SUBROUTINE SINFLX_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SNONLIN_FC (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, AKMEAN
    END SUBROUTINE SNONLIN_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE STOKESTRN_FC (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES,  &
    & STRNMS, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN)
      USE parkind_wave, ONLY: jwim, jwrb, jwro
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, STOKFAC
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, WDWAVE, CICOVER, CITHICK
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: USTOKES, VSTOKES, STRNMS
      REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN
    END SUBROUTINE STOKESTRN_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE WNFLUXES_FC (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD,  &
    & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD,  &
    & PHIEPS, PHIAW, LNUPD)
      USE parkind_wave, ONLY: jwim, jwrb, jwro
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: SSURF
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: PHIWA
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EM, F1, WSWAVE, WDWAVE
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, AIRD
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: PHIOCD, PHIEPS, PHIAW
      REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX
      REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOTAUY, NEMOWSWAVE, NEMOPHIF
      LOGICAL, INTENT(IN) :: LNUPD
    END SUBROUTINE WNFLUXES_FC
  END INTERFACE
  ! ----------------------------------------------------------------------
  
  
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  INTEGER(KIND=JWIM), PARAMETER :: NRNL = 25
  INTEGER(KIND=JWIM), PARAMETER :: NINL = 5
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CIWA(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
  
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: EMAXDPT(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDEP(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IODP(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IOBND(:, :)
  
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CITHICK(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSEMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSFMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTOKES(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTOKES(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRNMS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOUSTOKES(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOVSTOKES(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOSTRN(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
  
  
  INTEGER(KIND=JWIM) :: IJ
  INTEGER(KIND=JWIM) :: K
  INTEGER(KIND=JWIM) :: M
  
  REAL(KIND=JWRB) :: DELT
  REAL(KIND=JWRB) :: DELTM
  REAL(KIND=JWRB) :: XIMP
  REAL(KIND=JWRB) :: DELT5
  REAL(KIND=JWRB) :: GTEMP1
  REAL(KIND=JWRB) :: GTEMP2
  REAL(KIND=JWRB) :: FLHAB
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RAORW(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEANWS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEANWS(:, :)
  REAL(KIND=JWRB) :: USFM
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: F1MEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AKMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XKMEAN(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIWA(:, :)
  
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLM(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: COSWDIF(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINWDIF2(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RHOWGDFTH(:, :, :)
  !     *FLD* DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE
  !     *SL*  TOTAL SOURCE FUNCTION ARRAY.
  !     *SPOS* : POSITIVE SINPUT ONLY
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SPOS(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIREDUC(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SSOURCE(:, :, :, :)
  
  LOGICAL :: LCFLX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: AF11(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDICWA
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COFRM4(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CUMULW(:, :, :, :)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR2(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM1(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP1(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLMAX(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDELT
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM(:)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM1(:)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP(:)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP1(:)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INLCOEF(:, :)
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K11W(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K1W(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K21W(:, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K2W(:, :)
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
  LOGICAL, VALUE, INTENT(IN) :: LBIWBK
  LOGICAL, VALUE, INTENT(IN) :: LCIWABR
  LOGICAL, VALUE, INTENT(IN) :: LICERUN
  LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
  LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
  LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
  LOGICAL, VALUE, INTENT(IN) :: LLUNSTR
  LOGICAL, VALUE, INTENT(IN) :: LMASKICE
  LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
  LOGICAL, VALUE, INTENT(IN) :: LWCOU
  LOGICAL, VALUE, INTENT(IN) :: LWFLUX
  LOGICAL, VALUE, INTENT(IN) :: LWFLUXOUT
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
  LOGICAL, VALUE, INTENT(IN) :: LWVFLX_SNL
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_RED
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNLCOEF(:, :)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATERM1
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSEMEAN_MIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
  INTEGER(KIND=JWIM) :: ICHNK
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_start
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_end
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_step
  INTEGER, VALUE, INTENT(IN) :: NCHNK
  INTEGER, VALUE, INTENT(IN) :: NPROMA_WAM
  TYPE(dim3) :: BLOCKDIM
  TYPE(dim3) :: GRIDDIM
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_RNFAC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_TMP_EM(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_ENH(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_XNU(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_SIG_TH(:, :)
  IJ = threadIdx%x
  ICHNK = blockIdx%x
  
  IF (ICHNK <= NCHNK .and. IJ <= KIJL) THEN
    BLOCKDIM = dim3(NPROMA_WAM, 1, 1)
    GRIDDIM = dim3(NCHNK, 1, 1)
    
    ! START of Loki inserted loop ICHNK
    
    
    ! ----------------------------------------------------------------------
    
    
    
    !*    1. INITIALISATION.
    !        ---------------
    
    DELT = IDELT
    DELTM = 1.0_JWRB / DELT
    XIMP = 1.0_JWRB
    DELT5 = XIMP*DELT
    
    LCFLX = LWFLUX .or. LWFLUXOUT .or. LWNEMOCOU
    
    
    
    RAORW(IJ, ICHNK) = MAX(AIRD(IJ, ICHNK), 1.0_JWRB)*ROWATERM1
    
    DO K=1,NANG
      COSWDIF(IJ, K, ICHNK) = COS(TH(K) - WDWAVE(IJ, ICHNK))
      SINWDIF2(IJ, K, ICHNK) = SIN(TH(K) - WDWAVE(IJ, ICHNK))**2
    END DO
    
    
    ! ----------------------------------------------------------------------
    
    !*    2. COMPUTATION OF IMPLICIT INTEGRATION.
    !        ------------------------------------
    
    !         INTEGRATION IS DONE FROM CDATE UNTIL CDTPRO FOR A BLOCK
    !         OF LATITUDES BETWEEN PROPAGATION CALLS.
    
    
    !     REDUCE WAVE ENERGY IF LARGER THAN DEPTH LIMITED WAVE HEIGHT
    IF (LBIWBK) THEN
      CALL SDEPTHLIM_FC(KIJS, KIJL, EMAXDPT(:, :), FL1(:, :, :, :), DELTH, DFIM(:), EPSMIN, FR(:), NANG, NFRE, WETAIL, ICHNK,  &
      & NCHNK, IJ)
    END IF
    
    !*    2.2 COMPUTE MEAN PARAMETERS.
    !        ------------------------
    
    CALL FKMEAN_FC(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), EMEAN(:, ICHNK), FMEAN(:, ICHNK), F1MEAN(:, ICHNK),  &
    & AKMEAN(:, ICHNK), XKMEAN(:, ICHNK), DELTH, DFIM(:), DFIMFR(:), DFIMOFR(:), EPSMIN, FR(:), FRTAIL, G, NANG, NFRE, WETAIL,  &
    & WP1TAIL, ZPI, ICHNK, NCHNK, IJ)
    
    
    DO K=1,NANG
      FLM(IJ, K, ICHNK) = FLMIN*MAX(0.0_JWRB, COSWDIF(IJ, K, ICHNK))**2
    END DO
    
    
    !     COMPUTE DAMPING COEFFICIENT DUE TO FRICTION ON BOTTOM OF THE SEA ICE.
    !!! testing sea ice attenuation (might need to restrict usage when needed)
    IF (LCIWABR) THEN
      CALL CIWABR_FC(KIJS, KIJL, CICOVER(:, :), FL1(:, :, :, :), WAVNUM(:, :, :), CGROUP(:, :, :), CIREDUC(:, :, :, ICHNK),  &
      & CDICWA, DFIM(:), EPSMIN, IDELT, LICERUN, LMASKICE, NANG, NFRE, ICHNK, NCHNK, IJ)
      
      DO M=1,NFRE
        DO K=1,NANG
          CIREDUC(IJ, K, M, ICHNK) = CIWA(IJ, M, ICHNK)*CIREDUC(IJ, K, M, ICHNK)
        END DO
      END DO
      
    ELSE
      
      DO M=1,NFRE
        DO K=1,NANG
          CIREDUC(IJ, K, M, ICHNK) = CIWA(IJ, M, ICHNK)
        END DO
      END DO
      
    END IF
    
    ! ----------------------------------------------------------------------
    
    !*    2.3 COMPUTATION OF SOURCE FUNCTIONS.
    !         --------------------------------
    
    !*    2.3.1 ITERATIVELY UPDATE STRESS AND COMPUTE WIND INPUT TERMS.
    !           -------------------------------------------------------
    
    CALL SINFLX_FC(1, KIJS, KIJL, .true., FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :), WSWAVE(:, :),  &
    & WDWAVE(:, :), AIRD(:, :), RAORW(:, ICHNK), WSTAR(:, :), CICOVER(:, :), COSWDIF(:, :, ICHNK), SINWDIF2(:, :, ICHNK),  &
    & FMEAN(:, ICHNK), HALP(:, ICHNK), FMEANWS(:, ICHNK), FLM(:, :, ICHNK), UFRIC(:, :), TAUW(:, :), TAUWDIR(:, :), Z0M(:, :),  &
    & Z0B(:, :), CHRNCK(:, :), PHIWA(:, ICHNK), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), SPOS(:, :, :, ICHNK), MIJ(:, :),  &
    & RHOWGDFTH(:, :, ICHNK), XLLWS(:, :, :, :), ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A,  &
    & ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC(:), CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC(:),  &
    & COSTH(:), DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:), DELTH, DFIM(:), DFIMOFR(:), DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS,  &
    & FLOGSPRDM1, FR(:), FR5(:), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK,  &
    & LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC(:), OMEGA_GC(:), OMXKM3_GC(:), RHOWG_DFIM(:), RN1_RN, RNU,  &
    & RNUM, SINTH(:), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:),  &
    & TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH(:), WETAIL, WSPMIN, WTAUHF(:), X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC(:), XKM_GC(:),  &
    & XK_GC(:), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR(:), ICHNK, NCHNK, IJ, SINFLX_RNFAC,  &
    & SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST)
    CALL SINFLX_FC(2, KIJS, KIJL, .true., FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :), WSWAVE(:, :),  &
    & WDWAVE(:, :), AIRD(:, :), RAORW(:, ICHNK), WSTAR(:, :), CICOVER(:, :), COSWDIF(:, :, ICHNK), SINWDIF2(:, :, ICHNK),  &
    & FMEAN(:, ICHNK), HALP(:, ICHNK), FMEANWS(:, ICHNK), FLM(:, :, ICHNK), UFRIC(:, :), TAUW(:, :), TAUWDIR(:, :), Z0M(:, :),  &
    & Z0B(:, :), CHRNCK(:, :), PHIWA(:, ICHNK), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), SPOS(:, :, :, ICHNK), MIJ(:, :),  &
    & RHOWGDFTH(:, :, ICHNK), XLLWS(:, :, :, :), ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A,  &
    & ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC(:), CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC(:),  &
    & COSTH(:), DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:), DELTH, DFIM(:), DFIMOFR(:), DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS,  &
    & FLOGSPRDM1, FR(:), FR5(:), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK,  &
    & LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC(:), OMEGA_GC(:), OMXKM3_GC(:), RHOWG_DFIM(:), RN1_RN, RNU,  &
    & RNUM, SINTH(:), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:),  &
    & TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH(:), WETAIL, WSPMIN, WTAUHF(:), X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC(:), XKM_GC(:),  &
    & XK_GC(:), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR(:), ICHNK, NCHNK, IJ, SINFLX_RNFAC,  &
    & SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST)
    
    !     2.3.3 ADD THE OTHER SOURCE TERMS.
    !           ---------------------------
    
    CALL SDISSIP_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), INDEP(:, :), WAVNUM(:, :, :),  &
    & XK2CG(:, :, :), EMEAN(:, ICHNK), F1MEAN(:, ICHNK), XKMEAN(:, ICHNK), UFRIC(:, :), COSWDIF(:, :, ICHNK), RAORW(:, ICHNK),  &
    & CDIS, CDISVIS, CUMULW(:, :, :, :), DELTA_SDIS, G, INDICESSAT(:, :), IPHYS, IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL, NFRE,  &
    & NSDSNTH, RNU, SATWEIGHTS(:, :), SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR(:), ICHNK, NCHNK, IJ)
    
    !     Save source term contributions relevant for the calculation of ocean fluxes
    
    IF (LCFLX .and. .not.LWVFLX_SNL) THEN
      DO M=1,NFRE
        DO K=1,NANG
          SSOURCE(IJ, K, M, ICHNK) = SL(IJ, K, M, ICHNK)
        END DO
      END DO
    END IF
    
    
    CALL SNONLIN_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), WAVNUM(:, :, :), DEPTH(:, :),  &
    & AKMEAN(:, ICHNK), AF11(:), BATHYMAX, COSTH(:), DAL1, DAL2, DELTH, DFIM(:), DFIMFR(:), DFIMFR2(:), DKMAX, FKLAM(:),  &
    & FKLAM1(:), FKLAP(:), FKLAP1(:), FR(:), FRATIO, G, GM1, IKM(:), IKM1(:), IKP(:), IKP1(:), INLCOEF(:, :), ISNONLIN,  &
    & K11W(:, :), K1W(:, :), K21W(:, :), K2W(:, :), KFRH, MFRSTLW, MLSTHG, NANG, NFRE, RNLCOEF(:, :), SINTH(:), TH(:), WETAIL,  &
    & WP1TAIL, WP2TAIL, XKDMIN, ZPIFR(:), ICHNK, NCHNK, IJ, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH)
    
    
    IF (LCFLX .and. LWVFLX_SNL) THEN
      !     Save source term contributions relevant for the calculation of ocean fluxes
      !!!!!!  SL must only contain contributions contributed to fluxes into the oceans
      !       MODULATE SL BY IMPLICIT FACTOR
      DO M=1,NFRE
        DO K=1,NANG
          GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
          SSOURCE(IJ, K, M, ICHNK) = SL(IJ, K, M, ICHNK) / GTEMP1
        END DO
      END DO
    END IF
    
    
    
    CALL SDIWBK_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), DEPTH(:, :), EMAXDPT(:, :),  &
    & EMEAN(:, ICHNK), F1MEAN(:, ICHNK), LBIWBK, NANG, NFRE_RED, ICHNK, NCHNK, IJ)
    
    CALL SBOTTOM_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), WAVNUM(:, :, :), DEPTH(:, :),  &
    & BATHYMAX, GM1, NANG, NFRE_RED, ICHNK, NCHNK, IJ)
    
    ! ----------------------------------------------------------------------
    
    !*    2.4 COMPUTATION OF NEW SPECTRA.
    !         ---------------------------
    
    !     INCREASE OF SPECTRUM IN A TIME STEP IS LIMITED TO A FINITE
    !     FRACTION OF A TYPICAL F**(-4) EQUILIBRIUM SPECTRUM.
    
    
    USFM = UFRIC(IJ, ICHNK)*MAX(FMEANWS(IJ, ICHNK), FMEAN(IJ, ICHNK))
    
    IF (LLUNSTR) THEN
      DO K=1,NANG
        DO M=1,NFRE
          GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
          GTEMP2 = DELT*SL(IJ, K, M, ICHNK) / GTEMP1
          FLHAB = ABS(GTEMP2)
          FLHAB = MIN(FLHAB, USFM*COFRM4(M)*DELT)
          FL1(IJ, K, M, ICHNK) = FL1(IJ, K, M, ICHNK) + IOBND(IJ, ICHNK)*SIGN(FLHAB, GTEMP2)
          FL1(IJ, K, M, ICHNK) = MAX(IODP(IJ, ICHNK)*CIREDUC(IJ, K, M, ICHNK)*FL1(IJ, K, M, ICHNK), FLM(IJ, K, ICHNK))
          SSOURCE(IJ, K, M, ICHNK) = SSOURCE(IJ, K, M, ICHNK) + DELTM*MIN(FLMAX(M) - FL1(IJ, K, M, ICHNK), 0.0_JWRB)
          FL1(IJ, K, M, ICHNK) = MIN(FL1(IJ, K, M, ICHNK), FLMAX(M))
        END DO
      END DO
    ELSE
      DO K=1,NANG
        DO M=1,NFRE
          GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
          GTEMP2 = DELT*SL(IJ, K, M, ICHNK) / GTEMP1
          FLHAB = ABS(GTEMP2)
          FLHAB = MIN(FLHAB, USFM*COFRM4(M)*DELT)
          FL1(IJ, K, M, ICHNK) = FL1(IJ, K, M, ICHNK) + SIGN(FLHAB, GTEMP2)
          FL1(IJ, K, M, ICHNK) = MAX(CIREDUC(IJ, K, M, ICHNK)*FL1(IJ, K, M, ICHNK), FLM(IJ, K, ICHNK))
          SSOURCE(IJ, K, M, ICHNK) = SSOURCE(IJ, K, M, ICHNK) + DELTM*MIN(FLMAX(M) - FL1(IJ, K, M, ICHNK), 0.0_JWRB)
          FL1(IJ, K, M, ICHNK) = MIN(FL1(IJ, K, M, ICHNK), FLMAX(M))
        END DO
      END DO
    END IF
    
    
    IF (LCFLX) THEN
      CALL WNFLUXES_FC(KIJS, KIJL, MIJ(:, :), RHOWGDFTH(:, :, ICHNK), CINV(:, :, :), SSOURCE(:, :, :, ICHNK), CICOVER(:, :),  &
      & PHIWA(:, ICHNK), EMEAN(:, ICHNK), F1MEAN(:, ICHNK), WSWAVE(:, :), WDWAVE(:, :), UFRIC(:, :), AIRD(:, :), NPHIEPS(:, :),  &
      & NTAUOC(:, :), NSWH(:, :), NMWP(:, :), NEMOTAUX(:, :), NEMOTAUY(:, :), NEMOWSWAVE(:, :), NEMOPHIF(:, :), TAUXD(:, :),  &
      & TAUYD(:, :), TAUOCXD(:, :), TAUOCYD(:, :), TAUOC(:, :), PHIOCD(:, :), PHIEPS(:, :), PHIAW(:, :), .true., AFCRV, BFCRV,  &
      & CIBLOCK, CITHRSH, COSTH(:), EGRCRV, EPSU10, EPSUS, FR(:), G, LICERUN, LWAMRSETCI, LWNEMOCOU, LWNEMOTAUOC, NANG, NFRE,  &
      & PHIEPSMAX, PHIEPSMIN, SINTH(:), TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
    END IF
    ! ----------------------------------------------------------------------
    
    !*    2.5 REPLACE DIAGNOSTIC PART OF SPECTRA BY A F**(-5) TAIL.
    !         -----------------------------------------------------
    
    CALL FKMEAN_FC(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), EMEAN(:, ICHNK), FMEAN(:, ICHNK), F1MEAN(:, ICHNK),  &
    & AKMEAN(:, ICHNK), XKMEAN(:, ICHNK), DELTH, DFIM(:), DFIMFR(:), DFIMOFR(:), EPSMIN, FR(:), FRTAIL, G, NANG, NFRE, WETAIL,  &
    & WP1TAIL, ZPI, ICHNK, NCHNK, IJ)
    
    !     MEAN FREQUENCY CHARACTERISTIC FOR WIND SEA
    CALL FEMEANWS_FC(KIJS, KIJL, FL1(:, :, :, :), XLLWS(:, :, :, :), FMEANWS(:, ICHNK), EMEANWS(:, ICHNK), DELTH, DFIM(:),  &
    & DFIMOFR(:), EPSMIN, FR(:), FRTAIL, NANG, NFRE, WETAIL, ICHNK, NCHNK, IJ)
    
    CALL IMPHFTAIL_FC(KIJS, KIJL, MIJ(:, :), FLM(:, :, ICHNK), WAVNUM(:, :, :), XK2CG(:, :, :), FL1(:, :, :, :), NANG, NFRE,  &
    & ICHNK, NCHNK, IJ)
    
    
    !     UPDATE WINDSEA VARIANCE AND MEAN FREQUENCY IF PASSED TO ATMOSPHERE
    !     ------------------------------------------------------------------
    
    IF (LWFLUX) THEN
      IF (EMEANWS(IJ, ICHNK) < WSEMEAN_MIN) THEN
        WSEMEAN(IJ, ICHNK) = WSEMEAN_MIN
        WSFMEAN(IJ, ICHNK) = 2._JWRB*FR(NFRE)
      ELSE
        WSEMEAN(IJ, ICHNK) = EMEANWS(IJ, ICHNK)
        WSFMEAN(IJ, ICHNK) = FMEANWS(IJ, ICHNK)
      END IF
    END IF
    
    
    
    !*    2.6 SET FL1 ON ICE POINTS TO ZERO
    !         -----------------------------
    
    IF (LICERUN .and. LMASKICE) THEN
      CALL SETICE_FC(KIJS, KIJL, FL1(:, :, :, :), CICOVER(:, :), COSWDIF(:, :, ICHNK), CITHRSH, EPSMIN, FLMIN, NANG, NFRE,  &
      & ICHNK, NCHNK, IJ)
    END IF
    
    
    !*    2.7 SURFACE STOKES DRIFT AND STRAIN IN SEA ICE
    !         ------------------------------------------
    
    CALL STOKESTRN_FC(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), STOKFAC(:, :, :), DEPTH(:, :), WSWAVE(:, :), WDWAVE(:, :),  &
    & CICOVER(:, :), CITHICK(:, :), USTOKES(:, :), VSTOKES(:, :), STRNMS(:, :), NEMOUSTOKES(:, :), NEMOVSTOKES(:, :),  &
    & NEMOSTRN(:, :), CITHRSH, COSTH(:), DELTH, DFIM(:), DFIM_SIM(:), FLMIN, FR(:), G, LICERUN, LWAMRSETCI, LWCOU, LWNEMOCOU,  &
    & LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, SINTH(:), ZPI, ICHNK, NCHNK, IJ)
    
    ! ----------------------------------------------------------------------
    
    
    ! END of Loki inserted loop ICHNK
  END IF
END SUBROUTINE IMPLSCH_FC
