INTERFACE
  SUBROUTINE NS_GC_FC (USTAR, NWAV_GC, SQRTGOSURFT, XKM_GC, XLOGKRATIOM1_GC)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    REAL(KIND=JWRB), INTENT(IN) :: USTAR
    
    INTEGER(KIND=JWIM), INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), INTENT(IN) :: XLOGKRATIOM1_GC
!$acc routine seq
  END SUBROUTINE NS_GC_FC
END INTERFACE