INTERFACE
  SUBROUTINE SDISSIP_ARD_FC (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, UFRIC, COSWDIF, RAORW, CUMULW, G, INDICESSAT,  &
  & IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL, NFRE, NSDSNTH, SATWEIGHTS, SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR,  &
  & ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    USE YOWFRED, ONLY: FR, TH
    USE YOWPARAM, ONLY: NANG_PARAM
    USE YOWPHYS, ONLY: ISB, SSDSBRF1, BRKPBCOEF, ISDSDTH
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDEP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    
    
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CUMULW(:, :, :, :)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE SDISSIP_ARD_FC
END INTERFACE