! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
ATTRIBUTES(DEVICE) SUBROUTINE SDISSIP_FC (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF,  &
& RAORW, CDIS, CDISVIS, CUMULW, DELTA_SDIS, G, INDICESSAT, IPHYS, IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL, NFRE, NSDSNTH, RNU,  &
& SATWEIGHTS, SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR, ICHNK, NCHNK, IJ)
  ! ----------------------------------------------------------------------
  
  !**** *SDISSIP* - COMPUTATION OF DEEP WATER DISSIPATION SOURCE FUNCTION.
  
  
  !*    PURPOSE.
  !     --------
  !       COMPUTE DISSIPATION SOURCE FUNCTION AND STORE ADDITIVELY INTO
  !       NET SOURCE FUNCTION ARRAY. ALSO COMPUTE FUNCTIONAL DERIVATIVE
  !       OF DISSIPATION SOURCE FUNCTION.
  
  !**   INTERFACE.
  !     ----------
  
  !       *CALL* *SDISSIP (KIJS, KIJL, FL1, FLD, SL, *
  !                        INDEP, WAVNUM, XK2CG,
  !                        EMEAN, F1MEAN, XKMEAN,*
  !                        UFRIC, COSWDIF, RAORW)*
  !         *KIJS* - INDEX OF FIRST GRIDPOINT
  !         *KIJL* - INDEX OF LAST GRIDPOINT
  !         *FL1*  - SPECTRUM.
  !         *FLD*  - DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE
  !          *SL*  - TOTAL SOURCE FUNCTION ARRAY
  !       *INDEP*  - DEPTH INDEX
  !       *WAVNUM* - WAVE NUMBER
  !       *XK2CG*  - (WAVNUM)**2 * GROUP SPEED
  !        *EMEAN* - MEAN ENERGY DENSITY
  !       *F1MEAN* - MEAN FREQUENCY BASED ON 1st MOMENT.
  !       *XKMEAN* - MEAN WAVE NUMBER BASED ON 1st MOMENT.
  !       *UFRIC*  - FRICTION VELOCITY IN M/S.
  !       *RAORW*  - RATIO AIR DENSITY TO WATER DENSITY
  !       *COSWDIF*-  COS(TH(K)-WDWAVE(IJ))
  
  ! ----------------------------------------------------------------------
  USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
  
  
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE SDISSIP_ARD_FC (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, UFRIC, COSWDIF, RAORW)
      USE parkind_wave, ONLY: jwim, jwrb
      USE yowparam, ONLY: nang, nfre
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: INDEP
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, RAORW
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
    END SUBROUTINE SDISSIP_ARD_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SDISSIP_JAN_FC (KIJS, KIJL, FL1, FLD, SL, WAVNUM, EMEAN, F1MEAN, XKMEAN)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMEAN, F1MEAN, XKMEAN
    END SUBROUTINE SDISSIP_JAN_FC
  END INTERFACE
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDEP(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: EMEAN(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: F1MEAN(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMEAN(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
  
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CUMULW(:, :, :, :)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
  INTEGER, VALUE, INTENT(IN) :: NCHNK
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
  
  ! ----------------------------------------------------------------------
  
  
  SELECT CASE (IPHYS)
  CASE (0)
    CALL SDISSIP_JAN_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :), SL(:, :, :), WAVNUM(:, :, :), EMEAN(:), F1MEAN(:), XKMEAN(:),  &
    & CDIS, CDISVIS, DELTA_SDIS, NANG, NFRE, RNU, ZPI, ICHNK, NCHNK, IJ)
    
  CASE (1)
    CALL SDISSIP_ARD_FC(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :), SL(:, :, :), INDEP(:, :), WAVNUM(:, :, :), XK2CG(:, :, :),  &
    & UFRIC(:, :), COSWDIF(:, :), RAORW(:), CUMULW(:, :, :, :), G, INDICESSAT(:, :), IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL,  &
    & NFRE, NSDSNTH, SATWEIGHTS(:, :), SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR(:), ICHNK, NCHNK, IJ)
  END SELECT
  
  
END SUBROUTINE SDISSIP_FC
