MODULE SDISSIP_ARD_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SDISSIP_ARD_fc (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, UFRIC, COSWDIF, RAORW, CUMULW, G, INDICESSAT,  &
  & IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL, NFRE, NSDSNTH, SATWEIGHTS, SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR,  &
  & ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SDISSIP_ARD_iso_c (KIJS, KIJL, FL1, FLD, SL, INDEP, WAVNUM, XK2CG, UFRIC, COSWDIF, RAORW, CUMULW, G,  &
      & INDICESSAT, IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL, NFRE, NSDSNTH, SATWEIGHTS, SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5,  &
      & SSDSC6, ZPI, ZPIFR, ICHNK, NCHNK, IJ) BIND(c, name="sdissip_ard_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: INDEP
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: CUMULW
        REAL, VALUE :: G
        TYPE(c_ptr), VALUE :: INDICESSAT
        INTEGER(KIND=c_int), VALUE :: IPSAT
        REAL, VALUE :: MICHE
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NDEPTH
        INTEGER(KIND=c_int), VALUE :: NDIKCUMUL
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NSDSNTH
        TYPE(c_ptr), VALUE :: SATWEIGHTS
        REAL, VALUE :: SDSBR
        REAL, VALUE :: SSDSC2
        REAL, VALUE :: SSDSC3
        REAL, VALUE :: SSDSC4
        REAL, VALUE :: SSDSC5
        REAL, VALUE :: SSDSC6
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE SDISSIP_ARD_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDEP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CUMULW(:, :, :, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
!$acc host_data use_device( FL1, FLD, SL, INDEP, WAVNUM, XK2CG, UFRIC, COSWDIF, RAORW, CUMULW, INDICESSAT, SATWEIGHTS, ZPIFR )
    CALL SDISSIP_ARD_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(FLD), c_loc(SL), c_loc(INDEP), c_loc(WAVNUM), c_loc(XK2CG),  &
    & c_loc(UFRIC), c_loc(COSWDIF), c_loc(RAORW), c_loc(CUMULW), G, c_loc(INDICESSAT), IPSAT, MICHE, NANG, NDEPTH, NDIKCUMUL,  &
    & NFRE, NSDSNTH, c_loc(SATWEIGHTS), SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE SDISSIP_ARD_fc
END MODULE SDISSIP_ARD_FC_MOD
