! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
ATTRIBUTES(DEVICE) SUBROUTINE SINFLX_FC (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW,  &
& WSTAR, CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS,  &
& MIJ, RHOWGDFTH, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD,  &
& BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC, COSTH, DELKCC_GC_NS, DELKCC_OMXKM3_GC,  &
& DELTH, DFIM, DFIMOFR, DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR, FR5, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE,  &
& ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC, OMEGA_GC,  &
& OMXKM3_GC, RHOWG_DFIM, RN1_RN, RNU, RNUM, SINTH, SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7,  &
& SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH, WETAIL, WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC,  &
& XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ, RNFAC, TMP_EM,  &
& STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST)
  
  ! ----------------------------------------------------------------------
  
  !**** *SINFLX* - UPDATE STRESS AND COMPUTE WIND INPUT SOURCE TERM.
  
  ! ----------------------------------------------------------------------
  
  USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
  
  
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE AIRSEA_FC (KIJS, KIJL, HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG)
      USE parkind_wave, ONLY: jwim, jwrb
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, ICODE_WND, IUSFG
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: HALP, U10DIR, TAUW, TAUWDIR, RNFAC
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: U10, US
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: Z0, Z0B, CHRNCK
    END SUBROUTINE AIRSEA_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE FEMEANWS_FC (KIJS, KIJL, FL1, XLLWS, FM, EM)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
      REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
    END SUBROUTINE FEMEANWS_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE FRCUTINDEX_FC (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FM, FMWS, UFRIC, CICOVER
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
    END SUBROUTINE FRCUTINDEX_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE HALPHAP_FC (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP)
      USE parkind_wave, ONLY: jwim, jwrb
      USE yowparam, ONLY: nang, nfre
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: HALP
    END SUBROUTINE HALPHAP_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE SINPUT_FC (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
    & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: NGST
      LOGICAL, INTENT(IN) :: LLSNEG
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CINV, XK2CG
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, WSWAVE, UFRIC, Z0M
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW, WSTAR, RNFAC
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL, SPOS
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
    END SUBROUTINE SINPUT_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE STRESSO_FC (KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2,  &
    & TAUW, TAUWDIR, PHIWA, LLPHIWA)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), INTENT(IN) :: MIJ(KIJL)
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, SL, SPOS
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, UFRIC, Z0M, AIRD, RNFAC
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: TAUW, TAUWDIR, PHIWA
      LOGICAL, INTENT(IN) :: LLPHIWA
    END SUBROUTINE STRESSO_FC
  END INTERFACE
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICALL  !! CALL NUMBER.
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS  !! GRID POINT INDEXES.
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL  !! GRID POINT INDEXES.
  
  LOGICAL, VALUE, INTENT(IN) :: LUPDTUS  !! IF TRUE UFRIC AND Z0M WILL BE UPDATED (CALLING AIRSEA).
  
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)  !! WAVE SPECTRUM.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)  !! WAVE NUMBER.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)  !! INVERSE PHASE VELOCITY.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)  !! (WAVNUM)**2 * GROUP SPPED.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)  !! WIND SPEED IN M/S.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)  !! WIND DIRECTION IN RADIANS IN OCEANOGRAPHIC NOTATION.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)  !! AIR DENSITY (KG/M**3).
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)  !! RATIO AIR DENSITY TO WATER DENSITY.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)  !! FREE CONVECTION VELOCITY SCALE (M/S)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)  !! SEA ICE COVER.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)  !! COS(TH(K)-WDWAVE(IJ))
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)  !! SIN(TH(K)-WDWAVE(IJ))**2
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FMEAN(:)  !! MEAN FREQUENCY.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:)  !! 1/2 PHILLIPS PARAMETER
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FMEANWS(:)  !! MEAN FREQUENCY OF THE WINDSEA.
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLM(:, :)  !! SPECTAL DENSITY MINIMUM VALUE
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)  !! FRICTION VELOCITY IN M/S.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)  !! WAVE STRESS IN (M/S)**2
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)  !! WAVE STRESS DIRECTION.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)  !! ROUGHNESS LENGTH IN M.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)  !! BACKGROUND ROUGHNESS LENGTH.
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)  !! CHARNOCK COEFFICIENT.
  
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: PHIWA(:)  !! ENERGY FLUX FROM WIND INTO WAVES.
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)  !! DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE.
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)  !! TOTAL SOURCE FUNCTION ARRAY.
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)  !!  POSITIVE SINPUT ONLY.
  
  INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)  !! LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
  
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: RHOWGDFTH(:, :)  !! WATER DENSITY * G * DF * DTHETA
  
  REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)  !! TOTAL WINDSEA MASK FROM INPUT SOURCE TERM.
  
  
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
  INTEGER(KIND=JWIM) :: K
  INTEGER(KIND=JWIM) :: IUSFG
  INTEGER(KIND=JWIM) :: ICODE_WND
  INTEGER(KIND=JWIM) :: NGST
  
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RNFAC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TMP_EM(:, :)
  
  LOGICAL :: LLPHIWA
  LOGICAL :: LLSNEG
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
  LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
  LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
  LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
  LOGICAL, VALUE, INTENT(IN) :: LWCOU
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
  INTEGER, VALUE, INTENT(IN) :: NCHNK
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
  
  ! ----------------------------------------------------------------------
  
  
  ! UPDATE UFRIC AND Z0M
  IF (ICALL == 1) THEN
    IUSFG = 0
    IF (LWCOU) THEN
      ICODE_WND = ICODE_CPL
    ELSE
      ICODE_WND = ICODE
    END IF
    
    LLPHIWA = .false.
    LLSNEG = .false.
  ELSE
    IUSFG = 1
    ICODE_WND = 3
    
    LLPHIWA = .true.
    LLSNEG = .true.
  END IF
  
  
  IF (LLNORMAGAM .and. LLCAPCHNK) THEN
    RNFAC(IJ, ICHNK) = 1.0_JWRB + DTHRN_A*(1.0_JWRB + TANH(WSWAVE(IJ, ICHNK) - DTHRN_U))
  ELSE
    RNFAC(IJ, ICHNK) = 1.0_JWRB
  END IF
  
  
  
  IF (LUPDTUS) THEN
    ! increase noise level in the tail
    IF (ICALL == 1) THEN
      
      DO K=1,NANG
        FL1(IJ, K, NFRE, ICHNK) = MAX(FL1(IJ, K, NFRE, ICHNK), FLM(IJ, K))
      END DO
      
      
      IF (LLGCBZ0) THEN
        CALL HALPHAP_FC(KIJS, KIJL, WAVNUM(:, :, :), COSWDIF(:, :), FL1(:, :, :, :), HALP(:), ALPHAPMAX, DELTH, DFIM(:),  &
        & DFIMOFR(:), EPSMIN, FR(:), FR5(:), FRTAIL, NANG, NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ)
      ELSE
        
        HALP(IJ) = 0.0_JWRB
        
      END IF
      
    END IF
    
    CALL AIRSEA_FC(KIJS, KIJL, HALP(:), WSWAVE(:, :), WDWAVE(:, :), TAUW(:, :), TAUWDIR(:, :), RNFAC(:, ICHNK), UFRIC(:, :),  &
    & Z0M(:, :), Z0B(:, :), CHRNCK(:, :), ICODE_WND, IUSFG, ACD, ALPHA, ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD,  &
    & BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC(:), CDMAX, CHNKMIN_U, CM_GC(:), DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:), EPS1,  &
    & EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, NWAV_GC, OM3GMKM_GC(:), OMXKM3_GC(:), RN1_RN, RNU, RNUM,  &
    & SQRTGOSURFT, WSPMIN, XKAPPA, XKMSQRTVGOC2_GC(:), XKM_GC(:), XK_GC(:), XLOGKRATIOM1_GC, XNLEV, ZALP, ICHNK, NCHNK, IJ)
    
  END IF
  
  ! COMPUTE WIND INPUT
  !!  FLD AND SL ARE INITIALISED IN SINPUT
  
  CALL SINPUT_FC(ICALL, LLSNEG, KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :), WDWAVE(:, :),  &
  & WSWAVE(:, :), UFRIC(:, :), Z0M(:, :), COSWDIF(:, :), SINWDIF2(:, :), RAORW(:), WSTAR(:, :), RNFAC(:, ICHNK), FLD(:, :, :),  &
  & SL(:, :, :), SPOS(:, :, :), XLLWS(:, :, :, :), ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, COSTH(:),  &
  & DELTH, DFIM(:), EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH(:), SWELLF,  &
  & SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:), TAUWSHELTER, TH(:), WSPMIN, XKAPPA, Z0RAT,  &
  & Z0TUBMAX, ZALP, ZPI, ZPIFR(:), ICHNK, NCHNK, IJ)
  
  
  ! MEAN FREQUENCY CHARACTERISTIC FOR WIND SEA
  CALL FEMEANWS_FC(KIJS, KIJL, FL1(:, :, :, :), XLLWS(:, :, :, :), FMEANWS(:), TMP_EM(:, ICHNK), DELTH, DFIM(:), DFIMOFR(:),  &
  & EPSMIN, FR(:), FRTAIL, NANG, NFRE, WETAIL, ICHNK, NCHNK, IJ)
  
  ! COMPUTE LAST FREQUENCY INDEX OF PROGNOSTIC PART OF SPECTRUM.
  CALL FRCUTINDEX_FC(KIJS, KIJL, FMEAN(:), FMEANWS(:), UFRIC(:, :), CICOVER(:, :), MIJ(:, :), RHOWGDFTH(:, :), CITHRSH_TAIL,  &
  & EPSMIN, FLOGSPRDM1, FR(:), FRIC, G, NFRE, RHOWG_DFIM(:), TAILFACTOR, TAILFACTOR_PM, ZPIFR(:), ICHNK, NCHNK, IJ)
  
  ! UPDATE TAUW
  CALL STRESSO_FC(KIJS, KIJL, MIJ(:, :), RHOWGDFTH(:, :), FL1(:, :, :, :), SL(:, :, :), SPOS(:, :, :), CINV(:, :, :),  &
  & WDWAVE(:, :), UFRIC(:, :), Z0M(:, :), AIRD(:, :), RNFAC(:, ICHNK), COSWDIF(:, :), SINWDIF2(:, :), TAUW(:, :), TAUWDIR(:, :),  &
  & PHIWA(:), LLPHIWA, COSTH(:), DELTH, EPS1, FR5(:), G, GAMNCONST, GM1, IPHYS, JTOT_TAUHF, LLGCBZ0, LLNORMAGAM, NANG, NFRE,  &
  & NWAV_GC, OMEGA_GC(:), RHOWG_DFIM(:), SINTH(:), SQRTGOSURFT, TAUWSHELTER, WTAUHF(:), X0TAUHF, XKAPPA, XKM_GC(:), XK_GC(:),  &
  & XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, ZPIFR(:), ICHNK, NCHNK, IJ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF,  &
  & STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST)
  
  ! ----------------------------------------------------------------------
  
  
END SUBROUTINE SINFLX_FC
