MODULE SINFLX_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SINFLX_fc (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER,  &
  & COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ, RHOWGDFTH,  &
  & XLLWS, ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BCDLIN,  &
  & BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC, COSTH, DELKCC_GC_NS, DELKCC_OMXKM3_GC,  &
  & DELTH, DFIM, DFIMOFR, DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR, FR5, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB,  &
  & ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC,  &
  & OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RN1_RN, RNU, RNUM, SINTH, SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6,  &
  & SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH, WETAIL, WSPMIN, WTAUHF, X0TAUHF, XKAPPA,  &
  & XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK,  &
  & IJ, RNFAC, TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE AIRSEA (KIJS, KIJL, HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, ICODE_WND, IUSFG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: HALP, U10DIR, TAUW, TAUWDIR, RNFAC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: U10, US
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: Z0, Z0B, CHRNCK
      END SUBROUTINE AIRSEA
    END INTERFACE
    INTERFACE
      SUBROUTINE FEMEANWS (KIJS, KIJL, FL1, XLLWS, FM, EM)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
        REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
      END SUBROUTINE FEMEANWS
    END INTERFACE
    INTERFACE
      SUBROUTINE FRCUTINDEX (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FM, FMWS, UFRIC, CICOVER
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
      END SUBROUTINE FRCUTINDEX
    END INTERFACE
    INTERFACE
      SUBROUTINE HALPHAP (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: HALP
      END SUBROUTINE HALPHAP
    END INTERFACE
    INTERFACE
      SUBROUTINE SINPUT (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
      & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: NGST
        LOGICAL, INTENT(IN) :: LLSNEG
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CINV, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, WSWAVE, UFRIC, Z0M
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW, WSTAR, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL, SPOS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINPUT
    END INTERFACE
    INTERFACE
      SUBROUTINE STRESSO (KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2,  &
      & TAUW, TAUWDIR, PHIWA, LLPHIWA)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, SL, SPOS
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, UFRIC, Z0M, AIRD, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: TAUW, TAUWDIR, PHIWA
        LOGICAL, INTENT(IN) :: LLPHIWA
      END SUBROUTINE STRESSO
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICALL    !! CALL NUMBER.
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS    !! GRID POINT INDEXES.
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL    !! GRID POINT INDEXES.
    
    LOGICAL, VALUE, INTENT(IN) :: LUPDTUS    !! IF TRUE UFRIC AND Z0M WILL BE UPDATED (CALLING AIRSEA).
    
    
    
    
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SINFLX_iso_c (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR,  &
      & CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS,  &
      & MIJ, RHOWGDFTH, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C,  &
      & BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC, COSTH, DELKCC_GC_NS,  &
      & DELKCC_OMXKM3_GC, DELTH, DFIM, DFIMOFR, DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR, FR5, FRIC, FRTAIL, G,  &
      & GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE,  &
      & NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RN1_RN, RNU, RNUM, SINTH, SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3,  &
      & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH, WETAIL, WSPMIN,  &
      & WTAUHF, X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ, RNFAC, TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF,  &
      & STRESSO_USDIRP, STRESSO_UST) BIND(c, name="sinflx_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: ICALL
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        LOGICAL, VALUE :: LUPDTUS
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: FMEAN
        TYPE(c_ptr), VALUE :: HALP
        TYPE(c_ptr), VALUE :: FMEANWS
        TYPE(c_ptr), VALUE :: FLM
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: Z0B
        TYPE(c_ptr), VALUE :: CHRNCK
        TYPE(c_ptr), VALUE :: PHIWA
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACD
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHA
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: ANG_GC_A
        REAL, VALUE :: ANG_GC_B
        REAL, VALUE :: ANG_GC_C
        REAL, VALUE :: BCD
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BMAXOKAP
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        REAL, VALUE :: CDMAX
        REAL, VALUE :: CHNKMIN_U
        REAL, VALUE :: CITHRSH_TAIL
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: COSTH
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMOFR
        REAL, VALUE :: DTHRN_A
        REAL, VALUE :: DTHRN_U
        REAL, VALUE :: EPS1
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: FLOGSPRDM1
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRIC
        REAL, VALUE :: FRTAIL
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: IAB
        INTEGER(KIND=c_int), VALUE :: ICODE
        INTEGER(KIND=c_int), VALUE :: ICODE_CPL
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        LOGICAL, VALUE :: LLCAPCHNK
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        LOGICAL, VALUE :: LWCOU
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        REAL, VALUE :: RN1_RN
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAILFACTOR
        REAL, VALUE :: TAILFACTOR_PM
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WSPMIN
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: XNLEV
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: TMP_EM
        TYPE(c_ptr), VALUE :: STRESSO_XSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_YSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_TAUHF
        TYPE(c_ptr), VALUE :: STRESSO_PHIHF
        TYPE(c_ptr), VALUE :: STRESSO_USDIRP
        TYPE(c_ptr), VALUE :: STRESSO_UST
      END SUBROUTINE SINFLX_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FMEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FMEANWS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: PHIWA(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TMP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
!$acc host_data use_device( FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER, COSWDIF, SINWDIF2, FMEAN,  &
!$acc & HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ, RHOWGDFTH, XLLWS, C2OSQRTVG_GC,  &
!$acc & CM_GC, COSTH, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DFIM, DFIMOFR, FR, FR5, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM,  &
!$acc & SINTH, SWELLFT, TH, WTAUHF, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, ZPIFR, RNFAC, TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS,  &
!$acc & STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST )
    CALL SINFLX_iso_c(ICALL, KIJS, KIJL, LUPDTUS, c_loc(FL1), c_loc(WAVNUM), c_loc(CINV), c_loc(XK2CG), c_loc(WSWAVE),  &
    & c_loc(WDWAVE), c_loc(AIRD), c_loc(RAORW), c_loc(WSTAR), c_loc(CICOVER), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(FMEAN),  &
    & c_loc(HALP), c_loc(FMEANWS), c_loc(FLM), c_loc(UFRIC), c_loc(TAUW), c_loc(TAUWDIR), c_loc(Z0M), c_loc(Z0B), c_loc(CHRNCK),  &
    & c_loc(PHIWA), c_loc(FLD), c_loc(SL), c_loc(SPOS), c_loc(MIJ), c_loc(RHOWGDFTH), c_loc(XLLWS), ABMAX, ABMIN, ACD, ACDLIN,  &
    & ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP,  &
    & c_loc(C2OSQRTVG_GC), CDMAX, CHNKMIN_U, CITHRSH_TAIL, c_loc(CM_GC), c_loc(COSTH), c_loc(DELKCC_GC_NS),  &
    & c_loc(DELKCC_OMXKM3_GC), DELTH, c_loc(DFIM), c_loc(DFIMOFR), DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, c_loc(FR),  &
    & c_loc(FR5), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0,  &
    & LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, c_loc(OM3GMKM_GC), c_loc(OMEGA_GC), c_loc(OMXKM3_GC), c_loc(RHOWG_DFIM), RN1_RN,  &
    & RNU, RNUM, c_loc(SINTH), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1,  &
    & c_loc(SWELLFT), TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, c_loc(TH), WETAIL, WSPMIN, c_loc(WTAUHF), X0TAUHF, XKAPPA,  &
    & c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2,  &
    & c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(RNFAC), c_loc(TMP_EM), c_loc(STRESSO_XSTRESS), c_loc(STRESSO_YSTRESS),  &
    & c_loc(STRESSO_TAUHF), c_loc(STRESSO_PHIHF), c_loc(STRESSO_USDIRP), c_loc(STRESSO_UST))
!$acc end host_data
  END SUBROUTINE SINFLX_fc
END MODULE SINFLX_FC_MOD
