INTERFACE
  SUBROUTINE SINPUT_FC (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
  & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, COSTH, DELTH,  &
  & DFIM, EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH, SWELLF, SWELLF2, SWELLF3,  &
  & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPIFR,  &
  & ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    
    USE SINPUT_ARD_FC_MOD, ONLY: SINPUT_ARD_FC, SINPUT_JAN_FC
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NGST
    LOGICAL, VALUE, INTENT(IN) :: LLSNEG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
  END SUBROUTINE SINPUT_FC
END INTERFACE