MODULE SNONLIN_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SNONLIN_fc (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN, AF11, BATHYMAX, COSTH, DAL1, DAL2, DELTH, DFIM,  &
  & DFIMFR, DFIMFR2, DKMAX, FKLAM, FKLAM1, FKLAP, FKLAP1, FR, FRATIO, G, GM1, IKM, IKM1, IKP, IKP1, INLCOEF, ISNONLIN, K11W,  &
  & K1W, K21W, K2W, KFRH, MFRSTLW, MLSTHG, NANG, NFRE, RNLCOEF, SINTH, TH, WETAIL, WP1TAIL, WP2TAIL, XKDMIN, ZPIFR, ICHNK,  &
  & NCHNK, IJ, ENH, XNU, SIG_TH)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE PEAK_ANG (KIJS, KIJL, FL1, XNU, SIG_TH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: XNU, SIG_TH
      END SUBROUTINE PEAK_ANG
    END INTERFACE
    INTERFACE
      FUNCTION TRANSF (XK, D)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: TRANSF
        REAL(KIND=JWRB), INTENT(IN) :: XK, D
      END FUNCTION TRANSF
    END INTERFACE
    INTERFACE
      FUNCTION TRANSF_SNL (XK0, D, XNU, SIG_TH)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: TRANSF_SNL
        REAL(KIND=JWRB), INTENT(IN) :: XK0, D, XNU, SIG_TH
      END FUNCTION TRANSF_SNL
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SNONLIN_iso_c (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN, AF11, BATHYMAX, COSTH, DAL1, DAL2, DELTH, DFIM,  &
      & DFIMFR, DFIMFR2, DKMAX, FKLAM, FKLAM1, FKLAP, FKLAP1, FR, FRATIO, G, GM1, IKM, IKM1, IKP, IKP1, INLCOEF, ISNONLIN, K11W,  &
      & K1W, K21W, K2W, KFRH, MFRSTLW, MLSTHG, NANG, NFRE, RNLCOEF, SINTH, TH, WETAIL, WP1TAIL, WP2TAIL, XKDMIN, ZPIFR, ICHNK,  &
      & NCHNK, IJ, ENH, XNU, SIG_TH) BIND(c, name="snonlin_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: DEPTH
        TYPE(c_ptr), VALUE :: AKMEAN
        TYPE(c_ptr), VALUE :: AF11
        REAL, VALUE :: BATHYMAX
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DAL1
        REAL, VALUE :: DAL2
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMFR
        TYPE(c_ptr), VALUE :: DFIMFR2
        REAL, VALUE :: DKMAX
        TYPE(c_ptr), VALUE :: FKLAM
        TYPE(c_ptr), VALUE :: FKLAM1
        TYPE(c_ptr), VALUE :: FKLAP
        TYPE(c_ptr), VALUE :: FKLAP1
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: FRATIO
        REAL, VALUE :: G
        REAL, VALUE :: GM1
        TYPE(c_ptr), VALUE :: IKM
        TYPE(c_ptr), VALUE :: IKM1
        TYPE(c_ptr), VALUE :: IKP
        TYPE(c_ptr), VALUE :: IKP1
        TYPE(c_ptr), VALUE :: INLCOEF
        INTEGER(KIND=c_int), VALUE :: ISNONLIN
        TYPE(c_ptr), VALUE :: K11W
        TYPE(c_ptr), VALUE :: K1W
        TYPE(c_ptr), VALUE :: K21W
        TYPE(c_ptr), VALUE :: K2W
        INTEGER(KIND=c_int), VALUE :: KFRH
        INTEGER(KIND=c_int), VALUE :: MFRSTLW
        INTEGER(KIND=c_int), VALUE :: MLSTHG
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        TYPE(c_ptr), VALUE :: RNLCOEF
        TYPE(c_ptr), VALUE :: SINTH
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WP1TAIL
        REAL, VALUE :: WP2TAIL
        REAL, VALUE :: XKDMIN
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: ENH
        TYPE(c_ptr), VALUE :: XNU
        TYPE(c_ptr), VALUE :: SIG_TH
      END SUBROUTINE SNONLIN_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AKMEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AF11(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR2(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INLCOEF(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K11W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K1W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K21W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K2W(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNLCOEF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ENH(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XNU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SIG_TH(:, :)
!$acc host_data use_device( FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN, AF11, COSTH, DFIM, DFIMFR, DFIMFR2, FKLAM, FKLAM1, FKLAP,  &
!$acc & FKLAP1, FR, IKM, IKM1, IKP, IKP1, INLCOEF, K11W, K1W, K21W, K2W, RNLCOEF, SINTH, TH, ZPIFR, ENH, XNU, SIG_TH )
    CALL SNONLIN_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(FLD), c_loc(SL), c_loc(WAVNUM), c_loc(DEPTH), c_loc(AKMEAN), c_loc(AF11),  &
    & BATHYMAX, c_loc(COSTH), DAL1, DAL2, DELTH, c_loc(DFIM), c_loc(DFIMFR), c_loc(DFIMFR2), DKMAX, c_loc(FKLAM), c_loc(FKLAM1),  &
    & c_loc(FKLAP), c_loc(FKLAP1), c_loc(FR), FRATIO, G, GM1, c_loc(IKM), c_loc(IKM1), c_loc(IKP), c_loc(IKP1), c_loc(INLCOEF),  &
    & ISNONLIN, c_loc(K11W), c_loc(K1W), c_loc(K21W), c_loc(K2W), KFRH, MFRSTLW, MLSTHG, NANG, NFRE, c_loc(RNLCOEF),  &
    & c_loc(SINTH), c_loc(TH), WETAIL, WP1TAIL, WP2TAIL, XKDMIN, c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(ENH), c_loc(XNU),  &
    & c_loc(SIG_TH))
!$acc end host_data
  END SUBROUTINE SNONLIN_fc
END MODULE SNONLIN_FC_MOD
