INTERFACE
  SUBROUTINE SNONLIN_FC (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN, AF11, BATHYMAX, COSTH, DAL1, DAL2, DELTH, DFIM,  &
  & DFIMFR, DFIMFR2, DKMAX, FKLAM, FKLAM1, FKLAP, FKLAP1, FR, FRATIO, G, GM1, IKM, IKM1, IKP, IKP1, INLCOEF, ISNONLIN, K11W,  &
  & K1W, K21W, K2W, KFRH, MFRSTLW, MLSTHG, NANG, NFRE, RNLCOEF, SINTH, TH, WETAIL, WP1TAIL, WP2TAIL, XKDMIN, ZPIFR, ICHNK,  &
  & NCHNK, IJ, ENH, XNU, SIG_TH)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE PEAK_ANG_FC (KIJS, KIJL, FL1, XNU, SIG_TH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: XNU, SIG_TH
      END SUBROUTINE PEAK_ANG_FC
    END INTERFACE
    INTERFACE
      FUNCTION TRANSF_FC (XK, D)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: TRANSF
        REAL(KIND=JWRB), INTENT(IN) :: XK, D
      END FUNCTION TRANSF_FC
    END INTERFACE
    INTERFACE
      FUNCTION TRANSF_SNL_FC (XK0, D, XNU, SIG_TH)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: TRANSF_SNL
        REAL(KIND=JWRB), INTENT(IN) :: XK0, D, XNU, SIG_TH
      END FUNCTION TRANSF_SNL_FC
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AKMEAN(:)
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ENH(:, :, :)
    
    
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XNU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SIG_TH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AF11(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR2(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INLCOEF(:, :)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K11W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K1W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K21W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K2W(:, :)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNLCOEF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE SNONLIN_FC
END INTERFACE