MODULE STOKESDRIFT_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE STOKESDRIFT_fc (KIJS, KIJL, FL1, STOKFAC, WSWAVE, WDWAVE, CICOVER, USTOKES, VSTOKES, CITHRSH, COSTH, DELTH,  &
  & DFIM_SIM, FR, G, LICERUN, LWAMRSETCI, NANG, NFRE_ODD, SINTH, ZPI, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE STOKESDRIFT_iso_c (KIJS, KIJL, FL1, STOKFAC, WSWAVE, WDWAVE, CICOVER, USTOKES, VSTOKES, CITHRSH, COSTH, DELTH,  &
      & DFIM_SIM, FR, G, LICERUN, LWAMRSETCI, NANG, NFRE_ODD, SINTH, ZPI, ICHNK, NCHNK, IJ) BIND(c, name="stokesdrift_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: STOKFAC
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: USTOKES
        TYPE(c_ptr), VALUE :: VSTOKES
        REAL, VALUE :: CITHRSH
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM_SIM
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: G
        LOGICAL, VALUE :: LICERUN
        LOGICAL, VALUE :: LWAMRSETCI
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE_ODD
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: ZPI
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE STOKESDRIFT_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: USTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: VSTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
!$acc host_data use_device( FL1, STOKFAC, WSWAVE, WDWAVE, CICOVER, USTOKES, VSTOKES, COSTH, DFIM_SIM, FR, SINTH )
    CALL STOKESDRIFT_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(STOKFAC), c_loc(WSWAVE), c_loc(WDWAVE), c_loc(CICOVER), c_loc(USTOKES),  &
    & c_loc(VSTOKES), CITHRSH, c_loc(COSTH), DELTH, c_loc(DFIM_SIM), c_loc(FR), G, LICERUN, LWAMRSETCI, NANG, NFRE_ODD,  &
    & c_loc(SINTH), ZPI, ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE STOKESDRIFT_fc
END MODULE STOKESDRIFT_FC_MOD
