! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
ATTRIBUTES(DEVICE) SUBROUTINE STOKESTRN_FC (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES,  &
& VSTOKES, STRNMS, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, CITHRSH, COSTH, DELTH, DFIM, DFIM_SIM, FLMIN, FR, G, LICERUN, LWAMRSETCI,  &
& LWCOU, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, SINTH, ZPI, ICHNK, NCHNK, IJ)
  
  ! ----------------------------------------------------------------------
  
  !**** *STOKESTRN* - WRAPPER TO CALL STOKESDRIFT and CIMSSTRN
  
  !*    PURPOSE.
  !     --------
  
  !**   INTERFACE.
  !     ----------
  
  !       *CALL* *STOKESTRN (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, FF_NOW, INTFLDS, WAM2NEMO)
  
  !          *KIJS*    - INDEX OF FIRST GRIDPOINT.
  !          *KIJL*    - INDEX OF LAST GRIDPOINT.
  !          *FL1*     - SPECTRUM(INPUT).
  !          *WAVNUM*  - WAVE NUMBER.
  !          *STOKFAC* - STOKES DRIFT FACTOR.
  !          *DEPTH*   - WATER DEPTH.
  !          *FF_NOW*  - FORCING FIELDS AT CURRENT TIME.
  !          *INTFLDS* - INTEGRATED/DERIVED PARAMETERS
  !          *WAM2NEMO*- WAVE FIELDS PASSED TO NEMO
  
  ! ----------------------------------------------------------------------
  
  USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRO, JWRB
  USE YOWDRVTYPE, ONLY: WAVE2OCEAN, FORCING_FIELDS, INTGT_PARAM_FIELDS
  
  
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE CIMSSTRN_FC (KIJS, KIJL, FL1, WAVNUM, DEPTH, CITHICK, STRN)
      USE parkind_wave, ONLY: jwim, jwrb
      USE YOWPARAM, ONLY: NANG, NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CITHICK
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: STRN
    END SUBROUTINE CIMSSTRN_FC
  END INTERFACE
  INTERFACE
    SUBROUTINE STOKESDRIFT_FC (KIJS, KIJL, FL1, STOKFAC, WSWAVE, WDWAVE, CICOVER, USTOKES, VSTOKES)
      USE parkind_wave, ONLY: jwim, jwrb
      USE yowparam, ONLY: nang, nfre
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: STOKFAC
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, WDWAVE, CICOVER
      REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: USTOKES, VSTOKES
    END SUBROUTINE STOKESDRIFT_FC
  END INTERFACE
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
  
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CITHICK(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTOKES(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTOKES(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRNMS(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOUSTOKES(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOVSTOKES(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOSTRN(:, :)
  
  
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
  LOGICAL, VALUE, INTENT(IN) :: LICERUN
  LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
  LOGICAL, VALUE, INTENT(IN) :: LWCOU
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
  INTEGER, VALUE, INTENT(IN) :: NCHNK
  
  ! ----------------------------------------------------------------------
  
  
  CALL STOKESDRIFT_FC(KIJS, KIJL, FL1(:, :, :, :), STOKFAC(:, :, :), WSWAVE(:, :), WDWAVE(:, :), CICOVER(:, :), USTOKES(:, :),  &
  & VSTOKES(:, :), CITHRSH, COSTH(:), DELTH, DFIM_SIM(:), FR(:), G, LICERUN, LWAMRSETCI, NANG, NFRE_ODD, SINTH(:), ZPI, ICHNK,  &
  & NCHNK, IJ)
  
  IF (LWNEMOCOUSTRN) CALL CIMSSTRN_FC(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), DEPTH(:, :), CITHICK(:, :), STRNMS(:, :), DELTH, DFIM(:),  &
  & FLMIN, G, NANG, NFRE, ROWATER, ICHNK, NCHNK, IJ)
  
  
  
  IF (LWNEMOCOU .and. (LWNEMOCOUSEND .and. LWCOU .or. .not.LWCOU)) THEN
    IF (LWNEMOCOUSTK) THEN
      NEMOUSTOKES(IJ, ICHNK) = USTOKES(IJ, ICHNK)
      NEMOVSTOKES(IJ, ICHNK) = VSTOKES(IJ, ICHNK)
    ELSE
      NEMOUSTOKES(IJ, ICHNK) = 0.0_JWRO
      NEMOVSTOKES(IJ, ICHNK) = 0.0_JWRO
    END IF
    
    IF (LWNEMOCOUSTRN) NEMOSTRN(IJ, ICHNK) = STRNMS(IJ, ICHNK)
  END IF
  
  
  
  ! ----------------------------------------------------------------------
  
END SUBROUTINE STOKESTRN_FC
