MODULE STOKESTRN_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE STOKESTRN_fc (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES, STRNMS,  &
  & NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, CITHRSH, COSTH, DELTH, DFIM, DFIM_SIM, FLMIN, FR, G, LICERUN, LWAMRSETCI, LWCOU,  &
  & LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, SINTH, ZPI, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRO, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE CIMSSTRN (KIJS, KIJL, FL1, WAVNUM, DEPTH, CITHICK, STRN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CITHICK
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: STRN
      END SUBROUTINE CIMSSTRN
    END INTERFACE
    INTERFACE
      SUBROUTINE STOKESDRIFT (KIJS, KIJL, FL1, STOKFAC, WSWAVE, WDWAVE, CICOVER, USTOKES, VSTOKES)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: STOKFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, WDWAVE, CICOVER
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: USTOKES, VSTOKES
      END SUBROUTINE STOKESDRIFT
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE STOKESTRN_iso_c (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES,  &
      & STRNMS, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, CITHRSH, COSTH, DELTH, DFIM, DFIM_SIM, FLMIN, FR, G, LICERUN, LWAMRSETCI,  &
      & LWCOU, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, SINTH, ZPI, ICHNK, NCHNK, IJ &
      & ) BIND(c, name="stokestrn_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: STOKFAC
        TYPE(c_ptr), VALUE :: DEPTH
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: CITHICK
        TYPE(c_ptr), VALUE :: USTOKES
        TYPE(c_ptr), VALUE :: VSTOKES
        TYPE(c_ptr), VALUE :: STRNMS
        TYPE(c_ptr), VALUE :: NEMOUSTOKES
        TYPE(c_ptr), VALUE :: NEMOVSTOKES
        TYPE(c_ptr), VALUE :: NEMOSTRN
        REAL, VALUE :: CITHRSH
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIM_SIM
        REAL, VALUE :: FLMIN
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: G
        LOGICAL, VALUE :: LICERUN
        LOGICAL, VALUE :: LWAMRSETCI
        LOGICAL, VALUE :: LWCOU
        LOGICAL, VALUE :: LWNEMOCOU
        LOGICAL, VALUE :: LWNEMOCOUSEND
        LOGICAL, VALUE :: LWNEMOCOUSTK
        LOGICAL, VALUE :: LWNEMOCOUSTRN
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NFRE_ODD
        REAL, VALUE :: ROWATER
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: ZPI
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE STOKESTRN_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CITHICK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRNMS(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOUSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOVSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOSTRN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
!$acc host_data use_device( FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES, STRNMS,  &
!$acc & NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, COSTH, DFIM, DFIM_SIM, FR, SINTH )
    CALL STOKESTRN_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(STOKFAC), c_loc(DEPTH), c_loc(WSWAVE), c_loc(WDWAVE),  &
    & c_loc(CICOVER), c_loc(CITHICK), c_loc(USTOKES), c_loc(VSTOKES), c_loc(STRNMS), c_loc(NEMOUSTOKES), c_loc(NEMOVSTOKES),  &
    & c_loc(NEMOSTRN), CITHRSH, c_loc(COSTH), DELTH, c_loc(DFIM), c_loc(DFIM_SIM), FLMIN, c_loc(FR), G, LICERUN, LWAMRSETCI,  &
    & LWCOU, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, c_loc(SINTH), ZPI, ICHNK,  &
    & NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE STOKESTRN_fc
END MODULE STOKESTRN_FC_MOD
