MODULE STRESS_GC_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE STRESS_GC_fc (ANG_GC, USTAR, Z0, Z0MIN, HALP, RNFAC, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CM_GC, DELKCC_GC_NS,  &
  & DELKCC_OMXKM3_GC, EPSUS, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC, RN1_RN, SQRTGOSURFT, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC,  &
  & XK_GC, XLOGKRATIOM1_GC, ZALP)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    
    !----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      FUNCTION NS_GC (USTAR)
        USE parkind_wave, ONLY: jwrb
        INTEGER :: NS_GC
        REAL(KIND=JWRB), INTENT(IN) :: USTAR
      END FUNCTION NS_GC
    END INTERFACE
    
    REAL(KIND=JWRB), INTENT(IN) :: ANG_GC    ! factor to account for angular spreading of the input.
    REAL(KIND=JWRB), INTENT(IN) :: USTAR    ! friction velocity
    REAL(KIND=JWRB), INTENT(IN) :: Z0    !  surface roughness
    REAL(KIND=JWRB), INTENT(IN) :: Z0MIN    ! minimum surface roughness
    REAL(KIND=JWRB), INTENT(IN) :: HALP    ! 1/2 Phillips parameter
    REAL(KIND=JWRB), INTENT(IN) :: RNFAC    ! wind dependent factor used in the growth renormalisation
    
    
    
    ! XLAMBDA = 1.0_JWRB + XLAMA * TANH(XLAMB * USTAR**NLAM)
    
    REAL(KIND=JWRB), INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), INTENT(IN) :: EPSUS
    LOGICAL, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), INTENT(IN) :: ZALP
!$acc routine seq
    INTERFACE
      SUBROUTINE STRESS_GC_iso_c (ANG_GC, USTAR, Z0, Z0MIN, HALP, RNFAC, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CM_GC,  &
      & DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPSUS, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC, RN1_RN, SQRTGOSURFT, XKAPPA,  &
      & XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, ZALP) BIND(c, name="stress_gc_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        REAL, VALUE :: ANG_GC
        REAL, VALUE :: USTAR
        REAL, VALUE :: Z0
        REAL, VALUE :: Z0MIN
        REAL, VALUE :: HALP
        REAL, VALUE :: RNFAC
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BMAXOKAP
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: EPSUS
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        REAL, VALUE :: RN1_RN
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: ZALP
      END SUBROUTINE STRESS_GC_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
!$acc host_data use_device( C2OSQRTVG_GC, CM_GC, DELKCC_GC_NS, DELKCC_OMXKM3_GC, OM3GMKM_GC, OMXKM3_GC, XKMSQRTVGOC2_GC, XKM_GC,  &
!$acc & XK_GC )
    CALL STRESS_GC_iso_c(ANG_GC, USTAR, Z0, Z0MIN, HALP, RNFAC, BETAMAXOXKAPPA2, BMAXOKAP, c_loc(C2OSQRTVG_GC), c_loc(CM_GC),  &
    & c_loc(DELKCC_GC_NS), c_loc(DELKCC_OMXKM3_GC), EPSUS, LLNORMAGAM, NWAV_GC, c_loc(OM3GMKM_GC), c_loc(OMXKM3_GC), RN1_RN,  &
    & SQRTGOSURFT, XKAPPA, c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, ZALP)
!$acc end host_data
  END SUBROUTINE STRESS_GC_fc
END MODULE STRESS_GC_FC_MOD
