MODULE TAU_PHI_HF_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE TAU_PHI_HF_fc (KIJS, KIJL, MIJ, LTAUWSHELTER, UFRIC, Z0M, FL1, AIRD, RNFAC, COSWDIF, SINWDIF2, UST, TAUHF, PHIHF,  &
  & LLPHIHF, DELTH, FR5, G, GAMNCONST, GM1, JTOT_TAUHF, LLGCBZ0, LLNORMAGAM, NANG, NWAV_GC, OMEGA_GC, SQRTGOSURFT, TAUWSHELTER,  &
  & WTAUHF, X0TAUHF, XKAPPA, XKM_GC, XK_GC, XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRB
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    LOGICAL, VALUE, INTENT(IN) :: LTAUWSHELTER
    LOGICAL, VALUE, INTENT(IN) :: LLPHIHF
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE TAU_PHI_HF_iso_c (KIJS, KIJL, MIJ, LTAUWSHELTER, UFRIC, Z0M, FL1, AIRD, RNFAC, COSWDIF, SINWDIF2, UST, TAUHF,  &
      & PHIHF, LLPHIHF, DELTH, FR5, G, GAMNCONST, GM1, JTOT_TAUHF, LLGCBZ0, LLNORMAGAM, NANG, NWAV_GC, OMEGA_GC, SQRTGOSURFT,  &
      & TAUWSHELTER, WTAUHF, X0TAUHF, XKAPPA, XKM_GC, XK_GC, XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ) &
      &  BIND(c, name="tau_phi_hf_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: MIJ
        LOGICAL, VALUE :: LTAUWSHELTER
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: UST
        TYPE(c_ptr), VALUE :: TAUHF
        TYPE(c_ptr), VALUE :: PHIHF
        LOGICAL, VALUE :: LLPHIHF
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE TAU_PHI_HF_iso_c
    END INTERFACE
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UST(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: TAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: PHIHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
!$acc host_data use_device( MIJ, UFRIC, Z0M, FL1, AIRD, RNFAC, COSWDIF, SINWDIF2, UST, TAUHF, PHIHF, FR5, OMEGA_GC, WTAUHF,  &
!$acc & XKM_GC, XK_GC, ZPIFR )
    CALL TAU_PHI_HF_iso_c(KIJS, KIJL, c_loc(MIJ), LTAUWSHELTER, c_loc(UFRIC), c_loc(Z0M), c_loc(FL1), c_loc(AIRD), c_loc(RNFAC),  &
    & c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(UST), c_loc(TAUHF), c_loc(PHIHF), LLPHIHF, DELTH, c_loc(FR5), G, GAMNCONST, GM1,  &
    & JTOT_TAUHF, LLGCBZ0, LLNORMAGAM, NANG, NWAV_GC, c_loc(OMEGA_GC), SQRTGOSURFT, TAUWSHELTER, c_loc(WTAUHF), X0TAUHF, XKAPPA,  &
    & c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, c_loc(ZPIFR), ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE TAU_PHI_HF_fc
END MODULE TAU_PHI_HF_FC_MOD
