INTERFACE
  SUBROUTINE TAUT_Z0_FC (KIJS, KIJL, IUSFG, HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC, USTAR, Z0, Z0B, CHRNCK, ACD, ALPHA,  &
  & ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CM_GC,  &
  & DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPS1, EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC,  &
  & RN1_RN, RNU, RNUM, SQRTGOSURFT, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, ZALP, ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRB
    
    USE YOWPARAM, ONLY: NFRE, NANG
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      FUNCTION CHNKMIN_FC (U10)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: CHNKMIN
        REAL(KIND=JWRB), INTENT(IN) :: U10
      END FUNCTION CHNKMIN_FC
    END INTERFACE
    INTERFACE
      FUNCTION STRESS_GC_FC (ANG_GC, USTAR, Z0, Z0MIN, HALP, RNFAC)
        USE parkind_wave, ONLY: jwrb
        REAL(KIND=JWRB) :: STRESS_GC
        REAL(KIND=JWRB), INTENT(IN) :: ANG_GC
        REAL(KIND=JWRB), INTENT(IN) :: USTAR
        REAL(KIND=JWRB), INTENT(IN) :: Z0
        REAL(KIND=JWRB), INTENT(IN) :: Z0MIN
        REAL(KIND=JWRB), INTENT(IN) :: HALP
        REAL(KIND=JWRB), INTENT(IN) :: RNFAC
      END FUNCTION STRESS_GC_FC
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IUSFG
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UTOP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: Z0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: CHRNCK(:, :)
    
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    ! Cd and Z0 from Hersbach 2010, ECMWF Tech Memo (without the viscous part)
    !     CD = ACDLIN + BCDLIN*SQRT(PCHAR) * U10
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE TAUT_Z0_FC
END INTERFACE