! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
SUBROUTINE WAMINTGR_LOKI_GPU (CDTPRA, CDATE, CDATEWH, CDTIMP, CDTIMPNEXT, BLK2GLO, WVENVI, WVPRPT, FF_NOW, FF_NEXT, INTFLDS,  &
& WAM2NEMO, MIJ, FL1, XLLWS, TIME1)
  
  
  ! ----------------------------------------------------------------------
  
  !**** *WAMINTGR* - 3-G WAM MODEL - TIME INTEGRATION OF WAVE FIELDS.
  
  !*    PURPOSE.
  !     --------
  
  !       COMPUTATION OF THE 2-D FREQUENCY-DIRECTION WAVE SPECTRUM AT ALL
  !       GRID POINTS FOR A GIVEN INITIAL SPECTRUM AND FORCING SURFACE
  !       STRESS FIELD.
  
  !     REFERENCE.
  !     ----------
  
  !         IFS DOCUMENTATION, part VII
  
  ! -------------------------------------------------------------------

  USE IMPLSCH_FC_MOD, ONLY: IMPLSCH_FC

  ![Loki::GlobalVarHoistTransformation] -------- Added global variable imports for offload directives -----------
  USE yowstat, ONLY: IPHYS, ISNONLIN, IDAMPING, LBIWBK
  USE yowwndg, ONLY: ICODE, ICODE_CPL
  USE yowparam, ONLY: NFRE_RED, NFRE_ODD, LLUNSTR
  USE yowcout, ONLY: LWFLUXOUT
  USE yowtabl, ONLY: SWELLFT, IAB, EPS1
  USE yowaltas, ONLY: BFCRV, AFCRV, EGRCRV
  USE yowwind, ONLY: WSPMIN
  USE yowindn, ONLY: MFRSTLW, KFRH, IKP1, RNLCOEF, IKP, FKLAM1, K2W, INLCOEF, K21W, FKLAP, FKLAM, AF11, K1W, IKM, MLSTHG, DAL1,  &
  & FKLAP1, DAL2, K11W, IKM1
  USE yowice, ONLY: LCIWABR, LWAMRSETCI, CIBLOCK, CDICWA, CITHRSH, LICERUN, CITHRSH_TAIL, LMASKICE, FLMIN
  USE yowcoup, ONLY: JTOT_TAUHF, LWVFLX_SNL, LWNEMOCOUSTRN, WTAUHF, LWCOU, LWNEMOTAUOC, X0TAUHF, LLCAPCHNK, LLGCBZ0,  &
  & LWNEMOCOUSTK, LWNEMOCOUSEND, LLNORMAGAM, LWFLUX
  USE yowfred, ONLY: WETAIL, COFRM4, FRATIO, C2OSQRTVG_GC, FLOGSPRDM1, DELKCC_OMXKM3_GC, TH, OMXKM3_GC, FRIC, ZPIFR, FR5,  &
  & DFIM_SIM, DELKCC_GC_NS, DFIMOFR, OMEGA_GC, DFIM, DELTH, COSTH, WP1TAIL, DFIMFR, FR, XLOGKRATIOM1_GC, FRTAIL, CM_GC,  &
  & XKMSQRTVGOC2_GC, SINTH, XKM_GC, NWAV_GC, FLMAX, OM3GMKM_GC, DFIMFR2, XK_GC, RHOWG_DFIM, WP2TAIL
  USE yowpcons, ONLY: ROWATER, GM1, WSEMEAN_MIN, EPSUS, ZPI, ZPI4GM2, PHIEPSMAX, DKMAX, ACD, SQRTGOSURFT, ZPI4GM1, EPSU10,  &
  & TAUOCMAX, PHIEPSMIN, CDMAX, G, ACDLIN, TAUOCMIN, ROWATERM1, BCD, BCDLIN
  USE yowphys, ONLY: ZALP, INDICESSAT, CHNKMIN_U, DTHRN_A, RNU, NDIKCUMUL, SSDSC3, ALPHAMAX, ANG_GC_C, SWELLF3, SWELLF5, IPSAT,  &
  & SWELLF7M1, RNUM, CDIS, ANG_GC_B, Z0RAT, SWELLF2, MICHE, ABMIN, BETAMAXOXKAPPA2, GAMNCONST, NSDSNTH, ALPHA, ABMAX,  &
  & DELTA_SDIS, ANG_GC_A, SSDSC5, DTHRN_U, ALPHAMIN, XNLEV, CDISVIS, TAILFACTOR, SSDSC4, SATWEIGHTS, TAILFACTOR_PM, SSDSC2,  &
  & SSDSC6, RN1_RN, SWELLF7, SDSBR, BMAXOKAP, XKAPPA, TAUWSHELTER, ALPHAPMAX, SWELLF, CUMULW, SWELLF6, Z0TUBMAX, SWELLF4
  USE yowshal, ONLY: NDEPTH, BATHYMAX, XKDMIN
  ![Loki::GlobalVarHoistTransformation] ---------------------------------------
  USE PARKIND_WAVE, ONLY: JWIM, JWRB, JWRU
  USE YOWDRVTYPE, ONLY: WVGRIDGLO, ENVIRONMENT, FREQUENCY, FORCING_FIELDS, INTGT_PARAM_FIELDS, WAVE2OCEAN
  
  USE YOWCOUP, ONLY: LWNEMOCOU, NEMONTAU
  USE YOWGRID, ONLY: NPROMA_WAM, NCHNK
  USE YOWPARAM, ONLY: NIBLO, NANG, NFRE
  USE YOWPCONS, ONLY: EPSMIN
  USE YOWSTAT, ONLY: CDTPRO, IDELPRO, IDELT, IDELWI, LLSOURCE
  USE YOWWIND, ONLY: CDAWIFL, CDATEWO, CDATEFL
  USE YOWFIELD_MOD, ONLY: FREQUENCY_FIELD, ENVIRONMENT_FIELD, FORCING_FIELDS_FIELD, WAVE2OCEAN_FIELD, INTGT_PARAM_FIELDS_FIELD,  &
  & SOURCE_CONTRIBS_FIELD
  
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  ! INTERFACE
  !   SUBROUTINE IMPLSCH_FC (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, INDEP, DEPTH, IOBND, IODP,  &
  !   & AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN,  &
  !   & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, TAUXD,  &
  !   & TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS)
  !     USE parkind_wave, ONLY: jwim, jwrb, jwro
  !     USE yowparam, ONLY: nang, nfre
  !     INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
  !     REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CGROUP
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CIWA
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: XK2CG
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: STOKFAC
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMAXDPT
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
  !     INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: INDEP
  !     INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: IODP
  !     INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: IOBND
  !     REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, CICOVER, AIRD, WSTAR, CITHICK
  !     REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, WSWAVE
  !     REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS
  !     REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD
  !     REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: PHIEPS, PHIAW
  !     REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN
  !     REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX
  !     REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOTAUY, NEMOWSWAVE, NEMOPHIF
  !     INTEGER(KIND=JWIM), INTENT(OUT), DIMENSION(KIJL) :: MIJ
  !     REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
  !   END SUBROUTINE IMPLSCH_FC
  ! END INTERFACE
  INTERFACE
    SUBROUTINE INCDATE (CDATE, ISHIFT)
      USE parkind_wave, ONLY: jwim
      INTEGER(KIND=JWIM), INTENT(IN) :: ISHIFT
      CHARACTER(LEN=*), INTENT(INOUT) :: CDATE
    END SUBROUTINE INCDATE
  END INTERFACE
  INTERFACE
    SUBROUTINE NEWWIND (CDATE, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
      USE YOWDRVTYPE, ONLY: FREQUENCY, FORCING_FIELDS
      CHARACTER(LEN=14), INTENT(IN) :: CDATE
      CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH
      LOGICAL, INTENT(INOUT) :: LLNEWFILE
      TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW
      TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT
    END SUBROUTINE NEWWIND
  END INTERFACE
  INTERFACE
    SUBROUTINE PROPAG_WAM (BLK2GLO, WAVNUM, CGROUP, OMOSNH2KD, FL1, DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
      USE parkind_wave, ONLY: jwrb
      USE yowdrvtype, ONLY: wvgridglo
      USE yowgrid, ONLY: nproma_wam, nchnk
      USE yowparam, ONLY: nang, nfre
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NFRE, NCHNK) :: WAVNUM, CGROUP, OMOSNH2KD
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NCHNK) :: DEPTH, DELLAM1, COSPHM1, UCUR, VCUR
    END SUBROUTINE PROPAG_WAM
  END INTERFACE
  INTERFACE
    FUNCTION WAM_USER_CLOCK ()
      USE parkind_wave, ONLY: jwru
      REAL(KIND=JWRU) :: WAM_USER_CLOCK
    END FUNCTION WAM_USER_CLOCK
  END INTERFACE
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  CHARACTER(LEN=14), INTENT(IN) :: CDTPRA  ! DATE FOR CALL PROPAGATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATE  ! CURRENT DATE
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH  ! DATE OF THE NEXT FORCING FIELDS
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMP  ! START DATE OF SOURCE FUNCTION INTEGRATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMPNEXT  ! NEXT START DATE OF SOURCE FUNCTION INTEGRATION
  TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO  ! BLOCK TO GRID TRANSFORMATION
  TYPE(ENVIRONMENT), INTENT(INOUT) :: WVENVI  !  WAVE ENVIRONMENT FIELDS
  TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT  ! WAVE PROPERTIES FIELDS
  TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW  ! FORCING FIELDS AT CURRENT TIME
  TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT  !  DATA STRUCTURE WITH THE NEXT FORCING FIELDS
  TYPE(INTGT_PARAM_FIELDS), INTENT(INOUT) :: INTFLDS  ! INTEGRATED/DERIVED PARAMETERS
  TYPE(WAVE2OCEAN), INTENT(INOUT) :: WAM2NEMO  ! WAVE FIELDS PASSED TO NEMO
  INTEGER(KIND=JWIM), INTENT(INOUT) :: MIJ(NPROMA_WAM, NCHNK)  ! LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE
  REAL(KIND=JWRB), INTENT(INOUT) :: FL1(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB), INTENT(INOUT) :: XLLWS(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)  ! TOTAL WINDSEA MASK FROM INPUT SOURCE TERM
  
  REAL(KIND=JWRB), INTENT(INOUT) :: TIME1(3)
  REAL(KIND=JWRB) :: TIME0, TIME2
  
  
  INTEGER(KIND=JWIM) :: IJ, K, M
  INTEGER(KIND=JWIM) :: ICHNK
  INTEGER(KIND=JWIM) :: IDELWH
  
  ! Objects to store fields
  TYPE(FREQUENCY_FIELD) :: WVPRPT_FIELD
  TYPE(ENVIRONMENT_FIELD) :: WVENVI_FIELD
  TYPE(FORCING_FIELDS_FIELD) :: FF_NOW_FIELD
  TYPE(WAVE2OCEAN_FIELD) :: WAM2NEMO_FIELD
  TYPE(INTGT_PARAM_FIELDS_FIELD) :: INTFLDS_FIELD
  TYPE(SOURCE_CONTRIBS_FIELD) :: SRC_CONTRIBS
  
  ! DEVICE POINTERS
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: FL1_DPTR(:, :, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XLLWS_DPTR(:, :, :, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: MIJ_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WAVNUM_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CGROUP_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: OMOSNH2KD_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CIWA_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CINV_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XK2CG_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STOKFAC_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: EMAXDPT_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: INDEP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DEPTH_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DELLAM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: COSPHM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UCUR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VCUR_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IOBND_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IODP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUWDIR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0M_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0B_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOUSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOVSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOSTRN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NPHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NTAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NSWH_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NMWP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOTAUX_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOTAUY_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOWSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOPHIF_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSEMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSFMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STRNMS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIOCD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIAW_DPTR(:, :) => NULL()
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  
  LOGICAL, SAVE :: LLNEWFILE
  
  DATA LLNEWFILE / .false. /
  INTEGER :: istat
  REAL(KIND=JWRB) :: IMPLSCH_RAORW(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_EMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_HALP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_EMEANWS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FMEANWS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_F1MEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_AKMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_XKMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_PHIWA(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FLM(NPROMA_WAM, NANG_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_COSWDIF(NPROMA_WAM, NANG_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SINWDIF2(NPROMA_WAM, NANG_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_RHOWGDFTH(NPROMA_WAM, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FLD(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SL(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SPOS(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_CIREDUC(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SSOURCE(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB) :: SINFLX_RNFAC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINFLX_TMP_EM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_XSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_YSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUHF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_PHIHF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_USDIRP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_UST(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_ENH(NPROMA_WAM, MLSTHG, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_XNU(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_SIG_TH(NPROMA_WAM, NCHNK)
  
!$acc enter data create( IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP, IMPLSCH_EMEANWS, IMPLSCH_FMEANWS,  &
!$acc & IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA, IMPLSCH_FLM, IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2,  &
!$acc & IMPLSCH_RHOWGDFTH, IMPLSCH_FLD, IMPLSCH_SL, IMPLSCH_SPOS, IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, SINFLX_RNFAC, SINFLX_TMP_EM,  &
!$acc & STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU,  &
!$acc & SNONLIN_SIG_TH )
  
  
  ! ----------------------------------------------------------------------
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 0, ZHOOK_HANDLE)
  
  !*     PROPAGATION TIME
  !      ----------------
  
  CALL SRC_CONTRIBS%INIT(FL1=FL1(:, :, :, :))
  CALL SRC_CONTRIBS%UPDATE_DEVICE(FL1=FL1_DPTR)
  CALL WVPRPT_FIELD%INIT(WAVNUM=WVPRPT%WAVNUM, CGROUP=WVPRPT%CGROUP, OMOSNH2KD=WVPRPT%OMOSNH2KD)
  CALL WVPRPT_FIELD%UPDATE_DEVICE(WAVNUM=WAVNUM_DPTR, CGROUP=CGROUP_DPTR, OMOSNH2KD=OMOSNH2KD_DPTR)
  CALL WVENVI_FIELD%INIT(DEPTH=WVENVI%DEPTH, DELLAM1=WVENVI%DELLAM1, COSPHM1=WVENVI%COSPHM1, UCUR=WVENVI%UCUR, VCUR=WVENVI%VCUR)
  CALL WVENVI_FIELD%UPDATE_DEVICE(DEPTH=DEPTH_DPTR, DELLAM1=DELLAM1_DPTR, COSPHM1=COSPHM1_DPTR, UCUR=UCUR_DPTR, VCUR=VCUR_DPTR)
!$acc data present( FL1_DPTR, WAVNUM_DPTR, CGROUP_DPTR, OMOSNH2KD_DPTR, DEPTH_DPTR, DELLAM1_DPTR, COSPHM1_DPTR, UCUR_DPTR,  &
!$acc & VCUR_DPTR )
  
  IF (CDATE == CDTPRA) THEN
    TIME0 = -WAM_USER_CLOCK()
    CALL PROPAG_WAM(BLK2GLO, WAVNUM_DPTR(:, :, :), CGROUP_DPTR(:, :, :), OMOSNH2KD_DPTR(:, :, :), FL1_DPTR(:, :, :, :),  &
    & DEPTH_DPTR(:, :), DELLAM1_DPTR(:, :), COSPHM1_DPTR(:, :), UCUR_DPTR(:, :), VCUR_DPTR(:, :))
    TIME1(1) = TIME1(1) + (TIME0 + WAM_USER_CLOCK())*1.E-06
    CDATE = CDTPRO
  END IF
!$acc end data
  
  !* RETRIEVING NEW FORCING FIELDS IF NEEDED.
  !  ----------------------------------------
  CALL NEWWIND(CDTIMP, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
  
  ! IT IS TIME TO INTEGRATE THE SOURCE TERMS
  ! ----------------------------------------
  IF (CDATE >= CDTIMPNEXT) THEN
    ! COMPUTE UPDATE DUE TO SOURCE TERMS
    CALL GSTATS(1431, 0)
    IF (LLSOURCE) THEN
      
      TIME2 = -WAM_USER_CLOCK()
      CALL WVPRPT_FIELD%INIT(CIWA=WVPRPT%CIWA, CINV=WVPRPT%CINV, XK2CG=WVPRPT%XK2CG, STOKFAC=WVPRPT%STOKFAC)
      CALL WVENVI_FIELD%INIT(EMAXDPT=WVENVI%EMAXDPT, INDEP=WVENVI%INDEP, IOBND=WVENVI%IOBND, IODP=WVENVI%IODP)
      CALL FF_NOW_FIELD%INIT(AIRD=FF_NOW%AIRD, WDWAVE=FF_NOW%WDWAVE, CICOVER=FF_NOW%CICOVER, WSWAVE=FF_NOW%WSWAVE,  &
      & WSTAR=FF_NOW%WSTAR, UFRIC=FF_NOW%UFRIC, TAUW=FF_NOW%TAUW, TAUWDIR=FF_NOW%TAUWDIR, Z0M=FF_NOW%Z0M, Z0B=FF_NOW%Z0B,  &
      & CHRNCK=FF_NOW%CHRNCK, CITHICK=FF_NOW%CITHICK)
      CALL WAM2NEMO_FIELD%INIT(NEMOUSTOKES=WAM2NEMO%NEMOUSTOKES, NEMOVSTOKES=WAM2NEMO%NEMOVSTOKES, NEMOSTRN=WAM2NEMO%NEMOSTRN,  &
      & NPHIEPS=WAM2NEMO%NPHIEPS, NTAUOC=WAM2NEMO%NTAUOC, NSWH=WAM2NEMO%NSWH, NMWP=WAM2NEMO%NMWP, NEMOTAUX=WAM2NEMO%NEMOTAUX,  &
      & NEMOTAUY=WAM2NEMO%NEMOTAUY, NEMOWSWAVE=WAM2NEMO%NEMOWSWAVE, NEMOPHIF=WAM2NEMO%NEMOPHIF)
      CALL INTFLDS_FIELD%INIT(WSEMEAN=INTFLDS%WSEMEAN, WSFMEAN=INTFLDS%WSFMEAN, USTOKES=INTFLDS%USTOKES,  &
      & VSTOKES=INTFLDS%VSTOKES, STRNMS=INTFLDS%STRNMS, TAUXD=INTFLDS%TAUXD, TAUYD=INTFLDS%TAUYD, TAUOCXD=INTFLDS%TAUOCXD,  &
      & TAUOCYD=INTFLDS%TAUOCYD, TAUOC=INTFLDS%TAUOC, PHIOCD=INTFLDS%PHIOCD, PHIEPS=INTFLDS%PHIEPS, PHIAW=INTFLDS%PHIAW)
      CALL SRC_CONTRIBS%INIT(XLLWS=XLLWS(:, :, :, :), MIJ=MIJ(:, :))
      
      
      CALL WVPRPT_FIELD%UPDATE_DEVICE(CIWA=CIWA_DPTR, CINV=CINV_DPTR, XK2CG=XK2CG_DPTR, STOKFAC=STOKFAC_DPTR)
      CALL WVENVI_FIELD%UPDATE_DEVICE(EMAXDPT=EMAXDPT_DPTR, INDEP=INDEP_DPTR, IOBND=IOBND_DPTR, IODP=IODP_DPTR)
      CALL FF_NOW_FIELD%UPDATE_DEVICE(AIRD=AIRD_DPTR, WDWAVE=WDWAVE_DPTR, CICOVER=CICOVER_DPTR, WSWAVE=WSWAVE_DPTR,  &
      & WSTAR=WSTAR_DPTR, UFRIC=UFRIC_DPTR, TAUW=TAUW_DPTR, TAUWDIR=TAUWDIR_DPTR, Z0M=Z0M_DPTR, Z0B=Z0B_DPTR,  &
      & CHRNCK=CHRNCK_DPTR, CITHICK=CITHICK_DPTR)
      CALL WAM2NEMO_FIELD%UPDATE_DEVICE(NEMOUSTOKES=NEMOUSTOKES_DPTR, NEMOVSTOKES=NEMOVSTOKES_DPTR, NEMOSTRN=NEMOSTRN_DPTR,  &
      & NPHIEPS=NPHIEPS_DPTR, NTAUOC=NTAUOC_DPTR, NSWH=NSWH_DPTR, NMWP=NMWP_DPTR, NEMOTAUX=NEMOTAUX_DPTR,  &
      & NEMOTAUY=NEMOTAUY_DPTR, NEMOWSWAVE=NEMOWSWAVE_DPTR, NEMOPHIF=NEMOPHIF_DPTR)
      CALL INTFLDS_FIELD%UPDATE_DEVICE(WSEMEAN=WSEMEAN_DPTR, WSFMEAN=WSFMEAN_DPTR, USTOKES=USTOKES_DPTR, VSTOKES=VSTOKES_DPTR,  &
      & STRNMS=STRNMS_DPTR, TAUXD=TAUXD_DPTR, TAUYD=TAUYD_DPTR, TAUOCXD=TAUOCXD_DPTR, TAUOCYD=TAUOCYD_DPTR, TAUOC=TAUOC_DPTR,  &
      & PHIOCD=PHIOCD_DPTR, PHIEPS=PHIEPS_DPTR, PHIAW=PHIAW_DPTR)
      CALL SRC_CONTRIBS%UPDATE_DEVICE(XLLWS=XLLWS_DPTR, MIJ=MIJ_DPTR)
      
! $ acc data copyin( af11, c2osqrtvg_gc, cm_gc, cofrm4, costh, cumulw, delkcc_gc_ns, delkcc_omxkm3_gc, dfim, dfimfr, dfimfr2,  &
! $ acc & dfimofr, dfim_sim, fklam, fklam1, fklap, fklap1, flmax, fr, fr5, ikm, ikm1, ikp, ikp1, indicessat, inlcoef, k11w, k1w,  &
! $ acc & k21w, k2w, om3gmkm_gc, omega_gc, omxkm3_gc, rhowg_dfim, rnlcoef, satweights, sinth, swellft, th, wtauhf,  &
! $ acc & xkmsqrtvgoc2_gc, xkm_gc, xk_gc, zpifr )

!$acc update device( af11, c2osqrtvg_gc, cm_gc, cofrm4, costh, cumulw, delkcc_gc_ns, delkcc_omxkm3_gc, dfim, dfimfr, dfimfr2,  &
!$acc & dfimofr, dfim_sim, fklam, fklam1, fklap, fklap1, flmax, fr, fr5, ikm, ikm1, ikp, ikp1, indicessat, inlcoef, k11w, k1w,  &
!$acc & k21w, k2w, om3gmkm_gc, omega_gc, omxkm3_gc, rhowg_dfim, rnlcoef, satweights, sinth, swellft, th, wtauhf,  &
!$acc & xkmsqrtvgoc2_gc, xkm_gc, xk_gc, zpifr )

!$acc data present( FL1_DPTR,XLLWS_DPTR,MIJ_DPTR,WAVNUM_DPTR,CGROUP_DPTR,CIWA_DPTR,CINV_DPTR,XK2CG_DPTR,STOKFAC_DPTR,  &
!$acc & EMAXDPT_DPTR,INDEP_DPTR,DEPTH_DPTR,IOBND_DPTR,IODP_DPTR,CICOVER_DPTR,WSWAVE_DPTR,WDWAVE_DPTR,AIRD_DPTR,  &
!$acc & WSTAR_DPTR,UFRIC_DPTR,TAUW_DPTR,TAUWDIR_DPTR,Z0M_DPTR,Z0B_DPTR,CHRNCK_DPTR,CITHICK_DPTR,NEMOUSTOKES_DPTR,  &
!$acc & NEMOVSTOKES_DPTR,NEMOSTRN_DPTR,NPHIEPS_DPTR,NTAUOC_DPTR,NSWH_DPTR,NMWP_DPTR,NEMOTAUX_DPTR,NEMOTAUY_DPTR,  &
!$acc & NEMOWSWAVE_DPTR,NEMOPHIF_DPTR,WSEMEAN_DPTR,WSFMEAN_DPTR,USTOKES_DPTR,VSTOKES_DPTR,STRNMS_DPTR,TAUXD_DPTR,  &
!$acc & TAUYD_DPTR,TAUOCXD_DPTR,TAUOCYD_DPTR,TAUOC_DPTR,PHIOCD_DPTR,PHIEPS_DPTR,PHIAW_DPTR )
      TIME0 = -WAM_USER_CLOCK()
      
!$loki start removed loop
      
      CALL IMPLSCH_FC(1, NPROMA_WAM, FL1_DPTR(:, :, :, :), WAVNUM_DPTR(:, :, :), CGROUP_DPTR(:, :, :), CIWA_DPTR(:, :, :),  &
      & CINV_DPTR(:, :, :), XK2CG_DPTR(:, :, :), STOKFAC_DPTR(:, :, :), EMAXDPT_DPTR(:, :), INDEP_DPTR(:, :), DEPTH_DPTR(:, :),  &
      & IOBND_DPTR(:, :), IODP_DPTR(:, :), AIRD_DPTR(:, :), WDWAVE_DPTR(:, :), CICOVER_DPTR(:, :), WSWAVE_DPTR(:, :),  &
      & WSTAR_DPTR(:, :), UFRIC_DPTR(:, :), TAUW_DPTR(:, :), TAUWDIR_DPTR(:, :), Z0M_DPTR(:, :), Z0B_DPTR(:, :),  &
      & CHRNCK_DPTR(:, :), CITHICK_DPTR(:, :), NEMOUSTOKES_DPTR(:, :), NEMOVSTOKES_DPTR(:, :), NEMOSTRN_DPTR(:, :),  &
      & NPHIEPS_DPTR(:, :), NTAUOC_DPTR(:, :), NSWH_DPTR(:, :), NMWP_DPTR(:, :), NEMOTAUX_DPTR(:, :), NEMOTAUY_DPTR(:, :),  &
      & NEMOWSWAVE_DPTR(:, :), NEMOPHIF_DPTR(:, :), WSEMEAN_DPTR(:, :), WSFMEAN_DPTR(:, :), USTOKES_DPTR(:, :),  &
      & VSTOKES_DPTR(:, :), STRNMS_DPTR(:, :), TAUXD_DPTR(:, :), TAUYD_DPTR(:, :), TAUOCXD_DPTR(:, :), TAUOCYD_DPTR(:, :),  &
      & TAUOC_DPTR(:, :), PHIOCD_DPTR(:, :), PHIEPS_DPTR(:, :), PHIAW_DPTR(:, :), MIJ_DPTR(:, :), XLLWS_DPTR(:, :, :, :), ABMAX,  &
      & ABMIN, ACD, ACDLIN, AF11(:), AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD,  &
      & BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, C2OSQRTVG_GC(:), CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH,  &
      & CITHRSH_TAIL, CM_GC(:), COFRM4(:), COSTH(:), CUMULW(:, :, :, :), DAL1, DAL2, DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:),  &
      & DELTA_SDIS, DELTH, DFIM(:), DFIMFR(:), DFIMFR2(:), DFIMOFR(:), DFIM_SIM(:), DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1,  &
      & EPSMIN, EPSU10, EPSUS, FKLAM(:), FKLAM1(:), FKLAP(:), FKLAP1(:), FLMAX(:), FLMIN, FLOGSPRDM1, FR(:), FR5(:), FRATIO,  &
      & FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM(:), IKM1(:), IKP(:), IKP1(:),  &
      & INDICESSAT(:, :), INLCOEF(:, :), IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W(:, :), K1W(:, :), K21W(:, :), K2W(:, :), KFRH,  &
      & LBIWBK, LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT,  &
      & LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH,  &
      & NDIKCUMUL, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC(:), OMEGA_GC(:), OMXKM3_GC(:), PHIEPSMAX, PHIEPSMIN,  &
      & RHOWG_DFIM(:), RN1_RN, RNLCOEF(:, :), RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS(:, :), SDSBR, SINTH(:), SQRTGOSURFT,  &
      & SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1,  &
      & SWELLFT(:), TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH(:), WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN,  &
      & WSPMIN, WTAUHF(:), X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC(:), XKM_GC(:), XK_GC(:), XLOGKRATIOM1_GC, XNLEV, Z0RAT,  &
      & Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR(:), 1, NCHNK, 1, NCHNK, NPROMA_WAM, &
      & IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP,  &
      & IMPLSCH_EMEANWS, IMPLSCH_FMEANWS, IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA,  &
      & IMPLSCH_FLM, IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2, IMPLSCH_RHOWGDFTH, IMPLSCH_FLD,  &
      & IMPLSCH_SL, IMPLSCH_SPOS, IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, SINFLX_RNFAC,  &
      & SINFLX_TMP_EM, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP,  &
      & STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH) 
      ! RAORW=IMPLSCH_RAORW,  &
      ! & EMEAN=IMPLSCH_EMEAN, FMEAN=IMPLSCH_FMEAN, HALP=IMPLSCH_HALP, EMEANWS=IMPLSCH_EMEANWS, FMEANWS=IMPLSCH_FMEANWS,  &
      ! & F1MEAN=IMPLSCH_F1MEAN, AKMEAN=IMPLSCH_AKMEAN, XKMEAN=IMPLSCH_XKMEAN, PHIWA=IMPLSCH_PHIWA, FLM=IMPLSCH_FLM,  &
      ! & COSWDIF=IMPLSCH_COSWDIF, SINWDIF2=IMPLSCH_SINWDIF2, RHOWGDFTH=IMPLSCH_RHOWGDFTH, FLD=IMPLSCH_FLD, SL=IMPLSCH_SL,  &
      ! & SPOS=IMPLSCH_SPOS, CIREDUC=IMPLSCH_CIREDUC, SSOURCE=IMPLSCH_SSOURCE, SINFLX_RNFAC=SINFLX_RNFAC,  &
      ! & SINFLX_TMP_EM=SINFLX_TMP_EM, STRESSO_XSTRESS=STRESSO_XSTRESS, STRESSO_YSTRESS=STRESSO_YSTRESS,  &
      ! & STRESSO_TAUHF=STRESSO_TAUHF, STRESSO_PHIHF=STRESSO_PHIHF, STRESSO_USDIRP=STRESSO_USDIRP, STRESSO_UST=STRESSO_UST,  &
      ! & SNONLIN_ENH=SNONLIN_ENH, SNONLIN_XNU=SNONLIN_XNU, SNONLIN_SIG_TH=SNONLIN_SIG_TH)
      
!$loki end removed loop
      
      TIME1(2) = TIME1(2) + (TIME0 + WAM_USER_CLOCK())*1.E-06
! $ acc end data
      
!$acc end data
      
      CALL WVPRPT_FIELD%ENSURE_HOST()
      CALL WVENVI_FIELD%ENSURE_HOST()
      CALL FF_NOW_FIELD%ENSURE_HOST()
      CALL WAM2NEMO_FIELD%ENSURE_HOST()
      CALL INTFLDS_FIELD%ENSURE_HOST()
      CALL SRC_CONTRIBS%ENSURE_HOST()
      
      CALL WVPRPT_FIELD%FINAL()
      CALL WVENVI_FIELD%FINAL()
      CALL FF_NOW_FIELD%FINAL()
      CALL WAM2NEMO_FIELD%FINAL()
      CALL INTFLDS_FIELD%FINAL()
      CALL SRC_CONTRIBS%FINAL()
      TIME1(3) = TIME1(3) + (TIME2 + WAM_USER_CLOCK())*1.E-06
      
      IF (LWNEMOCOU) NEMONTAU = NEMONTAU + 1
      
    ELSE
      !   NO SOURCE TERM CONTRIBUTION
!$OMP PARALLEL DO SCHEDULE( STATIC ) PRIVATE( ICHNK )
      DO ICHNK=1,NCHNK
        MIJ(:, ICHNK) = NFRE
        FL1(:, :, :, ICHNK) = MAX(FL1(:, :, :, ICHNK), EPSMIN)
        XLLWS(:, :, :, ICHNK) = 0.0_JWRB
      END DO
!$OMP END PARALLEL DO
    END IF
    CALL GSTATS(1431, 1)
    
    
    !*       UPDATE FORCING FIELDS TIME COUNTER
    !        ----------------------------------
    IF (LLNEWFILE) THEN
      LLNEWFILE = .false.
      IDELWH = MAX(IDELWI, IDELPRO)
      CALL INCDATE(CDAWIFL, IDELWH)
      CALL INCDATE(CDATEFL, IDELWH)
    END IF
    
    CDATEWO = CDATEWH
    CDTIMP = CDTIMPNEXT
    CALL INCDATE(CDTIMPNEXT, IDELT)
    
  END IF
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 1, ZHOOK_HANDLE)
  
  
!$acc exit data delete( IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP, IMPLSCH_EMEANWS, IMPLSCH_FMEANWS,  &
!$acc & IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA, IMPLSCH_FLM, IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2,  &
!$acc & IMPLSCH_RHOWGDFTH, IMPLSCH_FLD, IMPLSCH_SL, IMPLSCH_SPOS, IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, SINFLX_RNFAC, SINFLX_TMP_EM,  &
!$acc & STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_USDIRP, STRESSO_UST, SNONLIN_ENH, SNONLIN_XNU,  &
!$acc & SNONLIN_SIG_TH )
  
END SUBROUTINE WAMINTGR_LOKI_GPU
