! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
ATTRIBUTES(DEVICE) SUBROUTINE WNFLUXES_FC (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE,  &
& UFRIC, AIRD, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC,  &
& PHIOCD, PHIEPS, PHIAW, LNUPD, AFCRV, BFCRV, CIBLOCK, CITHRSH, COSTH, EGRCRV, EPSU10, EPSUS, FR, G, LICERUN, LWAMRSETCI,  &
& LWNEMOCOU, LWNEMOTAUOC, NANG, NFRE, PHIEPSMAX, PHIEPSMIN, SINTH, TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
  
  ! ----------------------------------------------------------------------
  
  !**** *WNFLUXES* - WAVE FLUXES CALCULATION
  
  !*    PURPOSE.
  !     --------
  
  !**   INTERFACE.
  !     ----------
  
  !       *CALL* *WNFLUXES* (KIJS, KIJL,
  !    &                     MIJ, RHOWGDFTH,
  !    &                     CINV,
  !    &                     SSURF, CICOVER,
  !    &                     PHIWA,
  !    &                     EM, F1, WSWAVE, WDWAVE,
  !    &                     UFRIC, AIRD, INTFLDS, WAM2NEMO,
  !    &                     LNUPD)
  !          *KIJS*    - INDEX OF FIRST GRIDPOINT.
  !          *KIJL*    - INDEX OF LAST GRIDPOINT.
  !          *MIJ*    - LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE
  !         *RHOWGDFTH    - WATER DENSITY * G * DF * DTHETA
  !                         FOR TRAPEZOIDAL INTEGRATION BETWEEN FR(1) and FR(MIJ)
  !                         !!!!!!!!  RHOWGDFTH=0 FOR FR > FR(MIJ)
  !          *CINV*   - INVERSE PHASE SPEED.
  !          *SSURF*  - CONTRIBUTION OF ALL SOURCE TERMS ACTING ON
  !                     THE SURFACE MOMENTUM AND ENERGY FLUXES.
  !          *CICOVER*- SEA ICE COVER.
  !          *PHIWA*  - ENERGY FLUX FROM WIND INTO WAVES INTEGRATED
  !                     OVER THE FULL FREQUENCY RANGE.
  !          *EM*     - MEAN WAVE VARIANCE.
  !          *F1*     - MEAN WAVE FREQUENCY BASED ON f*F INTEGRATION.
  !          *WSWAVE* - WIND SPEED IN M/S.
  !          *WDWAVE* - WIND DIRECTION IN RADIANS IN OCEANOGRAPHIC CONVENTION
  !          *UFRIC*  - FRICTION VELOCITY IN M/S.
  !          *AIRD*   - AIR DENSITY IN KG/M3.
  !          *INTFLDS*-  INTEGRATED/DERIVED PARAMETERS
  !          WAM2NEMO*- WAVE FIELDS PASSED TO NEMO
  !          *LNUPD*  - UPDATE NEMO FIELDS.
  
  ! ----------------------------------------------------------------------
  
  USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRO, JWRB
  USE YOWDRVTYPE, ONLY: WAVE2OCEAN, FORCING_FIELDS, INTGT_PARAM_FIELDS
  
  
  USE YOWPCONS, ONLY: ZPI
  
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
  INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: MIJ(:, :)
  
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWGDFTH(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SSURF(:, :, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: PHIWA(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: EM(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: F1(:)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
  REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
  REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
  LOGICAL, VALUE, INTENT(IN) :: LNUPD
  
  
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
  INTEGER(KIND=JWIM) :: K
  INTEGER(KIND=JWIM) :: M
  
  !     FICTITIOUS VALUE OF THE NORMALISED WAVE ENERGY FLUX UNDER THE SEA ICE
  !     (negative because it is defined as leaving the waves)
  REAL(KIND=JWRB), PARAMETER :: PHIOC_ICE = -3.75_JWRB
  REAL(KIND=JWRB), PARAMETER :: PHIAW_ICE = 3.75_JWRB
  
  !     USE HERSBACH 2011 FOR CD(U10) (SEE ALSO EDSON et al. 2013)
  REAL(KIND=JWRB), PARAMETER :: C1 = 1.03E-3_JWRB
  REAL(KIND=JWRB), PARAMETER :: C2 = 0.04E-3_JWRB
  REAL(KIND=JWRB), PARAMETER :: P1 = 1.48_JWRB
  REAL(KIND=JWRB), PARAMETER :: P2 = -0.21_JWRB
  REAL(KIND=JWRB), PARAMETER :: CDMAX = 0.003_JWRB
  
  REAL(KIND=JWRB), PARAMETER :: EFD_MIN = 0.0625_JWRB  ! corresponds to min Hs=1m under sea ice
  REAL(KIND=JWRB), PARAMETER :: EFD_MAX = 6.25_JWRB  ! corresponds to max Hs=10m under sea ice
  
  REAL(KIND=JWRB) :: TAU
  REAL(KIND=JWRB) :: XN
  REAL(KIND=JWRB) :: TAUO
  REAL(KIND=JWRB) :: U10P
  REAL(KIND=JWRB) :: CD_BULK
  REAL(KIND=JWRB) :: CD_WAVE
  REAL(KIND=JWRB) :: CD_ICE
  REAL(KIND=JWRB) :: CNST
  REAL(KIND=JWRB) :: EPSUS3
  REAL(KIND=JWRB) :: CITHRSH_INV
  REAL(KIND=JWRB) :: EFD
  REAL(KIND=JWRB) :: FFD
  REAL(KIND=JWRB) :: EFD_FAC
  REAL(KIND=JWRB) :: FFD_FAC
  
  REAL(KIND=JWRB) :: XSTRESS
  REAL(KIND=JWRB) :: YSTRESS
  REAL(KIND=JWRB) :: USTAR
  REAL(KIND=JWRB) :: PHILF
  REAL(KIND=JWRB) :: OOVAL
  REAL(KIND=JWRB) :: EM_OC
  REAL(KIND=JWRB) :: F1_OC
  REAL(KIND=JWRB) :: CMRHOWGDFTH
  REAL(KIND=JWRB) :: SUMT
  REAL(KIND=JWRB) :: SUMX
  REAL(KIND=JWRB) :: SUMY
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
  LOGICAL, VALUE, INTENT(IN) :: LICERUN
  LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
  LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
  REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
  REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
  INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
  INTEGER, VALUE, INTENT(IN) :: NCHNK
  
  ! ----------------------------------------------------------------------
  
  
  EPSUS3 = EPSUS*SQRT(EPSUS)
  
  CITHRSH_INV = 1._JWRB / MAX(CITHRSH, 0.01_JWRB)
  
  EFD_FAC = 4.0_JWRB*EGRCRV / G**2
  FFD_FAC = (EGRCRV / AFCRV)**(1.0_JWRB / BFCRV)*G
  
  !*    DETERMINE NORMALIZED FLUXES FROM AIR TO WAVE AND FROM WAVE TO OCEAN.
  !     -------------------------------------------------------------------
  
  !     ENERGY FLUX from SSURF
  !     MOMENTUM FLUX FROM SSURF
  
  PHILF = 0.0_JWRB
  XSTRESS = 0.0_JWRB
  YSTRESS = 0.0_JWRB
  
  !     THE INTEGRATION ONLY UP TO FR=MIJ
  DO M=1,NFRE
    K = 1
    SUMT = SSURF(IJ, K, M)
    SUMX = SINTH(K)*SSURF(IJ, K, M)
    SUMY = COSTH(K)*SSURF(IJ, K, M)
    DO K=2,NANG
      SUMT = SUMT + SSURF(IJ, K, M)
      SUMX = SUMX + SINTH(K)*SSURF(IJ, K, M)
      SUMY = SUMY + COSTH(K)*SSURF(IJ, K, M)
    END DO
    PHILF = PHILF + SUMT*RHOWGDFTH(IJ, M)
    CMRHOWGDFTH = CINV(IJ, M, ICHNK)*RHOWGDFTH(IJ, M)
    XSTRESS = XSTRESS + SUMX*CMRHOWGDFTH
    YSTRESS = YSTRESS + SUMY*CMRHOWGDFTH
  END DO
  
  IF (LICERUN .and. LWAMRSETCI) THEN
    IF (CICOVER(IJ, ICHNK) > CIBLOCK) THEN
      OOVAL = EXP(-MIN((CICOVER(IJ, ICHNK)*CITHRSH_INV)**4, 10._JWRB))
      !           ADJUST USTAR FOR THE PRESENCE OF SEA ICE
      U10P = MAX(WSWAVE(IJ, ICHNK), EPSU10)
      CD_BULK = MIN((C1 + C2*U10P**P1)*U10P**P2, CDMAX)
      CD_WAVE = (UFRIC(IJ, ICHNK) / U10P)**2
      CD_ICE = OOVAL*CD_WAVE + (1.0_JWRB - OOVAL)*CD_BULK
      USTAR = MAX(SQRT(CD_ICE)*U10P, EPSUS)
      
      ! EM_OC and F1_OC with fully developed model ENERGY
      ! The significant wave height derived from EM_OC will be used
      ! by NEMO as a scaling factor as if it was open ocean
      EFD = MIN(EFD_FAC*USTAR**4, EFD_MAX)
      EM_OC = MAX(OOVAL*EM(IJ) + (1.0_JWRB - OOVAL)*EFD, EFD_MIN)
      FFD = FFD_FAC / USTAR
      F1_OC = OOVAL*F1(IJ) + (1.0_JWRB - OOVAL)*FFD
      F1_OC = MIN(MAX(F1_OC, FR(2)), FR(NFRE))
    ELSE
      OOVAL = 1.0_JWRB
      USTAR = UFRIC(IJ, ICHNK)
      EM_OC = EM(IJ)
      F1_OC = F1(IJ)
    END IF
  ELSE
    OOVAL = 1.0_JWRB
    USTAR = UFRIC(IJ, ICHNK)
    EM_OC = EM(IJ)
    F1_OC = F1(IJ)
  END IF
  
  
  TAU = AIRD(IJ, ICHNK)*MAX(USTAR**2, EPSUS)
  TAUXD(IJ, ICHNK) = TAU*SIN(WDWAVE(IJ, ICHNK))
  TAUYD(IJ, ICHNK) = TAU*COS(WDWAVE(IJ, ICHNK))
  
  TAUOCXD(IJ, ICHNK) = TAUXD(IJ, ICHNK) - OOVAL*XSTRESS
  TAUOCYD(IJ, ICHNK) = TAUYD(IJ, ICHNK) - OOVAL*YSTRESS
  TAUO = SQRT(TAUOCXD(IJ, ICHNK)**2 + TAUOCYD(IJ, ICHNK)**2)
  TAUOC(IJ, ICHNK) = MIN(MAX(TAUO / TAU, TAUOCMIN), TAUOCMAX)
  
  XN = AIRD(IJ, ICHNK)*MAX(USTAR**3, EPSUS3)
  PHIOCD(IJ, ICHNK) = OOVAL*(PHILF - PHIWA(IJ)) + (1.0_JWRB - OOVAL)*PHIOC_ICE*XN
  
  PHIEPS(IJ, ICHNK) = PHIOCD(IJ, ICHNK) / XN
  PHIEPS(IJ, ICHNK) = MIN(MAX(PHIEPS(IJ, ICHNK), PHIEPSMIN), PHIEPSMAX)
  
  PHIOCD(IJ, ICHNK) = PHIEPS(IJ, ICHNK)*XN
  
  PHIAW(IJ, ICHNK) = PHIWA(IJ) / XN
  PHIAW(IJ, ICHNK) = OOVAL*PHIWA(IJ) / XN + (1.0_JWRB - OOVAL)*PHIAW_ICE
  
  IF (LWNEMOCOU .and. LNUPD) THEN
    NPHIEPS(IJ, ICHNK) = PHIEPS(IJ, ICHNK)
    NTAUOC(IJ, ICHNK) = TAUOC(IJ, ICHNK)
    IF (EM_OC /= 0.0_JWRB) THEN
      NSWH(IJ, ICHNK) = 4.0_JWRO*SQRT(EM_OC)
    ELSE
      NSWH(IJ, ICHNK) = 0.0_JWRO
    END IF
    IF (F1_OC /= 0.0_JWRB) THEN
      NMWP(IJ, ICHNK) = 1.0_JWRO / F1_OC
    ELSE
      NMWP(IJ, ICHNK) = 0.0_JWRO
    END IF
    
    IF (LWNEMOTAUOC) THEN
      NEMOTAUX(IJ, ICHNK) = NEMOTAUX(IJ, ICHNK) + TAUOCXD(IJ, ICHNK)
      NEMOTAUY(IJ, ICHNK) = NEMOTAUY(IJ, ICHNK) + TAUOCYD(IJ, ICHNK)
    ELSE
      NEMOTAUX(IJ, ICHNK) = NEMOTAUX(IJ, ICHNK) + TAUXD(IJ, ICHNK)
      NEMOTAUY(IJ, ICHNK) = NEMOTAUY(IJ, ICHNK) + TAUYD(IJ, ICHNK)
    END IF
    NEMOWSWAVE(IJ, ICHNK) = NEMOWSWAVE(IJ, ICHNK) + WSWAVE(IJ, ICHNK)
    NEMOPHIF(IJ, ICHNK) = NEMOPHIF(IJ, ICHNK) + PHIOCD(IJ, ICHNK)
  END IF
  
  
  ! ----------------------------------------------------------------------
  
END SUBROUTINE WNFLUXES_FC
