MODULE WNFLUXES_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE WNFLUXES_fc (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD, NPHIEPS,  &
  & NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW,  &
  & LNUPD, AFCRV, BFCRV, CIBLOCK, CITHRSH, COSTH, EGRCRV, EPSU10, EPSUS, FR, G, LICERUN, LWAMRSETCI, LWNEMOCOU, LWNEMOTAUOC,  &
  & NANG, NFRE, PHIEPSMAX, PHIEPSMIN, SINTH, TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWIM, JWRO, JWRB
    
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    LOGICAL, VALUE, INTENT(IN) :: LNUPD
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    !     FICTITIOUS VALUE OF THE NORMALISED WAVE ENERGY FLUX UNDER THE SEA ICE
    !     (negative because it is defined as leaving the waves)
    
    !     USE HERSBACH 2011 FOR CD(U10) (SEE ALSO EDSON et al. 2013)
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE WNFLUXES_iso_c (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD,  &
      & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD,  &
      & PHIEPS, PHIAW, LNUPD, AFCRV, BFCRV, CIBLOCK, CITHRSH, COSTH, EGRCRV, EPSU10, EPSUS, FR, G, LICERUN, LWAMRSETCI,  &
      & LWNEMOCOU, LWNEMOTAUOC, NANG, NFRE, PHIEPSMAX, PHIEPSMIN, SINTH, TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ) &
      &  BIND(c, name="wnfluxes_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: SSURF
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: PHIWA
        TYPE(c_ptr), VALUE :: EM
        TYPE(c_ptr), VALUE :: F1
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: NPHIEPS
        TYPE(c_ptr), VALUE :: NTAUOC
        TYPE(c_ptr), VALUE :: NSWH
        TYPE(c_ptr), VALUE :: NMWP
        TYPE(c_ptr), VALUE :: NEMOTAUX
        TYPE(c_ptr), VALUE :: NEMOTAUY
        TYPE(c_ptr), VALUE :: NEMOWSWAVE
        TYPE(c_ptr), VALUE :: NEMOPHIF
        TYPE(c_ptr), VALUE :: TAUXD
        TYPE(c_ptr), VALUE :: TAUYD
        TYPE(c_ptr), VALUE :: TAUOCXD
        TYPE(c_ptr), VALUE :: TAUOCYD
        TYPE(c_ptr), VALUE :: TAUOC
        TYPE(c_ptr), VALUE :: PHIOCD
        TYPE(c_ptr), VALUE :: PHIEPS
        TYPE(c_ptr), VALUE :: PHIAW
        LOGICAL, VALUE :: LNUPD
        REAL, VALUE :: AFCRV
        REAL, VALUE :: BFCRV
        REAL, VALUE :: CIBLOCK
        REAL, VALUE :: CITHRSH
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: EGRCRV
        REAL, VALUE :: EPSU10
        REAL, VALUE :: EPSUS
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: G
        LOGICAL, VALUE :: LICERUN
        LOGICAL, VALUE :: LWAMRSETCI
        LOGICAL, VALUE :: LWNEMOCOU
        LOGICAL, VALUE :: LWNEMOTAUOC
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: PHIEPSMAX
        REAL, VALUE :: PHIEPSMIN
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: TAUOCMAX
        REAL, VALUE :: TAUOCMIN
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE WNFLUXES_iso_c
    END INTERFACE
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SSURF(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: PHIWA(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: EM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: F1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
!$acc host_data use_device( MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD, NPHIEPS, NTAUOC,  &
!$acc & NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW,  &
!$acc & COSTH, FR, SINTH )
    CALL WNFLUXES_iso_c(KIJS, KIJL, c_loc(MIJ), c_loc(RHOWGDFTH), c_loc(CINV), c_loc(SSURF), c_loc(CICOVER), c_loc(PHIWA),  &
    & c_loc(EM), c_loc(F1), c_loc(WSWAVE), c_loc(WDWAVE), c_loc(UFRIC), c_loc(AIRD), c_loc(NPHIEPS), c_loc(NTAUOC), c_loc(NSWH),  &
    & c_loc(NMWP), c_loc(NEMOTAUX), c_loc(NEMOTAUY), c_loc(NEMOWSWAVE), c_loc(NEMOPHIF), c_loc(TAUXD), c_loc(TAUYD),  &
    & c_loc(TAUOCXD), c_loc(TAUOCYD), c_loc(TAUOC), c_loc(PHIOCD), c_loc(PHIEPS), c_loc(PHIAW), LNUPD, AFCRV, BFCRV, CIBLOCK,  &
    & CITHRSH, c_loc(COSTH), EGRCRV, EPSU10, EPSUS, c_loc(FR), G, LICERUN, LWAMRSETCI, LWNEMOCOU, LWNEMOTAUOC, NANG, NFRE,  &
    & PHIEPSMAX, PHIEPSMIN, c_loc(SINTH), TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE WNFLUXES_fc
END MODULE WNFLUXES_FC_MOD
