INTERFACE
  SUBROUTINE WNFLUXES_FC (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, UFRIC, AIRD, NPHIEPS,  &
  & NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW,  &
  & LNUPD, AFCRV, BFCRV, CIBLOCK, CITHRSH, COSTH, EGRCRV, EPSU10, EPSUS, FR, G, LICERUN, LWAMRSETCI, LWNEMOCOU, LWNEMOTAUOC,  &
  & NANG, NFRE, PHIEPSMAX, PHIEPSMIN, SINTH, TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
    USE PARKIND_WAVE, ONLY: JWRU, JWIM, JWRO, JWRB
    USE YOWDRVTYPE, ONLY: WAVE2OCEAN, FORCING_FIELDS, INTGT_PARAM_FIELDS
    
    
    USE YOWPCONS, ONLY: ZPI
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: MIJ(:, :)
    
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SSURF(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: PHIWA(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: EM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: F1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
    LOGICAL, VALUE, INTENT(IN) :: LNUPD
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    !     FICTITIOUS VALUE OF THE NORMALISED WAVE ENERGY FLUX UNDER THE SEA ICE
    !     (negative because it is defined as leaving the waves)
    
    !     USE HERSBACH 2011 FOR CD(U10) (SEE ALSO EDSON et al. 2013)
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
  END SUBROUTINE WNFLUXES_FC
END INTERFACE