! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
MODULE IMPLSCH_CUF_HOIST_NEW_MOD
  CONTAINS
  ATTRIBUTES(GLOBAL) SUBROUTINE IMPLSCH_CUF_HOIST_NEW (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT,  &
  & INDEP, DEPTH, IOBND, IODP, AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK,  &
  & NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN,  &
  & USTOKES, VSTOKES, STRNMS, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD,  &
  & ACDLIN, AF11, AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN,  &
  & BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL,  &
  & CM_GC, COFRM4, COSTH, CUMULW, DAL1, DAL2, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR,  &
  & DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN,  &
  & FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1,  &
  & INDICESSAT, INLCOEF, IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK,  &
  & LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK,  &
  & LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH,  &
  & NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU, RNUM, ROWATER, ROWATERM1,  &
  & SATWEIGHTS, SDSBR, SINTH, SQRTGOSURFT, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5,  &
  & SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL,  &
  & WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV,  &
  & Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK_start, ICHNK_end, ICHNK_step, NCHNK, RAORW, EMEAN, FMEAN, HALP,  &
  & EMEANWS, FMEANWS, F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE,  &
  & SINFLX_RNFAC, SINFLX_TMP_EM, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_UST, SNONLIN_XNU, SNONLIN_SIG_TH, ENH)
    
    ! ----------------------------------------------------------------------
    
    !**** *IMPLSCH* - IMPLICIT SCHEME FOR TIME INTEGRATION OF SOURCE
    !****             FUNCTIONS.
    
    
    !*    PURPOSE.
    !     --------
    
    !       THE IMPLICIT SCHEME ENABLES THE USE OF A TIMESTEP WHICH IS
    !       LARGE COMPARED WITH THE CHARACTERISTIC DYNAMIC TIME SCALE.
    !       THE SCHEME IS REQUIRED FOR THE HIGH FREQUENCIES WHICH
    !       RAPIDLY ADJUST TO A QUASI-EQUILIBRIUM.
    
    !**   INTERFACE.
    !     ----------
    
    !       *CALL* *IMPLSCH (KIJS, KIJL, FL1,
    !    &                   WVPRPT,
    !    &                   WVENVI, FF_NOW,
    !    &                   INTFLDS, WAM2NEMO,
    !    &                   MIJ,  XLLWS)
    !      *KIJS*    - LOCAL INDEX OF FIRST GRIDPOINT
    !      *KIJL*    - LOCAL INDEX OF LAST GRIDPOINT
    !      *FL1*     - FREQUENCY SPECTRUM(INPUT AND OUTPUT).
    !      *WVPRPT*  - WAVE PROPERTIES FIELDS
    !      *WVENVI*  - WAVE ENVIRONMENT
    !      *FF_NOW*    FORCING FIELDS
    !      *INTFLDS*   INTEGRATED/DERIVED PARAMETERS
    !      *WAM2NEMO*  WAVE FIELDS PASSED TO NEMO
    !      *MIJ*       LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
    !      *XLLWS*     TOTAL WINDSEA MASK FROM INPUT SOURCE TERM
    
    
    !     METHOD.
    !     -------
    
    !       THE SPECTRUM AT TIME (TN+1) IS COMPUTED AS
    !       FN+1=FN+DELT*(SN+SN+1)/2., WHERE SN IS THE TOTAL SOURCE
    !       FUNCTION AT TIME TN, SN+1=SN+(DS/DF)*DF - ONLY THE DIAGONAL
    !       TERMS OF THE FUNCTIONAL MATRIX DS/DF ARE YOWPUTED, THE
    !       NONDIAGONAL TERMS ARE NEGLIGIBLE.
    !       THE ROUTINE IS CALLED AFTER PROPAGATION FOR TIME PERIOD
    !       BETWEEN TWO PROPAGATION CALLS - ARRAY FL1 CONTAINS THE
    !       SPECTRUM AND FL IS USED AS AN INTERMEDIATE STORAGE FOR THE
    !       DIAGONAL TERM OF THE FUNCTIONAL MATRIX.
    
    
    !     REFERENCE.
    !     ----------
    
    !       S. HASSELMANN AND K. HASSELMANN, "A GLOBAL WAVE MODEL",
    !       30/6/85 (UNPUBLISHED NOTE)
    
    ! ----------------------------------------------------------------------
    
    USE WNFLUXES_CUF_HOIST_NEW_MOD, ONLY: WNFLUXES_CUF_HOIST_NEW
    USE STOKESTRN_CUF_HOIST_NEW_MOD, ONLY: STOKESTRN_CUF_HOIST_NEW
    USE SNONLIN_CUF_HOIST_NEW_MOD, ONLY: SNONLIN_CUF_HOIST_NEW
    USE SINFLX_CUF_HOIST_NEW_MOD, ONLY: SINFLX_CUF_HOIST_NEW
    USE SETICE_CUF_HOIST_NEW_MOD, ONLY: SETICE_CUF_HOIST_NEW
    USE SDIWBK_CUF_HOIST_NEW_MOD, ONLY: SDIWBK_CUF_HOIST_NEW
    USE SDISSIP_CUF_HOIST_NEW_MOD, ONLY: SDISSIP_CUF_HOIST_NEW
    USE SDEPTHLIM_CUF_HOIST_NEW_MOD, ONLY: SDEPTHLIM_CUF_HOIST_NEW
    USE IMPHFTAIL_CUF_HOIST_NEW_MOD, ONLY: IMPHFTAIL_CUF_HOIST_NEW
    USE SBOTTOM_CUF_HOIST_NEW_MOD, ONLY: SBOTTOM_CUF_HOIST_NEW
    USE FKMEAN_CUF_HOIST_NEW_MOD, ONLY: FKMEAN_CUF_HOIST_NEW
    USE FEMEANWS_CUF_HOIST_NEW_MOD, ONLY: FEMEANWS_CUF_HOIST_NEW
    USE CIWABR_CUF_HOIST_NEW_MOD, ONLY: CIWABR_CUF_HOIST_NEW
    USE cudafor
    USE PARKIND_WAVE, ONLY: JWIM, JWRU, JWRO, JWRB
    USE YOWDRVTYPE, ONLY: INTGT_PARAM_FIELDS, FORCING_FIELDS, FREQUENCY, ENVIRONMENT, WAVE2OCEAN
    
    
    
    IMPLICIT NONE
    ! ----------------------------------------------------------------------
    
    
    INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
    INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
    INTEGER(KIND=JWIM), PARAMETER :: NRNL = 25
    INTEGER(KIND=JWIM), PARAMETER :: NINL = 5
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    REAL(KIND=JWRB), INTENT(INOUT) :: FL1(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: WAVNUM(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CGROUP(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CIWA(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CINV(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: XK2CG(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: STOKFAC(KIJL, NFRE_loki_param, NCHNK)
    
    REAL(KIND=JWRB), INTENT(IN) :: EMAXDPT(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: DEPTH(KIJL, NCHNK)
    INTEGER(KIND=JWIM), INTENT(IN) :: INDEP(KIJL, NCHNK)
    INTEGER(KIND=JWIM), INTENT(IN) :: IODP(KIJL, NCHNK)
    INTEGER(KIND=JWIM), INTENT(IN) :: IOBND(KIJL, NCHNK)
    
    REAL(KIND=JWRB), INTENT(IN) :: WDWAVE(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CICOVER(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: AIRD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: WSTAR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CITHICK(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: UFRIC(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUW(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUWDIR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: Z0M(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: Z0B(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: CHRNCK(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: WSWAVE(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: WSEMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: WSFMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: USTOKES(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: VSTOKES(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: STRNMS(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUXD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUYD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUOCXD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUOCYD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: TAUOC(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: PHIOCD(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: PHIEPS(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: PHIAW(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOUSTOKES(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOVSTOKES(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOSTRN(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NPHIEPS(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NTAUOC(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NSWH(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NMWP(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOTAUX(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOTAUY(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOWSWAVE(KIJL, NCHNK)
    REAL(KIND=JWRO), INTENT(INOUT) :: NEMOPHIF(KIJL, NCHNK)
    INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(OUT) :: XLLWS(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    
REAL(KIND=JWRB), INTENT(INOUT), DEVICE, DIMENSION(KIJL, MLSTHG, NCHNK) :: ENH

    INTEGER(KIND=JWIM) :: IJ
    INTEGER(KIND=JWIM) :: K
    INTEGER(KIND=JWIM) :: M
    
    REAL(KIND=JWRB) :: DELT
    REAL(KIND=JWRB) :: DELTM
    REAL(KIND=JWRB) :: XIMP
    REAL(KIND=JWRB) :: DELT5
    REAL(KIND=JWRB) :: GTEMP1
    REAL(KIND=JWRB) :: GTEMP2
    REAL(KIND=JWRB) :: FLHAB
    REAL(KIND=JWRB), INTENT(INOUT) :: RAORW(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: EMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: FMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: HALP(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: EMEANWS(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: FMEANWS(KIJL, NCHNK)
    REAL(KIND=JWRB) :: USFM
    REAL(KIND=JWRB), INTENT(INOUT) :: F1MEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: AKMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: XKMEAN(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: PHIWA(KIJL, NCHNK)
    
    REAL(KIND=JWRB), INTENT(INOUT) :: FLM(KIJL, NANG_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: COSWDIF(KIJL, NANG_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SINWDIF2(KIJL, NANG_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: RHOWGDFTH(KIJL, NFRE_loki_param, NCHNK)
    !     *FLD* DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE
    !     *SL*  TOTAL SOURCE FUNCTION ARRAY.
    !     *SPOS* : POSITIVE SINPUT ONLY
    REAL(KIND=JWRB), INTENT(INOUT) :: FLD(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SL(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SPOS(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: CIREDUC(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SSOURCE(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    
    LOGICAL :: LCFLX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: AF11(MFRSTLW:MLSTHG)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: C2OSQRTVG_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDICWA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: CM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: COFRM4(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: COSTH(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: CUMULW(NDEPTH, 0:NANG/2, NFRE_loki_param, NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DELKCC_GC_NS(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DELKCC_OMXKM3_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIM(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIMFR(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIMFR2(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIMOFR(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIM_SIM(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FKLAM(MFRSTLW:MLSTHG)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FKLAM1(MFRSTLW:MLSTHG)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FKLAP(MFRSTLW:MLSTHG)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FKLAP1(MFRSTLW:MLSTHG)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FLMAX(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FR(NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: FR5(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDELT
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: IKM(MFRSTLW:MLSTHG)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: IKM1(MFRSTLW:MLSTHG)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: IKP(MFRSTLW:MLSTHG)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: IKP1(MFRSTLW:MLSTHG)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: INDICESSAT(NANG_loki_param, NSDSNTH*2+1)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: INLCOEF(NINL, 1:MLSTHG)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: K11W(NANG_loki_param, 2)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: K1W(NANG_loki_param, 2)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: K21W(NANG_loki_param, 2)
    INTEGER(KIND=JWIM), INTENT(IN), DEVICE :: K2W(NANG_loki_param, 2)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
    LOGICAL, VALUE, INTENT(IN) :: LBIWBK
    LOGICAL, VALUE, INTENT(IN) :: LCIWABR
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    LOGICAL, VALUE, INTENT(IN) :: LLUNSTR
    LOGICAL, VALUE, INTENT(IN) :: LMASKICE
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    LOGICAL, VALUE, INTENT(IN) :: LWFLUX
    LOGICAL, VALUE, INTENT(IN) :: LWFLUXOUT
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
    LOGICAL, VALUE, INTENT(IN) :: LWVFLX_SNL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDEPTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NDIKCUMUL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_RED
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: OM3GMKM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: OMEGA_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: OMXKM3_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: RHOWG_DFIM(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: RNLCOEF(NRNL, 1:MLSTHG)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATERM1
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: SATWEIGHTS(NANG_loki_param, NSDSNTH*2+1)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: SINTH(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), INTENT(IN) :: SWELLFT(IAB)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: TH(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSEMEAN_MIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), INTENT(IN) :: WTAUHF(JTOT_TAUHF)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XKMSQRTVGOC2_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XKM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XK_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: ZPIFR(NFRE_loki_param)
    INTEGER(KIND=JWIM) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_start
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_end
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK_step
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    REAL(KIND=JWRB), INTENT(INOUT) :: SINFLX_RNFAC(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SINFLX_TMP_EM(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: STRESSO_TAUHF(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: STRESSO_PHIHF(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: STRESSO_UST(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SNONLIN_XNU(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: SNONLIN_SIG_TH(KIJL, NCHNK)
    IJ = THREADIDX%X
    ICHNK = BLOCKIDX%Z
    
    IF (ICHNK <= NCHNK .and. IJ <= KIJL) THEN
      
      ! START of Loki inserted loop ICHNK
      
      
      ! ----------------------------------------------------------------------
      
      
      
      !*    1. INITIALISATION.
      !        ---------------
      
      DELT = IDELT
      DELTM = 1.0_JWRB / DELT
      XIMP = 1.0_JWRB
      DELT5 = XIMP*DELT
      
      LCFLX = LWFLUX .or. LWFLUXOUT .or. LWNEMOCOU
      
      
      
      RAORW(IJ, ICHNK) = MAX(AIRD(IJ, ICHNK), 1.0_JWRB)*ROWATERM1
      
      DO K=1,NANG
        COSWDIF(IJ, K, ICHNK) = COS(TH(K) - WDWAVE(IJ, ICHNK))
        SINWDIF2(IJ, K, ICHNK) = SIN(TH(K) - WDWAVE(IJ, ICHNK))**2
      END DO
      
      
      ! ----------------------------------------------------------------------
      
      !*    2. COMPUTATION OF IMPLICIT INTEGRATION.
      !        ------------------------------------
      
      !         INTEGRATION IS DONE FROM CDATE UNTIL CDTPRO FOR A BLOCK
      !         OF LATITUDES BETWEEN PROPAGATION CALLS.
      
      
      !     REDUCE WAVE ENERGY IF LARGER THAN DEPTH LIMITED WAVE HEIGHT
      IF (LBIWBK) THEN
        CALL SDEPTHLIM_CUF_HOIST_NEW(KIJS, KIJL, EMAXDPT(:, :), FL1(:, :, :, :), DELTH, DFIM(:), EPSMIN, FR(:), NANG, NFRE,  &
        & WETAIL, ICHNK, NCHNK, IJ)
      END IF

      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sdepthlim FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      
      !*    2.2 COMPUTE MEAN PARAMETERS.
      !        ------------------------
      
      CALL FKMEAN_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), EMEAN(:, ICHNK), FMEAN(:, ICHNK),  &
      & F1MEAN(:, ICHNK), AKMEAN(:, ICHNK), XKMEAN(:, ICHNK), DELTH, DFIM(:), DFIMFR(:), DFIMOFR(:), EPSMIN, FR(:), FRTAIL, G,  &
      & NANG, NFRE, WETAIL, WP1TAIL, ZPI, ICHNK, NCHNK, IJ)
      
     
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after fkmean FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF

      DO K=1,NANG
        FLM(IJ, K, ICHNK) = FLMIN*MAX(0.0_JWRB, COSWDIF(IJ, K, ICHNK))**2
      END DO
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after fkmean FLM(1, 1, 1) = ", FLM(1, 1, 1)
      !   print *, "  FLMIN: ", FLMIN
      !   print *, "  COSWDIF(1, 1, 1): ", COSWDIF(1, 1, 1)
      ! END IF

      !     COMPUTE DAMPING COEFFICIENT DUE TO FRICTION ON BOTTOM OF THE SEA ICE.
      !!! testing sea ice attenuation (might need to restrict usage when needed)
      IF (LCIWABR) THEN
        CALL CIWABR_CUF_HOIST_NEW(KIJS, KIJL, CICOVER(:, :), FL1(:, :, :, :), WAVNUM(:, :, :), CGROUP(:, :, :),  &
        & CIREDUC(:, :, :, ICHNK), CDICWA, DFIM(:), EPSMIN, IDELT, LICERUN, LMASKICE, NANG, NFRE, ICHNK, NCHNK, IJ)
        ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
        !   print *, "within implsch after ciwabr FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
        ! END IF 
        DO M=1,NFRE
          DO K=1,NANG
            CIREDUC(IJ, K, M, ICHNK) = CIWA(IJ, M, ICHNK)*CIREDUC(IJ, K, M, ICHNK)
          END DO
        END DO
        
      ELSE
        
        DO M=1,NFRE
          DO K=1,NANG
            CIREDUC(IJ, K, M, ICHNK) = CIWA(IJ, M, ICHNK)
          END DO
        END DO
        
      END IF
      
      ! ----------------------------------------------------------------------
      
      !*    2.3 COMPUTATION OF SOURCE FUNCTIONS.
      !         --------------------------------
      
      !*    2.3.1 ITERATIVELY UPDATE STRESS AND COMPUTE WIND INPUT TERMS.
      !           -------------------------------------------------------
      
      CALL SINFLX_CUF_HOIST_NEW(1, KIJS, KIJL, .true., FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :),  &
      & WSWAVE(:, :), WDWAVE(:, :), AIRD(:, :), RAORW(:, ICHNK), WSTAR(:, :), CICOVER(:, :), COSWDIF(:, :, ICHNK),  &
      & SINWDIF2(:, :, ICHNK), FMEAN(:, ICHNK), HALP(:, ICHNK), FMEANWS(:, ICHNK), FLM(:, :, ICHNK), UFRIC(:, :), TAUW(:, :),  &
      & TAUWDIR(:, :), Z0M(:, :), Z0B(:, :), CHRNCK(:, :), PHIWA(:, ICHNK), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK),  &
      & SPOS(:, :, :, ICHNK), MIJ(:, :), RHOWGDFTH(:, :, ICHNK), XLLWS(:, :, :, :), ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX,  &
      & ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC(:), CDMAX,  &
      & CHNKMIN_U, CITHRSH_TAIL, CM_GC(:), COSTH(:), DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:), DELTH, DFIM(:), DFIMOFR(:), DTHRN_A,  &
      & DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR(:), FR5(:), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL,  &
      & IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC(:), OMEGA_GC(:),  &
      & OMXKM3_GC(:), RHOWG_DFIM(:), RN1_RN, RNU, RNUM, SINTH(:), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5,  &
      & SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:), TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH(:), WETAIL, WSPMIN, WTAUHF(:),  &
      & X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC(:), XKM_GC(:), XK_GC(:), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR(:), ICHNK, NCHNK, IJ, RNFAC=SINFLX_RNFAC, TMP_EM=SINFLX_TMP_EM, STRESSO_TAUHF=STRESSO_TAUHF,  &
      & STRESSO_PHIHF=STRESSO_PHIHF, STRESSO_UST=STRESSO_UST)
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sinflx (1) FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      CALL SINFLX_CUF_HOIST_NEW(2, KIJS, KIJL, .true., FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :),  &
      & WSWAVE(:, :), WDWAVE(:, :), AIRD(:, :), RAORW(:, ICHNK), WSTAR(:, :), CICOVER(:, :), COSWDIF(:, :, ICHNK),  &
      & SINWDIF2(:, :, ICHNK), FMEAN(:, ICHNK), HALP(:, ICHNK), FMEANWS(:, ICHNK), FLM(:, :, ICHNK), UFRIC(:, :), TAUW(:, :),  &
      & TAUWDIR(:, :), Z0M(:, :), Z0B(:, :), CHRNCK(:, :), PHIWA(:, ICHNK), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK),  &
      & SPOS(:, :, :, ICHNK), MIJ(:, :), RHOWGDFTH(:, :, ICHNK), XLLWS(:, :, :, :), ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX,  &
      & ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC(:), CDMAX,  &
      & CHNKMIN_U, CITHRSH_TAIL, CM_GC(:), COSTH(:), DELKCC_GC_NS(:), DELKCC_OMXKM3_GC(:), DELTH, DFIM(:), DFIMOFR(:), DTHRN_A,  &
      & DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR(:), FR5(:), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL,  &
      & IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, OM3GMKM_GC(:), OMEGA_GC(:),  &
      & OMXKM3_GC(:), RHOWG_DFIM(:), RN1_RN, RNU, RNUM, SINTH(:), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5,  &
      & SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:), TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH(:), WETAIL, WSPMIN, WTAUHF(:),  &
      & X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC(:), XKM_GC(:), XK_GC(:), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR(:), ICHNK, NCHNK, IJ, RNFAC=SINFLX_RNFAC, TMP_EM=SINFLX_TMP_EM, STRESSO_TAUHF=STRESSO_TAUHF,  &
      & STRESSO_PHIHF=STRESSO_PHIHF, STRESSO_UST=STRESSO_UST)
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sinflux (2) FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      !     2.3.3 ADD THE OTHER SOURCE TERMS.
      !           ---------------------------
      
      CALL SDISSIP_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), INDEP(:, :),  &
      & WAVNUM(:, :, :), XK2CG(:, :, :), EMEAN(:, ICHNK), F1MEAN(:, ICHNK), XKMEAN(:, ICHNK), UFRIC(:, :), COSWDIF(:, :, ICHNK),  &
      & RAORW(:, ICHNK), CDIS, CDISVIS, CUMULW(:, :, :, :), DELTA_SDIS, G, INDICESSAT(:, :), IPHYS, IPSAT, MICHE, NANG, NDEPTH,  &
      & NDIKCUMUL, NFRE, NSDSNTH, RNU, SATWEIGHTS(:, :), SDSBR, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR(:), ICHNK,  &
      & NCHNK, IJ)
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sdissip FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      !     Save source term contributions relevant for the calculation of ocean fluxes
      
      IF (LCFLX .and. .not.LWVFLX_SNL) THEN
        DO M=1,NFRE
          DO K=1,NANG
            SSOURCE(IJ, K, M, ICHNK) = SL(IJ, K, M, ICHNK)
          END DO
        END DO
      END IF
      
      
      CALL SNONLIN_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), WAVNUM(:, :, :),  &
      & DEPTH(:, :), AKMEAN(:, ICHNK), AF11(:), BATHYMAX, COSTH(:), DAL1, DAL2, DELTH, DFIM(:), DFIMFR(:), DFIMFR2(:), DKMAX,  &
      & FKLAM(:), FKLAM1(:), FKLAP(:), FKLAP1(:), FR(:), FRATIO, G, GM1, IKM(:), IKM1(:), IKP(:), IKP1(:), INLCOEF(:, :),  &
      & ISNONLIN, K11W(:, :), K1W(:, :), K21W(:, :), K2W(:, :), KFRH, MFRSTLW, MLSTHG, NANG, NFRE, RNLCOEF(:, :), SINTH(:),  &
      & TH(:), WETAIL, WP1TAIL, WP2TAIL, XKDMIN, ZPIFR(:), ICHNK, NCHNK, IJ, XNU=SNONLIN_XNU, SIG_TH=SNONLIN_SIG_TH, ENH=ENH(:,:,ICHNK))
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after snonlin FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      IF (LCFLX .and. LWVFLX_SNL) THEN
        !     Save source term contributions relevant for the calculation of ocean fluxes
        !!!!!!  SL must only contain contributions contributed to fluxes into the oceans
        !       MODULATE SL BY IMPLICIT FACTOR
        DO M=1,NFRE
          DO K=1,NANG
            GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
            SSOURCE(IJ, K, M, ICHNK) = SL(IJ, K, M, ICHNK) / GTEMP1
          END DO
        END DO
      END IF
      
      
      
      CALL SDIWBK_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), DEPTH(:, :),  &
      & EMAXDPT(:, :), EMEAN(:, ICHNK), F1MEAN(:, ICHNK), LBIWBK, NANG, NFRE_RED, ICHNK, NCHNK, IJ)
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sdiwbk FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF

      CALL SBOTTOM_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), FLD(:, :, :, ICHNK), SL(:, :, :, ICHNK), WAVNUM(:, :, :),  &
      & DEPTH(:, :), BATHYMAX, GM1, NANG, NFRE_RED, ICHNK, NCHNK, IJ)
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after sbottom FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      ! ----------------------------------------------------------------------
      
      !*    2.4 COMPUTATION OF NEW SPECTRA.
      !         ---------------------------
      
      !     INCREASE OF SPECTRUM IN A TIME STEP IS LIMITED TO A FINITE
      !     FRACTION OF A TYPICAL F**(-4) EQUILIBRIUM SPECTRUM.
      
      
      USFM = UFRIC(IJ, ICHNK)*MAX(FMEANWS(IJ, ICHNK), FMEAN(IJ, ICHNK))
      
      IF (LLUNSTR) THEN
        ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
        !  print *, "within branch 1 ..."
        ! ENDIF
        DO K=1,NANG
          DO M=1,NFRE
            GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
            GTEMP2 = DELT*SL(IJ, K, M, ICHNK) / GTEMP1
            FLHAB = ABS(GTEMP2)
            FLHAB = MIN(FLHAB, USFM*COFRM4(M)*DELT)
            FL1(IJ, K, M, ICHNK) = FL1(IJ, K, M, ICHNK) + IOBND(IJ, ICHNK)*SIGN(FLHAB, GTEMP2)
            FL1(IJ, K, M, ICHNK) = MAX(IODP(IJ, ICHNK)*CIREDUC(IJ, K, M, ICHNK)*FL1(IJ, K, M, ICHNK), FLM(IJ, K, ICHNK))
            SSOURCE(IJ, K, M, ICHNK) = SSOURCE(IJ, K, M, ICHNK) + DELTM*MIN(FLMAX(M) - FL1(IJ, K, M, ICHNK), 0.0_JWRB)
            FL1(IJ, K, M, ICHNK) = MIN(FL1(IJ, K, M, ICHNK), FLMAX(M))
          END DO
        END DO
      ELSE
       ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
       !   print *, "within branch 2 ..."
       ! ENDIF
        DO K=1,NANG
          DO M=1,NFRE
            GTEMP1 = MAX((1.0_JWRB - DELT5*FLD(IJ, K, M, ICHNK)), 1.0_JWRB)
            GTEMP2 = DELT*SL(IJ, K, M, ICHNK) / GTEMP1
            FLHAB = ABS(GTEMP2)
            FLHAB = MIN(FLHAB, USFM*COFRM4(M)*DELT)
            FL1(IJ, K, M, ICHNK) = FL1(IJ, K, M, ICHNK) + SIGN(FLHAB, GTEMP2)
            FL1(IJ, K, M, ICHNK) = MAX(CIREDUC(IJ, K, M, ICHNK)*FL1(IJ, K, M, ICHNK), FLM(IJ, K, ICHNK))
            SSOURCE(IJ, K, M, ICHNK) = SSOURCE(IJ, K, M, ICHNK) + DELTM*MIN(FLMAX(M) - FL1(IJ, K, M, ICHNK), 0.0_JWRB)
            FL1(IJ, K, M, ICHNK) = MIN(FL1(IJ, K, M, ICHNK), FLMAX(M))
          END DO
        END DO
      END IF

      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after computation of new spectra FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      !   print *, "    FLM(1, 1, 1) = ", FLM(1, 1, 1)
      !   print *, "    CIREDUC(1, 1, 1, 1) = ", CIREDUC(1, 1, 1, 1)
      !   print *, "    FLHAB = ", FLHAB
      !   print *, "    GTEMP2 = ", GTEMP2
      ! END IF
      
      
      IF (LCFLX) THEN
        CALL WNFLUXES_CUF_HOIST_NEW(KIJS, KIJL, MIJ(:, :), RHOWGDFTH(:, :, ICHNK), CINV(:, :, :), SSOURCE(:, :, :, ICHNK),  &
        & CICOVER(:, :), PHIWA(:, ICHNK), EMEAN(:, ICHNK), F1MEAN(:, ICHNK), WSWAVE(:, :), WDWAVE(:, :), UFRIC(:, :),  &
        & AIRD(:, :), NPHIEPS(:, :), NTAUOC(:, :), NSWH(:, :), NMWP(:, :), NEMOTAUX(:, :), NEMOTAUY(:, :), NEMOWSWAVE(:, :),  &
        & NEMOPHIF(:, :), TAUXD(:, :), TAUYD(:, :), TAUOCXD(:, :), TAUOCYD(:, :), TAUOC(:, :), PHIOCD(:, :), PHIEPS(:, :),  &
        & PHIAW(:, :), .true., AFCRV, BFCRV, CIBLOCK, CITHRSH, COSTH(:), EGRCRV, EPSU10, EPSUS, FR(:), G, LICERUN, LWAMRSETCI,  &
        & LWNEMOCOU, LWNEMOTAUOC, NANG, NFRE, PHIEPSMAX, PHIEPSMIN, SINTH(:), TAUOCMAX, TAUOCMIN, ICHNK, NCHNK, IJ)
      END IF
      ! ----------------------------------------------------------------------
      
      !*    2.5 REPLACE DIAGNOSTIC PART OF SPECTRA BY A F**(-5) TAIL.
      !         -----------------------------------------------------
      
      CALL FKMEAN_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), EMEAN(:, ICHNK), FMEAN(:, ICHNK),  &
      & F1MEAN(:, ICHNK), AKMEAN(:, ICHNK), XKMEAN(:, ICHNK), DELTH, DFIM(:), DFIMFR(:), DFIMOFR(:), EPSMIN, FR(:), FRTAIL, G,  &
      & NANG, NFRE, WETAIL, WP1TAIL, ZPI, ICHNK, NCHNK, IJ)
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after fkmean FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF

      !     MEAN FREQUENCY CHARACTERISTIC FOR WIND SEA
      CALL FEMEANWS_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), XLLWS(:, :, :, :), FMEANWS(:, ICHNK), EMEANWS(:, ICHNK), DELTH,  &
      & DFIM(:), DFIMOFR(:), EPSMIN, FR(:), FRTAIL, NANG, NFRE, WETAIL, ICHNK, NCHNK, IJ)
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after femeanws FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF

      CALL IMPHFTAIL_CUF_HOIST_NEW(KIJS, KIJL, MIJ(:, :), FLM(:, :, ICHNK), WAVNUM(:, :, :), XK2CG(:, :, :), FL1(:, :, :, :),  &
      & NANG, NFRE, ICHNK, NCHNK, IJ)
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after imphftail FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      !     UPDATE WINDSEA VARIANCE AND MEAN FREQUENCY IF PASSED TO ATMOSPHERE
      !     ------------------------------------------------------------------
      
      IF (LWFLUX) THEN
        IF (EMEANWS(IJ, ICHNK) < WSEMEAN_MIN) THEN
          WSEMEAN(IJ, ICHNK) = WSEMEAN_MIN
          WSFMEAN(IJ, ICHNK) = 2._JWRB*FR(NFRE)
        ELSE
          WSEMEAN(IJ, ICHNK) = EMEANWS(IJ, ICHNK)
          WSFMEAN(IJ, ICHNK) = FMEANWS(IJ, ICHNK)
        END IF
      END IF
      
      
      
      !*    2.6 SET FL1 ON ICE POINTS TO ZERO
      !         -----------------------------
      
      IF (LICERUN .and. LMASKICE) THEN
        CALL SETICE_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), CICOVER(:, :), COSWDIF(:, :, ICHNK), CITHRSH, EPSMIN, FLMIN,  &
        & NANG, NFRE, ICHNK, NCHNK, IJ)
      END IF
      
      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after settice FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      
      !*    2.7 SURFACE STOKES DRIFT AND STRAIN IN SEA ICE
      !         ------------------------------------------
      
      CALL STOKESTRN_CUF_HOIST_NEW(KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), STOKFAC(:, :, :), DEPTH(:, :), WSWAVE(:, :),  &
      & WDWAVE(:, :), CICOVER(:, :), CITHICK(:, :), USTOKES(:, :), VSTOKES(:, :), STRNMS(:, :), NEMOUSTOKES(:, :),  &
      & NEMOVSTOKES(:, :), NEMOSTRN(:, :), CITHRSH, COSTH(:), DELTH, DFIM(:), DFIM_SIM(:), FLMIN, FR(:), G, LICERUN, LWAMRSETCI,  &
      & LWCOU, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, NANG, NFRE, NFRE_ODD, ROWATER, SINTH(:), ZPI, ICHNK,  &
      & NCHNK, IJ)

      ! IF (IJ .eq. 1 .AND. ICHNK .eq. 1) THEN
      !   print *, "within implsch after stokestrn FL1(1, 1, 1, 1) = ", FL1(1, 1, 1, 1)
      ! END IF
      
      ! ----------------------------------------------------------------------
      
      
      ! END of Loki inserted loop ICHNK
    END IF
  END SUBROUTINE IMPLSCH_CUF_HOIST_NEW
END MODULE IMPLSCH_CUF_HOIST_NEW_MOD
