! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
MODULE SINPUT_CUF_HOIST_NEW_MOD
  CONTAINS
  ATTRIBUTES(DEVICE) SUBROUTINE SINPUT_CUF_HOIST_NEW (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC,  &
  & Z0M, COSWDIF, SINWDIF2, RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN,  &
  & BETAMAXOXKAPPA2, COSTH, DELTH, DFIM, EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM,  &
  & SINTH, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA,  &
  & Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPIFR, ICHNK, NCHNK, IJ)
    ! ----------------------------------------------------------------------
    
    !**** *SINPUT* - COMPUTATION OF INPUT SOURCE FUNCTION.
    
    
    !**   INTERFACE.
    !     ----------
    
    !     *CALL* *SINPUT (NGST, LLSNEG, KIJS, KIJL, FL1,
    !    &                WAVNUM, CINV, XK2CG,
    !    &                WDWAVE, UFRIC, Z0M,
    !    &                COSWDIF, SINWDIF2,
    !    &                RAORW, WSTAR, FLD, SL, SPOS, XLLWS)
    !         *NGST* - IF = 1 THEN NO GUSTINESS PARAMETERISATION
    !                - IF = 2 THEN GUSTINESS PARAMETERISATION
    !         *LLSNEG* - IF TRUE THEN THE NEGATIVE SINPUT WILL BE COMPUTED
    !         *KIJS* - INDEX OF FIRST GRIDPOINT.
    !         *KIJL* - INDEX OF LAST GRIDPOINT.
    !          *FL1* - SPECTRUM.
    !       *WAVNUM* - WAVE NUMBER.
    !         *CINV* - INVERSE PHASE VELOCITY.
    !       *XK2CG*  - (WAVE NUMBER)**2 * GROUP SPPED.
    !       *WDWAVE* - WIND DIRECTION IN RADIANS IN OCEANOGRAPHIC
    !                  NOTATION (POINTING ANGLE OF WIND VECTOR,
    !                  CLOCKWISE FROM NORTH).
    !        *UFRIC* - FRICTION VELOCITY IN M/S.
    !        *Z0M*   - ROUGHNESS LENGTH IN M.
    !      *COSWDIF* - COS(TH(K)-WDWAVE(IJ))
    !     *SINWDIF2* - SIN(TH(K)-WDWAVE(IJ))**2
    !        *RAORW* - RATIO AIR DENSITY TO WATER DENSITY.
    !        *WSTAR* - FREE CONVECTION VELOCITY SCALE (M/S).
    !        *RNFAC* - WIND DEPENDENT FACTOR USED IN THE GROWTH RENORMALISATION.
    !          *FLD* - DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE.
    !           *SL* - TOTAL SOURCE FUNCTION ARRAY.
    !         *SPOS* - POSITIVE SOURCE FUNCTION ARRAY.
    !        *XLLWS* - = 1 WHERE SINPUT IS POSITIVE
    
    !     METHOD.
    !     -------
    
    !     DEPENDING ON THE VALUE OF IPHYS, DIFFERENT INPUTE SOURCE TERm WILL BE CALLED
    
    !     EXTERNALS.
    !     ----------
    
    !     MODIFICATIONS
    !     -------------
    
    !     REFERENCE.
    !     ----------
    
    
    ! ----------------------------------------------------------------------
    USE cudafor
    USE PARKIND_WAVE, ONLY: JWIM, JWRU, JWRB
    
    
    USE SINPUT_ARD_CUF_HOIST_NEW_MOD, ONLY: SINPUT_JAN_CUF_HOIST_NEW, SINPUT_ARD_CUF_HOIST_NEW
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
    INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NGST
    LOGICAL, VALUE, INTENT(IN) :: LLSNEG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    REAL(KIND=JWRB), INTENT(IN) :: FL1(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: WAVNUM(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: CINV(KIJL, NFRE_loki_param, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: XK2CG(KIJL, NFRE_loki_param, NCHNK)
    
    REAL(KIND=JWRB), INTENT(IN) :: WDWAVE(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: WSWAVE(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: UFRIC(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: Z0M(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: RAORW(KIJL)
    REAL(KIND=JWRB), INTENT(IN) :: RNFAC(KIJL)
    REAL(KIND=JWRB), INTENT(IN) :: WSTAR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: COSWDIF(KIJL, NANG_loki_param)
    REAL(KIND=JWRB), INTENT(IN) :: SINWDIF2(KIJL, NANG_loki_param)
    
    REAL(KIND=JWRB), INTENT(OUT) :: FLD(KIJL, NANG_loki_param, NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(OUT) :: SL(KIJL, NANG_loki_param, NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(OUT) :: SPOS(KIJL, NANG_loki_param, NFRE_loki_param)
    REAL(KIND=JWRB), INTENT(OUT) :: XLLWS(KIJL, NANG_loki_param, NFRE_loki_param, NCHNK)
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: COSTH(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DFIM(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: SINTH(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), INTENT(IN) :: SWELLFT(IAB)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: TH(NFRE_loki_param)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: ZPIFR(NFRE_loki_param)
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    ! ----------------------------------------------------------------------
    
    
    SELECT CASE (IPHYS)
    CASE (0)
      CALL SINPUT_JAN_CUF_HOIST_NEW(NGST, LLSNEG, KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :),  &
      & WSWAVE(:, :), UFRIC(:, :), Z0M(:, :), COSWDIF(:, :), SINWDIF2(:, :), RAORW(:), WSTAR(:, :), RNFAC(:), FLD(:, :, :),  &
      & SL(:, :, :), SPOS(:, :, :), XLLWS(:, :, :, :), ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, DELTH, EPSUS, G,  &
      & IDAMPING, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNUM, WSPMIN, XKAPPA, ZALP, ZPI, ZPIFR(:), ICHNK, NCHNK, IJ)
    CASE (1)
      CALL SINPUT_ARD_CUF_HOIST_NEW(NGST, LLSNEG, KIJS, KIJL, FL1(:, :, :, :), WAVNUM(:, :, :), CINV(:, :, :), XK2CG(:, :, :),  &
      & WDWAVE(:, :), WSWAVE(:, :), UFRIC(:, :), Z0M(:, :), COSWDIF(:, :), SINWDIF2(:, :), RAORW(:), WSTAR(:, :), RNFAC(:),  &
      & FLD(:, :, :), SL(:, :, :), SPOS(:, :, :), XLLWS(:, :, :, :), ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN,  &
      & BETAMAXOXKAPPA2, COSTH(:), DELTH, DFIM(:), EPSMIN, EPSUS, G, IAB, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH(:),  &
      & SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT(:), TAUWSHELTER, TH(:), WSPMIN, XKAPPA,  &
      & Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPIFR(:), ICHNK, NCHNK, IJ)
    END SELECT
    
    
  END SUBROUTINE SINPUT_CUF_HOIST_NEW
END MODULE SINPUT_CUF_HOIST_NEW_MOD
