! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
MODULE TAUT_Z0_CUF_HOIST_NEW_MOD
  CONTAINS
  ATTRIBUTES(DEVICE) SUBROUTINE TAUT_Z0_CUF_HOIST_NEW (KIJS, KIJL, IUSFG, HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC, USTAR, Z0,  &
  & Z0B, CHRNCK, ACD, ALPHA, ALPHAMAX, ALPHAMIN, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC,  &
  & CDMAX, CHNKMIN_U, CM_GC, DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPS1, EPSMIN, EPSUS, G, GM1, LLCAPCHNK, LLGCBZ0, LLNORMAGAM,  &
  & NWAV_GC, OM3GMKM_GC, OMXKM3_GC, RN1_RN, RNU, RNUM, SQRTGOSURFT, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC,  &
  & XNLEV, ZALP, ICHNK, NCHNK, IJ)
    
    ! ----------------------------------------------------------------------
    
    !**** *TAUT_Z0* - COMPUTATION OF TOTAL STRESS AND ROUGHNESS LENGTH SCALE.
    
    
    !**   INTERFACE.
    !     ----------
    
    !       *CALL* *TAUT_Z0(KIJS, KIJL, IUSFG, FL1, WAVNUM,
    !                       UTOP, UDIR, TAUW, TAUWDIR, RNFAC,
    !                       USTAR, Z0, Z0B, CHRNCK)
    !          *KIJS*    - INDEX OF FIRST GRIDPOINT
    !          *KIJL*    - INDEX OF LAST GRIDPOINT
    !          *IUSFG*   - IF = 1 THEN USE THE FRICTION VELOCITY (US) AS FIRST GUESS in TAUT_Z0
    !                           0 DO NOT USE THE FIELD USTAR
    !          *FL1*     - 2D-SPECTRA
    !          *WAVNUM*  - WAVE NUMBER
    !          *HALP*    - 1/2 PHILLIPS PARAMETER
    !          *UTOP*    - WIND SPEED AT REFERENCE LEVEL XNLEV
    !          *UDIR*    - WIND SPEED DIRECTION AT REFERENCE LEVEL XNLEV
    !          *TAUW*    - WAVE STRESS.
    !          *TAUWDIR* - WAVE STRESS DIRECTION.
    !          *RNFAC*   - WIND DEPENDENT FACTOR USED IN THE GROWTH RENORMALISATION.
    !          *USTAR*   - FRICTION VELOCITY
    !          *Z0*      - ROUGHNESS LENGTH
    !          *Z0B*     - BACKGROUND ROUGHNESS LENGTH
    !          *CHRNCK*  - CHARNOCK COEFFICIENT
    
    !     METHOD.
    !     -------
    
    !       A STEADY STATE WIND PROFILE IS ASSUMED.
    !       THE WIND STRESS IS COMPUTED USING THE ROUGHNESS LENGTH
    
    !                  Z1=Z0/SQRT(1-TAUW/TAU)
    
    !       WHERE Z0 IS THE CHARNOCK RELATION , TAUW IS THE WAVE-
    !       INDUCED STRESS AND TAU IS THE TOTAL STRESS.
    !       WE SEARCH FOR STEADY-STATE SOLUTIONS FOR WHICH TAUW/TAU < 1.
    
    !       IT WAS EXTENDED TO INCLUDE THE GRAVITY-CAPILLARY MODEL FOR THE CALCULATION
    !       OF THE BACKGROUND ROUGHNESS.
    
    !     EXTERNALS.
    !     ----------
    
    !       NONE.
    
    !     REFERENCE.
    !     ----------
    
    !       FOR QUASILINEAR EFFECT SEE PETER A.E.M. JANSSEN,1990.
    
    ! ----------------------------------------------------------------------
    
    USE STRESS_GC_CUF_HOIST_NEW_MOD, ONLY: STRESS_GC_CUF_HOIST_NEW
    USE CHNKMIN_CUF_HOIST_NEW_MOD, ONLY: CHNKMIN_CUF_HOIST_NEW
    USE cudafor
    USE PARKIND_WAVE, ONLY: JWIM, JWRU, JWRB
    
    USE YOWPARAM, ONLY: NFRE, NANG
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IUSFG
    REAL(KIND=JWRB), INTENT(IN) :: HALP(KIJL)
    REAL(KIND=JWRB), INTENT(IN) :: RNFAC(KIJL)
    REAL(KIND=JWRB), INTENT(IN) :: UTOP(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: UDIR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: TAUW(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(IN) :: TAUWDIR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(INOUT) :: USTAR(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(OUT) :: Z0(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(OUT) :: Z0B(KIJL, NCHNK)
    REAL(KIND=JWRB), INTENT(OUT) :: CHRNCK(KIJL, NCHNK)
    
    
    INTEGER(KIND=JWIM), PARAMETER :: NITER = 17
    
    REAL(KIND=JWRB), PARAMETER :: TWOXMP1 = 3.0_JWRB
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    INTEGER(KIND=JWIM) :: ITER
    INTEGER(KIND=JWIM) :: IFRPH
    
    ! Cd and Z0 from Hersbach 2010, ECMWF Tech Memo (without the viscous part)
    !     CD = ACDLIN + BCDLIN*SQRT(PCHAR) * U10
    REAL(KIND=JWRB), PARAMETER :: ACDLIN = 0.0008_JWRB
    REAL(KIND=JWRB), PARAMETER :: BCDLIN = 0.00047_JWRB
    REAL(KIND=JWRB) :: ALPHAGM1
    
    REAL(KIND=JWRB), PARAMETER :: Z0MIN = 0.000001_JWRB
    REAL(KIND=JWRB) :: PCE_GC
    REAL(KIND=JWRB) :: Z0MINRST
    REAL(KIND=JWRB) :: CHARNOCK_MIN
    REAL(KIND=JWRB) :: COSDIFF
    REAL(KIND=JWRB) :: ZCHAR
    REAL(KIND=JWRB) :: US2TOTAUW
    REAL(KIND=JWRB) :: USMAX
    REAL(KIND=JWRB) :: XLOGXL
    REAL(KIND=JWRB) :: XKUTOP
    REAL(KIND=JWRB) :: XOLOGZ0
    REAL(KIND=JWRB) :: USTOLD
    REAL(KIND=JWRB) :: USTNEW
    REAL(KIND=JWRB) :: TAUOLD
    REAL(KIND=JWRB) :: TAUNEW
    REAL(KIND=JWRB) :: X
    REAL(KIND=JWRB) :: F
    REAL(KIND=JWRB) :: DELF
    REAL(KIND=JWRB) :: CDFG
    REAL(KIND=JWRB) :: USTM1
    REAL(KIND=JWRB) :: Z0TOT
    REAL(KIND=JWRB) :: Z0CH
    REAL(KIND=JWRB) :: Z0VIS
    REAL(KIND=JWRB) :: HZ0VISO1MX
    REAL(KIND=JWRB) :: ZZ
    REAL(KIND=JWRB) :: CONST
    REAL(KIND=JWRB) :: TAUV
    REAL(KIND=JWRB) :: DEL
    REAL(KIND=JWRB) :: RNUEFF
    REAL(KIND=JWRB) :: RNUKAPPAM1
    REAL(KIND=JWRB) :: ALPHAOG
    REAL(KIND=JWRB) :: XMIN
    REAL(KIND=JWRB) :: W1
    REAL(KIND=JWRB) :: TAUWACT
    REAL(KIND=JWRB) :: TAUWEFF
    REAL(KIND=JWRB) :: ANG_GC
    REAL(KIND=JWRB) :: TAUUNR
    
    LOGICAL :: LLCOSDIFF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: C2OSQRTVG_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: CM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DELKCC_GC_NS(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: DELKCC_OMXKM3_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: OM3GMKM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: OMXKM3_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XKMSQRTVGOC2_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XKM_GC(NWAV_GC)
    REAL(KIND=JWRB), INTENT(IN), DEVICE :: XK_GC(NWAV_GC)
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER, VALUE, INTENT(IN) :: NCHNK
    
    ! ----------------------------------------------------------------------
    
    
    XLOGXL = LOG(XNLEV)
    US2TOTAUW = 1.0_JWRB + EPS1
    
    !     ONLY take the contribution of TAUW that is in the wind direction
    
    COSDIFF = COS(UDIR(IJ, ICHNK) - TAUWDIR(IJ, ICHNK))
    TAUWACT = MAX(TAUW(IJ, ICHNK)*COSDIFF, EPSMIN)
    LLCOSDIFF = COSDIFF > 0.9_JWRB
    
    !  USING THE CG MODEL:
    IF (LLGCBZ0) THEN
      
      IF (LLCAPCHNK) THEN
        CHARNOCK_MIN = CHNKMIN_CUF_HOIST_NEW(UTOP(IJ, ICHNK), ALPHA, ALPHAMIN, CHNKMIN_U)
        ALPHAOG = CHARNOCK_MIN*GM1
      ELSE
        ALPHAOG = 0.0_JWRB
      END IF
      
      USMAX = MAX(-0.21339_JWRB + 0.093698_JWRB*UTOP(IJ, ICHNK) - 0.0020944_JWRB*UTOP(IJ, ICHNK)**2 + 5.5091E-5_JWRB*UTOP(IJ,  &
      & ICHNK)**3, 0.03_JWRB)
      TAUWEFF = MIN(TAUWACT*US2TOTAUW, USMAX**2)
      
      RNUEFF = 0.04_JWRB*RNU
      
      RNUKAPPAM1 = RNUEFF / XKAPPA
      
      PCE_GC = 0.001_JWRB*IUSFG + (1 - IUSFG)*0.005_JWRB
      
      IF (IUSFG == 0) THEN
        ALPHAGM1 = ALPHA*GM1
        IF (UTOP(IJ, ICHNK) < 1.0_JWRB) THEN
          CDFG = 0.002_JWRB
        ELSE IF (LLCOSDIFF) THEN
          X = MIN(TAUWACT / MAX(USTAR(IJ, ICHNK), EPSUS)**2, 0.99_JWRB)
          ZCHAR = MIN(ALPHAGM1*USTAR(IJ, ICHNK)**2 / SQRT(1.0_JWRB - X), 0.05_JWRB*EXP(-0.05_JWRB*(UTOP(IJ, ICHNK) - 35._JWRB)))
          ZCHAR = MIN(ZCHAR, ALPHAMAX)
          CDFG = ACDLIN + BCDLIN*SQRT(ZCHAR)*UTOP(IJ, ICHNK)
        ELSE
          ! CDFG = CDM(UTOP(IJ)) ! TODO: revert and automate
          CDFG = MAX(MIN(0.0006_JWRB + 0.00008_JWRB*UTOP(IJ, ICHNK), 0.001_JWRB + 0.0018_JWRB*EXP(-0.05_JWRB*(UTOP(IJ, ICHNK) -  &
          & 33._JWRB))), 0.001_JWRB)
        END IF
        USTAR(IJ, ICHNK) = UTOP(IJ, ICHNK)*SQRT(CDFG)
      END IF
      
      W1 = 0.85_JWRB - 0.05_JWRB*(TANH(10.0_JWRB*(UTOP(IJ, ICHNK) - 5.0_JWRB)) + 1.0_JWRB)
      
      XKUTOP = XKAPPA*UTOP(IJ, ICHNK)
      
      USTOLD = USTAR(IJ, ICHNK)
      TAUOLD = USTOLD**2
      
      DO ITER=1,NITER
        !         Z0 IS DERIVED FROM THE NEUTRAL LOG PROFILE: UTOP = (USTAR/XKAPPA)*LOG((XNLEV+Z0)/Z0)
        Z0(IJ, ICHNK) = MAX(XNLEV / (EXP(MIN(XKUTOP / USTOLD, 50.0_JWRB)) - 1.0_JWRB), Z0MIN)
        ! Viscous kinematic stress nu_air * dU/dz at z=0 of the neutral log profile reduced by factor 25 (0.04)
        TAUV = RNUKAPPAM1*USTOLD / Z0(IJ, ICHNK)
        
        ANG_GC = ANG_GC_A + ANG_GC_B*TANH(ANG_GC_C*TAUOLD)
        
        TAUUNR = STRESS_GC_CUF_HOIST_NEW(ANG_GC, USTAR(IJ, ICHNK), Z0(IJ, ICHNK), Z0MIN, HALP(IJ), RNFAC(IJ), BETAMAXOXKAPPA2,  &
        & BMAXOKAP, C2OSQRTVG_GC, CM_GC, DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPSUS, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC,  &
        & RN1_RN, SQRTGOSURFT, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, ZALP)
        
        !         TOTAL kinematic STRESS:
        TAUNEW = TAUWEFF + TAUV + TAUUNR
        USTNEW = SQRT(TAUNEW)
        USTAR(IJ, ICHNK) = W1*USTOLD + (1.0_JWRB - W1)*USTNEW
        
        !         CONVERGENCE ?
        DEL = USTAR(IJ, ICHNK) - USTOLD
        IF (ABS(DEL) < PCE_GC*USTAR(IJ, ICHNK)) EXIT
        TAUOLD = USTAR(IJ, ICHNK)**2
        USTOLD = USTAR(IJ, ICHNK)
      END DO
      ! protection just in case there is no convergence
      IF (ITER > NITER) THEN
        ! CDFG = CDM(UTOP(IJ))
        CDFG = MAX(MIN(0.0006_JWRB + 0.00008_JWRB*UTOP(IJ, ICHNK), 0.001_JWRB + 0.0018_JWRB*EXP(-0.05_JWRB*(UTOP(IJ, ICHNK) -  &
        & 33._JWRB))), 0.001_JWRB)
        USTAR(IJ, ICHNK) = UTOP(IJ, ICHNK)*SQRT(CDFG)
        Z0MINRST = USTAR(IJ, ICHNK)**2*ALPHA*GM1
        Z0(IJ, ICHNK) = MAX(XNLEV / (EXP(XKUTOP / USTAR(IJ, ICHNK)) - 1.0_JWRB), Z0MINRST)
        Z0B(IJ, ICHNK) = Z0MINRST
      ELSE
        Z0(IJ, ICHNK) = MAX(XNLEV / (EXP(XKUTOP / USTAR(IJ, ICHNK)) - 1.0_JWRB), Z0MIN)
        Z0B(IJ, ICHNK) = Z0(IJ, ICHNK)*SQRT(TAUUNR / TAUOLD)
      END IF
      
      !       Refine solution
      X = TAUWEFF / TAUOLD
      
      IF (X < 0.99_JWRB) THEN
        USTOLD = USTAR(IJ, ICHNK)
        TAUOLD = MAX(USTOLD**2, TAUWEFF)
        
        DO ITER=1,NITER
          X = MIN(TAUWEFF / TAUOLD, 0.99_JWRB)
          USTM1 = 1.0_JWRB / MAX(USTOLD, EPSUS)
          !!!! Limit how small z0 could become
          !!!! This is a bit of a compromise to limit very low Charnock for intermediate high winds (15 -25 m/s)
          !!!! It is not ideal !!!
          Z0(IJ, ICHNK) = MAX(XNLEV / (EXP(MIN(XKUTOP / USTOLD, 50.0_JWRB)) - 1.0_JWRB), Z0MIN)
          
          TAUUNR = STRESS_GC_CUF_HOIST_NEW(ANG_GC, USTOLD, Z0(IJ, ICHNK), Z0MIN, HALP(IJ), RNFAC(IJ), BETAMAXOXKAPPA2, BMAXOKAP,  &
          & C2OSQRTVG_GC, CM_GC, DELKCC_GC_NS, DELKCC_OMXKM3_GC, EPSUS, LLNORMAGAM, NWAV_GC, OM3GMKM_GC, OMXKM3_GC, RN1_RN,  &
          & SQRTGOSURFT, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, ZALP)
          
          Z0B(IJ, ICHNK) = MAX(Z0(IJ, ICHNK)*SQRT(TAUUNR / TAUOLD), ALPHAOG*TAUOLD)
          Z0VIS = RNUM*USTM1
          HZ0VISO1MX = 0.5_JWRB*Z0VIS / (1.0_JWRB - X)
          Z0(IJ, ICHNK) = HZ0VISO1MX + SQRT(HZ0VISO1MX**2 + Z0B(IJ, ICHNK)**2 / (1.0_JWRB - X))
          
          XOLOGZ0 = 1.0_JWRB / (XLOGXL - LOG(Z0(IJ, ICHNK)))
          F = USTOLD - XKUTOP*XOLOGZ0
          ZZ = 2.0_JWRB*USTM1*(3.0_JWRB*Z0B(IJ, ICHNK)**2 + 0.5_JWRB*Z0VIS*Z0(IJ, ICHNK) - Z0(IJ, ICHNK)**2) / (2.0_JWRB*Z0(IJ,  &
          & ICHNK)**2*(1.0_JWRB - X) - Z0VIS*Z0(IJ, ICHNK))
          
          DELF = 1.0_JWRB - XKUTOP*XOLOGZ0**2*ZZ
          IF (DELF /= 0.0_JWRB) USTAR(IJ, ICHNK) = USTOLD - F / DELF
          
          !           CONVERGENCE ?
          DEL = USTAR(IJ, ICHNK) - USTOLD
          
          IF (ABS(DEL) < PCE_GC*USTAR(IJ, ICHNK)) EXIT
          USTOLD = USTAR(IJ, ICHNK)
          TAUOLD = MAX(USTOLD**2, TAUWEFF)
        END DO
        ! protection just in case there is no convergence
        IF (ITER > NITER) THEN
          ! CDFG = CDM(UTOP(IJ))
          CDFG = MAX(MIN(0.0006_JWRB + 0.00008_JWRB*UTOP(IJ, ICHNK), 0.001_JWRB + 0.0018_JWRB*EXP(-0.05_JWRB*(UTOP(IJ, ICHNK) -  &
          & 33._JWRB))), 0.001_JWRB)
          USTAR(IJ, ICHNK) = UTOP(IJ, ICHNK)*SQRT(CDFG)
          Z0MINRST = USTAR(IJ, ICHNK)**2*ALPHA*GM1
          Z0(IJ, ICHNK) = MAX(XNLEV / (EXP(XKUTOP / USTAR(IJ, ICHNK)) - 1.0_JWRB), Z0MINRST)
          Z0B(IJ, ICHNK) = Z0MINRST
          CHRNCK(IJ, ICHNK) = MAX(G*Z0(IJ, ICHNK) / USTAR(IJ, ICHNK)**2, ALPHAMIN)
        ELSE
          CHRNCK(IJ, ICHNK) = MAX(G*(Z0B(IJ, ICHNK) / SQRT(1.0_JWRB - X)) / MAX(USTAR(IJ, ICHNK), EPSUS)**2, ALPHAMIN)
        END IF
        
      ELSE
        USTM1 = 1.0_JWRB / MAX(USTAR(IJ, ICHNK), EPSUS)
        Z0VIS = RNUM*USTM1
        CHRNCK(IJ, ICHNK) = MAX(G*(Z0(IJ, ICHNK) - Z0VIS)*USTM1**2, ALPHAMIN)
      END IF
      
      
      
    ELSE
      
      TAUWEFF = TAUWACT*US2TOTAUW
      
      IF (LLCAPCHNK) THEN
        CHARNOCK_MIN = CHNKMIN_CUF_HOIST_NEW(UTOP(IJ, ICHNK), ALPHA, ALPHAMIN, CHNKMIN_U)
        XMIN = 0.15_JWRB*(ALPHA - CHARNOCK_MIN)
        ALPHAOG = CHARNOCK_MIN*GM1
      ELSE
        XMIN = 0.0_JWRB
        ALPHAOG = ALPHA*GM1
      END IF
      
      XKUTOP = XKAPPA*UTOP(IJ, ICHNK)
      
      USTOLD = (1 - IUSFG)*UTOP(IJ, ICHNK)*SQRT(MIN(ACD + BCD*UTOP(IJ, ICHNK), CDMAX)) + IUSFG*USTAR(IJ, ICHNK)
      TAUOLD = MAX(USTOLD**2, TAUWEFF)
      USTAR(IJ, ICHNK) = SQRT(TAUOLD)
      USTM1 = 1.0_JWRB / MAX(USTAR(IJ, ICHNK), EPSUS)
      
      DO ITER=1,NITER
        X = MAX(TAUWACT / TAUOLD, XMIN)
        Z0CH = ALPHAOG*TAUOLD / SQRT(1.0_JWRB - X)
        Z0VIS = RNUM*USTM1
        Z0TOT = Z0CH + Z0VIS
        
        XOLOGZ0 = 1.0_JWRB / (XLOGXL - LOG(Z0TOT))
        F = USTAR(IJ, ICHNK) - XKUTOP*XOLOGZ0
        ZZ = USTM1*(Z0CH*(2.0_JWRB - TWOXMP1*X) / (1.0_JWRB - X) - Z0VIS) / Z0TOT
        DELF = 1.0_JWRB - XKUTOP*XOLOGZ0**2*ZZ
        
        IF (DELF /= 0.0_JWRB) USTAR(IJ, ICHNK) = USTAR(IJ, ICHNK) - F / DELF
        TAUNEW = MAX(USTAR(IJ, ICHNK)**2, TAUWEFF)
        USTAR(IJ, ICHNK) = SQRT(TAUNEW)
        IF (TAUNEW == TAUOLD) EXIT
        USTM1 = 1.0_JWRB / MAX(USTAR(IJ, ICHNK), EPSUS)
        TAUOLD = TAUNEW
      END DO
      
      Z0(IJ, ICHNK) = Z0CH
      Z0B(IJ, ICHNK) = ALPHAOG*TAUOLD
      CHRNCK(IJ, ICHNK) = MAX(G*Z0(IJ, ICHNK)*USTM1**2, ALPHAMIN)
      
      
    END IF
    
    
    
    
  END SUBROUTINE TAUT_Z0_CUF_HOIST_NEW
END MODULE TAUT_Z0_CUF_HOIST_NEW_MOD
