! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
SUBROUTINE WAMINTGR_LOKI_GPU (CDTPRA, CDATE, CDATEWH, CDTIMP, CDTIMPNEXT, BLK2GLO, WVENVI, WVPRPT, FF_NOW, FF_NEXT, INTFLDS,  &
& WAM2NEMO, MIJ, FL1, XLLWS, TIME1)
  
  
  ! ----------------------------------------------------------------------
  
  !**** *WAMINTGR* - 3-G WAM MODEL - TIME INTEGRATION OF WAVE FIELDS.
  
  !*    PURPOSE.
  !     --------
  
  !       COMPUTATION OF THE 2-D FREQUENCY-DIRECTION WAVE SPECTRUM AT ALL
  !       GRID POINTS FOR A GIVEN INITIAL SPECTRUM AND FORCING SURFACE
  !       STRESS FIELD.
  
  !     REFERENCE.
  !     ----------
  
  !         IFS DOCUMENTATION, part VII
  
  ! -------------------------------------------------------------------
  
  USE IMPLSCH_CUF_HOIST_NEW_MOD, ONLY: IMPLSCH_CUF_HOIST_NEW
  USE cudafor
  ![Loki::GlobalVarHoistTransformation] -------- Added global variable imports for offload directives -----------
  USE yowwndg, ONLY: ICODE_CPL, ICODE
  USE yowwind, ONLY: WSPMIN
  USE yowparam, ONLY: NFRE_ODD, NFRE_RED, LLUNSTR
  USE yowtabl, ONLY: SWELLFT, EPS1, IAB
  USE yowcout, ONLY: LWFLUXOUT
  USE yowindn, ONLY: AF11, FKLAM, IKP, FKLAP, IKP1, INLCOEF, IKM, KFRH, K1W, DAL1, K2W, RNLCOEF, FKLAP1, DAL2, FKLAM1, MLSTHG,  &
  & K21W, MFRSTLW, IKM1, K11W
  USE yowstat, ONLY: ISNONLIN, LBIWBK, IPHYS, IDAMPING
  USE yowshal, ONLY: BATHYMAX, NDEPTH, XKDMIN
  USE yowaltas, ONLY: AFCRV, EGRCRV, BFCRV
  USE yowpcons, ONLY: TAUOCMIN, ZPI, ZPI4GM1, EPSUS, PHIEPSMIN, G, ZPI4GM2, BCD, EPSU10, WSEMEAN_MIN, ACDLIN, PHIEPSMAX,  &
  & ROWATER, CDMAX, BCDLIN, ROWATERM1, GM1, ACD, DKMAX, SQRTGOSURFT, TAUOCMAX
  USE yowcoup, ONLY: JTOT_TAUHF, LWVFLX_SNL, LWCOU, LWNEMOCOUSTK, LWFLUX, LLNORMAGAM, X0TAUHF, LLGCBZ0, LLCAPCHNK,  &
  & LWNEMOCOUSEND, WTAUHF, LWNEMOTAUOC, LWNEMOCOUSTRN
  USE yowfred, ONLY: FR, FLOGSPRDM1, DELKCC_OMXKM3_GC, XKM_GC, WP2TAIL, SINTH, DFIMFR2, XK_GC, FLMAX, OM3GMKM_GC, DELTH,  &
  & OMEGA_GC, OMXKM3_GC, CM_GC, XKMSQRTVGOC2_GC, RHOWG_DFIM, COFRM4, DFIM, TH, FRTAIL, C2OSQRTVG_GC, COSTH, FR5, DFIMOFR,  &
  & XLOGKRATIOM1_GC, NWAV_GC, WP1TAIL, DELKCC_GC_NS, FRATIO, WETAIL, ZPIFR, DFIMFR, DFIM_SIM, FRIC
  USE yowice, ONLY: LICERUN, LMASKICE, CIBLOCK, FLMIN, CITHRSH, CITHRSH_TAIL, LWAMRSETCI, LCIWABR, CDICWA
  USE yowphys, ONLY: SSDSC4, BETAMAXOXKAPPA2, SSDSC2, SWELLF5, SSDSC6, Z0TUBMAX, DELTA_SDIS, RNUM, DTHRN_A, ANG_GC_A, SSDSC5,  &
  & XNLEV, SWELLF7, CDIS, TAILFACTOR_PM, SSDSC3, ALPHA, SWELLF, ABMIN, GAMNCONST, SDSBR, SATWEIGHTS, XKAPPA, DTHRN_U, ALPHAMIN,  &
  & ALPHAPMAX, ZALP, TAUWSHELTER, TAILFACTOR, ABMAX, SWELLF4, ANG_GC_C, INDICESSAT, CUMULW, RN1_RN, SWELLF2, IPSAT, MICHE,  &
  & Z0RAT, NSDSNTH, ALPHAMAX, CDISVIS, SWELLF3, RNU, SWELLF6, NDIKCUMUL, SWELLF7M1, CHNKMIN_U, BMAXOKAP, ANG_GC_B
  ![Loki::GlobalVarHoistTransformation] ---------------------------------------
  USE PARKIND_WAVE, ONLY: JWIM, JWRB, JWRU
  USE YOWDRVTYPE, ONLY: WVGRIDGLO, ENVIRONMENT, FREQUENCY, FORCING_FIELDS, INTGT_PARAM_FIELDS, WAVE2OCEAN
  
  USE YOWCOUP, ONLY: LWNEMOCOU, NEMONTAU
  USE YOWGRID, ONLY: NPROMA_WAM, NCHNK
  USE YOWPARAM, ONLY: NIBLO, NANG, NFRE
  USE YOWPCONS, ONLY: EPSMIN
  USE YOWSTAT, ONLY: CDTPRO, IDELPRO, IDELT, IDELWI, LLSOURCE
  USE YOWWIND, ONLY: CDAWIFL, CDATEWO, CDATEFL
  USE YOWFIELD_MOD, ONLY: FREQUENCY_FIELD, ENVIRONMENT_FIELD, FORCING_FIELDS_FIELD, WAVE2OCEAN_FIELD, INTGT_PARAM_FIELDS_FIELD,  &
  & SOURCE_CONTRIBS_FIELD
  
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE INCDATE (CDATE, ISHIFT)
      USE parkind_wave, ONLY: jwim
      INTEGER(KIND=JWIM), INTENT(IN) :: ISHIFT
      CHARACTER(LEN=*), INTENT(INOUT) :: CDATE
    END SUBROUTINE INCDATE
  END INTERFACE
  INTERFACE
    SUBROUTINE NEWWIND (CDATE, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
      USE YOWDRVTYPE, ONLY: FREQUENCY, FORCING_FIELDS
      CHARACTER(LEN=14), INTENT(IN) :: CDATE
      CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH
      LOGICAL, INTENT(INOUT) :: LLNEWFILE
      TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW
      TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT
    END SUBROUTINE NEWWIND
  END INTERFACE
  INTERFACE
    SUBROUTINE PROPAG_WAM (BLK2GLO, WAVNUM, CGROUP, OMOSNH2KD, FL1, DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
      USE parkind_wave, ONLY: jwrb
      USE yowdrvtype, ONLY: wvgridglo
      USE yowgrid, ONLY: nproma_wam, nchnk
      USE yowparam, ONLY: nang, nfre
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NFRE, NCHNK) :: WAVNUM, CGROUP, OMOSNH2KD
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NCHNK) :: DEPTH, DELLAM1, COSPHM1, UCUR, VCUR
    END SUBROUTINE PROPAG_WAM
  END INTERFACE
  INTERFACE
    FUNCTION WAM_USER_CLOCK ()
      USE parkind_wave, ONLY: jwru
      REAL(KIND=JWRU) :: WAM_USER_CLOCK
    END FUNCTION WAM_USER_CLOCK
  END INTERFACE
  INTEGER(KIND=JWIM), PARAMETER :: NANG_loki_param = 24
  INTEGER(KIND=JWIM), PARAMETER :: NFRE_loki_param = 36
  CHARACTER(LEN=14), INTENT(IN) :: CDTPRA  ! DATE FOR CALL PROPAGATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATE  ! CURRENT DATE
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH  ! DATE OF THE NEXT FORCING FIELDS
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMP  ! START DATE OF SOURCE FUNCTION INTEGRATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMPNEXT  ! NEXT START DATE OF SOURCE FUNCTION INTEGRATION
  TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO  ! BLOCK TO GRID TRANSFORMATION
  TYPE(ENVIRONMENT), INTENT(INOUT) :: WVENVI  !  WAVE ENVIRONMENT FIELDS
  TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT  ! WAVE PROPERTIES FIELDS
  TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW  ! FORCING FIELDS AT CURRENT TIME
  TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT  !  DATA STRUCTURE WITH THE NEXT FORCING FIELDS
  TYPE(INTGT_PARAM_FIELDS), INTENT(INOUT) :: INTFLDS  ! INTEGRATED/DERIVED PARAMETERS
  TYPE(WAVE2OCEAN), INTENT(INOUT) :: WAM2NEMO  ! WAVE FIELDS PASSED TO NEMO
  INTEGER(KIND=JWIM), INTENT(INOUT) :: MIJ(NPROMA_WAM, NCHNK)  ! LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE
  REAL(KIND=JWRB), INTENT(INOUT) :: FL1(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)
  REAL(KIND=JWRB), INTENT(INOUT) :: XLLWS(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK)  ! TOTAL WINDSEA MASK FROM INPUT SOURCE TERM
  
  REAL(KIND=JWRB), INTENT(INOUT) :: TIME1(3)
  REAL(KIND=JWRB) :: TIME0, TIME2
  
  
  INTEGER(KIND=JWIM) :: IJ, K, M
  INTEGER(KIND=JWIM) :: ICHNK
  INTEGER(KIND=JWIM) :: IDELWH
  
  ! Objects to store fields
  TYPE(FREQUENCY_FIELD) :: WVPRPT_FIELD
  TYPE(ENVIRONMENT_FIELD) :: WVENVI_FIELD
  TYPE(FORCING_FIELDS_FIELD) :: FF_NOW_FIELD
  TYPE(WAVE2OCEAN_FIELD) :: WAM2NEMO_FIELD
  TYPE(INTGT_PARAM_FIELDS_FIELD) :: INTFLDS_FIELD
  TYPE(SOURCE_CONTRIBS_FIELD) :: SRC_CONTRIBS
  
  ! DEVICE POINTERS
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: FL1_DPTR(:, :, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XLLWS_DPTR(:, :, :, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: MIJ_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WAVNUM_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CGROUP_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: OMOSNH2KD_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CIWA_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CINV_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XK2CG_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STOKFAC_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: EMAXDPT_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: INDEP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DEPTH_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DELLAM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: COSPHM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UCUR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VCUR_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IOBND_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IODP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUWDIR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0M_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0B_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOUSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOVSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOSTRN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NPHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NTAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NSWH_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NMWP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOTAUX_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOTAUY_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOWSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: NEMOPHIF_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSEMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSFMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STRNMS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIOCD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIAW_DPTR(:, :) => NULL()
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  
  LOGICAL, SAVE :: LLNEWFILE
  
  DATA LLNEWFILE / .false. /
  INTEGER :: istat
  
  ! Device arrays
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: AF11_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: C2OSQRTVG_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: CM_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: COFRM4_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: COSTH_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: CUMULW_d(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DELKCC_GC_NS_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DELKCC_OMXKM3_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DFIM_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DFIMFR_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DFIMFR2_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DFIMOFR_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: DFIM_SIM_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FKLAM_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FKLAM1_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FKLAP_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FKLAP1_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FLMAX_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FR_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: FR5_d(:)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: IKM_d(:)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: IKM1_d(:)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: IKP_d(:)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: IKP1_d(:)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: INDICESSAT_d(:, :)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: INLCOEF_d(:, :)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: K11W_d(:, :)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: K1W_d(:, :)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: K21W_d(:, :)
  INTEGER(KIND=JWIM), ALLOCATABLE, DEVICE :: K2W_d(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: OM3GMKM_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: OMEGA_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: OMXKM3_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: RHOWG_DFIM_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: RNLCOEF_d(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SATWEIGHTS_d(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SINTH_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SWELLFT_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: TH_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: WTAUHF_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: XKMSQRTVGOC2_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: XKM_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: XK_GC_d(:)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: ZPIFR_d(:)
  TYPE(dim3) :: GRIDDIM, BLOCKDIM
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_RAORW(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_EMEAN(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_FMEAN(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_HALP(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_EMEANWS(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_FMEANWS(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_F1MEAN(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_AKMEAN(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_XKMEAN(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_PHIWA(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_FLM(:, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_COSWDIF(:, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_SINWDIF2(:, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_RHOWGDFTH(:, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_FLD(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_SL(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_SPOS(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_CIREDUC(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: IMPLSCH_SSOURCE(:, :, :, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SINFLX_RNFAC(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SINFLX_TMP_EM(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: STRESSO_TAUHF(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: STRESSO_PHIHF(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: STRESSO_UST(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SNONLIN_XNU(:, :)
  REAL(KIND=JWRB), ALLOCATABLE, DEVICE :: SNONLIN_SIG_TH(:, :)
 REAL(KIND=JWRB), DEVICE, ALLOCATABLE :: ENH(:,:,:)

  ! @!  cuf print *, 'executing SCC-CUF type: hoist - host side hoisted local arrays'
 
  ALLOCATE(ENH(NPROMA_WAM, MLSTHG, NCHNK)) 
  ! Device array allocation
  ALLOCATE (AF11_d, MOLD=AF11)
  ALLOCATE (C2OSQRTVG_GC_d, MOLD=C2OSQRTVG_GC)
  ALLOCATE (CM_GC_d, MOLD=CM_GC)
  ALLOCATE (COFRM4_d, MOLD=COFRM4)
  ALLOCATE (COSTH_d, MOLD=COSTH)
  ALLOCATE (CUMULW_d, MOLD=CUMULW)
  ALLOCATE (DELKCC_GC_NS_d, MOLD=DELKCC_GC_NS)
  ALLOCATE (DELKCC_OMXKM3_GC_d, MOLD=DELKCC_OMXKM3_GC)
  ALLOCATE (DFIM_d, MOLD=DFIM)
  ALLOCATE (DFIMFR_d, MOLD=DFIMFR)
  ALLOCATE (DFIMFR2_d, MOLD=DFIMFR2)
  ALLOCATE (DFIMOFR_d, MOLD=DFIMOFR)
  ALLOCATE (DFIM_SIM_d, MOLD=DFIM_SIM)
  ALLOCATE (FKLAM_d, MOLD=FKLAM)
  ALLOCATE (FKLAM1_d, MOLD=FKLAM1)
  ALLOCATE (FKLAP_d, MOLD=FKLAP)
  ALLOCATE (FKLAP1_d, MOLD=FKLAP1)
  ALLOCATE (FLMAX_d, MOLD=FLMAX)
  ALLOCATE (FR_d, MOLD=FR)
  ALLOCATE (FR5_d, MOLD=FR5)
  ALLOCATE (IKM_d, MOLD=IKM)
  ALLOCATE (IKM1_d, MOLD=IKM1)
  ALLOCATE (IKP_d, MOLD=IKP)
  ALLOCATE (IKP1_d, MOLD=IKP1)
  ALLOCATE (INDICESSAT_d, MOLD=INDICESSAT)
  ALLOCATE (INLCOEF_d, MOLD=INLCOEF)
  ALLOCATE (K11W_d, MOLD=K11W)
  ALLOCATE (K1W_d, MOLD=K1W)
  ALLOCATE (K21W_d, MOLD=K21W)
  ALLOCATE (K2W_d, MOLD=K2W)
  ALLOCATE (OM3GMKM_GC_d, MOLD=OM3GMKM_GC)
  ALLOCATE (OMEGA_GC_d, MOLD=OMEGA_GC)
  ALLOCATE (OMXKM3_GC_d, MOLD=OMXKM3_GC)
  ALLOCATE (RHOWG_DFIM_d, MOLD=RHOWG_DFIM)
  ALLOCATE (RNLCOEF_d, MOLD=RNLCOEF)
  ALLOCATE (SATWEIGHTS_d, MOLD=SATWEIGHTS)
  ALLOCATE (SINTH_d, MOLD=SINTH)
  ALLOCATE (SWELLFT_d, MOLD=SWELLFT)
  ALLOCATE (TH_d, MOLD=TH)
  ALLOCATE (WTAUHF_d, MOLD=WTAUHF)
  ALLOCATE (XKMSQRTVGOC2_GC_d, MOLD=XKMSQRTVGOC2_GC)
  ALLOCATE (XKM_GC_d, MOLD=XKM_GC)
  ALLOCATE (XK_GC_d, MOLD=XK_GC)
  ALLOCATE (ZPIFR_d, MOLD=ZPIFR)
  ALLOCATE (IMPLSCH_RAORW(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_EMEAN(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_FMEAN(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_HALP(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_EMEANWS(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_FMEANWS(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_F1MEAN(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_AKMEAN(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_XKMEAN(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_PHIWA(NPROMA_WAM, NCHNK))
  ALLOCATE (IMPLSCH_FLM(NPROMA_WAM, NANG_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_COSWDIF(NPROMA_WAM, NANG_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_SINWDIF2(NPROMA_WAM, NANG_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_RHOWGDFTH(NPROMA_WAM, NFRE_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_FLD(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_SL(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_SPOS(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_CIREDUC(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK))
  ALLOCATE (IMPLSCH_SSOURCE(NPROMA_WAM, NANG_loki_param, NFRE_loki_param, NCHNK))
  ALLOCATE (SINFLX_RNFAC(NPROMA_WAM, NCHNK))
  ALLOCATE (SINFLX_TMP_EM(NPROMA_WAM, NCHNK))
  ALLOCATE (STRESSO_TAUHF(NPROMA_WAM, NCHNK))
  ALLOCATE (STRESSO_PHIHF(NPROMA_WAM, NCHNK))
  ALLOCATE (STRESSO_UST(NPROMA_WAM, NCHNK))
  ALLOCATE (SNONLIN_XNU(NPROMA_WAM, NCHNK))
  ALLOCATE (SNONLIN_SIG_TH(NPROMA_WAM, NCHNK))
  
  ! Copy host to device
  AF11_d = AF11
  C2OSQRTVG_GC_d = C2OSQRTVG_GC
  CM_GC_d = CM_GC
  COFRM4_d = COFRM4
  COSTH_d = COSTH
  CUMULW_d = CUMULW
  DELKCC_GC_NS_d = DELKCC_GC_NS
  DELKCC_OMXKM3_GC_d = DELKCC_OMXKM3_GC
  DFIM_d = DFIM
  DFIMFR_d = DFIMFR
  DFIMFR2_d = DFIMFR2
  DFIMOFR_d = DFIMOFR
  DFIM_SIM_d = DFIM_SIM
  FKLAM_d = FKLAM
  FKLAM1_d = FKLAM1
  FKLAP_d = FKLAP
  FKLAP1_d = FKLAP1
  FLMAX_d = FLMAX
  FR_d = FR
  FR5_d = FR5
  IKM_d = IKM
  IKM1_d = IKM1
  IKP_d = IKP
  IKP1_d = IKP1
  INDICESSAT_d = INDICESSAT
  INLCOEF_d = INLCOEF
  K11W_d = K11W
  K1W_d = K1W
  K21W_d = K21W
  K2W_d = K2W
  OM3GMKM_GC_d = OM3GMKM_GC
  OMEGA_GC_d = OMEGA_GC
  OMXKM3_GC_d = OMXKM3_GC
  RHOWG_DFIM_d = RHOWG_DFIM
  RNLCOEF_d = RNLCOEF
  SATWEIGHTS_d = SATWEIGHTS
  SINTH_d = SINTH
  SWELLFT_d = SWELLFT
  TH_d = TH
  WTAUHF_d = WTAUHF
  XKMSQRTVGOC2_GC_d = XKMSQRTVGOC2_GC
  XKM_GC_d = XKM_GC
  XK_GC_d = XK_GC
  ZPIFR_d = ZPIFR
  
  ! ----------------------------------------------------------------------
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 0, ZHOOK_HANDLE)
  
  !*     PROPAGATION TIME
  !      ----------------
  
  CALL SRC_CONTRIBS%INIT(FL1=FL1(:, :, :, :))
  CALL SRC_CONTRIBS%UPDATE_DEVICE(FL1=FL1_DPTR)
  CALL WVPRPT_FIELD%INIT(WAVNUM=WVPRPT%WAVNUM, CGROUP=WVPRPT%CGROUP, OMOSNH2KD=WVPRPT%OMOSNH2KD)
  CALL WVPRPT_FIELD%UPDATE_DEVICE(WAVNUM=WAVNUM_DPTR, CGROUP=CGROUP_DPTR, OMOSNH2KD=OMOSNH2KD_DPTR)
  CALL WVENVI_FIELD%INIT(DEPTH=WVENVI%DEPTH, DELLAM1=WVENVI%DELLAM1, COSPHM1=WVENVI%COSPHM1, UCUR=WVENVI%UCUR, VCUR=WVENVI%VCUR)
  CALL WVENVI_FIELD%UPDATE_DEVICE(DEPTH=DEPTH_DPTR, DELLAM1=DELLAM1_DPTR, COSPHM1=COSPHM1_DPTR, UCUR=UCUR_DPTR, VCUR=VCUR_DPTR)
!$acc data present( FL1_DPTR, WAVNUM_DPTR, CGROUP_DPTR, OMOSNH2KD_DPTR, DEPTH_DPTR, DELLAM1_DPTR, COSPHM1_DPTR, UCUR_DPTR,  &
!$acc & VCUR_DPTR )
  
  IF (CDATE == CDTPRA) THEN
    TIME0 = -WAM_USER_CLOCK()
    CALL PROPAG_WAM(BLK2GLO, WAVNUM_DPTR(:, :, :), CGROUP_DPTR(:, :, :), OMOSNH2KD_DPTR(:, :, :), FL1_DPTR(:, :, :, :),  &
    & DEPTH_DPTR(:, :), DELLAM1_DPTR(:, :), COSPHM1_DPTR(:, :), UCUR_DPTR(:, :), VCUR_DPTR(:, :))
    TIME1(1) = TIME1(1) + (TIME0 + WAM_USER_CLOCK())*1.E-06
    CDATE = CDTPRO
  END IF
!$acc end data
  
  !* RETRIEVING NEW FORCING FIELDS IF NEEDED.
  !  ----------------------------------------
  CALL NEWWIND(CDTIMP, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
  
  ! IT IS TIME TO INTEGRATE THE SOURCE TERMS
  ! ----------------------------------------
  IF (CDATE >= CDTIMPNEXT) THEN
    ! COMPUTE UPDATE DUE TO SOURCE TERMS
    CALL GSTATS(1431, 0)
    IF (LLSOURCE) THEN
      
      TIME2 = -WAM_USER_CLOCK()
      CALL WVPRPT_FIELD%INIT(CIWA=WVPRPT%CIWA, CINV=WVPRPT%CINV, XK2CG=WVPRPT%XK2CG, STOKFAC=WVPRPT%STOKFAC)
      CALL WVENVI_FIELD%INIT(EMAXDPT=WVENVI%EMAXDPT, INDEP=WVENVI%INDEP, IOBND=WVENVI%IOBND, IODP=WVENVI%IODP)
      CALL FF_NOW_FIELD%INIT(AIRD=FF_NOW%AIRD, WDWAVE=FF_NOW%WDWAVE, CICOVER=FF_NOW%CICOVER, WSWAVE=FF_NOW%WSWAVE,  &
      & WSTAR=FF_NOW%WSTAR, UFRIC=FF_NOW%UFRIC, TAUW=FF_NOW%TAUW, TAUWDIR=FF_NOW%TAUWDIR, Z0M=FF_NOW%Z0M, Z0B=FF_NOW%Z0B,  &
      & CHRNCK=FF_NOW%CHRNCK, CITHICK=FF_NOW%CITHICK)
      CALL WAM2NEMO_FIELD%INIT(NEMOUSTOKES=WAM2NEMO%NEMOUSTOKES, NEMOVSTOKES=WAM2NEMO%NEMOVSTOKES, NEMOSTRN=WAM2NEMO%NEMOSTRN,  &
      & NPHIEPS=WAM2NEMO%NPHIEPS, NTAUOC=WAM2NEMO%NTAUOC, NSWH=WAM2NEMO%NSWH, NMWP=WAM2NEMO%NMWP, NEMOTAUX=WAM2NEMO%NEMOTAUX,  &
      & NEMOTAUY=WAM2NEMO%NEMOTAUY, NEMOWSWAVE=WAM2NEMO%NEMOWSWAVE, NEMOPHIF=WAM2NEMO%NEMOPHIF)
      CALL INTFLDS_FIELD%INIT(WSEMEAN=INTFLDS%WSEMEAN, WSFMEAN=INTFLDS%WSFMEAN, USTOKES=INTFLDS%USTOKES,  &
      & VSTOKES=INTFLDS%VSTOKES, STRNMS=INTFLDS%STRNMS, TAUXD=INTFLDS%TAUXD, TAUYD=INTFLDS%TAUYD, TAUOCXD=INTFLDS%TAUOCXD,  &
      & TAUOCYD=INTFLDS%TAUOCYD, TAUOC=INTFLDS%TAUOC, PHIOCD=INTFLDS%PHIOCD, PHIEPS=INTFLDS%PHIEPS, PHIAW=INTFLDS%PHIAW)
      CALL SRC_CONTRIBS%INIT(XLLWS=XLLWS(:, :, :, :), MIJ=MIJ(:, :))
      
! ! $ acc update device(  &
! ! $ acc & BETAMAXOXKAPPA2,FKLAP,FLOGSPRDM1,NANG,DELKCC_OMXKM3_GC,NFRE_RED,XKM_GC,SWELLFT,LWNEMOCOU,LLUNSTR,SATWEIGHTS,OM3GMKM_GC,DTHRN_U,LWFLUXOUT,ALPHAMIN,IKM1,CM_GC,COFRM4,DFIM,KFRH,CUMULW,G,C2OSQRTVG_GC,LWNEMOCOUSEND,WTAUHF,COSTH,NSDSNTH,CDICWA,K2W,LWVFLX_SNL,RNLCOEF,K21W,CITHRSH_TAIL,LLCAPCHNK,BMAXOKAP,EGRCRV,DFIM_SIM,FR,IKM,CDIS,MLSTHG,FLMAX,CITHRSH,DELTH,MFRSTLW,ZPI,ZALP,IKP1,TAUWSHELTER,INDICESSAT,RN1_RN,X0TAUHF,Z0RAT,LBIWBK,DFIMOFR,DAL2,ZPIFR,CHNKMIN_U,LLGCBZ0,ANG_GC_B,LICERUN,IKP,ZPI4GM1,INLCOEF,ISNONLIN,LWAMRSETCI,DTHRN_A,NFRE_ODD,TAILFACTOR_PM,AFCRV,CIBLOCK,LWNEMOTAUOC,ALPHAPMAX,OMXKM3_GC,OMEGA_GC,AF11,XKMSQRTVGOC2_GC,LWCOU,TAILFACTOR,ANG_GC_C,K1W,IDELT,FR5,NFRE,DAL1,WSPMIN,LWNEMOCOUSTK,ICODE,ICODE_CPL,SQRTGOSURFT,SWELLF5,LLNORMAGAM,Z0TUBMAX,ZPI4GM2,LCIWABR,DELTA_SDIS,RNUM,ANG_GC_A,SINTH,LWFLUX,FKLAM1,ALPHA,LMASKICE,DFIMFR2,XK_GC,GAMNCONST,BFCRV,FKLAM,RHOWG_DFIM,TH,LWNEMOCOUSTRN,NDEPTH,NWAV_GC,FKLAP1,CDISVIS,RNU,DELKCC_GC_NS,IPHYS,GM1,NDIKCUMUL,DFIMFR,IDAMPING,K11W &
! ! $ !acc &  )
      
      CALL WVPRPT_FIELD%UPDATE_DEVICE(CIWA=CIWA_DPTR, CINV=CINV_DPTR, XK2CG=XK2CG_DPTR, STOKFAC=STOKFAC_DPTR)
      CALL WVENVI_FIELD%UPDATE_DEVICE(EMAXDPT=EMAXDPT_DPTR, INDEP=INDEP_DPTR, IOBND=IOBND_DPTR, IODP=IODP_DPTR)
      CALL FF_NOW_FIELD%UPDATE_DEVICE(AIRD=AIRD_DPTR, WDWAVE=WDWAVE_DPTR, CICOVER=CICOVER_DPTR, WSWAVE=WSWAVE_DPTR,  &
      & WSTAR=WSTAR_DPTR, UFRIC=UFRIC_DPTR, TAUW=TAUW_DPTR, TAUWDIR=TAUWDIR_DPTR, Z0M=Z0M_DPTR, Z0B=Z0B_DPTR,  &
      & CHRNCK=CHRNCK_DPTR, CITHICK=CITHICK_DPTR)
      CALL WAM2NEMO_FIELD%UPDATE_DEVICE(NEMOUSTOKES=NEMOUSTOKES_DPTR, NEMOVSTOKES=NEMOVSTOKES_DPTR, NEMOSTRN=NEMOSTRN_DPTR,  &
      & NPHIEPS=NPHIEPS_DPTR, NTAUOC=NTAUOC_DPTR, NSWH=NSWH_DPTR, NMWP=NMWP_DPTR, NEMOTAUX=NEMOTAUX_DPTR,  &
      & NEMOTAUY=NEMOTAUY_DPTR, NEMOWSWAVE=NEMOWSWAVE_DPTR, NEMOPHIF=NEMOPHIF_DPTR)
      CALL INTFLDS_FIELD%UPDATE_DEVICE(WSEMEAN=WSEMEAN_DPTR, WSFMEAN=WSFMEAN_DPTR, USTOKES=USTOKES_DPTR, VSTOKES=VSTOKES_DPTR,  &
      & STRNMS=STRNMS_DPTR, TAUXD=TAUXD_DPTR, TAUYD=TAUYD_DPTR, TAUOCXD=TAUOCXD_DPTR, TAUOCYD=TAUOCYD_DPTR, TAUOC=TAUOC_DPTR,  &
      & PHIOCD=PHIOCD_DPTR, PHIEPS=PHIEPS_DPTR, PHIAW=PHIAW_DPTR)
      CALL SRC_CONTRIBS%UPDATE_DEVICE(XLLWS=XLLWS_DPTR, MIJ=MIJ_DPTR)
      
!$acc data present( FL1_DPTR,XLLWS_DPTR,MIJ_DPTR,WAVNUM_DPTR,CGROUP_DPTR,CIWA_DPTR,CINV_DPTR,XK2CG_DPTR,STOKFAC_DPTR,  &
!$acc & EMAXDPT_DPTR,INDEP_DPTR,DEPTH_DPTR,IOBND_DPTR,IODP_DPTR,CICOVER_DPTR,WSWAVE_DPTR,WDWAVE_DPTR,AIRD_DPTR,  &
!$acc & WSTAR_DPTR,UFRIC_DPTR,TAUW_DPTR,TAUWDIR_DPTR,Z0M_DPTR,Z0B_DPTR,CHRNCK_DPTR,CITHICK_DPTR,NEMOUSTOKES_DPTR,  &
!$acc & NEMOVSTOKES_DPTR,NEMOSTRN_DPTR,NPHIEPS_DPTR,NTAUOC_DPTR,NSWH_DPTR,NMWP_DPTR,NEMOTAUX_DPTR,NEMOTAUY_DPTR,  &
!$acc & NEMOWSWAVE_DPTR,NEMOPHIF_DPTR,WSEMEAN_DPTR,WSFMEAN_DPTR,USTOKES_DPTR,VSTOKES_DPTR,STRNMS_DPTR,TAUXD_DPTR,  &
!$acc & TAUYD_DPTR,TAUOCXD_DPTR,TAUOCYD_DPTR,TAUOC_DPTR,PHIOCD_DPTR,PHIEPS_DPTR,PHIAW_DPTR )
      TIME0 = -WAM_USER_CLOCK()
      
!$loki start removed loop
      
      BLOCKDIM = DIM3(NPROMA_WAM, 1, 1)
      GRIDDIM = DIM3(1, 1, NCHNK)
!$acc host_data use_device( FL1_DPTR, WAVNUM_DPTR, CGROUP_DPTR, CIWA_DPTR, CINV_DPTR, XK2CG_DPTR, STOKFAC_DPTR, EMAXDPT_DPTR,  &
!$acc & INDEP_DPTR, DEPTH_DPTR, IOBND_DPTR, IODP_DPTR, AIRD_DPTR, WDWAVE_DPTR, CICOVER_DPTR, WSWAVE_DPTR, WSTAR_DPTR,  &
!$acc & UFRIC_DPTR, TAUW_DPTR, TAUWDIR_DPTR, Z0M_DPTR, Z0B_DPTR, CHRNCK_DPTR, CITHICK_DPTR, NEMOUSTOKES_DPTR, NEMOVSTOKES_DPTR,  &
!$acc & NEMOSTRN_DPTR, NPHIEPS_DPTR, NTAUOC_DPTR, NSWH_DPTR, NMWP_DPTR, NEMOTAUX_DPTR, NEMOTAUY_DPTR, NEMOWSWAVE_DPTR,  &
!$acc & NEMOPHIF_DPTR, WSEMEAN_DPTR, WSFMEAN_DPTR, USTOKES_DPTR, VSTOKES_DPTR, STRNMS_DPTR, TAUXD_DPTR, TAUYD_DPTR,  &
!$acc & TAUOCXD_DPTR, TAUOCYD_DPTR, TAUOC_DPTR, PHIOCD_DPTR, PHIEPS_DPTR, PHIAW_DPTR, MIJ_DPTR, XLLWS_DPTR )
      
      CALL IMPLSCH_CUF_HOIST_NEW<<<GRIDDIM,BLOCKDIM>>>(1, NPROMA_WAM, FL1_DPTR(:, :, :, :), WAVNUM_DPTR(:, :, :),  &
      & CGROUP_DPTR(:, :, :), CIWA_DPTR(:, :, :), CINV_DPTR(:, :, :), XK2CG_DPTR(:, :, :), STOKFAC_DPTR(:, :, :),  &
      & EMAXDPT_DPTR(:, :), INDEP_DPTR(:, :), DEPTH_DPTR(:, :), IOBND_DPTR(:, :), IODP_DPTR(:, :), AIRD_DPTR(:, :),  &
      & WDWAVE_DPTR(:, :), CICOVER_DPTR(:, :), WSWAVE_DPTR(:, :), WSTAR_DPTR(:, :), UFRIC_DPTR(:, :), TAUW_DPTR(:, :),  &
      & TAUWDIR_DPTR(:, :), Z0M_DPTR(:, :), Z0B_DPTR(:, :), CHRNCK_DPTR(:, :), CITHICK_DPTR(:, :), NEMOUSTOKES_DPTR(:, :),  &
      & NEMOVSTOKES_DPTR(:, :), NEMOSTRN_DPTR(:, :), NPHIEPS_DPTR(:, :), NTAUOC_DPTR(:, :), NSWH_DPTR(:, :), NMWP_DPTR(:, :),  &
      & NEMOTAUX_DPTR(:, :), NEMOTAUY_DPTR(:, :), NEMOWSWAVE_DPTR(:, :), NEMOPHIF_DPTR(:, :), WSEMEAN_DPTR(:, :),  &
      & WSFMEAN_DPTR(:, :), USTOKES_DPTR(:, :), VSTOKES_DPTR(:, :), STRNMS_DPTR(:, :), TAUXD_DPTR(:, :), TAUYD_DPTR(:, :),  &
      & TAUOCXD_DPTR(:, :), TAUOCYD_DPTR(:, :), TAUOC_DPTR(:, :), PHIOCD_DPTR(:, :), PHIEPS_DPTR(:, :), PHIAW_DPTR(:, :),  &
      & MIJ_DPTR(:, :), XLLWS_DPTR(:, :, :, :), ABMAX, ABMIN, ACD, ACDLIN, AF11_d, AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX,  &
      & ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, C2OSQRTVG_GC_d, CDICWA, CDIS,  &
      & CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC_d, COFRM4_d, COSTH_d, CUMULW_d, DAL1, DAL2,  &
      & DELKCC_GC_NS_d, DELKCC_OMXKM3_GC_d, DELTA_SDIS, DELTH, DFIM_d, DFIMFR_d, DFIMFR2_d, DFIMOFR_d, DFIM_SIM_d, DKMAX,  &
      & DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM_d, FKLAM1_d, FKLAP_d, FKLAP1_d, FLMAX_d, FLMIN, FLOGSPRDM1,  &
      & FR_d, FR5_d, FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM_d, IKM1_d, IKP_d,  &
      & IKP1_d, INDICESSAT_d, INLCOEF_d, IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W_d, K1W_d, K21W_d, K2W_d, KFRH, LBIWBK,  &
      & LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWFLUX, LWFLUXOUT, LWNEMOCOU,  &
      & LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NDEPTH, NDIKCUMUL,  &
      & NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC_d, OMEGA_GC_d, OMXKM3_GC_d, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM_d,  &
      & RN1_RN, RNLCOEF_d, RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS_d, SDSBR, SINTH_d, SQRTGOSURFT, SSDSC2, SSDSC3, SSDSC4,  &
      & SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT_d, TAILFACTOR,  &
      & TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH_d, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF_d, X0TAUHF,  &
      & XKAPPA, XKDMIN, XKMSQRTVGOC2_GC_d, XKM_GC_d, XK_GC_d, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR_d, 1, NCHNK, 1, NCHNK, RAORW=IMPLSCH_RAORW, EMEAN=IMPLSCH_EMEAN, FMEAN=IMPLSCH_FMEAN, HALP=IMPLSCH_HALP,  &
      & EMEANWS=IMPLSCH_EMEANWS, FMEANWS=IMPLSCH_FMEANWS, F1MEAN=IMPLSCH_F1MEAN, AKMEAN=IMPLSCH_AKMEAN, XKMEAN=IMPLSCH_XKMEAN,  &
      & PHIWA=IMPLSCH_PHIWA, FLM=IMPLSCH_FLM, COSWDIF=IMPLSCH_COSWDIF, SINWDIF2=IMPLSCH_SINWDIF2, RHOWGDFTH=IMPLSCH_RHOWGDFTH,  &
      & FLD=IMPLSCH_FLD, SL=IMPLSCH_SL, SPOS=IMPLSCH_SPOS, CIREDUC=IMPLSCH_CIREDUC, SSOURCE=IMPLSCH_SSOURCE,  &
      & SINFLX_RNFAC=SINFLX_RNFAC, SINFLX_TMP_EM=SINFLX_TMP_EM, STRESSO_TAUHF=STRESSO_TAUHF, STRESSO_PHIHF=STRESSO_PHIHF,  &
      & STRESSO_UST=STRESSO_UST, SNONLIN_XNU=SNONLIN_XNU, SNONLIN_SIG_TH=SNONLIN_SIG_TH, ENH=ENH)
      istat = cudaDeviceSynchronize()
     
     ! print *, "finished call to implsch ..." 
!$acc end host_data
      
!$loki end removed loop
      
      TIME1(2) = TIME1(2) + (TIME0 + WAM_USER_CLOCK())*1.E-06
!$acc end data
      CALL WVPRPT_FIELD%ENSURE_HOST()
      CALL WVENVI_FIELD%ENSURE_HOST()
      CALL FF_NOW_FIELD%ENSURE_HOST()
      CALL WAM2NEMO_FIELD%ENSURE_HOST()
      CALL INTFLDS_FIELD%ENSURE_HOST()
      CALL SRC_CONTRIBS%ENSURE_HOST()
      
      CALL WVPRPT_FIELD%FINAL()
      CALL WVENVI_FIELD%FINAL()
      CALL FF_NOW_FIELD%FINAL()
      CALL WAM2NEMO_FIELD%FINAL()
      CALL INTFLDS_FIELD%FINAL()
      CALL SRC_CONTRIBS%FINAL()
      TIME1(3) = TIME1(3) + (TIME2 + WAM_USER_CLOCK())*1.E-06
      
      IF (LWNEMOCOU) NEMONTAU = NEMONTAU + 1
      
    ELSE
      !   NO SOURCE TERM CONTRIBUTION
!$OMP PARALLEL DO SCHEDULE( STATIC ) PRIVATE( ICHNK )
      DO ICHNK=1,NCHNK
        MIJ(:, ICHNK) = NFRE
        FL1(:, :, :, ICHNK) = MAX(FL1(:, :, :, ICHNK), EPSMIN)
        XLLWS(:, :, :, ICHNK) = 0.0_JWRB
      END DO
!$OMP END PARALLEL DO
    END IF
    CALL GSTATS(1431, 1)
    
    
    !*       UPDATE FORCING FIELDS TIME COUNTER
    !        ----------------------------------
    IF (LLNEWFILE) THEN
      LLNEWFILE = .false.
      IDELWH = MAX(IDELWI, IDELPRO)
      CALL INCDATE(CDAWIFL, IDELWH)
      CALL INCDATE(CDATEFL, IDELWH)
    END IF
    
    CDATEWO = CDATEWH
    CDTIMP = CDTIMPNEXT
    CALL INCDATE(CDTIMPNEXT, IDELT)
    
  END IF
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 1, ZHOOK_HANDLE)
  
  
  ! Copy device to host
  ZPIFR = ZPIFR_d
  XK_GC = XK_GC_d
  XKM_GC = XKM_GC_d
  XKMSQRTVGOC2_GC = XKMSQRTVGOC2_GC_d
  WTAUHF = WTAUHF_d
  TH = TH_d
  SWELLFT = SWELLFT_d
  SINTH = SINTH_d
  SATWEIGHTS = SATWEIGHTS_d
  RNLCOEF = RNLCOEF_d
  RHOWG_DFIM = RHOWG_DFIM_d
  OMXKM3_GC = OMXKM3_GC_d
  OMEGA_GC = OMEGA_GC_d
  OM3GMKM_GC = OM3GMKM_GC_d
  K2W = K2W_d
  K21W = K21W_d
  K1W = K1W_d
  K11W = K11W_d
  INLCOEF = INLCOEF_d
  INDICESSAT = INDICESSAT_d
  IKP1 = IKP1_d
  IKP = IKP_d
  IKM1 = IKM1_d
  IKM = IKM_d
  FR5 = FR5_d
  FR = FR_d
  FLMAX = FLMAX_d
  FKLAP1 = FKLAP1_d
  FKLAP = FKLAP_d
  FKLAM1 = FKLAM1_d
  FKLAM = FKLAM_d
  DFIM_SIM = DFIM_SIM_d
  DFIMOFR = DFIMOFR_d
  DFIMFR2 = DFIMFR2_d
  DFIMFR = DFIMFR_d
  DFIM = DFIM_d
  DELKCC_OMXKM3_GC = DELKCC_OMXKM3_GC_d
  DELKCC_GC_NS = DELKCC_GC_NS_d
  CUMULW = CUMULW_d
  COSTH = COSTH_d
  COFRM4 = COFRM4_d
  CM_GC = CM_GC_d
  C2OSQRTVG_GC = C2OSQRTVG_GC_d
  AF11 = AF11_d
  
  ! De-allocation
  DEALLOCATE (AF11_d)
  DEALLOCATE (C2OSQRTVG_GC_d)
  DEALLOCATE (CM_GC_d)
  DEALLOCATE (COFRM4_d)
  DEALLOCATE (COSTH_d)
  DEALLOCATE (CUMULW_d)
  DEALLOCATE (DELKCC_GC_NS_d)
  DEALLOCATE (DELKCC_OMXKM3_GC_d)
  DEALLOCATE (DFIM_d)
  DEALLOCATE (DFIMFR_d)
  DEALLOCATE (DFIMFR2_d)
  DEALLOCATE (DFIMOFR_d)
  DEALLOCATE (DFIM_SIM_d)
  DEALLOCATE (FKLAM_d)
  DEALLOCATE (FKLAM1_d)
  DEALLOCATE (FKLAP_d)
  DEALLOCATE (FKLAP1_d)
  DEALLOCATE (FLMAX_d)
  DEALLOCATE (FR_d)
  DEALLOCATE (FR5_d)
  DEALLOCATE (IKM_d)
  DEALLOCATE (IKM1_d)
  DEALLOCATE (IKP_d)
  DEALLOCATE (IKP1_d)
  DEALLOCATE (INDICESSAT_d)
  DEALLOCATE (INLCOEF_d)
  DEALLOCATE (K11W_d)
  DEALLOCATE (K1W_d)
  DEALLOCATE (K21W_d)
  DEALLOCATE (K2W_d)
  DEALLOCATE (OM3GMKM_GC_d)
  DEALLOCATE (OMEGA_GC_d)
  DEALLOCATE (OMXKM3_GC_d)
  DEALLOCATE (RHOWG_DFIM_d)
  DEALLOCATE (RNLCOEF_d)
  DEALLOCATE (SATWEIGHTS_d)
  DEALLOCATE (SINTH_d)
  DEALLOCATE (SWELLFT_d)
  DEALLOCATE (TH_d)
  DEALLOCATE (WTAUHF_d)
  DEALLOCATE (XKMSQRTVGOC2_GC_d)
  DEALLOCATE (XKM_GC_d)
  DEALLOCATE (XK_GC_d)
  DEALLOCATE (ZPIFR_d)
  DEALLOCATE (IMPLSCH_RAORW)
  DEALLOCATE (IMPLSCH_EMEAN)
  DEALLOCATE (IMPLSCH_FMEAN)
  DEALLOCATE (IMPLSCH_HALP)
  DEALLOCATE (IMPLSCH_EMEANWS)
  DEALLOCATE (IMPLSCH_FMEANWS)
  DEALLOCATE (IMPLSCH_F1MEAN)
  DEALLOCATE (IMPLSCH_AKMEAN)
  DEALLOCATE (IMPLSCH_XKMEAN)
  DEALLOCATE (IMPLSCH_PHIWA)
  DEALLOCATE (IMPLSCH_FLM)
  DEALLOCATE (IMPLSCH_COSWDIF)
  DEALLOCATE (IMPLSCH_SINWDIF2)
  DEALLOCATE (IMPLSCH_RHOWGDFTH)
  DEALLOCATE (IMPLSCH_FLD)
  DEALLOCATE (IMPLSCH_SL)
  DEALLOCATE (IMPLSCH_SPOS)
  DEALLOCATE (IMPLSCH_CIREDUC)
  DEALLOCATE (IMPLSCH_SSOURCE)
  DEALLOCATE (SINFLX_RNFAC)
  DEALLOCATE (SINFLX_TMP_EM)
  DEALLOCATE (STRESSO_TAUHF)
  DEALLOCATE (STRESSO_PHIHF)
  DEALLOCATE (STRESSO_UST)
  DEALLOCATE (SNONLIN_XNU)
  DEALLOCATE (SNONLIN_SIG_TH)
  DEALLOCATE (ENH)
END SUBROUTINE WAMINTGR_LOKI_GPU
