

__device__ void airsea_c(int kijs, int kijl, const double * __restrict__ halp, 
  double * __restrict__ u10, const double * __restrict__ u10dir, 
  const double * __restrict__ tauw, const double * __restrict__ tauwdir, 
  const double * __restrict__ rnfac, double * __restrict__ us, double * __restrict__ z0, 
  double * __restrict__ z0b, double * __restrict__ chrnck, int icode_wnd, int iusfg, 
  double acd, double alpha, double alphamax, double alphamin, double ang_gc_a, 
  double ang_gc_b, double ang_gc_c, double bcd, double betamaxoxkappa2, double bmaxokap, 
  const double * __restrict__ c2osqrtvg_gc, double cdmax, double chnkmin_u, 
  const double * __restrict__ cm_gc, const double * __restrict__ delkcc_gc_ns, 
  const double * __restrict__ delkcc_omxkm3_gc, double eps1, double epsmin, 
  double epsus, double g, double gm1, int llcapchnk, int llgcbz0, int llnormagam, 
  int nwav_gc, const double * __restrict__ om3gmkm_gc, 
  const double * __restrict__ omxkm3_gc, double rn1_rn, double rnu, double rnum, 
  double sqrtgosurft, double wspmin, double xkappa, 
  const double * __restrict__ xkmsqrtvgoc2_gc, const double * __restrict__ xkm_gc, 
  const double * __restrict__ xk_gc, double xlogkratiom1_gc, double xnlev, double zalp, 
  int ichnk, int nchnk, int ij, double * __restrict__ taut_z0_alphaog, 
  double * __restrict__ taut_z0_xmin, double * __restrict__ taut_z0_w1, 
  double * __restrict__ taut_z0_tauwact, double * __restrict__ taut_z0_tauweff, 
  double * __restrict__ taut_z0_ang_gc, double * __restrict__ taut_z0_tauunr, 
  int * __restrict__ taut_z0_llcosdiff, double * __restrict__ stress_gc_gam_w, 
  double * __restrict__ z0wave_alphaog);
