MODULE FKMEAN_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE FKMEAN_fc (KIJS, KIJL, FL1, WAVNUM, EM, FM1, F1, AK, XK, DELTH, DFIM, DFIMFR, DFIMOFR, EPSMIN, FR, FRTAIL, G, NANG,  &
  & NFRE, WETAIL, WP1TAIL, ZPI, ICHNK, NCHNK, IJ, TEMPA, TEMPX, TEMP2)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE FKMEAN_iso_c (KIJS, KIJL, FL1, WAVNUM, EM, FM1, F1, AK, XK, DELTH, DFIM, DFIMFR, DFIMOFR, EPSMIN, FR, FRTAIL,  &
      & G, NANG, NFRE, WETAIL, WP1TAIL, ZPI, ICHNK, NCHNK, IJ, TEMPA, TEMPX, TEMP2) BIND(c, name="fkmean_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: EM
        TYPE(c_ptr), VALUE :: FM1
        TYPE(c_ptr), VALUE :: F1
        TYPE(c_ptr), VALUE :: AK
        TYPE(c_ptr), VALUE :: XK
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMFR
        TYPE(c_ptr), VALUE :: DFIMOFR
        REAL, VALUE :: EPSMIN
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: FRTAIL
        REAL, VALUE :: G
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WP1TAIL
        REAL, VALUE :: ZPI
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: TEMPA
        TYPE(c_ptr), VALUE :: TEMPX
        TYPE(c_ptr), VALUE :: TEMP2
      END SUBROUTINE FKMEAN_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: EM(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FM1(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: F1(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: AK(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XK(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMPA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMPX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP2(:, :)
!$acc host_data use_device( FL1, WAVNUM, EM, FM1, F1, AK, XK, DFIM, DFIMFR, DFIMOFR, FR, TEMPA, TEMPX, TEMP2 )
    CALL FKMEAN_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(EM), c_loc(FM1), c_loc(F1), c_loc(AK), c_loc(XK), DELTH,  &
    & c_loc(DFIM), c_loc(DFIMFR), c_loc(DFIMOFR), EPSMIN, c_loc(FR), FRTAIL, G, NANG, NFRE, WETAIL, WP1TAIL, ZPI, ICHNK, NCHNK,  &
    & IJ, c_loc(TEMPA), c_loc(TEMPX), c_loc(TEMP2))
!$acc end host_data
  END SUBROUTINE FKMEAN_fc
END MODULE FKMEAN_FC_MOD
