MODULE FRCUTINDEX_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE FRCUTINDEX_fc (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH, CITHRSH_TAIL, EPSMIN, FLOGSPRDM1, FR, FRIC, G,  &
  & NFRE, RHOWG_DFIM, TAILFACTOR, TAILFACTOR_PM, ZPIFR, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE FRCUTINDEX_iso_c (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH, CITHRSH_TAIL, EPSMIN, FLOGSPRDM1, FR,  &
      & FRIC, G, NFRE, RHOWG_DFIM, TAILFACTOR, TAILFACTOR_PM, ZPIFR, ICHNK, NCHNK, IJ) BIND(c, name="frcutindex_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FM
        TYPE(c_ptr), VALUE :: FMWS
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        REAL, VALUE :: CITHRSH_TAIL
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: FLOGSPRDM1
        TYPE(c_ptr), VALUE :: FR
        REAL, VALUE :: FRIC
        REAL, VALUE :: G
        INTEGER(KIND=c_int), VALUE :: NFRE
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        REAL, VALUE :: TAILFACTOR
        REAL, VALUE :: TAILFACTOR_PM
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE FRCUTINDEX_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FMWS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
!$acc host_data use_device( FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH, FR, RHOWG_DFIM, ZPIFR )
    CALL FRCUTINDEX_iso_c(KIJS, KIJL, c_loc(FM), c_loc(FMWS), c_loc(UFRIC), c_loc(CICOVER), c_loc(MIJ), c_loc(RHOWGDFTH),  &
    & CITHRSH_TAIL, EPSMIN, FLOGSPRDM1, c_loc(FR), FRIC, G, NFRE, c_loc(RHOWG_DFIM), TAILFACTOR, TAILFACTOR_PM, c_loc(ZPIFR),  &
    & ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE FRCUTINDEX_fc
END MODULE FRCUTINDEX_FC_MOD
