MODULE HALPHAP_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE HALPHAP_fc (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP, ALPHAPMAX, DELTH, DFIM, DFIMOFR, EPSMIN, FR, FR5, FRTAIL, NANG,  &
  & NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ, ALPHAP, XMSS, EM, FM, F1D, WD, FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1,  &
  & MEANSQS_LF_TEMP2)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE FEMEAN (KIJS, KIJL, F, EM, FM)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: F
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: EM, FM
      END SUBROUTINE FEMEAN
    END INTERFACE
    INTERFACE
      SUBROUTINE MEANSQS_LF (NFRE_EFF, KIJS, KIJL, F, WAVNUM, XMSS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: NFRE_EFF
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: F
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: XMSS
      END SUBROUTINE MEANSQS_LF
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE HALPHAP_iso_c (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP, ALPHAPMAX, DELTH, DFIM, DFIMOFR, EPSMIN, FR, FR5,  &
      & FRTAIL, NANG, NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ, ALPHAP, XMSS, EM, FM, F1D, WD, FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
      & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2) BIND(c, name="halphap_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: HALP
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMOFR
        REAL, VALUE :: EPSMIN
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRTAIL
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: WETAIL
        REAL, VALUE :: ZPI4GM2
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: ALPHAP
        TYPE(c_ptr), VALUE :: XMSS
        TYPE(c_ptr), VALUE :: EM
        TYPE(c_ptr), VALUE :: FM
        TYPE(c_ptr), VALUE :: F1D
        TYPE(c_ptr), VALUE :: WD
        TYPE(c_ptr), VALUE :: FLWD
        TYPE(c_ptr), VALUE :: FEMEAN_TEMP2
        TYPE(c_ptr), VALUE :: MEANSQS_LF_FD
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP1
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP2
      END SUBROUTINE HALPHAP_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ALPHAP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XMSS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLWD(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEAN_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_FD(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP2(:, :)
!$acc host_data use_device( WAVNUM, COSWDIF, FL1, HALP, DFIM, DFIMOFR, FR, FR5, ALPHAP, XMSS, EM, FM, F1D, WD, FLWD,  &
!$acc & FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2 )
    CALL HALPHAP_iso_c(KIJS, KIJL, c_loc(WAVNUM), c_loc(COSWDIF), c_loc(FL1), c_loc(HALP), ALPHAPMAX, DELTH, c_loc(DFIM),  &
    & c_loc(DFIMOFR), EPSMIN, c_loc(FR), c_loc(FR5), FRTAIL, NANG, NFRE, WETAIL, ZPI4GM2, ICHNK, NCHNK, IJ, c_loc(ALPHAP),  &
    & c_loc(XMSS), c_loc(EM), c_loc(FM), c_loc(F1D), c_loc(WD), c_loc(FLWD), c_loc(FEMEAN_TEMP2), c_loc(MEANSQS_LF_FD),  &
    & c_loc(MEANSQS_LF_TEMP1), c_loc(MEANSQS_LF_TEMP2))
!$acc end host_data
  END SUBROUTINE HALPHAP_fc
END MODULE HALPHAP_FC_MOD
