MODULE IMPLSCH_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE IMPLSCH_fc (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, DEPTH, IOBND, IODP, AIRD, WDWAVE,  &
  & CICOVER, WSWAVE, WSTAR, USTRA, VSTRA, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN,  &
  & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, TAUXD,  &
  & TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, AF11, AFCRV, ALPHA, ALPHAMAX,  &
  & ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, BRKPBCOEF,  &
  & C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC, COFRM4, COSTH, DAL1, DAL2,  &
  & DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U,  &
  & EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN, FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL,  &
  & G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, IPHYS, IPSAT,  &
  & ISNONLIN, JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR,  &
  & LMASKICE, LWAMRSETCI, LWCOU, LWCOUAST, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN,  &
  & LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC, OMEGA_GC,  &
  & OMXKM3_GC, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR, SINTH,  &
  & SQRTGOSURFT, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7,  &
  & SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN,  &
  & WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI,  &
  & ZPI4GM1, ZPI4GM2, ZPIFR, NCHNK, NPROMA_WAM, DELFL, RAORW, EMEAN, FMEAN, HALP, EMEANWS, FMEANWS, USFM, F1MEAN, AKMEAN,  &
  & XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, TEMP, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC,  &
  & FKMEAN_TEMPA, FKMEAN_TEMPX, FKMEAN_TEMP2, SBOTTOM_SBO, IMPHFTAIL_TEMP1, IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP,  &
  & SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_,  &
  & SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D,  &
  & SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X,  &
  & SDISSIP_JAN_XK2, SDIWBK_SDS, SETICE_CIREDUC, SETICE_TEMP, SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG,  &
  & TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT, TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF,  &
  & STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, HALPHAP_ALPHAP, HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD,  &
  & HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11,  &
  & SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN,  &
  & SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB,  &
  & SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG,  &
  & SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP,  &
  & SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
  & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
  & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF,  &
  & SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US,  &
  & SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2,  &
  & SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0, SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS,  &
  & STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2, STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY,  &
  & STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX, STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS,  &
  & TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0,  &
  & TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI,  &
  & TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH,  &
  & SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD, SNONLIN_DELAP, SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0,  &
  & PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX, PEAK_ANG_TEMP, PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI,  &
  & CIMSSTRN_E, CIMSSTRN_SUME, STOKESDRIFT_STFAC, WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF,  &
  & WNFLUXES_OOVAL, WNFLUXES_EM_OC, WNFLUXES_F1_OC, WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWRO, JWIM
    
    ! needed for Loki
    ! needed for Loki
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE CIWABR (KIJS, KIJL, CICOVER, FL1, WAVNUM, CGROUP, CIWAB)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CGROUP
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: CIWAB
      END SUBROUTINE CIWABR
    END INTERFACE
    INTERFACE
      SUBROUTINE FEMEANWS (KIJS, KIJL, FL1, XLLWS, FM, EM)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
        REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
      END SUBROUTINE FEMEANWS
    END INTERFACE
    INTERFACE
      SUBROUTINE FKMEAN (KIJS, KIJL, FL1, WAVNUM, EM, FM1, F1, AK, XK)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: EM, FM1, F1, AK, XK
      END SUBROUTINE FKMEAN
    END INTERFACE
    INTERFACE
      SUBROUTINE SBOTTOM (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
      END SUBROUTINE SBOTTOM
    END INTERFACE
    INTERFACE
      SUBROUTINE IMPHFTAIL (KIJS, KIJL, MIJ, FLM, WAVNUM, XK2CG, FL1)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, XK2CG
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      END SUBROUTINE IMPHFTAIL
    END INTERFACE
    INTERFACE
      SUBROUTINE SDEPTHLIM (KIJS, KIJL, EMAXDPT, FL1)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMAXDPT
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
      END SUBROUTINE SDEPTHLIM
    END INTERFACE
    INTERFACE
      SUBROUTINE SDISSIP (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CGROUP, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMEAN, F1MEAN, XKMEAN
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, RAORW
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      END SUBROUTINE SDISSIP
    END INTERFACE
    INTERFACE
      SUBROUTINE SDIWBK (KIJS, KIJL, FL1, FLD, SL, DEPTH, EMAXDPT, EMEAN, F1MEAN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE yowparam, ONLY: nang, nfre
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, EMAXDPT, EMEAN, F1MEAN
      END SUBROUTINE SDIWBK
    END INTERFACE
    INTERFACE
      SUBROUTINE SETICE (KIJS, KIJL, FL1, CICOVER, COSWDIF)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      END SUBROUTINE SETICE
    END INTERFACE
    INTERFACE
      SUBROUTINE SINFLX (ICALL, NCALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR,  &
      & CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS,  &
      & MIJ, RHOWGDFTH, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: ICALL
        INTEGER(KIND=JWIM), INTENT(IN) :: NCALL
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        LOGICAL, INTENT(IN) :: LUPDTUS
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: XK2CG
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: WSWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: AIRD
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSTAR
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: SINWDIF2
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FMEAN
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: HALP
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FMEANWS
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UFRIC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUW
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUWDIR
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0M
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0B
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: CHRNCK
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: PHIWA
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SL
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SPOS
        INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINFLX
    END INTERFACE
    INTERFACE
      SUBROUTINE SNONLIN (KIJS, KIJL, FL1, FLD, SL, WAVNUM, DEPTH, AKMEAN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH, AKMEAN
      END SUBROUTINE SNONLIN
    END INTERFACE
    INTERFACE
      SUBROUTINE STOKESTRN (KIJS, KIJL, FL1, WAVNUM, STOKFAC, DEPTH, WSWAVE, WDWAVE, CICOVER, CITHICK, USTOKES, VSTOKES, STRNMS,  &
      & NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN)
        USE parkind_wave, ONLY: jwim, jwrb, jwro
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, STOKFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: DEPTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, WDWAVE, CICOVER, CITHICK
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: USTOKES, VSTOKES, STRNMS
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN
      END SUBROUTINE STOKESTRN
    END INTERFACE
    INTERFACE
      SUBROUTINE WNFLUXES (KIJS, KIJL, MIJ, RHOWGDFTH, CINV, SSURF, CICOVER, PHIWA, EM, F1, WSWAVE, WDWAVE, USTRA, VSTRA, UFRIC,  &
      & AIRD, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC,  &
      & PHIOCD, PHIEPS, PHIAW, LNUPD)
        USE parkind_wave, ONLY: jwim, jwrb, jwro
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJL) :: MIJ
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: SSURF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: PHIWA
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EM, F1, WSWAVE, WDWAVE
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: USTRA, VSTRA
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, AIRD
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: PHIOCD, PHIEPS, PHIAW
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX
        REAL(KIND=JWRO), INTENT(INOUT), DIMENSION(KIJL) :: NEMOTAUY, NEMOWSWAVE, NEMOPHIF
        LOGICAL, INTENT(IN) :: LNUPD
      END SUBROUTINE WNFLUXES
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    
    
    
    !     *FLD* DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE
    !     *SL*  TOTAL SOURCE FUNCTION ARRAY.
    !     *SPOS* : POSITIVE SINPUT ONLY
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: AFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BATHYMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BFCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BRKPBCOEF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDICWA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CIBLOCK
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DAL2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DKMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EGRCRV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSU10
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDELT
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ISNONLIN
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KFRH
    LOGICAL, VALUE, INTENT(IN) :: LBIWBK
    LOGICAL, VALUE, INTENT(IN) :: LCIWABR
    LOGICAL, VALUE, INTENT(IN) :: LICERUN
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    LOGICAL, VALUE, INTENT(IN) :: LLUNSTR
    LOGICAL, VALUE, INTENT(IN) :: LMASKICE
    LOGICAL, VALUE, INTENT(IN) :: LWAMRSETCI
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    LOGICAL, VALUE, INTENT(IN) :: LWCOUAST
    LOGICAL, VALUE, INTENT(IN) :: LWFLUX
    LOGICAL, VALUE, INTENT(IN) :: LWFLUXOUT
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOU
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSEND
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTK
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOCOUSTRN
    LOGICAL, VALUE, INTENT(IN) :: LWNEMOTAUOC
    LOGICAL, VALUE, INTENT(IN) :: LWVFLX_SNL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MFRSTLW
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: MLSTHG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_ODD
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE_RED
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: PHIEPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ROWATERM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSBRF1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUOCMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP1TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WP2TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSEMEAN_MIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKDMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NPROMA_WAM
    INTERFACE
      SUBROUTINE IMPLSCH_iso_c (KIJS, KIJL, FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, DEPTH, IOBND, IODP, AIRD,  &
      & WDWAVE, CICOVER, WSWAVE, WSTAR, USTRA, VSTRA, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES,  &
      & NEMOSTRN, NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES,  &
      & STRNMS, TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, AF11,  &
      & AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2,  &
      & BFCRV, BMAXOKAP, BRKPBCOEF, C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL,  &
      & CM_GC, COFRM4, COSTH, DAL1, DAL2, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS, DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR,  &
      & DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN,  &
      & FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP,  &
      & IKP1, INDICESSAT, INLCOEF, IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W, K1W, K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN,  &
      & LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWCOUAST, LWFLUX, LWFLUXOUT, LWNEMOCOU,  &
      & LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NFRE, NFRE_ODD,  &
      & NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, PHIEPSMAX, PHIEPSMIN, RHOWG_DFIM, RN1_RN, RNLCOEF, RNU,  &
      & RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR, SINTH, SQRTGOSURFT, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6,  &
      & SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUOCMAX,  &
      & TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF, X0TAUHF, XKAPPA, XKDMIN,  &
      & XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, ZPIFR, NCHNK,  &
      & NPROMA_WAM, DELFL, RAORW, EMEAN, FMEAN, HALP, EMEANWS, FMEANWS, USFM, F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF,  &
      & SINWDIF2, TEMP, RHOWGDFTH, FLD, SL, SPOS, CIREDUC, SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, FKMEAN_TEMPA, FKMEAN_TEMPX,  &
      & FKMEAN_TEMP2, SBOTTOM_SBO, IMPHFTAIL_TEMP1, IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP, SDISSIP_ARD_FACTURB,  &
      & SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C,  &
      & SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL,  &
      & SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2,  &
      & SDIWBK_SDS, SETICE_CIREDUC, SETICE_TEMP, SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN,  &
      & TAUT_Z0_W1, TAUT_Z0_TAUWACT, TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W,  &
      & Z0WAVE_ALPHAOG, HALPHAP_ALPHAP, HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD,  &
      & FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11,  &
      & SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB,  &
      & SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C,  &
      & SINPUT_ARD_ZORB, SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG,  &
      & SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP,  &
      & SINPUT_ARD_SLP, SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1,  &
      & SINPUT_ARD_USDIRP, SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1,  &
      & SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD,  &
      & SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST,  &
      & SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1,  &
      & SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD,  &
      & SINPUT_JAN_GAM0, SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH,  &
      & STRESSO_US2, STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT,  &
      & STRESSO_SUMX, STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP,  &
      & TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH,  &
      & TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3,  &
      & TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH, SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD,  &
      & SNONLIN_DELAP, SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0, PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX,  &
      & PEAK_ANG_TEMP, PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI, CIMSSTRN_E, CIMSSTRN_SUME,  &
      & STOKESDRIFT_STFAC, WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF, WNFLUXES_OOVAL, WNFLUXES_EM_OC,  &
      & WNFLUXES_F1_OC, WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY) BIND(c, name="implsch_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CGROUP
        TYPE(c_ptr), VALUE :: CIWA
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: STOKFAC
        TYPE(c_ptr), VALUE :: EMAXDPT
        TYPE(c_ptr), VALUE :: DEPTH
        TYPE(c_ptr), VALUE :: IOBND
        TYPE(c_ptr), VALUE :: IODP
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: USTRA
        TYPE(c_ptr), VALUE :: VSTRA
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: Z0B
        TYPE(c_ptr), VALUE :: CHRNCK
        TYPE(c_ptr), VALUE :: CITHICK
        TYPE(c_ptr), VALUE :: NEMOUSTOKES
        TYPE(c_ptr), VALUE :: NEMOVSTOKES
        TYPE(c_ptr), VALUE :: NEMOSTRN
        TYPE(c_ptr), VALUE :: NPHIEPS
        TYPE(c_ptr), VALUE :: NTAUOC
        TYPE(c_ptr), VALUE :: NSWH
        TYPE(c_ptr), VALUE :: NMWP
        TYPE(c_ptr), VALUE :: NEMOTAUX
        TYPE(c_ptr), VALUE :: NEMOTAUY
        TYPE(c_ptr), VALUE :: NEMOWSWAVE
        TYPE(c_ptr), VALUE :: NEMOPHIF
        TYPE(c_ptr), VALUE :: WSEMEAN
        TYPE(c_ptr), VALUE :: WSFMEAN
        TYPE(c_ptr), VALUE :: USTOKES
        TYPE(c_ptr), VALUE :: VSTOKES
        TYPE(c_ptr), VALUE :: STRNMS
        TYPE(c_ptr), VALUE :: TAUXD
        TYPE(c_ptr), VALUE :: TAUYD
        TYPE(c_ptr), VALUE :: TAUOCXD
        TYPE(c_ptr), VALUE :: TAUOCYD
        TYPE(c_ptr), VALUE :: TAUOC
        TYPE(c_ptr), VALUE :: PHIOCD
        TYPE(c_ptr), VALUE :: PHIEPS
        TYPE(c_ptr), VALUE :: PHIAW
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACD
        REAL, VALUE :: ACDLIN
        TYPE(c_ptr), VALUE :: AF11
        REAL, VALUE :: AFCRV
        REAL, VALUE :: ALPHA
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: ANG_GC_A
        REAL, VALUE :: ANG_GC_B
        REAL, VALUE :: ANG_GC_C
        REAL, VALUE :: BATHYMAX
        REAL, VALUE :: BCD
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BFCRV
        REAL, VALUE :: BMAXOKAP
        REAL, VALUE :: BRKPBCOEF
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        REAL, VALUE :: CDICWA
        REAL, VALUE :: CDIS
        REAL, VALUE :: CDISVIS
        REAL, VALUE :: CDMAX
        REAL, VALUE :: CHNKMIN_U
        REAL, VALUE :: CIBLOCK
        REAL, VALUE :: CITHRSH
        REAL, VALUE :: CITHRSH_TAIL
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: COFRM4
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DAL1
        REAL, VALUE :: DAL2
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: DELTA_SDIS
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMFR
        TYPE(c_ptr), VALUE :: DFIMFR2
        TYPE(c_ptr), VALUE :: DFIMOFR
        TYPE(c_ptr), VALUE :: DFIM_SIM
        REAL, VALUE :: DKMAX
        REAL, VALUE :: DTHRN_A
        REAL, VALUE :: DTHRN_U
        REAL, VALUE :: EGRCRV
        REAL, VALUE :: EPS1
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSU10
        REAL, VALUE :: EPSUS
        TYPE(c_ptr), VALUE :: FKLAM
        TYPE(c_ptr), VALUE :: FKLAM1
        TYPE(c_ptr), VALUE :: FKLAP
        TYPE(c_ptr), VALUE :: FKLAP1
        TYPE(c_ptr), VALUE :: FLMAX
        REAL, VALUE :: FLMIN
        REAL, VALUE :: FLOGSPRDM1
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRATIO
        REAL, VALUE :: FRIC
        REAL, VALUE :: FRTAIL
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: IAB
        INTEGER(KIND=c_int), VALUE :: ICODE
        INTEGER(KIND=c_int), VALUE :: ICODE_CPL
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        INTEGER(KIND=c_int), VALUE :: IDELT
        TYPE(c_ptr), VALUE :: IKM
        TYPE(c_ptr), VALUE :: IKM1
        TYPE(c_ptr), VALUE :: IKP
        TYPE(c_ptr), VALUE :: IKP1
        TYPE(c_ptr), VALUE :: INDICESSAT
        TYPE(c_ptr), VALUE :: INLCOEF
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: IPSAT
        INTEGER(KIND=c_int), VALUE :: ISNONLIN
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        TYPE(c_ptr), VALUE :: K11W
        TYPE(c_ptr), VALUE :: K1W
        TYPE(c_ptr), VALUE :: K21W
        TYPE(c_ptr), VALUE :: K2W
        INTEGER(KIND=c_int), VALUE :: KFRH
        LOGICAL, VALUE :: LBIWBK
        LOGICAL, VALUE :: LCIWABR
        LOGICAL, VALUE :: LICERUN
        LOGICAL, VALUE :: LLCAPCHNK
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        LOGICAL, VALUE :: LLUNSTR
        LOGICAL, VALUE :: LMASKICE
        LOGICAL, VALUE :: LWAMRSETCI
        LOGICAL, VALUE :: LWCOU
        LOGICAL, VALUE :: LWCOUAST
        LOGICAL, VALUE :: LWFLUX
        LOGICAL, VALUE :: LWFLUXOUT
        LOGICAL, VALUE :: LWNEMOCOU
        LOGICAL, VALUE :: LWNEMOCOUSEND
        LOGICAL, VALUE :: LWNEMOCOUSTK
        LOGICAL, VALUE :: LWNEMOCOUSTRN
        LOGICAL, VALUE :: LWNEMOTAUOC
        LOGICAL, VALUE :: LWVFLX_SNL
        INTEGER(KIND=c_int), VALUE :: MFRSTLW
        REAL, VALUE :: MICHE
        INTEGER(KIND=c_int), VALUE :: MLSTHG
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NFRE_ODD
        INTEGER(KIND=c_int), VALUE :: NFRE_RED
        INTEGER(KIND=c_int), VALUE :: NSDSNTH
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        REAL, VALUE :: PHIEPSMAX
        REAL, VALUE :: PHIEPSMIN
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        REAL, VALUE :: RN1_RN
        TYPE(c_ptr), VALUE :: RNLCOEF
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        REAL, VALUE :: ROWATER
        REAL, VALUE :: ROWATERM1
        TYPE(c_ptr), VALUE :: SATWEIGHTS
        REAL, VALUE :: SDSBR
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: SSDSBRF1
        REAL, VALUE :: SSDSC2
        REAL, VALUE :: SSDSC3
        REAL, VALUE :: SSDSC4
        REAL, VALUE :: SSDSC5
        REAL, VALUE :: SSDSC6
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAILFACTOR
        REAL, VALUE :: TAILFACTOR_PM
        REAL, VALUE :: TAUOCMAX
        REAL, VALUE :: TAUOCMIN
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WP1TAIL
        REAL, VALUE :: WP2TAIL
        REAL, VALUE :: WSEMEAN_MIN
        REAL, VALUE :: WSPMIN
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        REAL, VALUE :: XKDMIN
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: XNLEV
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: NPROMA_WAM
        TYPE(c_ptr), VALUE :: DELFL
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: EMEAN
        TYPE(c_ptr), VALUE :: FMEAN
        TYPE(c_ptr), VALUE :: HALP
        TYPE(c_ptr), VALUE :: EMEANWS
        TYPE(c_ptr), VALUE :: FMEANWS
        TYPE(c_ptr), VALUE :: USFM
        TYPE(c_ptr), VALUE :: F1MEAN
        TYPE(c_ptr), VALUE :: AKMEAN
        TYPE(c_ptr), VALUE :: XKMEAN
        TYPE(c_ptr), VALUE :: PHIWA
        TYPE(c_ptr), VALUE :: FLM
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: TEMP
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: CIREDUC
        TYPE(c_ptr), VALUE :: SSOURCE
        TYPE(c_ptr), VALUE :: FEMEANWS_TEMP2
        TYPE(c_ptr), VALUE :: FEMEANWS_EM_LOC
        TYPE(c_ptr), VALUE :: FKMEAN_TEMPA
        TYPE(c_ptr), VALUE :: FKMEAN_TEMPX
        TYPE(c_ptr), VALUE :: FKMEAN_TEMP2
        TYPE(c_ptr), VALUE :: SBOTTOM_SBO
        TYPE(c_ptr), VALUE :: IMPHFTAIL_TEMP1
        TYPE(c_ptr), VALUE :: IMPHFTAIL_TEMP2
        TYPE(c_ptr), VALUE :: SDEPTHLIM_EM
        TYPE(c_ptr), VALUE :: SEMEAN_TEMP
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACTURB
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACSAT
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACWTRB
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TEMP1
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_BTH0
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_C_
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_C_C
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_DSIP
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TRPZ_DSIP
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_BTH
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TEMP2
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_D
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_SCUMUL
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_RENEWALFREQ
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_WCUMUL
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_TEMP1
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_SDS
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_X
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_XK2
        TYPE(c_ptr), VALUE :: SDIWBK_SDS
        TYPE(c_ptr), VALUE :: SETICE_CIREDUC
        TYPE(c_ptr), VALUE :: SETICE_TEMP
        TYPE(c_ptr), VALUE :: SETICE_ICEFREE
        TYPE(c_ptr), VALUE :: SINFLX_RNFAC
        TYPE(c_ptr), VALUE :: SINFLX_TMP_EM
        TYPE(c_ptr), VALUE :: TAUT_Z0_ALPHAOG
        TYPE(c_ptr), VALUE :: TAUT_Z0_XMIN
        TYPE(c_ptr), VALUE :: TAUT_Z0_W1
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUWACT
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUWEFF
        TYPE(c_ptr), VALUE :: TAUT_Z0_ANG_GC
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUUNR
        TYPE(c_ptr), VALUE :: TAUT_Z0_LLCOSDIFF
        TYPE(c_ptr), VALUE :: STRESS_GC_GAM_W
        TYPE(c_ptr), VALUE :: Z0WAVE_ALPHAOG
        TYPE(c_ptr), VALUE :: HALPHAP_ALPHAP
        TYPE(c_ptr), VALUE :: HALPHAP_XMSS
        TYPE(c_ptr), VALUE :: HALPHAP_EM
        TYPE(c_ptr), VALUE :: HALPHAP_FM
        TYPE(c_ptr), VALUE :: HALPHAP_F1D
        TYPE(c_ptr), VALUE :: HALPHAP_WD
        TYPE(c_ptr), VALUE :: HALPHAP_FLWD
        TYPE(c_ptr), VALUE :: FEMEAN_TEMP2
        TYPE(c_ptr), VALUE :: MEANSQS_LF_FD
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP1
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONSTF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST11
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST22
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0VIS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0NOZ
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FWW
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PTURB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UORBT
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE_C
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ROGOROAIR
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AIRD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_YSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USG2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUX
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUY
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USDIRP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCNZALPD
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_COSLP
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZTANHKD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIGDEV
        TYPE(c_ptr), VALUE :: SINPUT_JAN_US
        TYPE(c_ptr), VALUE :: SINPUT_JAN_Z0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XVD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCND
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CONST3_UCN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_TEMPD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_LZ
        TYPE(c_ptr), VALUE :: STRESSO_XSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_YSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_TAUHF
        TYPE(c_ptr), VALUE :: STRESSO_PHIHF
        TYPE(c_ptr), VALUE :: STRESSO_CMRHOWGDFTH
        TYPE(c_ptr), VALUE :: STRESSO_US2
        TYPE(c_ptr), VALUE :: STRESSO_TAUX
        TYPE(c_ptr), VALUE :: STRESSO_TAUY
        TYPE(c_ptr), VALUE :: STRESSO_TAUPX
        TYPE(c_ptr), VALUE :: STRESSO_TAUPY
        TYPE(c_ptr), VALUE :: STRESSO_USDIRP
        TYPE(c_ptr), VALUE :: STRESSO_UST
        TYPE(c_ptr), VALUE :: STRESSO_SUMT
        TYPE(c_ptr), VALUE :: STRESSO_SUMX
        TYPE(c_ptr), VALUE :: STRESSO_SUMY
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_NS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XKS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_OMS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTZ0OG
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZSUP
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZINF
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_DELZ
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_TAUL
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XLOGGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_USTPH
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST1
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTTAU
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTPHI
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS3
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1D
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DSIN2
        TYPE(c_ptr), VALUE :: SNONLIN_ENH
        TYPE(c_ptr), VALUE :: SNONLIN_XNU
        TYPE(c_ptr), VALUE :: SNONLIN_SIG_TH
        TYPE(c_ptr), VALUE :: SNONLIN_FTEMP
        TYPE(c_ptr), VALUE :: SNONLIN_AD
        TYPE(c_ptr), VALUE :: SNONLIN_DELAD
        TYPE(c_ptr), VALUE :: SNONLIN_DELAP
        TYPE(c_ptr), VALUE :: SNONLIN_DELAM
        TYPE(c_ptr), VALUE :: SNONLIN_ENHFR
        TYPE(c_ptr), VALUE :: PEAK_ANG_MMAX
        TYPE(c_ptr), VALUE :: PEAK_ANG_SUM0
        TYPE(c_ptr), VALUE :: PEAK_ANG_SUM1
        TYPE(c_ptr), VALUE :: PEAK_ANG_SUM2
        TYPE(c_ptr), VALUE :: PEAK_ANG_XMAX
        TYPE(c_ptr), VALUE :: PEAK_ANG_TEMP
        TYPE(c_ptr), VALUE :: PEAK_ANG_THMEAN
        TYPE(c_ptr), VALUE :: PEAK_ANG_SUM_S
        TYPE(c_ptr), VALUE :: PEAK_ANG_SUM_C
        TYPE(c_ptr), VALUE :: CIMSSTRN_XKI
        TYPE(c_ptr), VALUE :: CIMSSTRN_E
        TYPE(c_ptr), VALUE :: CIMSSTRN_SUME
        TYPE(c_ptr), VALUE :: STOKESDRIFT_STFAC
        TYPE(c_ptr), VALUE :: WNFLUXES_XSTRESS
        TYPE(c_ptr), VALUE :: WNFLUXES_YSTRESS
        TYPE(c_ptr), VALUE :: WNFLUXES_USTAR
        TYPE(c_ptr), VALUE :: WNFLUXES_PHILF
        TYPE(c_ptr), VALUE :: WNFLUXES_OOVAL
        TYPE(c_ptr), VALUE :: WNFLUXES_EM_OC
        TYPE(c_ptr), VALUE :: WNFLUXES_F1_OC
        TYPE(c_ptr), VALUE :: WNFLUXES_CMRHOWGDFTH
        TYPE(c_ptr), VALUE :: WNFLUXES_SUMT
        TYPE(c_ptr), VALUE :: WNFLUXES_SUMX
        TYPE(c_ptr), VALUE :: WNFLUXES_SUMY
      END SUBROUTINE IMPLSCH_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CIWA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: STOKFAC(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: EMAXDPT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DEPTH(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IOBND(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IODP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTRA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTRA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CITHICK(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOUSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOVSTOKES(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOSTRN(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NPHIEPS(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NTAUOC(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NSWH(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NMWP(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUX(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOTAUY(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOWSWAVE(:, :)
    REAL(KIND=JWRO), TARGET, INTENT(INOUT) :: NEMOPHIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSEMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSFMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: VSTOKES(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRNMS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCXD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOCYD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIOCD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIEPS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIAW(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AF11(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COFRM4(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMFR2(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM_SIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAM1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FKLAP1(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLMAX(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKM1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: IKP1(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INLCOEF(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K11W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K1W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K21W(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: K2W(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNLCOEF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: DELFL(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RAORW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: EMEANWS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FMEANWS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USFM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: F1MEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AKMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XKMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIWA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: COSWDIF(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINWDIF2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RHOWGDFTH(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SPOS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIREDUC(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SSOURCE(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEANWS_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEANWS_EM_LOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FKMEAN_TEMPA(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FKMEAN_TEMPX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FKMEAN_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SBOTTOM_SBO(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: IMPHFTAIL_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: IMPHFTAIL_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDEPTHLIM_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SEMEAN_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACSAT(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACWTRB(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TEMP1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_BTH0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_C_(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_C_C(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TRPZ_DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_BTH(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TEMP2(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_D(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_SCUMUL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_RENEWALFREQ(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_WCUMUL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_SDS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_X(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_XK2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDIWBK_SDS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SETICE_CIREDUC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SETICE_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SETICE_ICEFREE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_RNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINFLX_TMP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_ALPHAOG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_XMIN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_W1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUWACT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUWEFF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_ANG_GC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUUNR(:, :)
    LOGICAL, TARGET, INTENT(INOUT) :: TAUT_Z0_LLCOSDIFF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESS_GC_GAM_W(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0WAVE_ALPHAOG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_ALPHAP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_XMSS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_FM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_WD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_FLWD(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEAN_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_FD(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONSTF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST11(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST22(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0VIS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0NOZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FWW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZCN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UORBT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE_C(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ROGOROAIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AIRD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_YSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USG2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUX(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUY(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USDIRP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCNZALPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAM0(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_COSLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZTANHKD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIGDEV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_US(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_Z0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XVD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCND(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CONST3_UCN2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_TEMPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAM0(:, :, :, :)
    LOGICAL, TARGET, INTENT(INOUT) :: SINPUT_JAN_LZ(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_CMRHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_US2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUPX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUPY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMY(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(INOUT) :: TAU_PHI_HF_NS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XKS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_OMS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTZ0OG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZSUP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZINF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_DELZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_TAUL(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XLOGGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_USTPH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTTAU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTPHI(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS3(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_ENH(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_XNU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_SIG_TH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_FTEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_AD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_DELAD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_DELAP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_DELAM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SNONLIN_ENHFR(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(INOUT) :: PEAK_ANG_MMAX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_SUM0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_SUM1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_SUM2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_XMAX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_THMEAN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_SUM_S(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PEAK_ANG_SUM_C(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIMSSTRN_XKI(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIMSSTRN_E(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CIMSSTRN_SUME(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STOKESDRIFT_STFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_USTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_PHILF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_OOVAL(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_EM_OC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_F1_OC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_CMRHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_SUMT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_SUMX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WNFLUXES_SUMY(:, :)
!$acc host_data use_device( FL1, WAVNUM, CGROUP, CIWA, CINV, XK2CG, STOKFAC, EMAXDPT, DEPTH, IOBND, IODP, AIRD, WDWAVE, CICOVER,  &
!$acc & WSWAVE, WSTAR, USTRA, VSTRA, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, CITHICK, NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN,  &
!$acc & NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, NEMOTAUY, NEMOWSWAVE, NEMOPHIF, WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS,  &
!$acc & TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, PHIEPS, PHIAW, MIJ, XLLWS, AF11, C2OSQRTVG_GC, CM_GC, COFRM4, COSTH,  &
!$acc & DELKCC_GC_NS, DELKCC_OMXKM3_GC, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, FKLAM, FKLAM1, FKLAP, FKLAP1, FLMAX, FR, FR5,  &
!$acc & IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, K11W, K1W, K21W, K2W, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RNLCOEF,  &
!$acc & SATWEIGHTS, SINTH, SWELLFT, TH, WTAUHF, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, ZPIFR, DELFL, RAORW, EMEAN, FMEAN, HALP,  &
!$acc & EMEANWS, FMEANWS, USFM, F1MEAN, AKMEAN, XKMEAN, PHIWA, FLM, COSWDIF, SINWDIF2, TEMP, RHOWGDFTH, FLD, SL, SPOS, CIREDUC,  &
!$acc & SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, FKMEAN_TEMPA, FKMEAN_TEMPX, FKMEAN_TEMP2, SBOTTOM_SBO, IMPHFTAIL_TEMP1,  &
!$acc & IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP, SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB,  &
!$acc & SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP,  &
!$acc & SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL,  &
!$acc & SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2, SDIWBK_SDS, SETICE_CIREDUC, SETICE_TEMP,  &
!$acc & SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT,  &
!$acc & TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, HALPHAP_ALPHAP,  &
!$acc & HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
!$acc & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS,  &
!$acc & SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N,  &
!$acc & SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN,  &
!$acc & SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR,  &
!$acc & SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2,  &
!$acc & SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
!$acc & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
!$acc & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN,  &
!$acc & SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
!$acc & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
!$acc & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
!$acc & SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2,  &
!$acc & STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX,  &
!$acc & STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF,  &
!$acc & TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1,  &
!$acc & TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D,  &
!$acc & TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH, SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD, SNONLIN_DELAP,  &
!$acc & SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0, PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX, PEAK_ANG_TEMP,  &
!$acc & PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI, CIMSSTRN_E, CIMSSTRN_SUME, STOKESDRIFT_STFAC,  &
!$acc & WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF, WNFLUXES_OOVAL, WNFLUXES_EM_OC, WNFLUXES_F1_OC,  &
!$acc & WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY )
    CALL IMPLSCH_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(CGROUP), c_loc(CIWA), c_loc(CINV), c_loc(XK2CG),  &
    & c_loc(STOKFAC), c_loc(EMAXDPT), c_loc(DEPTH), c_loc(IOBND), c_loc(IODP), c_loc(AIRD), c_loc(WDWAVE), c_loc(CICOVER),  &
    & c_loc(WSWAVE), c_loc(WSTAR), c_loc(USTRA), c_loc(VSTRA), c_loc(UFRIC), c_loc(TAUW), c_loc(TAUWDIR), c_loc(Z0M),  &
    & c_loc(Z0B), c_loc(CHRNCK), c_loc(CITHICK), c_loc(NEMOUSTOKES), c_loc(NEMOVSTOKES), c_loc(NEMOSTRN), c_loc(NPHIEPS),  &
    & c_loc(NTAUOC), c_loc(NSWH), c_loc(NMWP), c_loc(NEMOTAUX), c_loc(NEMOTAUY), c_loc(NEMOWSWAVE), c_loc(NEMOPHIF),  &
    & c_loc(WSEMEAN), c_loc(WSFMEAN), c_loc(USTOKES), c_loc(VSTOKES), c_loc(STRNMS), c_loc(TAUXD), c_loc(TAUYD), c_loc(TAUOCXD),  &
    & c_loc(TAUOCYD), c_loc(TAUOC), c_loc(PHIOCD), c_loc(PHIEPS), c_loc(PHIAW), c_loc(MIJ), c_loc(XLLWS), ABMAX, ABMIN, ACD,  &
    & ACDLIN, c_loc(AF11), AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BATHYMAX, BCD, BCDLIN,  &
    & BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, BRKPBCOEF, c_loc(C2OSQRTVG_GC), CDICWA, CDIS, CDISVIS, CDMAX, CHNKMIN_U, CIBLOCK,  &
    & CITHRSH, CITHRSH_TAIL, c_loc(CM_GC), c_loc(COFRM4), c_loc(COSTH), DAL1, DAL2, c_loc(DELKCC_GC_NS),  &
    & c_loc(DELKCC_OMXKM3_GC), DELTA_SDIS, DELTH, c_loc(DFIM), c_loc(DFIMFR), c_loc(DFIMFR2), c_loc(DFIMOFR), c_loc(DFIM_SIM),  &
    & DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, c_loc(FKLAM), c_loc(FKLAM1), c_loc(FKLAP), c_loc(FKLAP1),  &
    & c_loc(FLMAX), FLMIN, FLOGSPRDM1, c_loc(FR), c_loc(FR5), FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL,  &
    & IDAMPING, IDELT, c_loc(IKM), c_loc(IKM1), c_loc(IKP), c_loc(IKP1), c_loc(INDICESSAT), c_loc(INLCOEF), IPHYS, IPSAT,  &
    & ISNONLIN, JTOT_TAUHF, c_loc(K11W), c_loc(K1W), c_loc(K21W), c_loc(K2W), KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK,  &
    & LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU, LWCOUAST, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND,  &
    & LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW, MICHE, MLSTHG, NANG, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH,  &
    & NWAV_GC, c_loc(OM3GMKM_GC), c_loc(OMEGA_GC), c_loc(OMXKM3_GC), PHIEPSMAX, PHIEPSMIN, c_loc(RHOWG_DFIM), RN1_RN,  &
    & c_loc(RNLCOEF), RNU, RNUM, ROWATER, ROWATERM1, c_loc(SATWEIGHTS), SDSBR, c_loc(SINTH), SQRTGOSURFT, SSDSBRF1, SSDSC2,  &
    & SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, c_loc(SWELLFT),  &
    & TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, c_loc(TH), WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN,  &
    & c_loc(WTAUHF), X0TAUHF, XKAPPA, XKDMIN, c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, XNLEV,  &
    & Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2, c_loc(ZPIFR), NCHNK, NPROMA_WAM, c_loc(DELFL), c_loc(RAORW), c_loc(EMEAN),  &
    & c_loc(FMEAN), c_loc(HALP), c_loc(EMEANWS), c_loc(FMEANWS), c_loc(USFM), c_loc(F1MEAN), c_loc(AKMEAN), c_loc(XKMEAN),  &
    & c_loc(PHIWA), c_loc(FLM), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(TEMP), c_loc(RHOWGDFTH), c_loc(FLD), c_loc(SL),  &
    & c_loc(SPOS), c_loc(CIREDUC), c_loc(SSOURCE), c_loc(FEMEANWS_TEMP2), c_loc(FEMEANWS_EM_LOC), c_loc(FKMEAN_TEMPA),  &
    & c_loc(FKMEAN_TEMPX), c_loc(FKMEAN_TEMP2), c_loc(SBOTTOM_SBO), c_loc(IMPHFTAIL_TEMP1), c_loc(IMPHFTAIL_TEMP2),  &
    & c_loc(SDEPTHLIM_EM), c_loc(SEMEAN_TEMP), c_loc(SDISSIP_ARD_FACTURB), c_loc(SDISSIP_ARD_FACSAT),  &
    & c_loc(SDISSIP_ARD_FACWTRB), c_loc(SDISSIP_ARD_TEMP1), c_loc(SDISSIP_ARD_BTH0), c_loc(SDISSIP_ARD_C_),  &
    & c_loc(SDISSIP_ARD_C_C), c_loc(SDISSIP_ARD_DSIP), c_loc(SDISSIP_ARD_TRPZ_DSIP), c_loc(SDISSIP_ARD_BTH),  &
    & c_loc(SDISSIP_ARD_TEMP2), c_loc(SDISSIP_ARD_D), c_loc(SDISSIP_ARD_SCUMUL), c_loc(SDISSIP_ARD_RENEWALFREQ),  &
    & c_loc(SDISSIP_ARD_WCUMUL), c_loc(SDISSIP_JAN_TEMP1), c_loc(SDISSIP_JAN_SDS), c_loc(SDISSIP_JAN_X), c_loc(SDISSIP_JAN_XK2),  &
    & c_loc(SDIWBK_SDS), c_loc(SETICE_CIREDUC), c_loc(SETICE_TEMP), c_loc(SETICE_ICEFREE), c_loc(SINFLX_RNFAC),  &
    & c_loc(SINFLX_TMP_EM), c_loc(TAUT_Z0_ALPHAOG), c_loc(TAUT_Z0_XMIN), c_loc(TAUT_Z0_W1), c_loc(TAUT_Z0_TAUWACT),  &
    & c_loc(TAUT_Z0_TAUWEFF), c_loc(TAUT_Z0_ANG_GC), c_loc(TAUT_Z0_TAUUNR), c_loc(TAUT_Z0_LLCOSDIFF), c_loc(STRESS_GC_GAM_W),  &
    & c_loc(Z0WAVE_ALPHAOG), c_loc(HALPHAP_ALPHAP), c_loc(HALPHAP_XMSS), c_loc(HALPHAP_EM), c_loc(HALPHAP_FM),  &
    & c_loc(HALPHAP_F1D), c_loc(HALPHAP_WD), c_loc(HALPHAP_FLWD), c_loc(FEMEAN_TEMP2), c_loc(MEANSQS_LF_FD),  &
    & c_loc(MEANSQS_LF_TEMP1), c_loc(MEANSQS_LF_TEMP2), c_loc(SINPUT_ARD_CONSTF), c_loc(SINPUT_ARD_CONST11),  &
    & c_loc(SINPUT_ARD_CONST22), c_loc(SINPUT_ARD_Z0VIS), c_loc(SINPUT_ARD_Z0NOZ), c_loc(SINPUT_ARD_FWW),  &
    & c_loc(SINPUT_ARD_PVISC), c_loc(SINPUT_ARD_PTURB), c_loc(SINPUT_ARD_ZCN), c_loc(SINPUT_ARD_SIG_N), c_loc(SINPUT_ARD_UORBT),  &
    & c_loc(SINPUT_ARD_AORB), c_loc(SINPUT_ARD_TEMP), c_loc(SINPUT_ARD_RE), c_loc(SINPUT_ARD_RE_C), c_loc(SINPUT_ARD_ZORB),  &
    & c_loc(SINPUT_ARD_CNSN), c_loc(SINPUT_ARD_SUMF), c_loc(SINPUT_ARD_SUMFSIN2), c_loc(SINPUT_ARD_CSTRNFAC),  &
    & c_loc(SINPUT_ARD_FLP_AVG), c_loc(SINPUT_ARD_SLP_AVG), c_loc(SINPUT_ARD_ROGOROAIR), c_loc(SINPUT_ARD_AIRD_PVISC),  &
    & c_loc(SINPUT_ARD_XSTRESS), c_loc(SINPUT_ARD_YSTRESS), c_loc(SINPUT_ARD_FLP), c_loc(SINPUT_ARD_SLP),  &
    & c_loc(SINPUT_ARD_USG2), c_loc(SINPUT_ARD_TAUX), c_loc(SINPUT_ARD_TAUY), c_loc(SINPUT_ARD_USTP), c_loc(SINPUT_ARD_USTPM1),  &
    & c_loc(SINPUT_ARD_USDIRP), c_loc(SINPUT_ARD_UCN), c_loc(SINPUT_ARD_UCNZALPD), c_loc(SINPUT_ARD_XNGAMCONST),  &
    & c_loc(SINPUT_ARD_GAMNORMA), c_loc(SINPUT_ARD_DSTAB1), c_loc(SINPUT_ARD_TEMP1), c_loc(SINPUT_ARD_TEMP2),  &
    & c_loc(SINPUT_ARD_GAM0), c_loc(SINPUT_ARD_DSTAB), c_loc(SINPUT_ARD_COSLP), c_loc(SINPUT_JAN_ZTANHKD),  &
    & c_loc(SINPUT_JAN_SIG_N), c_loc(SINPUT_JAN_CNSN), c_loc(SINPUT_JAN_SUMF), c_loc(SINPUT_JAN_SUMFSIN2),  &
    & c_loc(SINPUT_JAN_CSTRNFAC), c_loc(SINPUT_JAN_XNGAMCONST), c_loc(SINPUT_JAN_GAMNORMA), c_loc(SINPUT_JAN_SIGDEV),  &
    & c_loc(SINPUT_JAN_US), c_loc(SINPUT_JAN_Z0), c_loc(SINPUT_JAN_UCN), c_loc(SINPUT_JAN_ZCN), c_loc(SINPUT_JAN_USTPM1),  &
    & c_loc(SINPUT_JAN_XVD), c_loc(SINPUT_JAN_UCND), c_loc(SINPUT_JAN_CONST3_UCN2), c_loc(SINPUT_JAN_UFAC1),  &
    & c_loc(SINPUT_JAN_UFAC2), c_loc(SINPUT_JAN_TEMPD), c_loc(SINPUT_JAN_GAM0), c_loc(SINPUT_JAN_LZ), c_loc(STRESSO_XSTRESS),  &
    & c_loc(STRESSO_YSTRESS), c_loc(STRESSO_TAUHF), c_loc(STRESSO_PHIHF), c_loc(STRESSO_CMRHOWGDFTH), c_loc(STRESSO_US2),  &
    & c_loc(STRESSO_TAUX), c_loc(STRESSO_TAUY), c_loc(STRESSO_TAUPX), c_loc(STRESSO_TAUPY), c_loc(STRESSO_USDIRP),  &
    & c_loc(STRESSO_UST), c_loc(STRESSO_SUMT), c_loc(STRESSO_SUMX), c_loc(STRESSO_SUMY), c_loc(TAU_PHI_HF_NS),  &
    & c_loc(TAU_PHI_HF_XKS), c_loc(TAU_PHI_HF_OMS), c_loc(TAU_PHI_HF_SQRTZ0OG), c_loc(TAU_PHI_HF_ZSUP), c_loc(TAU_PHI_HF_ZINF),  &
    & c_loc(TAU_PHI_HF_DELZ), c_loc(TAU_PHI_HF_TAUL), c_loc(TAU_PHI_HF_XLOGGZ0), c_loc(TAU_PHI_HF_SQRTGZ0),  &
    & c_loc(TAU_PHI_HF_USTPH), c_loc(TAU_PHI_HF_CONST1), c_loc(TAU_PHI_HF_CONST2), c_loc(TAU_PHI_HF_CONSTTAU),  &
    & c_loc(TAU_PHI_HF_CONSTPHI), c_loc(TAU_PHI_HF_F1DCOS2), c_loc(TAU_PHI_HF_F1DCOS3), c_loc(TAU_PHI_HF_F1D),  &
    & c_loc(TAU_PHI_HF_F1DSIN2), c_loc(SNONLIN_ENH), c_loc(SNONLIN_XNU), c_loc(SNONLIN_SIG_TH), c_loc(SNONLIN_FTEMP),  &
    & c_loc(SNONLIN_AD), c_loc(SNONLIN_DELAD), c_loc(SNONLIN_DELAP), c_loc(SNONLIN_DELAM), c_loc(SNONLIN_ENHFR),  &
    & c_loc(PEAK_ANG_MMAX), c_loc(PEAK_ANG_SUM0), c_loc(PEAK_ANG_SUM1), c_loc(PEAK_ANG_SUM2), c_loc(PEAK_ANG_XMAX),  &
    & c_loc(PEAK_ANG_TEMP), c_loc(PEAK_ANG_THMEAN), c_loc(PEAK_ANG_SUM_S), c_loc(PEAK_ANG_SUM_C), c_loc(CIMSSTRN_XKI),  &
    & c_loc(CIMSSTRN_E), c_loc(CIMSSTRN_SUME), c_loc(STOKESDRIFT_STFAC), c_loc(WNFLUXES_XSTRESS), c_loc(WNFLUXES_YSTRESS),  &
    & c_loc(WNFLUXES_USTAR), c_loc(WNFLUXES_PHILF), c_loc(WNFLUXES_OOVAL), c_loc(WNFLUXES_EM_OC), c_loc(WNFLUXES_F1_OC),  &
    & c_loc(WNFLUXES_CMRHOWGDFTH), c_loc(WNFLUXES_SUMT), c_loc(WNFLUXES_SUMX), c_loc(WNFLUXES_SUMY))
!$acc end host_data
  END SUBROUTINE IMPLSCH_fc
END MODULE IMPLSCH_FC_MOD
