

__device__ void sdissip_c(int kijs, int kijl, const double * __restrict__ fl1, 
  double * __restrict__ fld, double * __restrict__ sl, 
  const double * __restrict__ wavnum, const double * __restrict__ cgroup, 
  const double * __restrict__ xk2cg, const double * __restrict__ emean, 
  const double * __restrict__ f1mean, const double * __restrict__ xkmean, 
  const double * __restrict__ ufric, const double * __restrict__ coswdif, 
  const double * __restrict__ raorw, double brkpbcoef, double cdis, double cdisvis, 
  double delta_sdis, double delth, double fratio, double g, 
  const int * __restrict__ indicessat, int iphys, int ipsat, double miche, int nang, 
  int nfre, int nsdsnth, double rnu, const double * __restrict__ satweights, 
  double sdsbr, double ssdsbrf1, double ssdsc2, double ssdsc3, double ssdsc4, 
  double ssdsc5, double ssdsc6, double zpi, const double * __restrict__ zpifr, 
  int ichnk, int nchnk, int ij, double * __restrict__ sdissip_ard_facturb, 
  double * __restrict__ sdissip_ard_facsat, double * __restrict__ sdissip_ard_facwtrb, 
  double * __restrict__ sdissip_ard_temp1, double * __restrict__ sdissip_ard_bth0, 
  double * __restrict__ sdissip_ard_c_, double * __restrict__ sdissip_ard_c_c, 
  double * __restrict__ sdissip_ard_dsip, double * __restrict__ sdissip_ard_trpz_dsip, 
  double * __restrict__ sdissip_ard_bth, double * __restrict__ sdissip_ard_temp2, 
  double * __restrict__ sdissip_ard_d, double * __restrict__ sdissip_ard_scumul, 
  double * __restrict__ sdissip_ard_renewalfreq, 
  double * __restrict__ sdissip_ard_wcumul, double * __restrict__ sdissip_jan_temp1, 
  double * __restrict__ sdissip_jan_sds, double * __restrict__ sdissip_jan_x, 
  double * __restrict__ sdissip_jan_xk2);
