MODULE SDISSIP_ARD_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SDISSIP_ARD_fc (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, UFRIC, COSWDIF, RAORW, BRKPBCOEF, DELTH, FRATIO,  &
  & G, INDICESSAT, IPSAT, MICHE, NANG, NFRE, NSDSNTH, SATWEIGHTS, SDSBR, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI,  &
  & ZPIFR, ICHNK, NCHNK, IJ, FACTURB, FACSAT, FACWTRB, TEMP1, BTH0, C_, C_C, DSIP, TRPZ_DSIP, BTH, TEMP2, D, SCUMUL,  &
  & RENEWALFREQ, WCUMUL)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    ! Loki: parameters from YOWPHYS inlined
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    !     NDIKCUMUL is the  integer difference in frequency bands
    
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BRKPBCOEF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSBRF1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SDISSIP_ARD_iso_c (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, UFRIC, COSWDIF, RAORW, BRKPBCOEF, DELTH,  &
      & FRATIO, G, INDICESSAT, IPSAT, MICHE, NANG, NFRE, NSDSNTH, SATWEIGHTS, SDSBR, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5,  &
      & SSDSC6, ZPI, ZPIFR, ICHNK, NCHNK, IJ, FACTURB, FACSAT, FACWTRB, TEMP1, BTH0, C_, C_C, DSIP, TRPZ_DSIP, BTH, TEMP2, D,  &
      & SCUMUL, RENEWALFREQ, WCUMUL) BIND(c, name="sdissip_ard_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CGROUP
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: RAORW
        REAL, VALUE :: BRKPBCOEF
        REAL, VALUE :: DELTH
        REAL, VALUE :: FRATIO
        REAL, VALUE :: G
        TYPE(c_ptr), VALUE :: INDICESSAT
        INTEGER(KIND=c_int), VALUE :: IPSAT
        REAL, VALUE :: MICHE
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NSDSNTH
        TYPE(c_ptr), VALUE :: SATWEIGHTS
        REAL, VALUE :: SDSBR
        REAL, VALUE :: SSDSBRF1
        REAL, VALUE :: SSDSC2
        REAL, VALUE :: SSDSC3
        REAL, VALUE :: SSDSC4
        REAL, VALUE :: SSDSC5
        REAL, VALUE :: SSDSC6
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: FACTURB
        TYPE(c_ptr), VALUE :: FACSAT
        TYPE(c_ptr), VALUE :: FACWTRB
        TYPE(c_ptr), VALUE :: TEMP1
        TYPE(c_ptr), VALUE :: BTH0
        TYPE(c_ptr), VALUE :: C_
        TYPE(c_ptr), VALUE :: C_C
        TYPE(c_ptr), VALUE :: DSIP
        TYPE(c_ptr), VALUE :: TRPZ_DSIP
        TYPE(c_ptr), VALUE :: BTH
        TYPE(c_ptr), VALUE :: TEMP2
        TYPE(c_ptr), VALUE :: D
        TYPE(c_ptr), VALUE :: SCUMUL
        TYPE(c_ptr), VALUE :: RENEWALFREQ
        TYPE(c_ptr), VALUE :: WCUMUL
      END SUBROUTINE SDISSIP_ARD_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FACTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FACSAT(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FACWTRB(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: BTH0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: C_(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: C_C(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TRPZ_DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: BTH(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP2(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: D(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SCUMUL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RENEWALFREQ(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WCUMUL(:, :, :, :)
!$acc host_data use_device( FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, UFRIC, COSWDIF, RAORW, INDICESSAT, SATWEIGHTS, ZPIFR, FACTURB,  &
!$acc & FACSAT, FACWTRB, TEMP1, BTH0, C_, C_C, DSIP, TRPZ_DSIP, BTH, TEMP2, D, SCUMUL, RENEWALFREQ, WCUMUL )
    CALL SDISSIP_ARD_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(FLD), c_loc(SL), c_loc(WAVNUM), c_loc(CGROUP), c_loc(XK2CG),  &
    & c_loc(UFRIC), c_loc(COSWDIF), c_loc(RAORW), BRKPBCOEF, DELTH, FRATIO, G, c_loc(INDICESSAT), IPSAT, MICHE, NANG, NFRE,  &
    & NSDSNTH, c_loc(SATWEIGHTS), SDSBR, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ,  &
    & c_loc(FACTURB), c_loc(FACSAT), c_loc(FACWTRB), c_loc(TEMP1), c_loc(BTH0), c_loc(C_), c_loc(C_C), c_loc(DSIP),  &
    & c_loc(TRPZ_DSIP), c_loc(BTH), c_loc(TEMP2), c_loc(D), c_loc(SCUMUL), c_loc(RENEWALFREQ), c_loc(WCUMUL))
!$acc end host_data
  END SUBROUTINE SDISSIP_ARD_fc
END MODULE SDISSIP_ARD_FC_MOD
