MODULE SDISSIP_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SDISSIP_fc (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW,  &
  & BRKPBCOEF, CDIS, CDISVIS, DELTA_SDIS, DELTH, FRATIO, G, INDICESSAT, IPHYS, IPSAT, MICHE, NANG, NFRE, NSDSNTH, RNU,  &
  & SATWEIGHTS, SDSBR, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR, ICHNK, NCHNK, IJ, SDISSIP_ARD_FACTURB,  &
  & SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C,  &
  & SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL,  &
  & SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE SDISSIP_ARD (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, UFRIC, COSWDIF, RAORW)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CGROUP, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, RAORW
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
      END SUBROUTINE SDISSIP_ARD
    END INTERFACE
    INTERFACE
      SUBROUTINE SDISSIP_JAN (KIJS, KIJL, FL1, FLD, SL, WAVNUM, EMEAN, F1MEAN, XKMEAN)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: EMEAN, F1MEAN, XKMEAN
      END SUBROUTINE SDISSIP_JAN
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BRKPBCOEF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDISVIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTA_SDIS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRATIO
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPSAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: MICHE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NSDSNTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SDSBR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSBRF1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SSDSC6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    INTERFACE
      SUBROUTINE SDISSIP_iso_c (KIJS, KIJL, FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW,  &
      & BRKPBCOEF, CDIS, CDISVIS, DELTA_SDIS, DELTH, FRATIO, G, INDICESSAT, IPHYS, IPSAT, MICHE, NANG, NFRE, NSDSNTH, RNU,  &
      & SATWEIGHTS, SDSBR, SSDSBRF1, SSDSC2, SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, ZPIFR, ICHNK, NCHNK, IJ, SDISSIP_ARD_FACTURB,  &
      & SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C,  &
      & SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL,  &
      & SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2) &
      &  BIND(c, name="sdissip_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CGROUP
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: EMEAN
        TYPE(c_ptr), VALUE :: F1MEAN
        TYPE(c_ptr), VALUE :: XKMEAN
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: RAORW
        REAL, VALUE :: BRKPBCOEF
        REAL, VALUE :: CDIS
        REAL, VALUE :: CDISVIS
        REAL, VALUE :: DELTA_SDIS
        REAL, VALUE :: DELTH
        REAL, VALUE :: FRATIO
        REAL, VALUE :: G
        TYPE(c_ptr), VALUE :: INDICESSAT
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: IPSAT
        REAL, VALUE :: MICHE
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NSDSNTH
        REAL, VALUE :: RNU
        TYPE(c_ptr), VALUE :: SATWEIGHTS
        REAL, VALUE :: SDSBR
        REAL, VALUE :: SSDSBRF1
        REAL, VALUE :: SSDSC2
        REAL, VALUE :: SSDSC3
        REAL, VALUE :: SSDSC4
        REAL, VALUE :: SSDSC5
        REAL, VALUE :: SSDSC6
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACTURB
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACSAT
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_FACWTRB
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TEMP1
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_BTH0
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_C_
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_C_C
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_DSIP
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TRPZ_DSIP
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_BTH
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_TEMP2
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_D
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_SCUMUL
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_RENEWALFREQ
        TYPE(c_ptr), VALUE :: SDISSIP_ARD_WCUMUL
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_TEMP1
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_SDS
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_X
        TYPE(c_ptr), VALUE :: SDISSIP_JAN_XK2
      END SUBROUTINE SDISSIP_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CGROUP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: EMEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: F1MEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: INDICESSAT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SATWEIGHTS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACSAT(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_FACWTRB(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TEMP1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_BTH0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_C_(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_C_C(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TRPZ_DSIP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_BTH(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_TEMP2(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_D(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_SCUMUL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_RENEWALFREQ(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_ARD_WCUMUL(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_SDS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_X(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SDISSIP_JAN_XK2(:, :)
!$acc host_data use_device( FL1, FLD, SL, WAVNUM, CGROUP, XK2CG, EMEAN, F1MEAN, XKMEAN, UFRIC, COSWDIF, RAORW, INDICESSAT,  &
!$acc & SATWEIGHTS, ZPIFR, SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT, SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0,  &
!$acc & SDISSIP_ARD_C_, SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP, SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2,  &
!$acc & SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ, SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS,  &
!$acc & SDISSIP_JAN_X, SDISSIP_JAN_XK2 )
    CALL SDISSIP_iso_c(KIJS, KIJL, c_loc(FL1), c_loc(FLD), c_loc(SL), c_loc(WAVNUM), c_loc(CGROUP), c_loc(XK2CG), c_loc(EMEAN),  &
    & c_loc(F1MEAN), c_loc(XKMEAN), c_loc(UFRIC), c_loc(COSWDIF), c_loc(RAORW), BRKPBCOEF, CDIS, CDISVIS, DELTA_SDIS, DELTH,  &
    & FRATIO, G, c_loc(INDICESSAT), IPHYS, IPSAT, MICHE, NANG, NFRE, NSDSNTH, RNU, c_loc(SATWEIGHTS), SDSBR, SSDSBRF1, SSDSC2,  &
    & SSDSC3, SSDSC4, SSDSC5, SSDSC6, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(SDISSIP_ARD_FACTURB),  &
    & c_loc(SDISSIP_ARD_FACSAT), c_loc(SDISSIP_ARD_FACWTRB), c_loc(SDISSIP_ARD_TEMP1), c_loc(SDISSIP_ARD_BTH0),  &
    & c_loc(SDISSIP_ARD_C_), c_loc(SDISSIP_ARD_C_C), c_loc(SDISSIP_ARD_DSIP), c_loc(SDISSIP_ARD_TRPZ_DSIP),  &
    & c_loc(SDISSIP_ARD_BTH), c_loc(SDISSIP_ARD_TEMP2), c_loc(SDISSIP_ARD_D), c_loc(SDISSIP_ARD_SCUMUL),  &
    & c_loc(SDISSIP_ARD_RENEWALFREQ), c_loc(SDISSIP_ARD_WCUMUL), c_loc(SDISSIP_JAN_TEMP1), c_loc(SDISSIP_JAN_SDS),  &
    & c_loc(SDISSIP_JAN_X), c_loc(SDISSIP_JAN_XK2))
!$acc end host_data
  END SUBROUTINE SDISSIP_fc
END MODULE SDISSIP_FC_MOD
