MODULE SINFLX_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SINFLX_fc (ICALL, NCALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR,  &
  & CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ,  &
  & RHOWGDFTH, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD,  &
  & BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC, COSTH, DELKCC_GC_NS,  &
  & DELKCC_OMXKM3_GC, DELTH, DFIM, DFIMOFR, DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR, FR5, FRIC, FRTAIL, G,  &
  & GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE,  &
  & NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RN1_RN, RNU, RNUM, SINTH, SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3,  &
  & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH, WETAIL, WSPMIN, WTAUHF,  &
  & X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2,  &
  & ZPIFR, ICHNK, NCHNK, IJ, RNFAC, TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT, TAUT_Z0_TAUWEFF,  &
  & TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, FEMEANWS_TEMP2, FEMEANWS_EM_LOC,  &
  & HALPHAP_ALPHAP, HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
  & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS,  &
  & SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT,  &
  & SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN, SINPUT_ARD_SUMF,  &
  & SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR,  &
  & SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2,  &
  & SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
  & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
  & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF,  &
  & SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US,  &
  & SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2,  &
  & SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0, SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS,  &
  & STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2, STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY,  &
  & STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX, STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS,  &
  & TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0,  &
  & TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI,  &
  & TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    ! needed for Loki
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE AIRSEA (KIJS, KIJL, HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC, US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, ICODE_WND, IUSFG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: HALP, U10DIR, TAUW, TAUWDIR, RNFAC
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: U10, US
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: Z0, Z0B, CHRNCK
      END SUBROUTINE AIRSEA
    END INTERFACE
    INTERFACE
      SUBROUTINE FEMEANWS (KIJS, KIJL, FL1, XLLWS, FM, EM)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, XLLWS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FM
        REAL(KIND=JWRB), OPTIONAL, INTENT(OUT), DIMENSION(KIJL) :: EM
      END SUBROUTINE FEMEANWS
    END INTERFACE
    INTERFACE
      SUBROUTINE FRCUTINDEX (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, MIJ, RHOWGDFTH)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FM, FMWS, UFRIC, CICOVER
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
      END SUBROUTINE FRCUTINDEX
    END INTERFACE
    INTERFACE
      SUBROUTINE HALPHAP (KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: HALP
      END SUBROUTINE HALPHAP
    END INTERFACE
    INTERFACE
      SUBROUTINE SINPUT (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
      & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: NGST
        LOGICAL, INTENT(IN) :: LLSNEG
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CINV, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, WSWAVE, UFRIC, Z0M
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW, WSTAR, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL, SPOS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINPUT
    END INTERFACE
    INTERFACE
      SUBROUTINE STRESSO (KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2,  &
      & TAUW, TAUWDIR, PHIWA, LLPHIWA)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN) :: MIJ(KIJL)
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: RHOWGDFTH
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1, SL, SPOS
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, UFRIC, Z0M, AIRD, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: TAUW, TAUWDIR, PHIWA
        LOGICAL, INTENT(IN) :: LLPHIWA
      END SUBROUTINE STRESSO
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICALL    !! CALL NUMBER.
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCALL    !! TOTAL NUMBER OF CALLS.
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS    !! GRID POINT INDEXES.
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL    !! GRID POINT INDEXES.
    
    LOGICAL, VALUE, INTENT(IN) :: LUPDTUS    !! IF TRUE UFRIC AND Z0M WILL BE UPDATED (CALLING AIRSEA).
    
    
    
    
    
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAPMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_B
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ANG_GC_C
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCD
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BMAXOKAP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CDMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CHNKMIN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: CITHRSH_TAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_A
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DTHRN_U
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FLOGSPRDM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRIC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: FRTAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICODE_CPL
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    LOGICAL, VALUE, INTENT(IN) :: LLCAPCHNK
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    LOGICAL, VALUE, INTENT(IN) :: LWCOU
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RN1_RN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAILFACTOR_PM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WETAIL
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XNLEV
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SINFLX_iso_c (ICALL, NCALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR,  &
      & CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS,  &
      & MIJ, RHOWGDFTH, XLLWS, ABMAX, ABMIN, ACD, ACDLIN, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C,  &
      & BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP, C2OSQRTVG_GC, CDMAX, CHNKMIN_U, CITHRSH_TAIL, CM_GC, COSTH, DELKCC_GC_NS,  &
      & DELKCC_OMXKM3_GC, DELTH, DFIM, DFIMOFR, DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, FR, FR5, FRIC, FRTAIL, G,  &
      & GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LWCOU, NANG, NFRE,  &
      & NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM, RN1_RN, RNU, RNUM, SINTH, SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3,  &
      & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, TH, WETAIL, WSPMIN,  &
      & WTAUHF, X0TAUHF, XKAPPA, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ, RNFAC, TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT,  &
      & TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, FEMEANWS_TEMP2,  &
      & FEMEANWS_EM_LOC, HALPHAP_ALPHAP, HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD,  &
      & FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11,  &
      & SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB,  &
      & SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C,  &
      & SINPUT_ARD_ZORB, SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG,  &
      & SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP,  &
      & SINPUT_ARD_SLP, SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1,  &
      & SINPUT_ARD_USDIRP, SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1,  &
      & SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD,  &
      & SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST,  &
      & SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1,  &
      & SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD,  &
      & SINPUT_JAN_GAM0, SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH,  &
      & STRESSO_US2, STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT,  &
      & STRESSO_SUMX, STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP,  &
      & TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH,  &
      & TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3,  &
      & TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2) BIND(c, name="sinflx_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: ICALL
        INTEGER(KIND=c_int), VALUE :: NCALL
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        LOGICAL, VALUE :: LUPDTUS
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: CICOVER
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: FMEAN
        TYPE(c_ptr), VALUE :: HALP
        TYPE(c_ptr), VALUE :: FMEANWS
        TYPE(c_ptr), VALUE :: FLM
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: Z0B
        TYPE(c_ptr), VALUE :: CHRNCK
        TYPE(c_ptr), VALUE :: PHIWA
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACD
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHA
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: ALPHAPMAX
        REAL, VALUE :: ANG_GC_A
        REAL, VALUE :: ANG_GC_B
        REAL, VALUE :: ANG_GC_C
        REAL, VALUE :: BCD
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: BMAXOKAP
        TYPE(c_ptr), VALUE :: C2OSQRTVG_GC
        REAL, VALUE :: CDMAX
        REAL, VALUE :: CHNKMIN_U
        REAL, VALUE :: CITHRSH_TAIL
        TYPE(c_ptr), VALUE :: CM_GC
        TYPE(c_ptr), VALUE :: COSTH
        TYPE(c_ptr), VALUE :: DELKCC_GC_NS
        TYPE(c_ptr), VALUE :: DELKCC_OMXKM3_GC
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        TYPE(c_ptr), VALUE :: DFIMOFR
        REAL, VALUE :: DTHRN_A
        REAL, VALUE :: DTHRN_U
        REAL, VALUE :: EPS1
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: FLOGSPRDM1
        TYPE(c_ptr), VALUE :: FR
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: FRIC
        REAL, VALUE :: FRTAIL
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: IAB
        INTEGER(KIND=c_int), VALUE :: ICODE
        INTEGER(KIND=c_int), VALUE :: ICODE_CPL
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        LOGICAL, VALUE :: LLCAPCHNK
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        LOGICAL, VALUE :: LWCOU
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OM3GMKM_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        TYPE(c_ptr), VALUE :: OMXKM3_GC
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        REAL, VALUE :: RN1_RN
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAILFACTOR
        REAL, VALUE :: TAILFACTOR_PM
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WETAIL
        REAL, VALUE :: WSPMIN
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKMSQRTVGOC2_GC
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: XNLEV
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: TMP_EM
        TYPE(c_ptr), VALUE :: TAUT_Z0_ALPHAOG
        TYPE(c_ptr), VALUE :: TAUT_Z0_XMIN
        TYPE(c_ptr), VALUE :: TAUT_Z0_W1
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUWACT
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUWEFF
        TYPE(c_ptr), VALUE :: TAUT_Z0_ANG_GC
        TYPE(c_ptr), VALUE :: TAUT_Z0_TAUUNR
        TYPE(c_ptr), VALUE :: TAUT_Z0_LLCOSDIFF
        TYPE(c_ptr), VALUE :: STRESS_GC_GAM_W
        TYPE(c_ptr), VALUE :: Z0WAVE_ALPHAOG
        TYPE(c_ptr), VALUE :: FEMEANWS_TEMP2
        TYPE(c_ptr), VALUE :: FEMEANWS_EM_LOC
        TYPE(c_ptr), VALUE :: HALPHAP_ALPHAP
        TYPE(c_ptr), VALUE :: HALPHAP_XMSS
        TYPE(c_ptr), VALUE :: HALPHAP_EM
        TYPE(c_ptr), VALUE :: HALPHAP_FM
        TYPE(c_ptr), VALUE :: HALPHAP_F1D
        TYPE(c_ptr), VALUE :: HALPHAP_WD
        TYPE(c_ptr), VALUE :: HALPHAP_FLWD
        TYPE(c_ptr), VALUE :: FEMEAN_TEMP2
        TYPE(c_ptr), VALUE :: MEANSQS_LF_FD
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP1
        TYPE(c_ptr), VALUE :: MEANSQS_LF_TEMP2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONSTF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST11
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST22
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0VIS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0NOZ
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FWW
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PTURB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UORBT
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE_C
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ROGOROAIR
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AIRD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_YSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USG2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUX
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUY
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USDIRP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCNZALPD
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_COSLP
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZTANHKD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIGDEV
        TYPE(c_ptr), VALUE :: SINPUT_JAN_US
        TYPE(c_ptr), VALUE :: SINPUT_JAN_Z0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XVD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCND
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CONST3_UCN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_TEMPD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_LZ
        TYPE(c_ptr), VALUE :: STRESSO_XSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_YSTRESS
        TYPE(c_ptr), VALUE :: STRESSO_TAUHF
        TYPE(c_ptr), VALUE :: STRESSO_PHIHF
        TYPE(c_ptr), VALUE :: STRESSO_CMRHOWGDFTH
        TYPE(c_ptr), VALUE :: STRESSO_US2
        TYPE(c_ptr), VALUE :: STRESSO_TAUX
        TYPE(c_ptr), VALUE :: STRESSO_TAUY
        TYPE(c_ptr), VALUE :: STRESSO_TAUPX
        TYPE(c_ptr), VALUE :: STRESSO_TAUPY
        TYPE(c_ptr), VALUE :: STRESSO_USDIRP
        TYPE(c_ptr), VALUE :: STRESSO_UST
        TYPE(c_ptr), VALUE :: STRESSO_SUMT
        TYPE(c_ptr), VALUE :: STRESSO_SUMX
        TYPE(c_ptr), VALUE :: STRESSO_SUMY
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_NS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XKS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_OMS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTZ0OG
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZSUP
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZINF
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_DELZ
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_TAUL
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XLOGGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_USTPH
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST1
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTTAU
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTPHI
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS3
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1D
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DSIN2
      END SUBROUTINE SINFLX_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CICOVER(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FMEAN(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALP(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FMEANWS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FLM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0B(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CHRNCK(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: PHIWA(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(OUT) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: C2OSQRTVG_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_GC_NS(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DELKCC_OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIMOFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OM3GMKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMXKM3_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKMSQRTVGOC2_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TMP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_ALPHAOG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_XMIN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_W1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUWACT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUWEFF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_ANG_GC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUT_Z0_TAUUNR(:, :)
    LOGICAL, TARGET, INTENT(INOUT) :: TAUT_Z0_LLCOSDIFF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESS_GC_GAM_W(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0WAVE_ALPHAOG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEANWS_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEANWS_EM_LOC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_ALPHAP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_XMSS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_EM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_FM(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_WD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: HALPHAP_FLWD(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FEMEAN_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_FD(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: MEANSQS_LF_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONSTF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST11(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST22(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0VIS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0NOZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FWW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZCN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UORBT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE_C(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ROGOROAIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AIRD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_YSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USG2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUX(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUY(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USDIRP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCNZALPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAM0(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_COSLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZTANHKD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIGDEV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_US(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_Z0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XVD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCND(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CONST3_UCN2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_TEMPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAM0(:, :, :, :)
    LOGICAL, TARGET, INTENT(INOUT) :: SINPUT_JAN_LZ(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_PHIHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_CMRHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_US2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUPX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_TAUPY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_USDIRP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_UST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: STRESSO_SUMY(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(INOUT) :: TAU_PHI_HF_NS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XKS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_OMS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTZ0OG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZSUP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZINF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_DELZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_TAUL(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XLOGGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_USTPH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTTAU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTPHI(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS3(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DSIN2(:, :)
!$acc host_data use_device( FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER, COSWDIF, SINWDIF2, FMEAN,  &
!$acc & HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ, RHOWGDFTH, XLLWS, C2OSQRTVG_GC,  &
!$acc & CM_GC, COSTH, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DFIM, DFIMOFR, FR, FR5, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, RHOWG_DFIM,  &
!$acc & SINTH, SWELLFT, TH, WTAUHF, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, ZPIFR, RNFAC, TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN,  &
!$acc & TAUT_Z0_W1, TAUT_Z0_TAUWACT, TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W,  &
!$acc & Z0WAVE_ALPHAOG, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, HALPHAP_ALPHAP, HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D,  &
!$acc & HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD, MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF,  &
!$acc & SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC,  &
!$acc & SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE,  &
!$acc & SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC,  &
!$acc & SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS,  &
!$acc & SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP,  &
!$acc & SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA,  &
!$acc & SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP,  &
!$acc & SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC,  &
!$acc & SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN,  &
!$acc & SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1,  &
!$acc & SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0, SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF,  &
!$acc & STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2, STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY,  &
!$acc & STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX, STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS,  &
!$acc & TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0,  &
!$acc & TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI,  &
!$acc & TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2 )
    CALL SINFLX_iso_c(ICALL, NCALL, KIJS, KIJL, LUPDTUS, c_loc(FL1), c_loc(WAVNUM), c_loc(CINV), c_loc(XK2CG), c_loc(WSWAVE),  &
    & c_loc(WDWAVE), c_loc(AIRD), c_loc(RAORW), c_loc(WSTAR), c_loc(CICOVER), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(FMEAN),  &
    & c_loc(HALP), c_loc(FMEANWS), c_loc(FLM), c_loc(UFRIC), c_loc(TAUW), c_loc(TAUWDIR), c_loc(Z0M), c_loc(Z0B), c_loc(CHRNCK),  &
    & c_loc(PHIWA), c_loc(FLD), c_loc(SL), c_loc(SPOS), c_loc(MIJ), c_loc(RHOWGDFTH), c_loc(XLLWS), ABMAX, ABMIN, ACD, ACDLIN,  &
    & ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C, BCD, BCDLIN, BETAMAXOXKAPPA2, BMAXOKAP,  &
    & c_loc(C2OSQRTVG_GC), CDMAX, CHNKMIN_U, CITHRSH_TAIL, c_loc(CM_GC), c_loc(COSTH), c_loc(DELKCC_GC_NS),  &
    & c_loc(DELKCC_OMXKM3_GC), DELTH, c_loc(DFIM), c_loc(DFIMOFR), DTHRN_A, DTHRN_U, EPS1, EPSMIN, EPSUS, FLOGSPRDM1, c_loc(FR),  &
    & c_loc(FR5), FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE, ICODE_CPL, IDAMPING, IPHYS, JTOT_TAUHF, LLCAPCHNK, LLGCBZ0,  &
    & LLNORMAGAM, LWCOU, NANG, NFRE, NWAV_GC, c_loc(OM3GMKM_GC), c_loc(OMEGA_GC), c_loc(OMXKM3_GC), c_loc(RHOWG_DFIM), RN1_RN,  &
    & RNU, RNUM, c_loc(SINTH), SQRTGOSURFT, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1,  &
    & c_loc(SWELLFT), TAILFACTOR, TAILFACTOR_PM, TAUWSHELTER, c_loc(TH), WETAIL, WSPMIN, c_loc(WTAUHF), X0TAUHF, XKAPPA,  &
    & c_loc(XKMSQRTVGOC2_GC), c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1, ZPI4GM2,  &
    & c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(RNFAC), c_loc(TMP_EM), c_loc(TAUT_Z0_ALPHAOG), c_loc(TAUT_Z0_XMIN),  &
    & c_loc(TAUT_Z0_W1), c_loc(TAUT_Z0_TAUWACT), c_loc(TAUT_Z0_TAUWEFF), c_loc(TAUT_Z0_ANG_GC), c_loc(TAUT_Z0_TAUUNR),  &
    & c_loc(TAUT_Z0_LLCOSDIFF), c_loc(STRESS_GC_GAM_W), c_loc(Z0WAVE_ALPHAOG), c_loc(FEMEANWS_TEMP2), c_loc(FEMEANWS_EM_LOC),  &
    & c_loc(HALPHAP_ALPHAP), c_loc(HALPHAP_XMSS), c_loc(HALPHAP_EM), c_loc(HALPHAP_FM), c_loc(HALPHAP_F1D), c_loc(HALPHAP_WD),  &
    & c_loc(HALPHAP_FLWD), c_loc(FEMEAN_TEMP2), c_loc(MEANSQS_LF_FD), c_loc(MEANSQS_LF_TEMP1), c_loc(MEANSQS_LF_TEMP2),  &
    & c_loc(SINPUT_ARD_CONSTF), c_loc(SINPUT_ARD_CONST11), c_loc(SINPUT_ARD_CONST22), c_loc(SINPUT_ARD_Z0VIS),  &
    & c_loc(SINPUT_ARD_Z0NOZ), c_loc(SINPUT_ARD_FWW), c_loc(SINPUT_ARD_PVISC), c_loc(SINPUT_ARD_PTURB), c_loc(SINPUT_ARD_ZCN),  &
    & c_loc(SINPUT_ARD_SIG_N), c_loc(SINPUT_ARD_UORBT), c_loc(SINPUT_ARD_AORB), c_loc(SINPUT_ARD_TEMP), c_loc(SINPUT_ARD_RE),  &
    & c_loc(SINPUT_ARD_RE_C), c_loc(SINPUT_ARD_ZORB), c_loc(SINPUT_ARD_CNSN), c_loc(SINPUT_ARD_SUMF),  &
    & c_loc(SINPUT_ARD_SUMFSIN2), c_loc(SINPUT_ARD_CSTRNFAC), c_loc(SINPUT_ARD_FLP_AVG), c_loc(SINPUT_ARD_SLP_AVG),  &
    & c_loc(SINPUT_ARD_ROGOROAIR), c_loc(SINPUT_ARD_AIRD_PVISC), c_loc(SINPUT_ARD_XSTRESS), c_loc(SINPUT_ARD_YSTRESS),  &
    & c_loc(SINPUT_ARD_FLP), c_loc(SINPUT_ARD_SLP), c_loc(SINPUT_ARD_USG2), c_loc(SINPUT_ARD_TAUX), c_loc(SINPUT_ARD_TAUY),  &
    & c_loc(SINPUT_ARD_USTP), c_loc(SINPUT_ARD_USTPM1), c_loc(SINPUT_ARD_USDIRP), c_loc(SINPUT_ARD_UCN),  &
    & c_loc(SINPUT_ARD_UCNZALPD), c_loc(SINPUT_ARD_XNGAMCONST), c_loc(SINPUT_ARD_GAMNORMA), c_loc(SINPUT_ARD_DSTAB1),  &
    & c_loc(SINPUT_ARD_TEMP1), c_loc(SINPUT_ARD_TEMP2), c_loc(SINPUT_ARD_GAM0), c_loc(SINPUT_ARD_DSTAB),  &
    & c_loc(SINPUT_ARD_COSLP), c_loc(SINPUT_JAN_ZTANHKD), c_loc(SINPUT_JAN_SIG_N), c_loc(SINPUT_JAN_CNSN),  &
    & c_loc(SINPUT_JAN_SUMF), c_loc(SINPUT_JAN_SUMFSIN2), c_loc(SINPUT_JAN_CSTRNFAC), c_loc(SINPUT_JAN_XNGAMCONST),  &
    & c_loc(SINPUT_JAN_GAMNORMA), c_loc(SINPUT_JAN_SIGDEV), c_loc(SINPUT_JAN_US), c_loc(SINPUT_JAN_Z0), c_loc(SINPUT_JAN_UCN),  &
    & c_loc(SINPUT_JAN_ZCN), c_loc(SINPUT_JAN_USTPM1), c_loc(SINPUT_JAN_XVD), c_loc(SINPUT_JAN_UCND),  &
    & c_loc(SINPUT_JAN_CONST3_UCN2), c_loc(SINPUT_JAN_UFAC1), c_loc(SINPUT_JAN_UFAC2), c_loc(SINPUT_JAN_TEMPD),  &
    & c_loc(SINPUT_JAN_GAM0), c_loc(SINPUT_JAN_LZ), c_loc(STRESSO_XSTRESS), c_loc(STRESSO_YSTRESS), c_loc(STRESSO_TAUHF),  &
    & c_loc(STRESSO_PHIHF), c_loc(STRESSO_CMRHOWGDFTH), c_loc(STRESSO_US2), c_loc(STRESSO_TAUX), c_loc(STRESSO_TAUY),  &
    & c_loc(STRESSO_TAUPX), c_loc(STRESSO_TAUPY), c_loc(STRESSO_USDIRP), c_loc(STRESSO_UST), c_loc(STRESSO_SUMT),  &
    & c_loc(STRESSO_SUMX), c_loc(STRESSO_SUMY), c_loc(TAU_PHI_HF_NS), c_loc(TAU_PHI_HF_XKS), c_loc(TAU_PHI_HF_OMS),  &
    & c_loc(TAU_PHI_HF_SQRTZ0OG), c_loc(TAU_PHI_HF_ZSUP), c_loc(TAU_PHI_HF_ZINF), c_loc(TAU_PHI_HF_DELZ),  &
    & c_loc(TAU_PHI_HF_TAUL), c_loc(TAU_PHI_HF_XLOGGZ0), c_loc(TAU_PHI_HF_SQRTGZ0), c_loc(TAU_PHI_HF_USTPH),  &
    & c_loc(TAU_PHI_HF_CONST1), c_loc(TAU_PHI_HF_CONST2), c_loc(TAU_PHI_HF_CONSTTAU), c_loc(TAU_PHI_HF_CONSTPHI),  &
    & c_loc(TAU_PHI_HF_F1DCOS2), c_loc(TAU_PHI_HF_F1DCOS3), c_loc(TAU_PHI_HF_F1D), c_loc(TAU_PHI_HF_F1DSIN2))
!$acc end host_data
  END SUBROUTINE SINFLX_fc
END MODULE SINFLX_FC_MOD
