

__device__ void sinput_ard_c(int ngst, int llsneg, int kijs, int kijl, 
  const double * __restrict__ fl1, const double * __restrict__ wavnum, 
  const double * __restrict__ cinv, const double * __restrict__ xk2cg, 
  const double * __restrict__ wdwave, const double * __restrict__ wswave, 
  const double * __restrict__ ufric, const double * __restrict__ z0m, 
  const double * __restrict__ coswdif, const double * __restrict__ sinwdif2, 
  const double * __restrict__ raorw, const double * __restrict__ wstar, 
  const double * __restrict__ rnfac, double * __restrict__ fld, 
  double * __restrict__ sl, double * __restrict__ spos, double * __restrict__ xllws, 
  double abmax, double abmin, double acdlin, double alphamax, double alphamin, 
  double bcdlin, double betamaxoxkappa2, const double * __restrict__ costh, 
  double delth, const double * __restrict__ dfim, double epsmin, double epsus, double g, 
  int iab, int llgcbz0, int llnormagam, int nang, int nfre, double rnu, double rnum, 
  const double * __restrict__ sinth, double swellf, double swellf2, double swellf3, 
  double swellf4, double swellf5, double swellf6, double swellf7, double swellf7m1, 
  const double * __restrict__ swellft, double tauwshelter, 
  const double * __restrict__ th, double wspmin, double xkappa, double z0rat, 
  double z0tubmax, double zalp, double zpi, const double * __restrict__ zpifr, 
  int ichnk, int nchnk, int ij, double * __restrict__ constf, 
  double * __restrict__ const11, double * __restrict__ const22, 
  double * __restrict__ z0vis, double * __restrict__ z0noz, double * __restrict__ fww, 
  double * __restrict__ pvisc, double * __restrict__ pturb, double * __restrict__ zcn, 
  double * __restrict__ sig_n, double * __restrict__ uorbt, double * __restrict__ aorb, 
  double * __restrict__ temp, double * __restrict__ re, double * __restrict__ re_c, 
  double * __restrict__ zorb, double * __restrict__ cnsn, double * __restrict__ sumf, 
  double * __restrict__ sumfsin2, double * __restrict__ cstrnfac, 
  double * __restrict__ flp_avg, double * __restrict__ slp_avg, 
  double * __restrict__ rogoroair, double * __restrict__ aird_pvisc, 
  double * __restrict__ xstress, double * __restrict__ ystress, 
  double * __restrict__ flp, double * __restrict__ slp, double * __restrict__ usg2, 
  double * __restrict__ taux, double * __restrict__ tauy, double * __restrict__ ustp, 
  double * __restrict__ ustpm1, double * __restrict__ usdirp, double * __restrict__ ucn, 
  double * __restrict__ ucnzalpd, double * __restrict__ xngamconst, 
  double * __restrict__ gamnorma, double * __restrict__ dstab1, 
  double * __restrict__ temp1, double * __restrict__ temp2, double * __restrict__ gam0, 
  double * __restrict__ dstab, double * __restrict__ coslp);
