

__device__ void sinput_jan_c(int ngst, int llsneg, int kijs, int kijl, 
  const double * __restrict__ fl1, const double * __restrict__ wavnum, 
  const double * __restrict__ cinv, const double * __restrict__ xk2cg, 
  const double * __restrict__ wswave, const double * __restrict__ ufric, 
  const double * __restrict__ z0m, const double * __restrict__ coswdif, 
  const double * __restrict__ sinwdif2, const double * __restrict__ raorw, 
  const double * __restrict__ wstar, const double * __restrict__ rnfac, 
  double * __restrict__ fld, double * __restrict__ sl, double * __restrict__ spos, 
  double * __restrict__ xllws, double acdlin, double alphamax, double alphamin, 
  double bcdlin, double betamaxoxkappa2, double delth, double epsus, double g, 
  int idamping, int llgcbz0, int llnormagam, int nang, int nfre, double rnum, 
  double wspmin, double xkappa, double zalp, double zpi, 
  const double * __restrict__ zpifr, int ichnk, int nchnk, int ij, 
  double * __restrict__ ztanhkd, double * __restrict__ sig_n, 
  double * __restrict__ cnsn, double * __restrict__ sumf, 
  double * __restrict__ sumfsin2, double * __restrict__ cstrnfac, 
  double * __restrict__ xngamconst, double * __restrict__ gamnorma, 
  double * __restrict__ sigdev, double * __restrict__ us, double * __restrict__ z0, 
  double * __restrict__ ucn, double * __restrict__ zcn, double * __restrict__ ustpm1, 
  double * __restrict__ xvd, double * __restrict__ ucnd, 
  double * __restrict__ const3_ucn2, double * __restrict__ ufac1, 
  double * __restrict__ ufac2, double * __restrict__ tempd, double * __restrict__ gam0, 
  int * __restrict__ lz);
