MODULE SINPUT_JAN_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SINPUT_JAN_fc (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW,  &
  & WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, DELTH, EPSUS, G, IDAMPING, LLGCBZ0,  &
  & LLNORMAGAM, NANG, NFRE, RNUM, WSPMIN, XKAPPA, ZALP, ZPI, ZPIFR, ICHNK, NCHNK, IJ, ZTANHKD, SIG_N, CNSN, SUMF, SUMFSIN2,  &
  & CSTRNFAC, XNGAMCONST, GAMNORMA, SIGDEV, US, Z0, UCN, ZCN, USTPM1, XVD, UCND, CONST3_UCN2, UFAC1, UFAC2, TEMPD, GAM0, LZ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE ABORT1 ()
      END SUBROUTINE ABORT1
    END INTERFACE
    INTERFACE
      SUBROUTINE WSIGSTAR (KIJS, KIJL, WSWAVE, UFRIC, Z0M, WSTAR, SIG_N)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, UFRIC, Z0M, WSTAR
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: SIG_N
      END SUBROUTINE WSIGSTAR
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NGST
    LOGICAL, VALUE, INTENT(IN) :: LLSNEG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SINPUT_JAN_iso_c (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
      & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, DELTH, EPSUS, G,  &
      & IDAMPING, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNUM, WSPMIN, XKAPPA, ZALP, ZPI, ZPIFR, ICHNK, NCHNK, IJ, ZTANHKD, SIG_N,  &
      & CNSN, SUMF, SUMFSIN2, CSTRNFAC, XNGAMCONST, GAMNORMA, SIGDEV, US, Z0, UCN, ZCN, USTPM1, XVD, UCND, CONST3_UCN2, UFAC1,  &
      & UFAC2, TEMPD, GAM0, LZ) BIND(c, name="sinput_jan_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: NGST
        LOGICAL, VALUE :: LLSNEG
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        REAL, VALUE :: DELTH
        REAL, VALUE :: EPSUS
        REAL, VALUE :: G
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: RNUM
        REAL, VALUE :: WSPMIN
        REAL, VALUE :: XKAPPA
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: ZTANHKD
        TYPE(c_ptr), VALUE :: SIG_N
        TYPE(c_ptr), VALUE :: CNSN
        TYPE(c_ptr), VALUE :: SUMF
        TYPE(c_ptr), VALUE :: SUMFSIN2
        TYPE(c_ptr), VALUE :: CSTRNFAC
        TYPE(c_ptr), VALUE :: XNGAMCONST
        TYPE(c_ptr), VALUE :: GAMNORMA
        TYPE(c_ptr), VALUE :: SIGDEV
        TYPE(c_ptr), VALUE :: US
        TYPE(c_ptr), VALUE :: Z0
        TYPE(c_ptr), VALUE :: UCN
        TYPE(c_ptr), VALUE :: ZCN
        TYPE(c_ptr), VALUE :: USTPM1
        TYPE(c_ptr), VALUE :: XVD
        TYPE(c_ptr), VALUE :: UCND
        TYPE(c_ptr), VALUE :: CONST3_UCN2
        TYPE(c_ptr), VALUE :: UFAC1
        TYPE(c_ptr), VALUE :: UFAC2
        TYPE(c_ptr), VALUE :: TEMPD
        TYPE(c_ptr), VALUE :: GAM0
        TYPE(c_ptr), VALUE :: LZ
      END SUBROUTINE SINPUT_JAN_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ZTANHKD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SIGDEV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: US(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ZCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XVD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UCND(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CONST3_UCN2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFAC1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UFAC2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: GAM0(:, :, :, :)
    LOGICAL, TARGET, INTENT(INOUT) :: LZ(:, :, :)
!$acc host_data use_device( FL1, WAVNUM, CINV, XK2CG, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW, WSTAR, RNFAC, FLD, SL, SPOS,  &
!$acc & XLLWS, ZPIFR, ZTANHKD, SIG_N, CNSN, SUMF, SUMFSIN2, CSTRNFAC, XNGAMCONST, GAMNORMA, SIGDEV, US, Z0, UCN, ZCN, USTPM1,  &
!$acc & XVD, UCND, CONST3_UCN2, UFAC1, UFAC2, TEMPD, GAM0, LZ )
    CALL SINPUT_JAN_iso_c(NGST, LLSNEG, KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(CINV), c_loc(XK2CG), c_loc(WSWAVE),  &
    & c_loc(UFRIC), c_loc(Z0M), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(RAORW), c_loc(WSTAR), c_loc(RNFAC), c_loc(FLD),  &
    & c_loc(SL), c_loc(SPOS), c_loc(XLLWS), ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, DELTH, EPSUS, G, IDAMPING,  &
    & LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNUM, WSPMIN, XKAPPA, ZALP, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(ZTANHKD),  &
    & c_loc(SIG_N), c_loc(CNSN), c_loc(SUMF), c_loc(SUMFSIN2), c_loc(CSTRNFAC), c_loc(XNGAMCONST), c_loc(GAMNORMA),  &
    & c_loc(SIGDEV), c_loc(US), c_loc(Z0), c_loc(UCN), c_loc(ZCN), c_loc(USTPM1), c_loc(XVD), c_loc(UCND), c_loc(CONST3_UCN2),  &
    & c_loc(UFAC1), c_loc(UFAC2), c_loc(TEMPD), c_loc(GAM0), c_loc(LZ))
!$acc end host_data
  END SUBROUTINE SINPUT_JAN_fc
END MODULE SINPUT_JAN_FC_MOD
