MODULE SINPUT_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SINPUT_fc (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
  & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, COSTH, DELTH,  &
  & DFIM, EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH, SWELLF, SWELLF2, SWELLF3,  &
  & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPIFR,  &
  & ICHNK, NCHNK, IJ, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ,  &
  & SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB,  &
  & SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2,  &
  & SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC,  &
  & SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY,  &
  & SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST,  &
  & SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB,  &
  & SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2,  &
  & SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA, SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0,  &
  & SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD, SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2,  &
  & SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0, SINPUT_JAN_LZ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE SINPUT_ARD (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
      & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: NGST
        LOGICAL, INTENT(IN) :: LLSNEG
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CINV, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE, WSWAVE, UFRIC, Z0M
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW, WSTAR, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL, SPOS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINPUT_ARD
    END INTERFACE
    INTERFACE
      SUBROUTINE SINPUT_JAN (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW,  &
      & WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: NGST
        LOGICAL, INTENT(IN) :: LLSNEG
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM, CINV, XK2CG
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, UFRIC, Z0M
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW, WSTAR, RNFAC
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD, SL, SPOS
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS
      END SUBROUTINE SINPUT_JAN
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NGST
    LOGICAL, VALUE, INTENT(IN) :: LLSNEG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IDAMPING
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    INTERFACE
      SUBROUTINE SINPUT_iso_c (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF,  &
      & SINWDIF2, RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2,  &
      & COSTH, DELTH, DFIM, EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH, SWELLF,  &
      & SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA, Z0RAT,  &
      & Z0TUBMAX, ZALP, ZPI, ZPIFR, ICHNK, NCHNK, IJ, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22,  &
      & SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN,  &
      & SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB,  &
      & SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG,  &
      & SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP,  &
      & SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP,  &
      & SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1,  &
      & SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N,  &
      & SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
      & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
      & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
      & SINPUT_JAN_LZ) BIND(c, name="sinput_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: NGST
        LOGICAL, VALUE :: LLSNEG
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: G
        INTEGER(KIND=c_int), VALUE :: IAB
        INTEGER(KIND=c_int), VALUE :: IDAMPING
        INTEGER(KIND=c_int), VALUE :: IPHYS
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WSPMIN
        REAL, VALUE :: XKAPPA
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONSTF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST11
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CONST22
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0VIS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_Z0NOZ
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FWW
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_PTURB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UORBT
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE
        TYPE(c_ptr), VALUE :: SINPUT_ARD_RE_C
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ZORB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP_AVG
        TYPE(c_ptr), VALUE :: SINPUT_ARD_ROGOROAIR
        TYPE(c_ptr), VALUE :: SINPUT_ARD_AIRD_PVISC
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_YSTRESS
        TYPE(c_ptr), VALUE :: SINPUT_ARD_FLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_SLP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USG2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUX
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TAUY
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_USDIRP
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCN
        TYPE(c_ptr), VALUE :: SINPUT_ARD_UCNZALPD
        TYPE(c_ptr), VALUE :: SINPUT_ARD_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP1
        TYPE(c_ptr), VALUE :: SINPUT_ARD_TEMP2
        TYPE(c_ptr), VALUE :: SINPUT_ARD_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_ARD_DSTAB
        TYPE(c_ptr), VALUE :: SINPUT_ARD_COSLP
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZTANHKD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIG_N
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CNSN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMF
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SUMFSIN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CSTRNFAC
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XNGAMCONST
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAMNORMA
        TYPE(c_ptr), VALUE :: SINPUT_JAN_SIGDEV
        TYPE(c_ptr), VALUE :: SINPUT_JAN_US
        TYPE(c_ptr), VALUE :: SINPUT_JAN_Z0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_ZCN
        TYPE(c_ptr), VALUE :: SINPUT_JAN_USTPM1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_XVD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UCND
        TYPE(c_ptr), VALUE :: SINPUT_JAN_CONST3_UCN2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC1
        TYPE(c_ptr), VALUE :: SINPUT_JAN_UFAC2
        TYPE(c_ptr), VALUE :: SINPUT_JAN_TEMPD
        TYPE(c_ptr), VALUE :: SINPUT_JAN_GAM0
        TYPE(c_ptr), VALUE :: SINPUT_JAN_LZ
      END SUBROUTINE SINPUT_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONSTF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST11(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CONST22(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0VIS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_Z0NOZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FWW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_PTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZCN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UORBT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_RE_C(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ZORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_ROGOROAIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_AIRD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_YSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_FLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_SLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USG2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUX(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TAUY(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_USDIRP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_UCNZALPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_GAM0(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_DSTAB(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_ARD_COSLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZTANHKD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_SIGDEV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_US(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_Z0(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_ZCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_XVD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UCND(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_CONST3_UCN2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_UFAC2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_TEMPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SINPUT_JAN_GAM0(:, :, :, :)
    LOGICAL, TARGET, INTENT(INOUT) :: SINPUT_JAN_LZ(:, :, :)
!$acc host_data use_device( FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW, WSTAR, RNFAC, FLD,  &
!$acc & SL, SPOS, XLLWS, COSTH, DFIM, SINTH, SWELLFT, TH, ZPIFR, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22,  &
!$acc & SINPUT_ARD_Z0VIS, SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN,  &
!$acc & SINPUT_ARD_SIG_N, SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB,  &
!$acc & SINPUT_ARD_CNSN, SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG,  &
!$acc & SINPUT_ARD_ROGOROAIR, SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP,  &
!$acc & SINPUT_ARD_USG2, SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP,  &
!$acc & SINPUT_ARD_UCN, SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1,  &
!$acc & SINPUT_ARD_TEMP2, SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N,  &
!$acc & SINPUT_JAN_CNSN, SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
!$acc & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
!$acc & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
!$acc & SINPUT_JAN_LZ )
    CALL SINPUT_iso_c(NGST, LLSNEG, KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(CINV), c_loc(XK2CG), c_loc(WDWAVE),  &
    & c_loc(WSWAVE), c_loc(UFRIC), c_loc(Z0M), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(RAORW), c_loc(WSTAR), c_loc(RNFAC),  &
    & c_loc(FLD), c_loc(SL), c_loc(SPOS), c_loc(XLLWS), ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2,  &
    & c_loc(COSTH), DELTH, c_loc(DFIM), EPSMIN, EPSUS, G, IAB, IDAMPING, IPHYS, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM,  &
    & c_loc(SINTH), SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, c_loc(SWELLFT), TAUWSHELTER,  &
    & c_loc(TH), WSPMIN, XKAPPA, Z0RAT, Z0TUBMAX, ZALP, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(SINPUT_ARD_CONSTF),  &
    & c_loc(SINPUT_ARD_CONST11), c_loc(SINPUT_ARD_CONST22), c_loc(SINPUT_ARD_Z0VIS), c_loc(SINPUT_ARD_Z0NOZ),  &
    & c_loc(SINPUT_ARD_FWW), c_loc(SINPUT_ARD_PVISC), c_loc(SINPUT_ARD_PTURB), c_loc(SINPUT_ARD_ZCN), c_loc(SINPUT_ARD_SIG_N),  &
    & c_loc(SINPUT_ARD_UORBT), c_loc(SINPUT_ARD_AORB), c_loc(SINPUT_ARD_TEMP), c_loc(SINPUT_ARD_RE), c_loc(SINPUT_ARD_RE_C),  &
    & c_loc(SINPUT_ARD_ZORB), c_loc(SINPUT_ARD_CNSN), c_loc(SINPUT_ARD_SUMF), c_loc(SINPUT_ARD_SUMFSIN2),  &
    & c_loc(SINPUT_ARD_CSTRNFAC), c_loc(SINPUT_ARD_FLP_AVG), c_loc(SINPUT_ARD_SLP_AVG), c_loc(SINPUT_ARD_ROGOROAIR),  &
    & c_loc(SINPUT_ARD_AIRD_PVISC), c_loc(SINPUT_ARD_XSTRESS), c_loc(SINPUT_ARD_YSTRESS), c_loc(SINPUT_ARD_FLP),  &
    & c_loc(SINPUT_ARD_SLP), c_loc(SINPUT_ARD_USG2), c_loc(SINPUT_ARD_TAUX), c_loc(SINPUT_ARD_TAUY), c_loc(SINPUT_ARD_USTP),  &
    & c_loc(SINPUT_ARD_USTPM1), c_loc(SINPUT_ARD_USDIRP), c_loc(SINPUT_ARD_UCN), c_loc(SINPUT_ARD_UCNZALPD),  &
    & c_loc(SINPUT_ARD_XNGAMCONST), c_loc(SINPUT_ARD_GAMNORMA), c_loc(SINPUT_ARD_DSTAB1), c_loc(SINPUT_ARD_TEMP1),  &
    & c_loc(SINPUT_ARD_TEMP2), c_loc(SINPUT_ARD_GAM0), c_loc(SINPUT_ARD_DSTAB), c_loc(SINPUT_ARD_COSLP),  &
    & c_loc(SINPUT_JAN_ZTANHKD), c_loc(SINPUT_JAN_SIG_N), c_loc(SINPUT_JAN_CNSN), c_loc(SINPUT_JAN_SUMF),  &
    & c_loc(SINPUT_JAN_SUMFSIN2), c_loc(SINPUT_JAN_CSTRNFAC), c_loc(SINPUT_JAN_XNGAMCONST), c_loc(SINPUT_JAN_GAMNORMA),  &
    & c_loc(SINPUT_JAN_SIGDEV), c_loc(SINPUT_JAN_US), c_loc(SINPUT_JAN_Z0), c_loc(SINPUT_JAN_UCN), c_loc(SINPUT_JAN_ZCN),  &
    & c_loc(SINPUT_JAN_USTPM1), c_loc(SINPUT_JAN_XVD), c_loc(SINPUT_JAN_UCND), c_loc(SINPUT_JAN_CONST3_UCN2),  &
    & c_loc(SINPUT_JAN_UFAC1), c_loc(SINPUT_JAN_UFAC2), c_loc(SINPUT_JAN_TEMPD), c_loc(SINPUT_JAN_GAM0), c_loc(SINPUT_JAN_LZ))
!$acc end host_data
  END SUBROUTINE SINPUT_fc
END MODULE SINPUT_FC_MOD
