MODULE SINPUT_ARD_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE SINPUT_ARD_fc (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2,  &
  & RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2, COSTH, DELTH,  &
  & DFIM, EPSMIN, EPSUS, G, IAB, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5,  &
  & SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPIFR, ICHNK, NCHNK, IJ,  &
  & CONSTF, CONST11, CONST22, Z0VIS, Z0NOZ, FWW, PVISC, PTURB, ZCN, SIG_N, UORBT, AORB, TEMP, RE, RE_C, ZORB, CNSN, SUMF,  &
  & SUMFSIN2, CSTRNFAC, FLP_AVG, SLP_AVG, ROGOROAIR, AIRD_PVISC, XSTRESS, YSTRESS, FLP, SLP, USG2, TAUX, TAUY, USTP, USTPM1,  &
  & USDIRP, UCN, UCNZALPD, XNGAMCONST, GAMNORMA, DSTAB1, TEMP1, TEMP2, GAM0, DSTAB, COSLP)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE WSIGSTAR (KIJS, KIJL, WSWAVE, UFRIC, Z0M, WSTAR, SIG_N)
        USE parkind_wave, ONLY: jwim, jwrb
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSWAVE, UFRIC, Z0M, WSTAR
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: SIG_N
      END SUBROUTINE WSIGSTAR
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NGST
    LOGICAL, VALUE, INTENT(IN) :: LLSNEG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ABMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BETAMAXOXKAPPA2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IAB
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNU
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF2
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF3
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF4
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF5
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF6
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SWELLF7M1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0RAT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: Z0TUBMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE SINPUT_ARD_iso_c (NGST, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF,  &
      & SINWDIF2, RAORW, WSTAR, RNFAC, FLD, SL, SPOS, XLLWS, ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2,  &
      & COSTH, DELTH, DFIM, EPSMIN, EPSUS, G, IAB, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, SINTH, SWELLF, SWELLF2, SWELLF3,  &
      & SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT, TAUWSHELTER, TH, WSPMIN, XKAPPA, Z0RAT, Z0TUBMAX, ZALP, ZPI,  &
      & ZPIFR, ICHNK, NCHNK, IJ, CONSTF, CONST11, CONST22, Z0VIS, Z0NOZ, FWW, PVISC, PTURB, ZCN, SIG_N, UORBT, AORB, TEMP, RE,  &
      & RE_C, ZORB, CNSN, SUMF, SUMFSIN2, CSTRNFAC, FLP_AVG, SLP_AVG, ROGOROAIR, AIRD_PVISC, XSTRESS, YSTRESS, FLP, SLP, USG2,  &
      & TAUX, TAUY, USTP, USTPM1, USDIRP, UCN, UCNZALPD, XNGAMCONST, GAMNORMA, DSTAB1, TEMP1, TEMP2, GAM0, DSTAB, COSLP) &
      &  BIND(c, name="sinput_ard_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: NGST
        LOGICAL, VALUE :: LLSNEG
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: WAVNUM
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: XK2CG
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: RAORW
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: FLD
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: XLLWS
        REAL, VALUE :: ABMAX
        REAL, VALUE :: ABMIN
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: BETAMAXOXKAPPA2
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DELTH
        TYPE(c_ptr), VALUE :: DFIM
        REAL, VALUE :: EPSMIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: G
        INTEGER(KIND=c_int), VALUE :: IAB
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        REAL, VALUE :: RNU
        REAL, VALUE :: RNUM
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SWELLF
        REAL, VALUE :: SWELLF2
        REAL, VALUE :: SWELLF3
        REAL, VALUE :: SWELLF4
        REAL, VALUE :: SWELLF5
        REAL, VALUE :: SWELLF6
        REAL, VALUE :: SWELLF7
        REAL, VALUE :: SWELLF7M1
        TYPE(c_ptr), VALUE :: SWELLFT
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: TH
        REAL, VALUE :: WSPMIN
        REAL, VALUE :: XKAPPA
        REAL, VALUE :: Z0RAT
        REAL, VALUE :: Z0TUBMAX
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: CONSTF
        TYPE(c_ptr), VALUE :: CONST11
        TYPE(c_ptr), VALUE :: CONST22
        TYPE(c_ptr), VALUE :: Z0VIS
        TYPE(c_ptr), VALUE :: Z0NOZ
        TYPE(c_ptr), VALUE :: FWW
        TYPE(c_ptr), VALUE :: PVISC
        TYPE(c_ptr), VALUE :: PTURB
        TYPE(c_ptr), VALUE :: ZCN
        TYPE(c_ptr), VALUE :: SIG_N
        TYPE(c_ptr), VALUE :: UORBT
        TYPE(c_ptr), VALUE :: AORB
        TYPE(c_ptr), VALUE :: TEMP
        TYPE(c_ptr), VALUE :: RE
        TYPE(c_ptr), VALUE :: RE_C
        TYPE(c_ptr), VALUE :: ZORB
        TYPE(c_ptr), VALUE :: CNSN
        TYPE(c_ptr), VALUE :: SUMF
        TYPE(c_ptr), VALUE :: SUMFSIN2
        TYPE(c_ptr), VALUE :: CSTRNFAC
        TYPE(c_ptr), VALUE :: FLP_AVG
        TYPE(c_ptr), VALUE :: SLP_AVG
        TYPE(c_ptr), VALUE :: ROGOROAIR
        TYPE(c_ptr), VALUE :: AIRD_PVISC
        TYPE(c_ptr), VALUE :: XSTRESS
        TYPE(c_ptr), VALUE :: YSTRESS
        TYPE(c_ptr), VALUE :: FLP
        TYPE(c_ptr), VALUE :: SLP
        TYPE(c_ptr), VALUE :: USG2
        TYPE(c_ptr), VALUE :: TAUX
        TYPE(c_ptr), VALUE :: TAUY
        TYPE(c_ptr), VALUE :: USTP
        TYPE(c_ptr), VALUE :: USTPM1
        TYPE(c_ptr), VALUE :: USDIRP
        TYPE(c_ptr), VALUE :: UCN
        TYPE(c_ptr), VALUE :: UCNZALPD
        TYPE(c_ptr), VALUE :: XNGAMCONST
        TYPE(c_ptr), VALUE :: GAMNORMA
        TYPE(c_ptr), VALUE :: DSTAB1
        TYPE(c_ptr), VALUE :: TEMP1
        TYPE(c_ptr), VALUE :: TEMP2
        TYPE(c_ptr), VALUE :: GAM0
        TYPE(c_ptr), VALUE :: DSTAB
        TYPE(c_ptr), VALUE :: COSLP
      END SUBROUTINE SINPUT_ARD_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WAVNUM(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK2CG(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RAORW(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: FLD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SPOS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: XLLWS(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SWELLFT(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: TH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CONSTF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CONST11(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CONST22(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0VIS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: Z0NOZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FWW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PTURB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ZCN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SIG_N(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UORBT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: RE_C(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ZORB(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CNSN(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMFSIN2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CSTRNFAC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SLP_AVG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: ROGOROAIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: AIRD_PVISC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: YSTRESS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: FLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SLP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USG2(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUX(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUY(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USTPM1(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USDIRP(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UCN(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UCNZALPD(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XNGAMCONST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: GAMNORMA(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: DSTAB1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TEMP2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: GAM0(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: DSTAB(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: COSLP(:, :, :)
!$acc host_data use_device( FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW, WSTAR, RNFAC, FLD,  &
!$acc & SL, SPOS, XLLWS, COSTH, DFIM, SINTH, SWELLFT, TH, ZPIFR, CONSTF, CONST11, CONST22, Z0VIS, Z0NOZ, FWW, PVISC, PTURB, ZCN,  &
!$acc & SIG_N, UORBT, AORB, TEMP, RE, RE_C, ZORB, CNSN, SUMF, SUMFSIN2, CSTRNFAC, FLP_AVG, SLP_AVG, ROGOROAIR, AIRD_PVISC,  &
!$acc & XSTRESS, YSTRESS, FLP, SLP, USG2, TAUX, TAUY, USTP, USTPM1, USDIRP, UCN, UCNZALPD, XNGAMCONST, GAMNORMA, DSTAB1, TEMP1,  &
!$acc & TEMP2, GAM0, DSTAB, COSLP )
    CALL SINPUT_ARD_iso_c(NGST, LLSNEG, KIJS, KIJL, c_loc(FL1), c_loc(WAVNUM), c_loc(CINV), c_loc(XK2CG), c_loc(WDWAVE),  &
    & c_loc(WSWAVE), c_loc(UFRIC), c_loc(Z0M), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(RAORW), c_loc(WSTAR), c_loc(RNFAC),  &
    & c_loc(FLD), c_loc(SL), c_loc(SPOS), c_loc(XLLWS), ABMAX, ABMIN, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, BETAMAXOXKAPPA2,  &
    & c_loc(COSTH), DELTH, c_loc(DFIM), EPSMIN, EPSUS, G, IAB, LLGCBZ0, LLNORMAGAM, NANG, NFRE, RNU, RNUM, c_loc(SINTH), SWELLF,  &
    & SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, c_loc(SWELLFT), TAUWSHELTER, c_loc(TH), WSPMIN, XKAPPA,  &
    & Z0RAT, Z0TUBMAX, ZALP, ZPI, c_loc(ZPIFR), ICHNK, NCHNK, IJ, c_loc(CONSTF), c_loc(CONST11), c_loc(CONST22), c_loc(Z0VIS),  &
    & c_loc(Z0NOZ), c_loc(FWW), c_loc(PVISC), c_loc(PTURB), c_loc(ZCN), c_loc(SIG_N), c_loc(UORBT), c_loc(AORB), c_loc(TEMP),  &
    & c_loc(RE), c_loc(RE_C), c_loc(ZORB), c_loc(CNSN), c_loc(SUMF), c_loc(SUMFSIN2), c_loc(CSTRNFAC), c_loc(FLP_AVG),  &
    & c_loc(SLP_AVG), c_loc(ROGOROAIR), c_loc(AIRD_PVISC), c_loc(XSTRESS), c_loc(YSTRESS), c_loc(FLP), c_loc(SLP), c_loc(USG2),  &
    & c_loc(TAUX), c_loc(TAUY), c_loc(USTP), c_loc(USTPM1), c_loc(USDIRP), c_loc(UCN), c_loc(UCNZALPD), c_loc(XNGAMCONST),  &
    & c_loc(GAMNORMA), c_loc(DSTAB1), c_loc(TEMP1), c_loc(TEMP2), c_loc(GAM0), c_loc(DSTAB), c_loc(COSLP))
!$acc end host_data
  END SUBROUTINE SINPUT_ARD_fc
END MODULE SINPUT_ARD_FC_MOD
