

__device__ void snonlin_c(int kijs, int kijl, const double * __restrict__ fl1, 
  double * __restrict__ fld, double * __restrict__ sl, 
  const double * __restrict__ wavnum, const double * __restrict__ depth, 
  const double * __restrict__ akmean, const double * __restrict__ af11, double bathymax, 
  const double * __restrict__ costh, double dal1, double dal2, double delth, 
  const double * __restrict__ dfim, const double * __restrict__ dfimfr, 
  const double * __restrict__ dfimfr2, double dkmax, const double * __restrict__ fklam, 
  const double * __restrict__ fklam1, const double * __restrict__ fklap, 
  const double * __restrict__ fklap1, const double * __restrict__ fr, double fratio, 
  double g, double gm1, const int * __restrict__ ikm, const int * __restrict__ ikm1, 
  const int * __restrict__ ikp, const int * __restrict__ ikp1, 
  const int * __restrict__ inlcoef, int isnonlin, const int * __restrict__ k11w, 
  const int * __restrict__ k1w, const int * __restrict__ k21w, 
  const int * __restrict__ k2w, int kfrh, int mfrstlw, int mlsthg, int nang, int nfre, 
  const double * __restrict__ rnlcoef, const double * __restrict__ sinth, 
  const double * __restrict__ th, double wetail, double wp1tail, double wp2tail, 
  double xkdmin, const double * __restrict__ zpifr, int ichnk, int nchnk, int ij, 
  double * __restrict__ enh, double * __restrict__ xnu, double * __restrict__ sig_th, 
  double * __restrict__ ftemp, double * __restrict__ ad, double * __restrict__ delad, 
  double * __restrict__ delap, double * __restrict__ delam, double * __restrict__ enhfr, 
  int * __restrict__ peak_ang_mmax, double * __restrict__ peak_ang_sum0, 
  double * __restrict__ peak_ang_sum1, double * __restrict__ peak_ang_sum2, 
  double * __restrict__ peak_ang_xmax, double * __restrict__ peak_ang_temp, 
  double * __restrict__ peak_ang_thmean, double * __restrict__ peak_ang_sum_s, 
  double * __restrict__ peak_ang_sum_c);
