MODULE STRESSO_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE STRESSO_fc (KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2,  &
  & TAUW, TAUWDIR, PHIWA, LLPHIWA, COSTH, DELTH, EPS1, FR5, G, GAMNCONST, GM1, IPHYS, JTOT_TAUHF, LLGCBZ0, LLNORMAGAM, NANG,  &
  & NFRE, NWAV_GC, OMEGA_GC, RHOWG_DFIM, SINTH, SQRTGOSURFT, TAUWSHELTER, WTAUHF, X0TAUHF, XKAPPA, XKM_GC, XK_GC,  &
  & XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ, XSTRESS, YSTRESS, TAUHF, PHIHF, CMRHOWGDFTH, US2, TAUX,  &
  & TAUY, TAUPX, TAUPY, USDIRP, UST, SUMT, SUMX, SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG,  &
  & TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0,  &
  & TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2,  &
  & TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTERFACE
      SUBROUTINE TAU_PHI_HF (KIJS, KIJL, MIJ, LTAUWSHELTER, UFRIC, Z0M, FL1, AIRD, RNFAC, COSWDIF, SINWDIF2, UST, TAUHF, PHIHF,  &
      & LLPHIHF)
        USE parkind_wave, ONLY: jwim, jwrb
        USE YOWPARAM, ONLY: NANG, NFRE
        INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
        INTEGER(KIND=JWIM), INTENT(IN) :: MIJ(KIJL)
        LOGICAL, INTENT(IN) :: LTAUWSHELTER
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: UFRIC, Z0M
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG, NFRE) :: FL1
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: AIRD, RNFAC
        REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF, SINWDIF2
        REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UST
        REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: TAUHF, PHIHF
        LOGICAL, INTENT(IN) :: LLPHIHF
      END SUBROUTINE TAU_PHI_HF
    END INTERFACE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    LOGICAL, VALUE, INTENT(IN) :: LLPHIWA
    
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: DELTH
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPS1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GAMNCONST
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: GM1
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IPHYS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: JTOT_TAUHF
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    LOGICAL, VALUE, INTENT(IN) :: LLNORMAGAM
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NANG
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NFRE
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NWAV_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: SQRTGOSURFT
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: TAUWSHELTER
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: X0TAUHF
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XLOGKRATIOM1_GC
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZALP
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM1
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ZPI4GM2
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE STRESSO_iso_c (KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF,  &
      & SINWDIF2, TAUW, TAUWDIR, PHIWA, LLPHIWA, COSTH, DELTH, EPS1, FR5, G, GAMNCONST, GM1, IPHYS, JTOT_TAUHF, LLGCBZ0,  &
      & LLNORMAGAM, NANG, NFRE, NWAV_GC, OMEGA_GC, RHOWG_DFIM, SINTH, SQRTGOSURFT, TAUWSHELTER, WTAUHF, X0TAUHF, XKAPPA, XKM_GC,  &
      & XK_GC, XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, ZPIFR, ICHNK, NCHNK, IJ, XSTRESS, YSTRESS, TAUHF, PHIHF, CMRHOWGDFTH,  &
      & US2, TAUX, TAUY, TAUPX, TAUPY, USDIRP, UST, SUMT, SUMX, SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS,  &
      & TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0,  &
      & TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI,  &
      & TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2) BIND(c, name="stresso_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: MIJ
        TYPE(c_ptr), VALUE :: RHOWGDFTH
        TYPE(c_ptr), VALUE :: FL1
        TYPE(c_ptr), VALUE :: SL
        TYPE(c_ptr), VALUE :: SPOS
        TYPE(c_ptr), VALUE :: CINV
        TYPE(c_ptr), VALUE :: WDWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: AIRD
        TYPE(c_ptr), VALUE :: RNFAC
        TYPE(c_ptr), VALUE :: COSWDIF
        TYPE(c_ptr), VALUE :: SINWDIF2
        TYPE(c_ptr), VALUE :: TAUW
        TYPE(c_ptr), VALUE :: TAUWDIR
        TYPE(c_ptr), VALUE :: PHIWA
        LOGICAL, VALUE :: LLPHIWA
        TYPE(c_ptr), VALUE :: COSTH
        REAL, VALUE :: DELTH
        REAL, VALUE :: EPS1
        TYPE(c_ptr), VALUE :: FR5
        REAL, VALUE :: G
        REAL, VALUE :: GAMNCONST
        REAL, VALUE :: GM1
        INTEGER(KIND=c_int), VALUE :: IPHYS
        INTEGER(KIND=c_int), VALUE :: JTOT_TAUHF
        LOGICAL, VALUE :: LLGCBZ0
        LOGICAL, VALUE :: LLNORMAGAM
        INTEGER(KIND=c_int), VALUE :: NANG
        INTEGER(KIND=c_int), VALUE :: NFRE
        INTEGER(KIND=c_int), VALUE :: NWAV_GC
        TYPE(c_ptr), VALUE :: OMEGA_GC
        TYPE(c_ptr), VALUE :: RHOWG_DFIM
        TYPE(c_ptr), VALUE :: SINTH
        REAL, VALUE :: SQRTGOSURFT
        REAL, VALUE :: TAUWSHELTER
        TYPE(c_ptr), VALUE :: WTAUHF
        REAL, VALUE :: X0TAUHF
        REAL, VALUE :: XKAPPA
        TYPE(c_ptr), VALUE :: XKM_GC
        TYPE(c_ptr), VALUE :: XK_GC
        REAL, VALUE :: XLOGKRATIOM1_GC
        REAL, VALUE :: ZALP
        REAL, VALUE :: ZPI4GM1
        REAL, VALUE :: ZPI4GM2
        TYPE(c_ptr), VALUE :: ZPIFR
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
        TYPE(c_ptr), VALUE :: XSTRESS
        TYPE(c_ptr), VALUE :: YSTRESS
        TYPE(c_ptr), VALUE :: TAUHF
        TYPE(c_ptr), VALUE :: PHIHF
        TYPE(c_ptr), VALUE :: CMRHOWGDFTH
        TYPE(c_ptr), VALUE :: US2
        TYPE(c_ptr), VALUE :: TAUX
        TYPE(c_ptr), VALUE :: TAUY
        TYPE(c_ptr), VALUE :: TAUPX
        TYPE(c_ptr), VALUE :: TAUPY
        TYPE(c_ptr), VALUE :: USDIRP
        TYPE(c_ptr), VALUE :: UST
        TYPE(c_ptr), VALUE :: SUMT
        TYPE(c_ptr), VALUE :: SUMX
        TYPE(c_ptr), VALUE :: SUMY
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_NS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XKS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_OMS
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTZ0OG
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZSUP
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_ZINF
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_DELZ
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_TAUL
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_XLOGGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_SQRTGZ0
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_USTPH
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST1
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONST2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTTAU
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_CONSTPHI
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS2
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DCOS3
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1D
        TYPE(c_ptr), VALUE :: TAU_PHI_HF_F1DSIN2
      END SUBROUTINE STRESSO_iso_c
    END INTERFACE
    INTEGER(KIND=JWIM), TARGET, INTENT(IN) :: MIJ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FL1(:, :, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SL(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SPOS(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: CINV(:, :, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WDWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: AIRD(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RNFAC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSWDIF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINWDIF2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: TAUW(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: TAUWDIR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: PHIWA(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: COSTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: FR5(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: OMEGA_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: RHOWG_DFIM(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: SINTH(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WTAUHF(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XKM_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: XK_GC(:)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: ZPIFR(:)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: XSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: YSTRESS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: PHIHF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: CMRHOWGDFTH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: US2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUPX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAUPY(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: USDIRP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: UST(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMT(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMX(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: SUMY(:, :)
    INTEGER(KIND=JWIM), TARGET, INTENT(INOUT) :: TAU_PHI_HF_NS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XKS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_OMS(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTZ0OG(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZSUP(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_ZINF(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_DELZ(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_TAUL(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_XLOGGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_SQRTGZ0(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_USTPH(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST1(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONST2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTTAU(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_CONSTPHI(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS2(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DCOS3(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1D(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(INOUT) :: TAU_PHI_HF_F1DSIN2(:, :)
!$acc host_data use_device( MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2, TAUW,  &
!$acc & TAUWDIR, PHIWA, COSTH, FR5, OMEGA_GC, RHOWG_DFIM, SINTH, WTAUHF, XKM_GC, XK_GC, ZPIFR, XSTRESS, YSTRESS, TAUHF, PHIHF,  &
!$acc & CMRHOWGDFTH, US2, TAUX, TAUY, TAUPX, TAUPY, USDIRP, UST, SUMT, SUMX, SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS,  &
!$acc & TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF, TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL,  &
!$acc & TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1, TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU,  &
!$acc & TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D, TAU_PHI_HF_F1DSIN2 )
    CALL STRESSO_iso_c(KIJS, KIJL, c_loc(MIJ), c_loc(RHOWGDFTH), c_loc(FL1), c_loc(SL), c_loc(SPOS), c_loc(CINV), c_loc(WDWAVE),  &
    & c_loc(UFRIC), c_loc(Z0M), c_loc(AIRD), c_loc(RNFAC), c_loc(COSWDIF), c_loc(SINWDIF2), c_loc(TAUW), c_loc(TAUWDIR),  &
    & c_loc(PHIWA), LLPHIWA, c_loc(COSTH), DELTH, EPS1, c_loc(FR5), G, GAMNCONST, GM1, IPHYS, JTOT_TAUHF, LLGCBZ0, LLNORMAGAM,  &
    & NANG, NFRE, NWAV_GC, c_loc(OMEGA_GC), c_loc(RHOWG_DFIM), c_loc(SINTH), SQRTGOSURFT, TAUWSHELTER, c_loc(WTAUHF), X0TAUHF,  &
    & XKAPPA, c_loc(XKM_GC), c_loc(XK_GC), XLOGKRATIOM1_GC, ZALP, ZPI4GM1, ZPI4GM2, c_loc(ZPIFR), ICHNK, NCHNK, IJ,  &
    & c_loc(XSTRESS), c_loc(YSTRESS), c_loc(TAUHF), c_loc(PHIHF), c_loc(CMRHOWGDFTH), c_loc(US2), c_loc(TAUX), c_loc(TAUY),  &
    & c_loc(TAUPX), c_loc(TAUPY), c_loc(USDIRP), c_loc(UST), c_loc(SUMT), c_loc(SUMX), c_loc(SUMY), c_loc(TAU_PHI_HF_NS),  &
    & c_loc(TAU_PHI_HF_XKS), c_loc(TAU_PHI_HF_OMS), c_loc(TAU_PHI_HF_SQRTZ0OG), c_loc(TAU_PHI_HF_ZSUP), c_loc(TAU_PHI_HF_ZINF),  &
    & c_loc(TAU_PHI_HF_DELZ), c_loc(TAU_PHI_HF_TAUL), c_loc(TAU_PHI_HF_XLOGGZ0), c_loc(TAU_PHI_HF_SQRTGZ0),  &
    & c_loc(TAU_PHI_HF_USTPH), c_loc(TAU_PHI_HF_CONST1), c_loc(TAU_PHI_HF_CONST2), c_loc(TAU_PHI_HF_CONSTTAU),  &
    & c_loc(TAU_PHI_HF_CONSTPHI), c_loc(TAU_PHI_HF_F1DCOS2), c_loc(TAU_PHI_HF_F1DCOS3), c_loc(TAU_PHI_HF_F1D),  &
    & c_loc(TAU_PHI_HF_F1DSIN2))
!$acc end host_data
  END SUBROUTINE STRESSO_fc
END MODULE STRESSO_FC_MOD
