

__device__ void stresso_c(int kijs, int kijl, const int * __restrict__ mij, 
  const double * __restrict__ rhowgdfth, const double * __restrict__ fl1, 
  const double * __restrict__ sl, const double * __restrict__ spos, 
  const double * __restrict__ cinv, const double * __restrict__ wdwave, 
  const double * __restrict__ ufric, const double * __restrict__ z0m, 
  const double * __restrict__ aird, const double * __restrict__ rnfac, 
  const double * __restrict__ coswdif, const double * __restrict__ sinwdif2, 
  double * __restrict__ tauw, double * __restrict__ tauwdir, 
  double * __restrict__ phiwa, int llphiwa, const double * __restrict__ costh, 
  double delth, double eps1, const double * __restrict__ fr5, double g, 
  double gamnconst, double gm1, int iphys, int jtot_tauhf, int llgcbz0, int llnormagam, 
  int nang, int nfre, int nwav_gc, const double * __restrict__ omega_gc, 
  const double * __restrict__ rhowg_dfim, const double * __restrict__ sinth, 
  double sqrtgosurft, double tauwshelter, const double * __restrict__ wtauhf, 
  double x0tauhf, double xkappa, const double * __restrict__ xkm_gc, 
  const double * __restrict__ xk_gc, double xlogkratiom1_gc, double zalp, 
  double zpi4gm1, double zpi4gm2, const double * __restrict__ zpifr, int ichnk, 
  int nchnk, int ij, double * __restrict__ xstress, double * __restrict__ ystress, 
  double * __restrict__ tauhf, double * __restrict__ phihf, 
  double * __restrict__ cmrhowgdfth, double * __restrict__ us2, 
  double * __restrict__ taux, double * __restrict__ tauy, double * __restrict__ taupx, 
  double * __restrict__ taupy, double * __restrict__ usdirp, double * __restrict__ ust, 
  double * __restrict__ sumt, double * __restrict__ sumx, double * __restrict__ sumy, 
  int * __restrict__ tau_phi_hf_ns, double * __restrict__ tau_phi_hf_xks, 
  double * __restrict__ tau_phi_hf_oms, double * __restrict__ tau_phi_hf_sqrtz0og, 
  double * __restrict__ tau_phi_hf_zsup, double * __restrict__ tau_phi_hf_zinf, 
  double * __restrict__ tau_phi_hf_delz, double * __restrict__ tau_phi_hf_taul, 
  double * __restrict__ tau_phi_hf_xloggz0, double * __restrict__ tau_phi_hf_sqrtgz0, 
  double * __restrict__ tau_phi_hf_ustph, double * __restrict__ tau_phi_hf_const1, 
  double * __restrict__ tau_phi_hf_const2, double * __restrict__ tau_phi_hf_consttau, 
  double * __restrict__ tau_phi_hf_constphi, double * __restrict__ tau_phi_hf_f1dcos2, 
  double * __restrict__ tau_phi_hf_f1dcos3, double * __restrict__ tau_phi_hf_f1d, 
  double * __restrict__ tau_phi_hf_f1dsin2);
