! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
SUBROUTINE WAMINTGR_LOKI_GPU (CDTPRA, CDATE, CDATEWH, CDTIMP, CDTIMPNEXT, BLK2GLO, WVENVI, WVPRPT, FF_NOW, FF_NEXT, INTFLDS,  &
& WAM2NEMO, MIJ, FL1, XLLWS)
  
  
  ! ----------------------------------------------------------------------
  
  !**** *WAMINTGR* - 3-G WAM MODEL - TIME INTEGRATION OF WAVE FIELDS.
  
  !*    PURPOSE.
  !     --------
  
  !       COMPUTATION OF THE 2-D FREQUENCY-DIRECTION WAVE SPECTRUM AT ALL
  !       GRID POINTS FOR A GIVEN INITIAL SPECTRUM AND FORCING SURFACE
  !       STRESS FIELD.
  
  !     REFERENCE.
  !     ----------
  
  !         IFS DOCUMENTATION, part VII
  
  ! -------------------------------------------------------------------
  
  USE IMPLSCH_FC_MOD, ONLY: IMPLSCH_FC
  ![Loki::GlobalVarHoistTransformation] -------- Added global variable imports for offload directives -----------
  USE yowstat, ONLY: LBIWBK, IPHYS, IDAMPING, ISNONLIN
  USE yowparam, ONLY: LLUNSTR, NFRE_RED, NFRE_ODD
  USE yowtabl, ONLY: EPS1, IAB, SWELLFT
  USE yowwndg, ONLY: ICODE_CPL, ICODE
  USE yowshal, ONLY: XKDMIN, BATHYMAX
  USE yowwind, ONLY: WSPMIN
  USE yowcoup, ONLY: LWFLUX, LWCOUAST, LWNEMOCOUSTK, LWNEMOCOUSEND, LLGCBZ0, LWNEMOTAUOC, LWCOU, JTOT_TAUHF, LLCAPCHNK,  &
  & LWVFLX_SNL, LLNORMAGAM, LWNEMOCOUSTRN, X0TAUHF, WTAUHF
  USE yowindn, ONLY: INLCOEF, KFRH, K1W, IKM1, IKM, K11W, FKLAP1, K21W, RNLCOEF, AF11, FKLAM, IKP1, MFRSTLW, FKLAP, IKP, K2W,  &
  & DAL1, MLSTHG, DAL2, FKLAM1
  USE yowaltas, ONLY: AFCRV, EGRCRV, BFCRV
  USE yowcout, ONLY: LWFLUXOUT
  USE yowfred, ONLY: FR5, ZPIFR, DFIM_SIM, WP2TAIL, DFIMOFR, FLOGSPRDM1, WETAIL, XLOGKRATIOM1_GC, DELTH, SINTH, C2OSQRTVG_GC,  &
  & CM_GC, COSTH, XKM_GC, FRTAIL, DFIMFR2, OM3GMKM_GC, RHOWG_DFIM, OMXKM3_GC, OMEGA_GC, DELKCC_GC_NS, COFRM4, WP1TAIL, FLMAX,  &
  & DELKCC_OMXKM3_GC, FR, FRIC, DFIM, DFIMFR, NWAV_GC, TH, XK_GC, FRATIO, XKMSQRTVGOC2_GC
  USE yowpcons, ONLY: BCD, ROWATER, CDMAX, EPSUS, ZPI, ROWATERM1, G, SQRTGOSURFT, PHIEPSMAX, ZPI4GM1, ACD, GM1, WSEMEAN_MIN,  &
  & TAUOCMIN, TAUOCMAX, ACDLIN, BCDLIN, PHIEPSMIN, ZPI4GM2, DKMAX, EPSU10
  USE yowice, ONLY: FLMIN, CITHRSH, LMASKICE, CIBLOCK, CDICWA, LWAMRSETCI, CITHRSH_TAIL, LICERUN, LCIWABR
  USE yowphys, ONLY: SSDSC3, MICHE, BMAXOKAP, TAILFACTOR, ANG_GC_B, ZALP, DELTA_SDIS, SWELLF5, DTHRN_U, ANG_GC_C, RN1_RN,  &
  & ALPHAMAX, ABMIN, XNLEV, SSDSC4, SWELLF7, GAMNCONST, SWELLF, SWELLF2, ABMAX, RNUM, SWELLF6, SATWEIGHTS, SWELLF4, SDSBR,  &
  & SSDSC2, CHNKMIN_U, IPSAT, DTHRN_A, CDISVIS, TAUWSHELTER, SWELLF7M1, Z0RAT, BRKPBCOEF, Z0TUBMAX, TAILFACTOR_PM, CDIS,  &
  & INDICESSAT, SSDSBRF1, ALPHAPMAX, XKAPPA, SSDSC5, SSDSC6, SWELLF3, ANG_GC_A, ALPHAMIN, RNU, BETAMAXOXKAPPA2, ALPHA, NSDSNTH
  ![Loki::GlobalVarHoistTransformation] ---------------------------------------
  USE PARKIND_WAVE, ONLY: JWIM, JWRB, JWRU, JWRO
  USE YOWDRVTYPE, ONLY: WVGRIDGLO, ENVIRONMENT, FREQUENCY, FORCING_FIELDS, INTGT_PARAM_FIELDS, WAVE2OCEAN
  
  USE YOWCOUP, ONLY: LWNEMOCOU, NEMONTAU
  USE YOWGRID, ONLY: NPROMA_WAM, NCHNK
  USE YOWPARAM, ONLY: NANG, NFRE
  USE YOWPCONS, ONLY: EPSMIN
  USE YOWSTAT, ONLY: CDTPRO, IDELPRO, IDELT, IDELWI, LLSOURCE, TIME_PROPAG, TIME_PHYS, TIME_OFFLOAD
  USE YOWWIND, ONLY: CDAWIFL, CDATEWO, CDATEFL
  USE YOWFIELD_MOD, ONLY: FREQUENCY_FIELD, ENVIRONMENT_FIELD, FORCING_FIELDS_FIELD, WAVE2OCEAN_FIELD, INTGT_PARAM_FIELDS_FIELD,  &
  & SOURCE_CONTRIBS_FIELD
  
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  
  ! ----------------------------------------------------------------------
  
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE INCDATE (CDATE, ISHIFT)
      USE parkind_wave, ONLY: jwim
      INTEGER(KIND=JWIM), INTENT(IN) :: ISHIFT
      CHARACTER(LEN=*), INTENT(INOUT) :: CDATE
    END SUBROUTINE INCDATE
  END INTERFACE
  INTERFACE
    SUBROUTINE NEWWIND (CDATE, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
      USE YOWDRVTYPE, ONLY: FREQUENCY, FORCING_FIELDS
      CHARACTER(LEN=14), INTENT(IN) :: CDATE
      CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH
      LOGICAL, INTENT(INOUT) :: LLNEWFILE
      TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW
      TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT
    END SUBROUTINE NEWWIND
  END INTERFACE
  INTERFACE
    SUBROUTINE PROPAG_WAM (BLK2GLO, WAVNUM, CGROUP, OMOSNH2KD, FL1, DEPTH, DELLAM1, COSPHM1, UCUR, VCUR)
      USE parkind_wave, ONLY: jwrb
      USE yowdrvtype, ONLY: wvgridglo
      USE yowgrid, ONLY: nproma_wam, nchnk
      USE yowparam, ONLY: nang, nfre
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK) :: FL1
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NFRE, NCHNK) :: WAVNUM, CGROUP, OMOSNH2KD
      REAL(KIND=JWRB), INTENT(IN), DIMENSION(NPROMA_WAM, NCHNK) :: DEPTH, DELLAM1, COSPHM1, UCUR, VCUR
    END SUBROUTINE PROPAG_WAM
  END INTERFACE
  INTERFACE
    FUNCTION WAM_USER_CLOCK ()
      USE parkind_wave, ONLY: jwru
      REAL(KIND=JWRU) :: WAM_USER_CLOCK
    END FUNCTION WAM_USER_CLOCK
  END INTERFACE
  CHARACTER(LEN=14), INTENT(IN) :: CDTPRA  ! DATE FOR CALL PROPAGATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATE  ! CURRENT DATE
  CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH  ! DATE OF THE NEXT FORCING FIELDS
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMP  ! START DATE OF SOURCE FUNCTION INTEGRATION
  CHARACTER(LEN=14), INTENT(INOUT) :: CDTIMPNEXT  ! NEXT START DATE OF SOURCE FUNCTION INTEGRATION
  TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO  ! BLOCK TO GRID TRANSFORMATION
  TYPE(ENVIRONMENT), INTENT(INOUT) :: WVENVI  !  WAVE ENVIRONMENT FIELDS
  TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT  ! WAVE PROPERTIES FIELDS
  TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW  ! FORCING FIELDS AT CURRENT TIME
  TYPE(FORCING_FIELDS), INTENT(IN) :: FF_NEXT  !  DATA STRUCTURE WITH THE NEXT FORCING FIELDS
  TYPE(INTGT_PARAM_FIELDS), INTENT(INOUT) :: INTFLDS  ! INTEGRATED/DERIVED PARAMETERS
  TYPE(WAVE2OCEAN), INTENT(INOUT) :: WAM2NEMO  ! WAVE FIELDS PASSED TO NEMO
  INTEGER(KIND=JWIM), INTENT(INOUT), DIMENSION(NPROMA_WAM, NCHNK) :: MIJ  ! LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE
  REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK) :: FL1
  REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(NPROMA_WAM, NANG, NFRE, NCHNK) :: XLLWS  ! TOTAL WINDSEA MASK FROM INPUT SOURCE TERM
  
  REAL(KIND=JWRB) :: TIME0
  
  
  INTEGER(KIND=JWIM) :: IJ, K, M
  INTEGER(KIND=JWIM) :: ICHNK
  INTEGER(KIND=JWIM) :: IDELWH
  
  ! Objects to store fields
  TYPE(FREQUENCY_FIELD) :: WVPRPT_FIELD
  TYPE(ENVIRONMENT_FIELD) :: WVENVI_FIELD
  TYPE(FORCING_FIELDS_FIELD) :: FF_NOW_FIELD
  TYPE(WAVE2OCEAN_FIELD) :: WAM2NEMO_FIELD
  TYPE(INTGT_PARAM_FIELDS_FIELD) :: INTFLDS_FIELD
  TYPE(SOURCE_CONTRIBS_FIELD) :: SRC_CONTRIBS
  
  ! DEVICE POINTERS
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: FL1_DPTR(:, :, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XLLWS_DPTR(:, :, :, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: MIJ_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WAVNUM_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CGROUP_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: OMOSNH2KD_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CIWA_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CINV_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: XK2CG_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STOKFAC_DPTR(:, :, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: EMAXDPT_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DEPTH_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: DELLAM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: COSPHM1_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UCUR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VCUR_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IOBND_DPTR(:, :) => NULL()
  INTEGER(KIND=JWIM), POINTER, CONTIGUOUS :: IODP_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CICOVER_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WDWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: AIRD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSTAR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: UFRIC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUW_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUWDIR_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0M_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: Z0B_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CHRNCK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: CITHICK_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTRA_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTRA_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOUSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOVSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOSTRN_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NPHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NTAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NSWH_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NMWP_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOTAUX_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOTAUY_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOWSWAVE_DPTR(:, :) => NULL()
  REAL(KIND=JWRO), POINTER, CONTIGUOUS :: NEMOPHIF_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSEMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: WSFMEAN_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: USTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: VSTOKES_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: STRNMS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCXD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOCYD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: TAUOC_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIOCD_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIEPS_DPTR(:, :) => NULL()
  REAL(KIND=JWRB), POINTER, CONTIGUOUS :: PHIAW_DPTR(:, :) => NULL()
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  
  LOGICAL, SAVE :: LLNEWFILE
  
  DATA LLNEWFILE / .false. /
  INTEGER :: istat
  REAL(KIND=JWRB) :: IMPLSCH_DELFL(NFRE)
  REAL(KIND=JWRB) :: IMPLSCH_RAORW(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_EMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_HALP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_EMEANWS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FMEANWS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_USFM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_F1MEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_AKMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_XKMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_PHIWA(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FLM(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_COSWDIF(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SINWDIF2(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_TEMP(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_RHOWGDFTH(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_FLD(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SL(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SPOS(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_CIREDUC(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: IMPLSCH_SSOURCE(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: FEMEANWS_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: FEMEANWS_EM_LOC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: FKMEAN_TEMPA(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: FKMEAN_TEMPX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: FKMEAN_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SBOTTOM_SBO(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPHFTAIL_TEMP1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: IMPHFTAIL_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDEPTHLIM_EM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SEMEAN_TEMP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_FACTURB(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_FACSAT(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_FACWTRB(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_TEMP1(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_BTH0(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_C_(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_C_C(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_DSIP(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_TRPZ_DSIP(NPROMA_WAM, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_BTH(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_TEMP2(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_D(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_SCUMUL(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_RENEWALFREQ(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_ARD_WCUMUL(NPROMA_WAM, 0:NANG / 2, NFRE, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_JAN_TEMP1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_JAN_SDS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_JAN_X(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDISSIP_JAN_XK2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SDIWBK_SDS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SETICE_CIREDUC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SETICE_TEMP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SETICE_ICEFREE(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINFLX_RNFAC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINFLX_TMP_EM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_ALPHAOG(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_XMIN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_W1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_TAUWACT(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_TAUWEFF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_ANG_GC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAUT_Z0_TAUUNR(NPROMA_WAM, NCHNK)
  LOGICAL :: TAUT_Z0_LLCOSDIFF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESS_GC_GAM_W(NWAV_GC)
  REAL(KIND=JWRB) :: Z0WAVE_ALPHAOG(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_ALPHAP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_XMSS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_EM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_FM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_F1D(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_WD(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: HALPHAP_FLWD(NPROMA_WAM, NANG, NFRE, NCHNK)
  REAL(KIND=JWRB) :: FEMEAN_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: MEANSQS_LF_FD(NFRE)
  REAL(KIND=JWRB) :: MEANSQS_LF_TEMP1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: MEANSQS_LF_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_CONSTF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_CONST11(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_CONST22(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_Z0VIS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_Z0NOZ(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_FWW(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_PVISC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_PTURB(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_ZCN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_SIG_N(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_UORBT(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_AORB(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_TEMP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_RE(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_RE_C(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_ZORB(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_CNSN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_SUMF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_SUMFSIN2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_CSTRNFAC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_FLP_AVG(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_SLP_AVG(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_ROGOROAIR(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_AIRD_PVISC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_XSTRESS(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_YSTRESS(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_FLP(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_SLP(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_USG2(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_TAUX(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_TAUY(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_USTP(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_USTPM1(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_USDIRP(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_UCN(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_UCNZALPD(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_XNGAMCONST(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_GAMNORMA(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_DSTAB1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_TEMP1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_TEMP2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_GAM0(NPROMA_WAM, NANG, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_DSTAB(NPROMA_WAM, NANG, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_ARD_COSLP(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_ZTANHKD(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_SIG_N(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_CNSN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_SUMF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_SUMFSIN2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_CSTRNFAC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_XNGAMCONST(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_GAMNORMA(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_SIGDEV(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_US(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_Z0(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_UCN(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_ZCN(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_USTPM1(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_XVD(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_UCND(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_CONST3_UCN2(NPROMA_WAM, 2, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_UFAC1(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_UFAC2(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_TEMPD(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: SINPUT_JAN_GAM0(NPROMA_WAM, NANG, 2, NCHNK)
  LOGICAL :: SINPUT_JAN_LZ(NPROMA_WAM, NANG, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_XSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_YSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUHF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_PHIHF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_CMRHOWGDFTH(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_US2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUY(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUPX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_TAUPY(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_USDIRP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_UST(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_SUMT(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_SUMX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STRESSO_SUMY(NPROMA_WAM, NCHNK)
  INTEGER(KIND=JWIM) :: TAU_PHI_HF_NS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_XKS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_OMS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_SQRTZ0OG(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_ZSUP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_ZINF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_DELZ(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_TAUL(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_XLOGGZ0(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_SQRTGZ0(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_USTPH(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_CONST1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_CONST2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_CONSTTAU(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_CONSTPHI(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_F1DCOS2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_F1DCOS3(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_F1D(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: TAU_PHI_HF_F1DSIN2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_ENH(NPROMA_WAM, MLSTHG, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_XNU(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_SIG_TH(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_FTEMP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_AD(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_DELAD(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_DELAP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_DELAM(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: SNONLIN_ENHFR(NPROMA_WAM, NCHNK)
  INTEGER(KIND=JWIM) :: PEAK_ANG_MMAX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_SUM0(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_SUM1(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_SUM2(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_XMAX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_TEMP(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_THMEAN(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_SUM_S(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: PEAK_ANG_SUM_C(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: CIMSSTRN_XKI(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: CIMSSTRN_E(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: CIMSSTRN_SUME(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: STOKESDRIFT_STFAC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_XSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_YSTRESS(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_USTAR(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_PHILF(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_OOVAL(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_EM_OC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_F1_OC(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_CMRHOWGDFTH(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_SUMT(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_SUMX(NPROMA_WAM, NCHNK)
  REAL(KIND=JWRB) :: WNFLUXES_SUMY(NPROMA_WAM, NCHNK)
  
!$acc enter data create( IMPLSCH_DELFL, IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP, IMPLSCH_EMEANWS,  &
!$acc & IMPLSCH_FMEANWS, IMPLSCH_USFM, IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA, IMPLSCH_FLM,  &
!$acc & IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2, IMPLSCH_TEMP, IMPLSCH_RHOWGDFTH, IMPLSCH_FLD, IMPLSCH_SL, IMPLSCH_SPOS,  &
!$acc & IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, FKMEAN_TEMPA, FKMEAN_TEMPX, FKMEAN_TEMP2,  &
!$acc & SBOTTOM_SBO, IMPHFTAIL_TEMP1, IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP, SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT,  &
!$acc & SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP,  &
!$acc & SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ,  &
!$acc & SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2, SDIWBK_SDS, SETICE_CIREDUC,  &
!$acc & SETICE_TEMP, SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT,  &
!$acc & TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, HALPHAP_ALPHAP,  &
!$acc & HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
!$acc & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS,  &
!$acc & SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N,  &
!$acc & SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN,  &
!$acc & SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR,  &
!$acc & SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2,  &
!$acc & SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
!$acc & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
!$acc & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN,  &
!$acc & SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
!$acc & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
!$acc & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
!$acc & SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2,  &
!$acc & STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX,  &
!$acc & STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF,  &
!$acc & TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1,  &
!$acc & TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D,  &
!$acc & TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH, SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD, SNONLIN_DELAP,  &
!$acc & SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0, PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX, PEAK_ANG_TEMP,  &
!$acc & PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI, CIMSSTRN_E, CIMSSTRN_SUME, STOKESDRIFT_STFAC,  &
!$acc & WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF, WNFLUXES_OOVAL, WNFLUXES_EM_OC, WNFLUXES_F1_OC,  &
!$acc & WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY )
  
  
  ! ----------------------------------------------------------------------
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 0, ZHOOK_HANDLE)
  
  !*     PROPAGATION TIME
  !      ----------------
  
  TIME0 = -WAM_USER_CLOCK()
  CALL SRC_CONTRIBS%INIT(FL1=FL1)
  CALL SRC_CONTRIBS%UPDATE_DEVICE(FL1=FL1_DPTR)
  CALL WVPRPT_FIELD%INIT(WAVNUM=WVPRPT%WAVNUM, CGROUP=WVPRPT%CGROUP, OMOSNH2KD=WVPRPT%OMOSNH2KD)
  CALL WVPRPT_FIELD%UPDATE_DEVICE(WAVNUM=WAVNUM_DPTR, CGROUP=CGROUP_DPTR, OMOSNH2KD=OMOSNH2KD_DPTR)
  CALL WVENVI_FIELD%INIT(DEPTH=WVENVI%DEPTH, DELLAM1=WVENVI%DELLAM1, COSPHM1=WVENVI%COSPHM1, UCUR=WVENVI%UCUR, VCUR=WVENVI%VCUR)
  CALL WVENVI_FIELD%UPDATE_DEVICE(DEPTH=DEPTH_DPTR, DELLAM1=DELLAM1_DPTR, COSPHM1=COSPHM1_DPTR, UCUR=UCUR_DPTR, VCUR=VCUR_DPTR)
  TIME_OFFLOAD = TIME_OFFLOAD + (TIME0 + WAM_USER_CLOCK())*1.E-06
  
  IF (CDATE == CDTPRA) THEN
    TIME0 = -WAM_USER_CLOCK()
    CALL PROPAG_WAM(BLK2GLO, WAVNUM_DPTR, CGROUP_DPTR, OMOSNH2KD_DPTR, FL1_DPTR, DEPTH_DPTR, DELLAM1_DPTR, COSPHM1_DPTR,  &
    & UCUR_DPTR, VCUR_DPTR)
    TIME_PROPAG = TIME_PROPAG + (TIME0 + WAM_USER_CLOCK())*1.E-06
    CDATE = CDTPRO
  END IF
  
  !* RETRIEVING NEW FORCING FIELDS IF NEEDED.
  !  ----------------------------------------
  CALL NEWWIND(CDTIMP, CDATEWH, LLNEWFILE, WVPRPT, FF_NOW, FF_NEXT)
  
  ! IT IS TIME TO INTEGRATE THE SOURCE TERMS
  ! ----------------------------------------
  IF (CDATE >= CDTIMPNEXT) THEN
    ! COMPUTE UPDATE DUE TO SOURCE TERMS
    CALL GSTATS(1431, 0)
    IF (LLSOURCE) THEN
      
      TIME0 = -WAM_USER_CLOCK()
      CALL WVPRPT_FIELD%INIT(CIWA=WVPRPT%CIWA, CINV=WVPRPT%CINV, XK2CG=WVPRPT%XK2CG, STOKFAC=WVPRPT%STOKFAC)
      CALL WVENVI_FIELD%INIT(EMAXDPT=WVENVI%EMAXDPT, IOBND=WVENVI%IOBND, IODP=WVENVI%IODP)
      CALL FF_NOW_FIELD%INIT(AIRD=FF_NOW%AIRD, WDWAVE=FF_NOW%WDWAVE, CICOVER=FF_NOW%CICOVER, WSWAVE=FF_NOW%WSWAVE,  &
      & WSTAR=FF_NOW%WSTAR, UFRIC=FF_NOW%UFRIC, TAUW=FF_NOW%TAUW, TAUWDIR=FF_NOW%TAUWDIR, Z0M=FF_NOW%Z0M, Z0B=FF_NOW%Z0B,  &
      & CHRNCK=FF_NOW%CHRNCK, CITHICK=FF_NOW%CITHICK, USTRA=FF_NOW%USTRA, VSTRA=FF_NOW%VSTRA)
      CALL WAM2NEMO_FIELD%INIT(NEMOUSTOKES=WAM2NEMO%NEMOUSTOKES, NEMOVSTOKES=WAM2NEMO%NEMOVSTOKES, NEMOSTRN=WAM2NEMO%NEMOSTRN,  &
      & NPHIEPS=WAM2NEMO%NPHIEPS, NTAUOC=WAM2NEMO%NTAUOC, NSWH=WAM2NEMO%NSWH, NMWP=WAM2NEMO%NMWP, NEMOTAUX=WAM2NEMO%NEMOTAUX,  &
      & NEMOTAUY=WAM2NEMO%NEMOTAUY, NEMOWSWAVE=WAM2NEMO%NEMOWSWAVE, NEMOPHIF=WAM2NEMO%NEMOPHIF)
      CALL INTFLDS_FIELD%INIT(WSEMEAN=INTFLDS%WSEMEAN, WSFMEAN=INTFLDS%WSFMEAN, USTOKES=INTFLDS%USTOKES,  &
      & VSTOKES=INTFLDS%VSTOKES, STRNMS=INTFLDS%STRNMS, TAUXD=INTFLDS%TAUXD, TAUYD=INTFLDS%TAUYD, TAUOCXD=INTFLDS%TAUOCXD,  &
      & TAUOCYD=INTFLDS%TAUOCYD, TAUOC=INTFLDS%TAUOC, PHIOCD=INTFLDS%PHIOCD, PHIEPS=INTFLDS%PHIEPS, PHIAW=INTFLDS%PHIAW)
      CALL SRC_CONTRIBS%INIT(XLLWS=XLLWS, MIJ=MIJ)
      TIME_OFFLOAD = TIME_OFFLOAD + (TIME0 + WAM_USER_CLOCK())*1.E-06
      
      
      CALL WVPRPT_FIELD%UPDATE_DEVICE(CIWA=CIWA_DPTR, CINV=CINV_DPTR, XK2CG=XK2CG_DPTR, STOKFAC=STOKFAC_DPTR)
      CALL WVENVI_FIELD%UPDATE_DEVICE(EMAXDPT=EMAXDPT_DPTR, IOBND=IOBND_DPTR, IODP=IODP_DPTR)
      CALL FF_NOW_FIELD%UPDATE_DEVICE(AIRD=AIRD_DPTR, WDWAVE=WDWAVE_DPTR, CICOVER=CICOVER_DPTR, WSWAVE=WSWAVE_DPTR,  &
      & WSTAR=WSTAR_DPTR, UFRIC=UFRIC_DPTR, TAUW=TAUW_DPTR, TAUWDIR=TAUWDIR_DPTR, Z0M=Z0M_DPTR, Z0B=Z0B_DPTR,  &
      & CHRNCK=CHRNCK_DPTR, CITHICK=CITHICK_DPTR, USTRA=USTRA_DPTR, VSTRA=VSTRA_DPTR)
      CALL WAM2NEMO_FIELD%UPDATE_DEVICE(NEMOUSTOKES=NEMOUSTOKES_DPTR, NEMOVSTOKES=NEMOVSTOKES_DPTR, NEMOSTRN=NEMOSTRN_DPTR,  &
      & NPHIEPS=NPHIEPS_DPTR, NTAUOC=NTAUOC_DPTR, NSWH=NSWH_DPTR, NMWP=NMWP_DPTR, NEMOTAUX=NEMOTAUX_DPTR,  &
      & NEMOTAUY=NEMOTAUY_DPTR, NEMOWSWAVE=NEMOWSWAVE_DPTR, NEMOPHIF=NEMOPHIF_DPTR)
      CALL INTFLDS_FIELD%UPDATE_DEVICE(WSEMEAN=WSEMEAN_DPTR, WSFMEAN=WSFMEAN_DPTR, USTOKES=USTOKES_DPTR, VSTOKES=VSTOKES_DPTR,  &
      & STRNMS=STRNMS_DPTR, TAUXD=TAUXD_DPTR, TAUYD=TAUYD_DPTR, TAUOCXD=TAUOCXD_DPTR, TAUOCYD=TAUOCYD_DPTR, TAUOC=TAUOC_DPTR,  &
      & PHIOCD=PHIOCD_DPTR, PHIEPS=PHIEPS_DPTR, PHIAW=PHIAW_DPTR)
      CALL SRC_CONTRIBS%UPDATE_DEVICE(XLLWS=XLLWS_DPTR, MIJ=MIJ_DPTR)
      
!$acc data present( wavnum_dptr, cgroup_dptr, ciwa_dptr, cinv_dptr, xk2cg_dptr, stokfac_dptr, emaxdpt_dptr, depth_dptr,  &
!$acc & iobnd_dptr, iodp_dptr, mij_dptr, xllws_dptr, fl1_dptr, aird_dptr, wdwave_dptr, cicover_dptr, wswave_dptr, wstar_dptr,  &
!$acc & ustra_dptr, vstra_dptr, ufric_dptr, tauw_dptr, tauwdir_dptr, z0m_dptr, z0b_dptr, chrnck_dptr, cithick_dptr,  &
!$acc & nemoustokes_dptr, nemovstokes_dptr, nemostrn_dptr, nphieps_dptr, ntauoc_dptr, nswh_dptr, nmwp_dptr, nemotaux_dptr,  &
!$acc & nemotauy_dptr, nemowswave_dptr, nemophif_dptr, wsemean_dptr, wsfmean_dptr, ustokes_dptr, vstokes_dptr, strnms_dptr,  &
!$acc & tauxd_dptr, tauyd_dptr, tauocxd_dptr, tauocyd_dptr, tauoc_dptr, phiocd_dptr, phieps_dptr, phiaw_dptr )
!$acc update device( af11, c2osqrtvg_gc, cm_gc, cofrm4, costh, delkcc_gc_ns, delkcc_omxkm3_gc, dfim, dfimfr, dfimfr2, dfimofr,  &
!$acc & dfim_sim, fklam, fklam1, fklap, fklap1, flmax, fr, fr5, ikm, ikm1, ikp, ikp1, indicessat, inlcoef, k11w, k1w, k21w, k2w,  &
!$acc & om3gmkm_gc, omega_gc, omxkm3_gc, rhowg_dfim, rnlcoef, satweights, sinth, swellft, th, wtauhf, xkmsqrtvgoc2_gc, xkm_gc,  &
!$acc & xk_gc, zpifr )
      
      TIME0 = -WAM_USER_CLOCK()
      
!$loki removed_loop var( ICHNK ) lower( 1 ) upper( NCHNK ) step( 1 )
      CALL IMPLSCH_FC(1, NPROMA_WAM, FL1_DPTR, WAVNUM_DPTR, CGROUP_DPTR, CIWA_DPTR, CINV_DPTR, XK2CG_DPTR, STOKFAC_DPTR,  &
      & EMAXDPT_DPTR, DEPTH_DPTR, IOBND_DPTR, IODP_DPTR, AIRD_DPTR, WDWAVE_DPTR, CICOVER_DPTR, WSWAVE_DPTR, WSTAR_DPTR,  &
      & USTRA_DPTR, VSTRA_DPTR, UFRIC_DPTR, TAUW_DPTR, TAUWDIR_DPTR, Z0M_DPTR, Z0B_DPTR, CHRNCK_DPTR, CITHICK_DPTR,  &
      & NEMOUSTOKES_DPTR, NEMOVSTOKES_DPTR, NEMOSTRN_DPTR, NPHIEPS_DPTR, NTAUOC_DPTR, NSWH_DPTR, NMWP_DPTR, NEMOTAUX_DPTR,  &
      & NEMOTAUY_DPTR, NEMOWSWAVE_DPTR, NEMOPHIF_DPTR, WSEMEAN_DPTR, WSFMEAN_DPTR, USTOKES_DPTR, VSTOKES_DPTR, STRNMS_DPTR,  &
      & TAUXD_DPTR, TAUYD_DPTR, TAUOCXD_DPTR, TAUOCYD_DPTR, TAUOC_DPTR, PHIOCD_DPTR, PHIEPS_DPTR, PHIAW_DPTR, MIJ_DPTR,  &
      & XLLWS_DPTR, ABMAX, ABMIN, ACD, ACDLIN, AF11, AFCRV, ALPHA, ALPHAMAX, ALPHAMIN, ALPHAPMAX, ANG_GC_A, ANG_GC_B, ANG_GC_C,  &
      & BATHYMAX, BCD, BCDLIN, BETAMAXOXKAPPA2, BFCRV, BMAXOKAP, BRKPBCOEF, C2OSQRTVG_GC, CDICWA, CDIS, CDISVIS, CDMAX,  &
      & CHNKMIN_U, CIBLOCK, CITHRSH, CITHRSH_TAIL, CM_GC, COFRM4, COSTH, DAL1, DAL2, DELKCC_GC_NS, DELKCC_OMXKM3_GC, DELTA_SDIS,  &
      & DELTH, DFIM, DFIMFR, DFIMFR2, DFIMOFR, DFIM_SIM, DKMAX, DTHRN_A, DTHRN_U, EGRCRV, EPS1, EPSMIN, EPSU10, EPSUS, FKLAM,  &
      & FKLAM1, FKLAP, FKLAP1, FLMAX, FLMIN, FLOGSPRDM1, FR, FR5, FRATIO, FRIC, FRTAIL, G, GAMNCONST, GM1, IAB, ICODE,  &
      & ICODE_CPL, IDAMPING, IDELT, IKM, IKM1, IKP, IKP1, INDICESSAT, INLCOEF, IPHYS, IPSAT, ISNONLIN, JTOT_TAUHF, K11W, K1W,  &
      & K21W, K2W, KFRH, LBIWBK, LCIWABR, LICERUN, LLCAPCHNK, LLGCBZ0, LLNORMAGAM, LLUNSTR, LMASKICE, LWAMRSETCI, LWCOU,  &
      & LWCOUAST, LWFLUX, LWFLUXOUT, LWNEMOCOU, LWNEMOCOUSEND, LWNEMOCOUSTK, LWNEMOCOUSTRN, LWNEMOTAUOC, LWVFLX_SNL, MFRSTLW,  &
      & MICHE, MLSTHG, NANG, NFRE, NFRE_ODD, NFRE_RED, NSDSNTH, NWAV_GC, OM3GMKM_GC, OMEGA_GC, OMXKM3_GC, PHIEPSMAX, PHIEPSMIN,  &
      & RHOWG_DFIM, RN1_RN, RNLCOEF, RNU, RNUM, ROWATER, ROWATERM1, SATWEIGHTS, SDSBR, SINTH, SQRTGOSURFT, SSDSBRF1, SSDSC2,  &
      & SSDSC3, SSDSC4, SSDSC5, SSDSC6, SWELLF, SWELLF2, SWELLF3, SWELLF4, SWELLF5, SWELLF6, SWELLF7, SWELLF7M1, SWELLFT,  &
      & TAILFACTOR, TAILFACTOR_PM, TAUOCMAX, TAUOCMIN, TAUWSHELTER, TH, WETAIL, WP1TAIL, WP2TAIL, WSEMEAN_MIN, WSPMIN, WTAUHF,  &
      & X0TAUHF, XKAPPA, XKDMIN, XKMSQRTVGOC2_GC, XKM_GC, XK_GC, XLOGKRATIOM1_GC, XNLEV, Z0RAT, Z0TUBMAX, ZALP, ZPI, ZPI4GM1,  &
      & ZPI4GM2, ZPIFR, NCHNK, NPROMA_WAM, IMPLSCH_DELFL, IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP,  &
      & IMPLSCH_EMEANWS, IMPLSCH_FMEANWS, IMPLSCH_USFM, IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA,  &
      & IMPLSCH_FLM, IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2, IMPLSCH_TEMP, IMPLSCH_RHOWGDFTH, IMPLSCH_FLD, IMPLSCH_SL, IMPLSCH_SPOS,  &
      & IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, FKMEAN_TEMPA, FKMEAN_TEMPX, FKMEAN_TEMP2,  &
      & SBOTTOM_SBO, IMPHFTAIL_TEMP1, IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP, SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT,  &
      & SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP,  &
      & SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ,  &
      & SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2, SDIWBK_SDS, SETICE_CIREDUC,  &
      & SETICE_TEMP, SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT,  &
      & TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, HALPHAP_ALPHAP,  &
      & HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
      & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS,  &
      & SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N,  &
      & SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN,  &
      & SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR,  &
      & SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2,  &
      & SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
      & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
      & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN,  &
      & SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
      & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
      & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
      & SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2,  &
      & STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX,  &
      & STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF,  &
      & TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1,  &
      & TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D,  &
      & TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH, SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD, SNONLIN_DELAP,  &
      & SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0, PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX, PEAK_ANG_TEMP,  &
      & PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI, CIMSSTRN_E, CIMSSTRN_SUME, STOKESDRIFT_STFAC,  &
      & WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF, WNFLUXES_OOVAL, WNFLUXES_EM_OC, WNFLUXES_F1_OC,  &
      & WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY)
      
      TIME_PHYS = TIME_PHYS + (TIME0 + WAM_USER_CLOCK())*1.E-06
      
!$acc end data
      
      TIME0 = -WAM_USER_CLOCK()
      CALL WVPRPT_FIELD%SYNC_HOST()
      CALL WVENVI_FIELD%SYNC_HOST()
      CALL FF_NOW_FIELD%SYNC_HOST()
      CALL WAM2NEMO_FIELD%SYNC_HOST()
      CALL INTFLDS_FIELD%SYNC_HOST()
      CALL SRC_CONTRIBS%SYNC_HOST()
      TIME_OFFLOAD = TIME_OFFLOAD + (TIME0 + WAM_USER_CLOCK())*1.E-06
      
      CALL WVPRPT_FIELD%FINAL()
      CALL WVENVI_FIELD%FINAL()
      CALL FF_NOW_FIELD%FINAL()
      CALL WAM2NEMO_FIELD%FINAL()
      CALL INTFLDS_FIELD%FINAL()
      CALL SRC_CONTRIBS%FINAL()
      
      IF (LWNEMOCOU) NEMONTAU = NEMONTAU + 1
      
    ELSE
      !   NO SOURCE TERM CONTRIBUTION
      DO ICHNK=1,NCHNK
        MIJ(:, ICHNK) = NFRE
        FL1(:, :, :, ICHNK) = MAX(FL1(:, :, :, ICHNK), EPSMIN)
        XLLWS(:, :, :, ICHNK) = 0.0_JWRB
      END DO
    END IF
    CALL GSTATS(1431, 1)
    
    
    !*       UPDATE FORCING FIELDS TIME COUNTER
    !        ----------------------------------
    IF (LLNEWFILE) THEN
      LLNEWFILE = .false.
      IDELWH = MAX(IDELWI, IDELPRO)
      CALL INCDATE(CDAWIFL, IDELWH)
      CALL INCDATE(CDATEFL, IDELWH)
    END IF
    
    CDATEWO = CDATEWH
    CDTIMP = CDTIMPNEXT
    CALL INCDATE(CDTIMPNEXT, IDELT)
    
  END IF
  
  IF (LHOOK) CALL DR_HOOK('WAMINTGR', 1, ZHOOK_HANDLE)
  
  
!$acc exit data delete( IMPLSCH_DELFL, IMPLSCH_RAORW, IMPLSCH_EMEAN, IMPLSCH_FMEAN, IMPLSCH_HALP, IMPLSCH_EMEANWS,  &
!$acc & IMPLSCH_FMEANWS, IMPLSCH_USFM, IMPLSCH_F1MEAN, IMPLSCH_AKMEAN, IMPLSCH_XKMEAN, IMPLSCH_PHIWA, IMPLSCH_FLM,  &
!$acc & IMPLSCH_COSWDIF, IMPLSCH_SINWDIF2, IMPLSCH_TEMP, IMPLSCH_RHOWGDFTH, IMPLSCH_FLD, IMPLSCH_SL, IMPLSCH_SPOS,  &
!$acc & IMPLSCH_CIREDUC, IMPLSCH_SSOURCE, FEMEANWS_TEMP2, FEMEANWS_EM_LOC, FKMEAN_TEMPA, FKMEAN_TEMPX, FKMEAN_TEMP2,  &
!$acc & SBOTTOM_SBO, IMPHFTAIL_TEMP1, IMPHFTAIL_TEMP2, SDEPTHLIM_EM, SEMEAN_TEMP, SDISSIP_ARD_FACTURB, SDISSIP_ARD_FACSAT,  &
!$acc & SDISSIP_ARD_FACWTRB, SDISSIP_ARD_TEMP1, SDISSIP_ARD_BTH0, SDISSIP_ARD_C_, SDISSIP_ARD_C_C, SDISSIP_ARD_DSIP,  &
!$acc & SDISSIP_ARD_TRPZ_DSIP, SDISSIP_ARD_BTH, SDISSIP_ARD_TEMP2, SDISSIP_ARD_D, SDISSIP_ARD_SCUMUL, SDISSIP_ARD_RENEWALFREQ,  &
!$acc & SDISSIP_ARD_WCUMUL, SDISSIP_JAN_TEMP1, SDISSIP_JAN_SDS, SDISSIP_JAN_X, SDISSIP_JAN_XK2, SDIWBK_SDS, SETICE_CIREDUC,  &
!$acc & SETICE_TEMP, SETICE_ICEFREE, SINFLX_RNFAC, SINFLX_TMP_EM, TAUT_Z0_ALPHAOG, TAUT_Z0_XMIN, TAUT_Z0_W1, TAUT_Z0_TAUWACT,  &
!$acc & TAUT_Z0_TAUWEFF, TAUT_Z0_ANG_GC, TAUT_Z0_TAUUNR, TAUT_Z0_LLCOSDIFF, STRESS_GC_GAM_W, Z0WAVE_ALPHAOG, HALPHAP_ALPHAP,  &
!$acc & HALPHAP_XMSS, HALPHAP_EM, HALPHAP_FM, HALPHAP_F1D, HALPHAP_WD, HALPHAP_FLWD, FEMEAN_TEMP2, MEANSQS_LF_FD,  &
!$acc & MEANSQS_LF_TEMP1, MEANSQS_LF_TEMP2, SINPUT_ARD_CONSTF, SINPUT_ARD_CONST11, SINPUT_ARD_CONST22, SINPUT_ARD_Z0VIS,  &
!$acc & SINPUT_ARD_Z0NOZ, SINPUT_ARD_FWW, SINPUT_ARD_PVISC, SINPUT_ARD_PTURB, SINPUT_ARD_ZCN, SINPUT_ARD_SIG_N,  &
!$acc & SINPUT_ARD_UORBT, SINPUT_ARD_AORB, SINPUT_ARD_TEMP, SINPUT_ARD_RE, SINPUT_ARD_RE_C, SINPUT_ARD_ZORB, SINPUT_ARD_CNSN,  &
!$acc & SINPUT_ARD_SUMF, SINPUT_ARD_SUMFSIN2, SINPUT_ARD_CSTRNFAC, SINPUT_ARD_FLP_AVG, SINPUT_ARD_SLP_AVG, SINPUT_ARD_ROGOROAIR,  &
!$acc & SINPUT_ARD_AIRD_PVISC, SINPUT_ARD_XSTRESS, SINPUT_ARD_YSTRESS, SINPUT_ARD_FLP, SINPUT_ARD_SLP, SINPUT_ARD_USG2,  &
!$acc & SINPUT_ARD_TAUX, SINPUT_ARD_TAUY, SINPUT_ARD_USTP, SINPUT_ARD_USTPM1, SINPUT_ARD_USDIRP, SINPUT_ARD_UCN,  &
!$acc & SINPUT_ARD_UCNZALPD, SINPUT_ARD_XNGAMCONST, SINPUT_ARD_GAMNORMA, SINPUT_ARD_DSTAB1, SINPUT_ARD_TEMP1, SINPUT_ARD_TEMP2,  &
!$acc & SINPUT_ARD_GAM0, SINPUT_ARD_DSTAB, SINPUT_ARD_COSLP, SINPUT_JAN_ZTANHKD, SINPUT_JAN_SIG_N, SINPUT_JAN_CNSN,  &
!$acc & SINPUT_JAN_SUMF, SINPUT_JAN_SUMFSIN2, SINPUT_JAN_CSTRNFAC, SINPUT_JAN_XNGAMCONST, SINPUT_JAN_GAMNORMA,  &
!$acc & SINPUT_JAN_SIGDEV, SINPUT_JAN_US, SINPUT_JAN_Z0, SINPUT_JAN_UCN, SINPUT_JAN_ZCN, SINPUT_JAN_USTPM1, SINPUT_JAN_XVD,  &
!$acc & SINPUT_JAN_UCND, SINPUT_JAN_CONST3_UCN2, SINPUT_JAN_UFAC1, SINPUT_JAN_UFAC2, SINPUT_JAN_TEMPD, SINPUT_JAN_GAM0,  &
!$acc & SINPUT_JAN_LZ, STRESSO_XSTRESS, STRESSO_YSTRESS, STRESSO_TAUHF, STRESSO_PHIHF, STRESSO_CMRHOWGDFTH, STRESSO_US2,  &
!$acc & STRESSO_TAUX, STRESSO_TAUY, STRESSO_TAUPX, STRESSO_TAUPY, STRESSO_USDIRP, STRESSO_UST, STRESSO_SUMT, STRESSO_SUMX,  &
!$acc & STRESSO_SUMY, TAU_PHI_HF_NS, TAU_PHI_HF_XKS, TAU_PHI_HF_OMS, TAU_PHI_HF_SQRTZ0OG, TAU_PHI_HF_ZSUP, TAU_PHI_HF_ZINF,  &
!$acc & TAU_PHI_HF_DELZ, TAU_PHI_HF_TAUL, TAU_PHI_HF_XLOGGZ0, TAU_PHI_HF_SQRTGZ0, TAU_PHI_HF_USTPH, TAU_PHI_HF_CONST1,  &
!$acc & TAU_PHI_HF_CONST2, TAU_PHI_HF_CONSTTAU, TAU_PHI_HF_CONSTPHI, TAU_PHI_HF_F1DCOS2, TAU_PHI_HF_F1DCOS3, TAU_PHI_HF_F1D,  &
!$acc & TAU_PHI_HF_F1DSIN2, SNONLIN_ENH, SNONLIN_XNU, SNONLIN_SIG_TH, SNONLIN_FTEMP, SNONLIN_AD, SNONLIN_DELAD, SNONLIN_DELAP,  &
!$acc & SNONLIN_DELAM, SNONLIN_ENHFR, PEAK_ANG_MMAX, PEAK_ANG_SUM0, PEAK_ANG_SUM1, PEAK_ANG_SUM2, PEAK_ANG_XMAX, PEAK_ANG_TEMP,  &
!$acc & PEAK_ANG_THMEAN, PEAK_ANG_SUM_S, PEAK_ANG_SUM_C, CIMSSTRN_XKI, CIMSSTRN_E, CIMSSTRN_SUME, STOKESDRIFT_STFAC,  &
!$acc & WNFLUXES_XSTRESS, WNFLUXES_YSTRESS, WNFLUXES_USTAR, WNFLUXES_PHILF, WNFLUXES_OOVAL, WNFLUXES_EM_OC, WNFLUXES_F1_OC,  &
!$acc & WNFLUXES_CMRHOWGDFTH, WNFLUXES_SUMT, WNFLUXES_SUMX, WNFLUXES_SUMY )
  
END SUBROUTINE WAMINTGR_LOKI_GPU
