

__device__ void wnfluxes_c(int kijs, int kijl, const int * __restrict__ mij, 
  const double * __restrict__ rhowgdfth, const double * __restrict__ cinv, 
  const double * __restrict__ ssurf, const double * __restrict__ cicover, 
  const double * __restrict__ phiwa, const double * __restrict__ em, 
  const double * __restrict__ f1, const double * __restrict__ wswave, 
  const double * __restrict__ wdwave, const double * __restrict__ ustra, 
  const double * __restrict__ vstra, const double * __restrict__ ufric, 
  const double * __restrict__ aird, double * __restrict__ nphieps, 
  double * __restrict__ ntauoc, double * __restrict__ nswh, double * __restrict__ nmwp, 
  double * __restrict__ nemotaux, double * __restrict__ nemotauy, 
  double * __restrict__ nemowswave, double * __restrict__ nemophif, 
  double * __restrict__ tauxd, double * __restrict__ tauyd, 
  double * __restrict__ tauocxd, double * __restrict__ tauocyd, 
  double * __restrict__ tauoc, double * __restrict__ phiocd, 
  double * __restrict__ phieps, double * __restrict__ phiaw, int lnupd, double afcrv, 
  double bfcrv, double ciblock, double cithrsh, const double * __restrict__ costh, 
  double egrcrv, double epsu10, double epsus, const double * __restrict__ fr, double g, 
  int licerun, int lwamrsetci, int lwcouast, int lwnemocou, int lwnemotauoc, int nang, 
  int nfre, double phiepsmax, double phiepsmin, const double * __restrict__ sinth, 
  double tauocmax, double tauocmin, int ichnk, int nchnk, int ij, 
  double * __restrict__ xstress, double * __restrict__ ystress, 
  double * __restrict__ ustar, double * __restrict__ philf, double * __restrict__ ooval, 
  double * __restrict__ em_oc, double * __restrict__ f1_oc, 
  double * __restrict__ cmrhowgdfth, double * __restrict__ sumt, 
  double * __restrict__ sumx, double * __restrict__ sumy);
