MODULE WSIGSTAR_FC_MOD
  USE iso_c_binding
  CONTAINS
  SUBROUTINE WSIGSTAR_fc (KIJS, KIJL, WSWAVE, UFRIC, Z0M, WSTAR, SIG_N, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, EPSUS, G, LLGCBZ0,  &
  & RNUM, WSPMIN, XKAPPA, ICHNK, NCHNK, IJ)
    USE iso_c_binding, ONLY: c_loc
    USE PARKIND_WAVE, ONLY: JWRB, JWIM
    
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJS
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: KIJL
    
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: IJ
    
    
    
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ACDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMAX
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: ALPHAMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: BCDLIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: EPSUS
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: G
    LOGICAL, VALUE, INTENT(IN) :: LLGCBZ0
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: RNUM
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: WSPMIN
    REAL(KIND=JWRB), VALUE, INTENT(IN) :: XKAPPA
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: ICHNK
    INTEGER(KIND=JWIM), VALUE, INTENT(IN) :: NCHNK
    INTERFACE
      SUBROUTINE WSIGSTAR_iso_c (KIJS, KIJL, WSWAVE, UFRIC, Z0M, WSTAR, SIG_N, ACDLIN, ALPHAMAX, ALPHAMIN, BCDLIN, EPSUS, G,  &
      & LLGCBZ0, RNUM, WSPMIN, XKAPPA, ICHNK, NCHNK, IJ) BIND(c, name="wsigstar_c_launch")
        USE iso_c_binding, ONLY: c_int, c_ptr
        implicit none
        INTEGER(KIND=c_int), VALUE :: KIJS
        INTEGER(KIND=c_int), VALUE :: KIJL
        TYPE(c_ptr), VALUE :: WSWAVE
        TYPE(c_ptr), VALUE :: UFRIC
        TYPE(c_ptr), VALUE :: Z0M
        TYPE(c_ptr), VALUE :: WSTAR
        TYPE(c_ptr), VALUE :: SIG_N
        REAL, VALUE :: ACDLIN
        REAL, VALUE :: ALPHAMAX
        REAL, VALUE :: ALPHAMIN
        REAL, VALUE :: BCDLIN
        REAL, VALUE :: EPSUS
        REAL, VALUE :: G
        LOGICAL, VALUE :: LLGCBZ0
        REAL, VALUE :: RNUM
        REAL, VALUE :: WSPMIN
        REAL, VALUE :: XKAPPA
        INTEGER(KIND=c_int), VALUE :: ICHNK
        INTEGER(KIND=c_int), VALUE :: NCHNK
        INTEGER(KIND=c_int), VALUE :: IJ
      END SUBROUTINE WSIGSTAR_iso_c
    END INTERFACE
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSWAVE(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: UFRIC(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: Z0M(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(IN) :: WSTAR(:, :)
    REAL(KIND=JWRB), TARGET, INTENT(OUT) :: SIG_N(:)
!$acc host_data use_device( WSWAVE, UFRIC, Z0M, WSTAR, SIG_N )
    CALL WSIGSTAR_iso_c(KIJS, KIJL, c_loc(WSWAVE), c_loc(UFRIC), c_loc(Z0M), c_loc(WSTAR), c_loc(SIG_N), ACDLIN, ALPHAMAX,  &
    & ALPHAMIN, BCDLIN, EPSUS, G, LLGCBZ0, RNUM, WSPMIN, XKAPPA, ICHNK, NCHNK, IJ)
!$acc end host_data
  END SUBROUTINE WSIGSTAR_fc
END MODULE WSIGSTAR_FC_MOD
